import os
import re
import glob

# Common words mapping
WORDS_MAPPING = {
    r'Licitaci\?n': 'Licitación',
    r'licitaci\?n': 'licitación',
    r'Licitaciones y Compras \? MuniControl': 'Licitaciones y Compras | MuniControl',
    r'T\?tulo': 'Título',
    r'\?rea': 'Área',
    r'descripci\?n': 'descripción',
    r'Descripci\?n': 'Descripción',
    r'a\?o': 'año',
    r'A\?o': 'Año',
    r'p\?blico': 'público',
    r'P\?blico': 'Público',
    r'Informaci\?n': 'Información',
    r'Gesti\?n': 'Gestión',
    r'Evaluaci\?n': 'Evaluación',
    r'Jun\?n': 'Junín',
    r'Configuraci\?n': 'Configuración',
    r'M\?s': 'Más',
    r'm\?s': 'más',
    r'N\?mero': 'Número',
    r'n\?mero': 'número',
    r'D\?a': 'Día',
    r'd\?a': 'día',
    r'veh\?culo': 'vehículo',
    r'Veh\?culo': 'Vehículo',
    r'Tel\?fono': 'Teléfono',
    r'tel\?fono': 'teléfono',
    r'Atenci\?n': 'Atención',
    r'Inversi\?n': 'Inversión',
    r'Participaci\?n': 'Participación',
    r'Ejecuci\?n': 'Ejecución',
    r'Ubicaci\?n': 'Ubicación',
    r'Acci\?n': 'Acción',
    r'Direcci\?n': 'Dirección',
    r'Secci\?n': 'Sección',
    r'Asignaci\?n': 'Asignación',
    r'Pr\?ximo': 'Próximo',
    r'pr\?ximo': 'próximo',
    r'tr\?mite': 'trámite',
    r'Tr\?mite': 'Trámite',
    r'Categor\?a': 'Categoría',
    r'categor\?a': 'categoría',
    r'Pol\?tica': 'Política',
    r'Ocupaci\?n': 'Ocupación',
    r'Asociaci\?n': 'Asociación',
    r'aprobaci\?n': 'aprobación',
    r'Aprobaci\?n': 'Aprobación',
    r'p\?gina': 'página',
    r'P\?gina': 'Página',
    r'B\?squeda': 'Búsqueda',
    r'b\?squeda': 'búsqueda',
    r'Comit\?': 'Comité',
    r'comit\?': 'comité',
    r'est\?': 'está',
    r'Est\?': 'Está',
    r'aqu\?': 'aquí',
    r'Aqu\?': 'Aquí',
    r'seg\?n': 'según',
    r'Seg\?n': 'Según',
    r'Tambi\?n': 'También',
    r'tambi\?n': 'también',
    r'qu\?': 'qué',
    r'Qu\?': 'Qué',
    r'c\?mo': 'cómo',
    r'C\?mo': 'Cómo',
    r'cu\?ndo': 'cuándo',
    r'Cu\?ndo': 'Cuándo',
    r'd\?nde': 'dónde',
    r'D\?nde': 'Dónde',
    r'qui\?n': 'quién',
    r'Qui\?n': 'Quién',
    r'cu\?l': 'cuál',
    r'Cu\?l': 'Cuál',
    r'cu\?ntos': 'cuántos',
    r'Cu\?ntos': 'Cuántos',
    r'cu\?nto': 'cuánto',
    r'Cu\?nto': 'Cuánto',
    r'podr\?a': 'podría',
    r'Podr\?a': 'Podría',
    r'ser\?': 'será',
    r'Ser\?': 'Será',
    r'har\?': 'hará',
    r'Har\?': 'Hará',
    r'habr\?': 'habrá',
    r'Habr\?': 'Habrá',
    r'tendr\?': 'tendrá',
    r'Tendr\?': 'Tendrá',
    r'est\?n': 'están',
    r'Est\?n': 'Están',
    r'ser\?n': 'serán',
    r'Ser\?n': 'Serán',
    r'har\?n': 'harán',
    r'Har\?n': 'Harán',
    r'habr\?n': 'habrán',
    r'Habr\?n': 'Habrán',
    r'tendr\?n': 'tendrán',
    r'Tendr\?n': 'Tendrán',
    r'podr\?n': 'podrán',
    r'Podr\?n': 'Podrán',
    r'deber\?': 'deberá',
    r'Deber\?': 'Deberá',
    r'deber\?n': 'deberán',
    r'Deber\?n': 'Deberán',
    r'tambi\?n': 'también',
    r'Tambi\?n': 'También',
    r'adem\?s': 'además',
    r'Adem\?s': 'Además',
    r'despu\?s': 'después',
    r'Despu\?s': 'Después',
    r'atr\?s': 'atrás',
    r'Atr\?s': 'Atrás',
    r'm\?s': 'más',
    r'M\?s': 'Más',
    r'a\?n': 'aún',
    r'A\?n': 'Aún',
    r's\?lo': 'sólo',
    r'S\?lo': 'Sólo',
    r'S\?': 'Sí',
    r's\?': 'sí',
    r'M\?': 'Mí',
    r'm\?': 'mí',
    r'T\?': 'Tú',
    r't\?': 'tú',
    r'El\?': 'Él',
    r'el\?': 'él',
    r'c\?digo': 'código',
    r'C\?digo': 'Código',
    r'tel\?fono': 'teléfono',
    r'Tel\?fono': 'Teléfono',
    r'art\?culo': 'artículo',
    r'Art\?culo': 'Artículo',
    r'pr\?ctica': 'práctica',
    r'Pr\?ctica': 'Práctica',
    r'p\?gina': 'página',
    r'P\?gina': 'Página',
    r't\?rmino': 'término',
    r'T\?rmino': 'Término',
    r'pr\?ximo': 'próximo',
    r'Pr\?ximo': 'Próximo',
    r'\?ltimo': 'último',
    r'\?ltimo': 'Último',
    r'\?nico': 'único',
    r'\?nico': 'Único',
    r'p\?blico': 'público',
    r'P\?blico': 'Público',
    r'r\?pido': 'rápido',
    r'R\?pido': 'Rápido',
    r'f\?cil': 'fácil',
    r'F\?cil': 'Fácil',
    r'dif\?cil': 'difícil',
    r'Dif\?cil': 'Difícil',
    r'\?til': 'útil',
    r'\?til': 'Útil',
    r'D\?lar': 'Dólar',
    r'd\?lar': 'dólar',
    r'c\?lculo': 'cálculo',
    r'C\?lculo': 'Cálculo',
    r'an\?lisis': 'análisis',
    r'An\?lisis': 'Análisis',
    r'estad\?stica': 'estadística',
    r'Estad\?stica': 'Estadística',
    r'pol\?tica': 'política',
    r'Pol\?tica': 'Política',
    r'econ\?mico': 'económico',
    r'Econ\?mico': 'Económico',
    r'p\?liza': 'póliza',
    r'P\?liza': 'Póliza',
    r'tr\?nsito': 'tránsito',
    r'Tr\?nsito': 'Tránsito',
    r'veh\?culo': 'vehículo',
    r'Veh\?culo': 'Vehículo',
    r'v\?a': 'vía',
    r'V\?a': 'Vía',
    r'd\?a': 'día',
    r'D\?a': 'Día',
    r'R\?o': 'Río',
    r'r\?o': 'río',
    r'Comisi\?n': 'Comisión',
    r'comisi\?n': 'comisión',
    r'Inversi\?n': 'Inversión',
    r'inversi\?n': 'inversión',
    r'versi\?n': 'versión',
    r'Versi\?n': 'Versión',
    r'secci\?n': 'sección',
    r'Secci\?n': 'Sección',
    r'direcci\?n': 'dirección',
    r'Direcci\?n': 'Dirección',
    r'acci\?n': 'acción',
    r'Acci\?n': 'Acción',
    r'opci\?n': 'opción',
    r'Opci\?n': 'Opción',
    r'situaci\?n': 'situación',
    r'Situaci\?n': 'Situación',
    r'condici\?n': 'condición',
    r'Condici\?n': 'Condición',
    r'soluci\?n': 'solución',
    r'Soluci\?n': 'Solución',
    r'atenci\?n': 'atención',
    r'Atenci\?n': 'Atención',
    r'petici\?n': 'petición',
    r'Petici\?n': 'Petición',
    r'decisi\?n': 'decisión',
    r'Decisi\?n': 'Decisión',
    r'posici\?n': 'posición',
    r'Posici\?n': 'Posición',
    r'funci\?n': 'función',
    r'Funci\?n': 'Función',
    r'reuni\?n': 'reunión',
    r'Reuni\?n': 'Reunión',
    r'opini\?n': 'opinión',
    r'Opini\?n': 'Opinión',
    r'relaci\?n': 'relación',
    r'Relaci\?n': 'Relación',
    r'cuesti\?n': 'cuestión',
    r'Cuesti\?n': 'Cuestión',
    r'creaci\?n': 'creación',
    r'Creaci\?n': 'Creación',
    r'formaci\?n': 'formación',
    r'Formaci\?n': 'Formación',
    r'informaci\?n': 'información',
    r'Informaci\?n': 'Información',
    r'presentaci\?n': 'presentación',
    r'Presentaci\?n': 'Presentación',
    r'representaci\?n': 'representación',
    r'Representaci\?n': 'Representación',
    r'operaci\?n': 'operación',
    r'Operaci\?n': 'Operación',
    r'organizaci\?n': 'organización',
    r'Organizaci\?n': 'Organización',
    r'administraci\?n': 'administración',
    r'Administraci\?n': 'Administración',
    r'participaci\?n': 'participación',
    r'Participaci\?n': 'Participación',
    r'comunicaci\?n': 'comunicación',
    r'Comunicaci\?n': 'Comunicación',
    r'aplicaci\?n': 'aplicación',
    r'Aplicaci\?n': 'Aplicación',
    r'publicaci\?n': 'publicación',
    r'Publicaci\?n': 'Publicación',
    r'clasificaci\?n': 'clasificación',
    r'Clasificaci\?n': 'Clasificación',
    r'certificaci\?n': 'certificación',
    r'Certificaci\?n': 'Certificación',
    r'planificaci\?n': 'planificación',
    r'Planificaci\?n': 'Planificación',
    r'modificaci\?n': 'modificación',
    r'Modificaci\?n': 'Modificación',
    r'evaluaci\?n': 'evaluación',
    r'Evaluaci\?n': 'Evaluación',
    r'actuaci\?n': 'actuación',
    r'Actuaci\?n': 'Actuación',
    r'puntuaci\?n': 'puntuación',
    r'Puntuaci\?n': 'Puntuación',
    r'situaci\?n': 'situación',
    r'Situaci\?n': 'Situación',
    r'habitaci\?n': 'habitación',
    r'Habitaci\?n': 'Habitación',
    r'estaci\?n': 'estación',
    r'Estaci\?n': 'Estación',
    r'inversi\?n': 'inversión',
    r'Inversi\?n': 'Inversión',
    r'evoluci\?n': 'evolución',
    r'Evoluci\?n': 'Evolución',
    r'revoluci\?n': 'revolución',
    r'Revoluci\?n': 'Revolución',
    r'soluci\?n': 'solución',
    r'Soluci\?n': 'Solución',
    r'resoluci\?n': 'resolución',
    r'Resoluci\?n': 'Resolución',
    r'devoluci\?n': 'devolución',
    r'Devoluci\?n': 'Devolución',
    r'evoluci\?n': 'evolución',
    r'Evoluci\?n': 'Evolución',
    r'contribuci\?n': 'contribución',
    r'Contribuci\?n': 'Contribución',
    r'distribuci\?n': 'distribución',
    r'Distribuci\?n': 'Distribución',
    r'atribuci\?n': 'atribución',
    r'Atribuci\?n': 'Atribución',
    r'instituci\?n': 'institución',
    r'Instituci\?n': 'Institución',
    r'constituci\?n': 'constitución',
    r'Constituci\?n': 'Constitución',
    r'construcci\?n': 'construcción',
    r'Construcci\?n': 'Construcción',
    r'instrucci\?n': 'instrucción',
    r'Instrucci\?n': 'Instrucción',
    r'destrucci\?n': 'destrucción',
    r'Destrucci\?n': 'Destrucción',
    r'producci\?n': 'producción',
    r'Producci\?n': 'Producción',
    r'introducci\?n': 'introducción',
    r'Introducci\?n': 'Introducción',
    r'traducci\?n': 'traducción',
    r'Traducci\?n': 'Traducción',
    r'conducci\?n': 'conducción',
    r'Conducci\?n': 'Conducción',
    r'deducci\?n': 'deducción',
    r'Deducci\?n': 'Deducción',
    r'reducci\?n': 'reducción',
    r'Reducci\?n': 'Reducción',
    r'direcci\?n': 'dirección',
    r'Direcci\?n': 'Dirección',
    r'protecci\?n': 'protección',
    r'Protecci\?n': 'Protección',
    r'colecci\?n': 'colección',
    r'Colecci\?n': 'Colección',
    r'elecci\?n': 'elección',
    r'Elecci\?n': 'Elección',
    r'selecci\?n': 'selección',
    r'Selecci\?n': 'Selección',
    r'lecci\?n': 'lección',
    r'Lecci\?n': 'Lección',
    r'secci\?n': 'sección',
    r'Secci\?n': 'Sección',
    r'afecci\?n': 'afección',
    r'Afecci\?n': 'Afección',
    r'infecci\?n': 'infección',
    r'Infecci\?n': 'Infección',
    r'proyecci\?n': 'proyección',
    r'Proyecci\?n': 'Proyección',
    r'inyecci\?n': 'inyección',
    r'Inyecci\?n': 'Inyección',
    r'inspecci\?n': 'inspección',
    r'Inspecci\?n': 'Inspección',
    r'rececci\?n': 'recepción',
    r'Recepc\?n': 'Recepción',
    r'recepci\?n': 'recepción',
    r'Recepci\?n': 'Recepción',
    r'concepci\?n': 'concepción',
    r'Concepci\?n': 'Concepción',
    r'excepci\?n': 'excepción',
    r'Excepci\?n': 'Excepción',
    r'percepci\?n': 'percepción',
    r'Percepci\?n': 'Percepción',
    r'opci\?n': 'opción',
    r'Opci\?n': 'Opción',
    r'adopci\?n': 'adopción',
    r'Adopci\?n': 'Adopción',
    r'corrupci\?n': 'corrupción',
    r'Corrupci\?n': 'Corrupción',
    r'interrupci\?n': 'interrupción',
    r'Interrupci\?n': 'Interrupción',
    r'sanci\?n': 'sanción',
    r'Sanci\?n': 'Sanción',
    r'funci\?n': 'función',
    r'Funci\?n': 'Función',
    r'defunci\?n': 'defunción',
    r'Defunci\?n': 'Defunción',
    r'atenci\?n': 'atención',
    r'Atenci\?n': 'Atención',
    r'intenci\?n': 'intención',
    r'Intenci\?n': 'Intención',
    r'invenci\?n': 'invención',
    r'Invenci\?n': 'Invención',
    r'intervenci\?n': 'intervención',
    r'Intervenci\?n': 'Intervención',
    r'convenci\?n': 'convención',
    r'Convenci\?n': 'Convención',
    r'prevenci\?n': 'prevención',
    r'Prevenci\?n': 'Prevención',
    r'retenci\?n': 'retención',
    r'Retenci\?n': 'Retención',
    r'obtenci\?n': 'obtención',
    r'Obtenci\?n': 'Obtención',
    r'contenci\?n': 'contención',
    r'Contenci\?n': 'Contención',
    r'menci\?n': 'mención',
    r'Menci\?n': 'Mención',
    r'canci\?n': 'canción',
    r'Canci\?n': 'Canción',
    r'oraci\?n': 'oración',
    r'Oraci\?n': 'Oración',
    r'declaraci\?n': 'declaración',
    r'Declaraci\?n': 'Declaración',
    r'aclaraci\?n': 'aclaración',
    r'Aclaraci\?n': 'Aclaración',
    r'comparaci\?n': 'comparación',
    r'Comparaci\?n': 'Comparación',
    r'preparaci\?n': 'preparación',
    r'Preparaci\?n': 'Preparación',
    r'reparaci\?n': 'reparación',
    r'Reparaci\?n': 'Reparación',
    r'separaci\?n': 'separación',
    r'Separaci\?n': 'Separación',
    r'generaci\?n': 'generación',
    r'Generaci\?n': 'Generación',
    r'operaci\?n': 'operación',
    r'Operaci\?n': 'Operación',
    r'cooperaci\?n': 'cooperación',
    r'Cooperaci\?n': 'Cooperación',
    r'recuperaci\?n': 'recuperación',
    r'Recuperaci\?n': 'Recuperación',
    r'superaci\?n': 'superación',
    r'Superaci\?n': 'Superación',
    r'alteraci\?n': 'alteración',
    r'Alteraci\?n': 'Alteración',
    r'consideraci\?n': 'consideración',
    r'Consideraci\?n': 'Consideración',
    r'federaci\?n': 'federación',
    r'Federaci\?n': 'Federación',
    r'moderaci\?n': 'moderación',
    r'Moderaci\?n': 'Moderación',
    r'veneraci\?n': 'veneración',
    r'Veneraci\?n': 'Veneración',
    r'remuneraci\?n': 'remuneración',
    r'Remuneraci\?n': 'Remuneración',
    r'vulneraci\?n': 'vulneración',
    r'Vulneraci\?n': 'Vulneración',
    r'exageraci\?n': 'exageración',
    r'Exageraci\?n': 'Exageración',
    r'desesperaci\?n': 'desesperación',
    r'Desesperaci\?n': 'Desesperación',
    r'inspiraci\?n': 'inspiración',
    r'Inspiraci\?n': 'Inspiración',
    r'respiraci\?n': 'respiración',
    r'Respiraci\?n': 'Respiración',
    r'aspiraci\?n': 'aspiración',
    r'Aspiraci\?n': 'Aspiración',
    r'transpiraci\?n': 'transpiración',
    r'Transpiraci\?n': 'Transpiración',
    r'admiraci\?n': 'admiración',
    r'Admiraci\?n': 'Admiración',
    r'exploraci\?n': 'exploración',
    r'Exploraci\?n': 'Exploración',
    r'valoraci\?n': 'valoración',
    r'Valoraci\?n': 'Valoración',
    r'elaboraci\?n': 'elaboración',
    r'Elaboraci\?n': 'Elaboración',
    r'colaboraci\?n': 'colaboración',
    r'Colaboraci\?n': 'Colaboración',
    r'incorporaci\?n': 'incorporación',
    r'Incorporaci\?n': 'Incorporación',
    r'decoraci\?n': 'decoración',
    r'Decoraci\?n': 'Decoración',
    r'perforaci\?n': 'perforación',
    r'Perforaci\?n': 'Perforación',
    r'demostraci\?n': 'demostración',
    r'Demostraci\?n': 'Demostración',
    r'penetraci\?n': 'penetración',
    r'Penetraci\?n': 'Penetración',
    r'concentraci\?n': 'concentración',
    r'Concentraci\?n': 'Concentración',
    r'administraci\?n': 'administración',
    r'Administraci\?n': 'Administración',
    r'ilustraci\?n': 'ilustración',
    r'Ilustraci\?n': 'Ilustración',
    r'frustraci\?n': 'frustración',
    r'Frustraci\?n': 'Frustración',
    r'registrac\?n': 'registración',
    r'Registraci\?n': 'Registración',
    r'Duraci\?n': 'Duración',
    r'duraci\?n': 'duración',
    r'facturaci\?n': 'facturación',
    r'Facturaci\?n': 'Facturación',
    r'estructuraci\?n': 'estructuración',
    r'Estructuraci\?n': 'Estructuración',
    r'restauraci\?n': 'restauración',
    r'Restauraci\?n': 'Restauración',
    r'instauraci\?n': 'instauración',
    r'Instauraci\?n': 'Instauración',
    r'curaci\?n': 'curación',
    r'Curaci\?n': 'Curación',
    r'procuraci\?n': 'procuración',
    r'Procuraci\?n': 'Procuración',
    r'apuraci\?n': 'apuración',
    r'Apuraci\?n': 'Apuración',
    r'depuraci\?n': 'depuración',
    r'Depuraci\?n': 'Depuración',
    r'inauguraci\?n': 'inauguración',
    r'Inauguraci\?n': 'Inauguración',
    r'configuraci\?n': 'configuración',
    r'Configuraci\?n': 'Configuración',
    r'figuraci\?n': 'figuración',
    r'Figuraci\?n': 'Figuración',
    r'transfiguraci\?n': 'transfiguración',
    r'Transfiguraci\?n': 'Transfiguración',
    r'desfiguraci\?n': 'desfiguración',
    r'Desfiguraci\?n': 'Desfiguración',
    r'conjuraci\?n': 'conjuración',
    r'Conjuraci\?n': 'Conjuración',
    r'abjuraci\?n': 'abjuración',
    r'Abjuraci\?n': 'Abjuración',
    r'murmuraci\?n': 'murmuración',
    r'Murmuraci\?n': 'Murmuración',
    r'supuraci\?n': 'supuración',
    r'Supuraci\?n': 'Supuración',
    r'mensuraci\?n': 'mensuración',
    r'Mensuraci\?n': 'Mensuración',
    r'clausuraci\?n': 'clausuración',
    r'Clausuraci\?n': 'Clausuración',
    r'usuraci\?n': 'usuración',
    r'Usuraci\?n': 'Usuración',
    r'fisuraci\?n': 'fisuración',
    r'Fisuraci\?n': 'Fisuración',
    r'fracturaci\?n': 'fracturación',
    r'Fracturaci\?n': 'Fracturación',
    r'capturaci\?n': 'capturación',
    r'Capturaci\?n': 'Capturación',
    r'trituraci\?n': 'trituración',
    r'Trituraci\?n': 'Trituración',
    r'roturaci\?n': 'roturación',
    r'Roturaci\?n': 'Roturación',
    r'saturaci\?n': 'saturación',
    r'Saturaci\?n': 'Saturación',
    r'maturaci\?n': 'maturación',
    r'Maturaci\?n': 'Maturación',
    r'Garant\?a': 'Garantía',
    r'garant\?a': 'garantía',
    r'd\?as': 'días',
    r'D\?as': 'Días',
    r'v\?as': 'vías',
    r'V\?as': 'Vías',
    r'categor\?as': 'categorías',
    r'Categor\?as': 'Categorías',
    r'Mar\?a': 'María',
    r'polic\?a': 'policía',
    r'Polic\?a': 'Policía',
    r'alcald\?a': 'alcaldía',
    r'Alcald\?a': 'Alcaldía',
    r'secretar\?a': 'secretaría',
    r'Secretar\?a': 'Secretaría',
    r'tecnolog\?a': 'tecnología',
    r'Tecnolog\?a': 'Tecnología',
    r'metodolog\?a': 'metodología',
    r'Metodolog\?a': 'Metodología',
    r'ideolog\?a': 'ideología',
    r'Ideolog\?a': 'Ideología',
    r'biolog\?a': 'biología',
    r'Biolog\?a': 'Biología',
    r'psicolog\?a': 'psicología',
    r'Psicolog\?a': 'Psicología',
    r'sociolog\?a': 'sociología',
    r'Sociolog\?a': 'Sociología',
    r'ecolog\?a': 'ecología',
    r'Ecolog\?a': 'Ecología',
    r'geolog\?a': 'geología',
    r'Geolog\?a': 'Geología',
    r'patolog\?a': 'patología',
    r'Patolog\?a': 'Patología',
    r'filosof\?a': 'filosofía',
    r'Filosof\?a': 'Filosofía',
    r'fotograf\?a': 'fotografía',
    r'Fotograf\?a': 'Fotografía',
    r'geograf\?a': 'geografía',
    r'Geograf\?a': 'Geografía',
    r'biograf\?a': 'biografía',
    r'Biograf\?a': 'Biografía',
    r'demograf\?a': 'demografía',
    r'Demograf\?a': 'Demografía',
    r'radiograf\?a': 'radiografía',
    r'Radiograf\?a': 'Radiografía',
    r'caligraf\?a': 'caligrafía',
    r'Caligraf\?a': 'Caligrafía',
    r'ortograf\?a': 'ortografía',
    r'Ortograf\?a': 'Ortografía',
    r'tipograf\?a': 'tipografía',
    r'Tipograf\?a': 'Tipografía',
    r'cartograf\?a': 'cartografía',
    r'Cartograf\?a': 'Cartografía',
    r'coreograf\?a': 'coreografía',
    r'Coreograf\?a': 'Coreografía',
    r'bibliograf\?a': 'bibliografía',
    r'Bibliograf\?a': 'Bibliografía',
    r'econom\?a': 'economía',
    r'Econom\?a': 'Economía',
    r'autonom\?a': 'autonomía',
    r'Autonom\?a': 'Autonomía',
    r'astronom\?a': 'astronomía',
    r'Astronom\?a': 'Astronomía',
    r'gastronom\?a': 'gastronomía',
    r'Gastronom\?a': 'Gastronomía',
    r'anatom\?a': 'anatomía',
    r'Anatom\?a': 'Anatomía',
    r'simetr\?a': 'simetría',
    r'Simetr\?a': 'Simetría',
    r'geometr\?a': 'geometría',
    r'Geometr\?a': 'Geometría',
    r'psiquiatr\?a': 'psiquiatría',
    r'Psiquiatr\?a': 'Psiquiatría',
    r'pediatr\?a': 'pediatría',
    r'Pediatr\?a': 'Pediatría',
    r'geriatr\?a': 'geriatría',
    r'Geriatr\?a': 'Geriatría',
    r'foniatr\?a': 'foniatría',
    r'Foniatr\?a': 'Foniatría',
    r'barbacoa': 'barbacoa', # just in case
    r'Compa\?ia': 'Compañía',
    r'compa\?\?a': 'compañía',
    r'Compa\?\?a': 'Compañía',
    r'compa\?ia': 'compañía',
    r'alba\?il': 'albañil',
    r'Alba\?il': 'Albañil',
    r'dise\?o': 'diseño',
    r'Dise\?o': 'Diseño',
    r'peque\?o': 'pequeño',
    r'Peque\?o': 'Pequeño',
    r'ense\?anza': 'enseñanza',
    r'Ense\?anza': 'Enseñanza',
    r'ni\?o': 'niño',
    r'Ni\?o': 'Niño',
    r'se\?or': 'señor',
    r'Se\?or': 'Señor',
    r'sue\?o': 'sueño',
    r'Sue\?o': 'Sueño',
    r'ba\?o': 'baño',
    r'Ba\?o': 'Baño',
    r'da\?o': 'daño',
    r'Da\?o': 'Daño',
    r'tama\?o': 'tamaño',
    r'Tama\?o': 'Tamaño',
    r'enga\?o': 'engaño',
    r'Enga\?o': 'Engaño',
    r'reba\?o': 'rebaño',
    r'Reba\?o': 'Rebaño',
    r'oto\?o': 'otoño',
    r'Oto\?o': 'Otoño',
    r'desempe\?o': 'desempeño',
    r'Desempe\?o': 'Desempeño',
    r'empe\?o': 'empeño',
    r'Empe\?o': 'Empeño',
    r'due\?o': 'dueño',
    r'Due\?o': 'Dueño',
    r'espa\?ol': 'español',
    r'Espa\?ol': 'Español',
    r'campa\?a': 'campaña',
    r'Campa\?a': 'Campaña',
    r'monta\?a': 'montaña',
    r'Monta\?a': 'Montaña',
    r'ma\?ana': 'mañana',
    r'Ma\?ana': 'Mañana',
    r'caba\?a': 'cabaña',
    r'Caba\?a': 'Cabaña',
    r'haza\?a': 'hazaña',
    r'Haza\?a': 'Hazaña',
    r'ara\?a': 'araña',
    r'Ara\?a': 'Araña',
    r'pesta\?a': 'pestaña',
    r'Pesta\?a': 'Pestaña',
    r'artesan\?a': 'artesanía',
    r'Artesan\?a': 'Artesanía',
    r'ciudadan\?a': 'ciudadanía',
    r'Ciudadan\?a': 'Ciudadanía',
    r'cercan\?a': 'cercanía',
    r'Cercan\?a': 'Cercanía',
    r'lejan\?a': 'lejanía',
    r'Lejan\?a': 'Lejanía',
    r'mayor\?a': 'mayoría',
    r'Mayor\?a': 'Mayoría',
    r'minor\?a': 'minoría',
    r'Minor\?a': 'Minoría',
    r'auditor\?a': 'auditoría',
    r'Auditor\?a': 'Auditoría',
    r'asesor\?a': 'asesoría',
    r'Asesor\?a': 'Asesoría',
    r'consultor\?a': 'consultoría',
    r'Consultor\?a': 'Consultoría',
    r'categor\?a': 'categoría',
    r'Categor\?a': 'Categoría',
    r'jerarqu\?a': 'jerarquía',
    r'Jerarqu\?a': 'Jerarquía',
    r'anarqu\?a': 'anarquía',
    r'Anarqu\?a': 'Anarquía',
    r'monarqu\?a': 'monarquía',
    r'Monarqu\?a': 'Monarquía',
    r'oligarqu\?a': 'oligarquía',
    r'Oligarqu\?a': 'Oligarquía',
    r'energ\?a': 'energía',
    r'Energ\?a': 'Energía',
    r'sinerg\?a': 'sinergia',
    r'Sinerg\?a': 'Sinergia',
    r'alerg\?a': 'alergia',
    r'Alerg\?a': 'Alergia',
    r'cirug\?a': 'cirugía',
    r'Cirug\?a': 'Cirugía',
    r'liturg\?a': 'liturgia',
    r'Liturg\?a': 'Liturgia',
    r'siderurg\?a': 'siderurgia',
    r'Siderurg\?a': 'Siderurgia',
    r'metalurg\?a': 'metalurgia',
    r'Metalurg\?a': 'Metalurgia',
    r'estrateg\?a': 'estrategia',
    r'Estrateg\?a': 'Estrategia',
    r'Visi\?n': 'Visión',
    r'visi\?n': 'visión',
    r'Misi\?n': 'Misión',
    r'misi\?n': 'misión',
    r'Provisi\?n': 'Provisión',
    r'provisi\?n': 'provisión',
    r'Revisi\?n': 'Revisión',
    r'revisi\?n': 'revisión',
    r'Previsi\?n': 'Previsión',
    r'previsi\?n': 'previsión',
    r'Televisi\?n': 'Televisión',
    r'televisi\?n': 'televisión',
    r'Divisi\?n': 'División',
    r'divisi\?n': 'división',
    r'Decisi\?n': 'Decisión',
    r'decisi\?n': 'decisión',
    r'Precisi\?n': 'Precisión',
    r'precisi\?n': 'precisión',
    r'Inclusi\?n': 'Inclusión',
    r'inclusi\?n': 'inclusión',
    r'Exclusi\?n': 'Exclusión',
    r'exclusi\?n': 'exclusión',
    r'Conclusi\?n': 'Conclusión',
    r'conclusi\?n': 'conclusión',
    r'Ilusi\?n': 'Ilusión',
    r'ilusi\?n': 'ilusión',
    r'Alusi\?n': 'Alusión',
    r'alusi\?n': 'alusión',
    r'Garant\?a': 'Garantía',
    r'garant\?a': 'garantía',
    r'Gu\?a': 'Guía',
    r'gu\?a': 'guía',
    r'b\?sica': 'básica',
    r'B\?sica': 'Básica',
    r'b\?sico': 'básico',
    r'B\?sico': 'Básico',
    r'cl\?sico': 'clásico',
    r'Cl\?sico': 'Clásico',
    r'pl\?stico': 'plástico',
    r'Pl\?stico': 'Plástico',
    r'm\?gico': 'mágico',
    r'M\?gico': 'Mágico',
    r'tr\?gico': 'trágico',
    r'Tr\?gico': 'Trágico',
    r'l\?gico': 'lógico',
    r'L\?gico': 'Lógico',
    r'tecnol\?gico': 'tecnológico',
    r'Tecnol\?gico': 'Tecnológico',
    r'psicol\?gico': 'psicológico',
    r'Psicol\?gico': 'Psicológico',
    r'ecol\?gico': 'ecológico',
    r'Ecol\?gico': 'Ecológico',
    r'metodol\?gico': 'metodológico',
    r'Metodol\?gico': 'Metodológico',
    r'pedag\?gico': 'pedagógico',
    r'Pedag\?gico': 'Pedagógico',
    r'estrat\?gico': 'estratégico',
    r'Estrat\?gico': 'Estratégico',
    r'energ\?tico': 'energético',
    r'Energ\?tico': 'Energético',
    r'gen\?tico': 'genético',
    r'Gen\?tico': 'Genético',
    r'magn\?tico': 'magnético',
    r'Magn\?tico': 'Magnético',
    r'sint\?tico': 'sintético',
    r'Sint\?tico': 'Sintético',
    r'est\?tico': 'estético',
    r'Est\?tico': 'Estético',
    r'cr\?tico': 'crítico',
    r'Cr\?tico': 'Crítico',
    r'pol\?tico': 'político',
    r'Pol\?tico': 'Político',
    r'anal\?tico': 'analítico',
    r'Anal\?tico': 'Analítico',
    r'pr\?ctico': 'práctico',
    r'Pr\?ctico': 'Práctico',
    r't\?ctico': 'táctico',
    r'T\?ctico': 'Táctico',
    r'did\?ctico': 'didáctico',
    r'Did\?ctico': 'Didáctico',
    r'autom\?tico': 'automático',
    r'Autom\?tico': 'Automático',
    r'matem\?tico': 'matemático',
    r'Matem\?tico': 'Matemático',
    r'inform\?tico': 'informático',
    r'Inform\?tico': 'Informático',
    r'democr\?tico': 'democrático',
    r'Democr\?tico': 'Democrático',
    r'burocr\?tico': 'burocrático',
    r'Burocr\?tico': 'Burocrático',
    r'aristocr\?tico': 'aristocrático',
    r'Aristocr\?tico': 'Aristocrático',
    r'sistem\?tico': 'sistemático',
    r'Sistem\?tico': 'Sistemático',
    r'problem\?tico': 'problemático',
    r'Problem\?tico': 'Problemático',
    r'sintom\?tico': 'sintomático',
    r'Sintom\?tico': 'Sintomático',
    r'pragm\?tico': 'pragmático',
    r'Pragm\?tico': 'Pragmático',
    r'dogm\?tico': 'dogmático',
    r'Dogm\?tico': 'Dogmático',
    r'simp\?tico': 'simpático',
    r'Simp\?tico': 'Simpático',
    r'antip\?tico': 'antipático',
    r'Antip\?tico': 'Antipático',
    r'emp\?tico': 'empático',
    r'Emp\?tico': 'Empático',
    r'ap\?tico': 'apático',
    r'Ap\?tico': 'Apático',
    r'he\?tico': 'héctico', # actually it's just 'ético' -> \?tico
    r'\?tico': 'ético',
    r'\?tica': 'ética',
    r'\?ticos': 'éticos',
    r'\?ticas': 'éticas',
    r'\?rgano': 'órgano',
    r'\?rdenes': 'órdenes',
    r'\?ndice': 'índice',
    r'\?ntimo': 'íntimo',
    r'\?ntegro': 'íntegro',
    r'\?nclito': 'ínclito',
    r'\?bice': 'óbice',
    r'\?bito': 'óbito',
    r'\?poca': 'época',
    r'\?xito': 'éxito',
    r'\?nfasis': 'énfasis',
    r'\?lite': 'élite',
    r'\?rbitro': 'árbitro',
    r'\?mbito': 'ámbito',
    r'\?ngulo': 'ángulo',
    r'\?nimo': 'ánimo',
    r'\?rbol': 'árbol',
    r'\?rea': 'área',
    r'?? ': 'EMOJI_PLACEHOLDER ',
    r'\?\? ': 'EMOJI_PLACEHOLDER '
}

def replace_emoji(match):
    following_text = match.group(1).strip()
    
    if 'guardar' in following_text.lower(): return '💾 ' + following_text
    if 'crear' in following_text.lower(): return '✅ ' + following_text
    if 'nuevo' in following_text.lower(): return '➕ ' + following_text
    if 'exportar' in following_text.lower(): return '📥 ' + following_text
    if 'importar' in following_text.lower(): return '📤 ' + following_text
    if 'imprimir' in following_text.lower(): return '🖨️ ' + following_text
    if 'buscar' in following_text.lower(): return '🔍 ' + following_text
    if 'eliminar' in following_text.lower(): return '🗑️ ' + following_text
    if 'editar' in following_text.lower(): return '✏️ ' + following_text
    if 'cancelar' in following_text.lower(): return '❌ ' + following_text
    if 'confirmar' in following_text.lower(): return '✅ ' + following_text
    if 'volver' in following_text.lower(): return '⬅️ ' + following_text
    if 'siguiente' in following_text.lower(): return '➡️ ' + following_text
    if 'anterior' in following_text.lower(): return '⬅️ ' + following_text
    if 'inicio' in following_text.lower(): return '🏠 ' + following_text
    if 'ajustes' in following_text.lower(): return '⚙️ ' + following_text
    if 'perfil' in following_text.lower(): return '👤 ' + following_text
    if 'notificaciones' in following_text.lower(): return '🔔 ' + following_text
    if 'mensajes' in following_text.lower(): return '✉️ ' + following_text
    if 'ayuda' in following_text.lower(): return '❓ ' + following_text
    if 'salir' in following_text.lower(): return '🚪 ' + following_text
    if 'entrar' in following_text.lower(): return '🔑 ' + following_text
    if 'subir' in following_text.lower(): return '⬆️ ' + following_text
    if 'descargar' in following_text.lower(): return '⬇️ ' + following_text
    if 'adjuntar' in following_text.lower(): return '📎 ' + following_text
    if 'compartir' in following_text.lower(): return '🔗 ' + following_text
    if 'copiar' in following_text.lower(): return '📋 ' + following_text
    if 'pegar' in following_text.lower(): return '📋 ' + following_text
    if 'agregar' in following_text.lower(): return '➕ ' + following_text
    if 'más' in following_text.lower() or 'm\?s' in following_text.lower(): return '➕ ' + following_text
    if 'menos' in following_text.lower(): return '➖ ' + following_text
    if 'actualizar' in following_text.lower(): return '🔄 ' + following_text
    if 'cargar' in following_text.lower(): return '🔄 ' + following_text
    if 'generar' in following_text.lower(): return '⚡ ' + following_text
    if 'procesar' in following_text.lower(): return '⚙️ ' + following_text
    if 'analizar' in following_text.lower(): return '📊 ' + following_text
    if 'evaluar' in following_text.lower(): return '⚖️ ' + following_text
    if 'aprobar' in following_text.lower(): return '✅ ' + following_text
    if 'rechazar' in following_text.lower(): return '❌ ' + following_text
    if 'enviar' in following_text.lower(): return '📤 ' + following_text
    if 'recibir' in following_text.lower(): return '📥 ' + following_text
    if 'pagar' in following_text.lower(): return '💳 ' + following_text
    if 'cobrar' in following_text.lower(): return '💰 ' + following_text
    if 'facturar' in following_text.lower(): return '🧾 ' + following_text
    if 'impresión' in following_text.lower(): return '🖨️ ' + following_text
    if 'reporte' in following_text.lower(): return '📊 ' + following_text
    if 'estadísticas' in following_text.lower(): return '📈 ' + following_text
    if 'gráficos' in following_text.lower(): return '📉 ' + following_text
    if 'mapa' in following_text.lower(): return '🗺️ ' + following_text
    if 'ubicación' in following_text.lower(): return '📍 ' + following_text
    if 'dirección' in following_text.lower(): return '📍 ' + following_text
    if 'ciudadano' in following_text.lower(): return '👤 ' + following_text
    if 'vecino' in following_text.lower(): return '👤 ' + following_text
    if 'usuario' in following_text.lower(): return '👤 ' + following_text
    if 'administrador' in following_text.lower(): return '👨‍💼 ' + following_text
    if 'personal' in following_text.lower(): return '🧑‍🤝‍🧑 ' + following_text
    if 'rrhh' in following_text.lower(): return '👥 ' + following_text
    if 'hacienda' in following_text.lower(): return '💰 ' + following_text
    if 'obras' in following_text.lower(): return '🏗️ ' + following_text
    if 'servicios' in following_text.lower(): return '🔧 ' + following_text
    if 'control' in following_text.lower(): return '🚦 ' + following_text
    if 'manuales' in following_text.lower(): return '📚 ' + following_text
    if 'talleres' in following_text.lower(): return '🛠️ ' + following_text
    if 'presentación' in following_text.lower(): return '🎬 ' + following_text
    if 'landing' in following_text.lower(): return '🛬 ' + following_text
    if 'upload' in following_text.lower(): return '⬆️ ' + following_text
    if 'forms' in following_text.lower(): return '📝 ' + following_text
    if 'analytics' in following_text.lower(): return '📊 ' + following_text
    if 'presupuesto' in following_text.lower(): return '💰 ' + following_text
    if 'cuentas' in following_text.lower(): return '🧾 ' + following_text
    if 'claras' in following_text.lower(): return '✨ ' + following_text
    if 'offline' in following_text.lower(): return '📶 ' + following_text
    if 'whatsapp' in following_text.lower(): return '💬 ' + following_text
    if 'error' in following_text.lower(): return '❌ ' + following_text
    if 'éxito' in following_text.lower(): return '✅ ' + following_text
    if 'advertencia' in following_text.lower(): return '⚠️ ' + following_text
    if 'info' in following_text.lower(): return 'ℹ️ ' + following_text
    if 'pregunta' in following_text.lower(): return '❓ ' + following_text
    if 'ai' in following_text.lower() or 'ia ' in following_text.lower(): return '🤖 ' + following_text
    if 'licita' in following_text.lower(): return '📋 ' + following_text
    if 'proveedor' in following_text.lower(): return '🏢 ' + following_text
    if 'calendario' in following_text.lower(): return '📅 ' + following_text
    if 'registro' in following_text.lower(): return '📋 ' + following_text
    if 'activas' in following_text.lower(): return '✅ ' + following_text
    if 'flujo' in following_text.lower(): return '🔄 ' + following_text
    
    # Generic fallback emoji based on first letter or just a default point
    return '🔹 ' + following_text

html_files = glob.glob('*.html')
for file_name in html_files:
    with open(file_name, 'r', encoding='utf-8', errors='ignore') as f:
        content = f.read()

    original_content = content
    
    # 1. Replace common specific broken encodings
    for pattern, replacement in WORDS_MAPPING.items():
        if '?? ' in pattern or '\?\? ' in pattern:
            continue
        content = re.sub(pattern, replacement, content)

    # 2. Replace ?? emojis based on context
    content = re.sub(r'\?\?\s*([A-Za-z0-9_ÁÉÍÓÚáéíóúÑñ]+)', replace_emoji, content)

    # Some additional manual fixes for specific strings left over with ??
    content = content.replace('??', '🔹')

    # Fix meta tags and scripts
    if '<meta charset="UTF-8"' not in content and '<meta charset="utf-8"' not in content:
        content = content.replace('<head>', '<head>\n  <meta charset="UTF-8" />')
        
    if 'css/dashboard.css' not in content:
        content = content.replace('</title>', '</title>\n  <link rel="stylesheet" href="css/dashboard.css" />')
        
    if 'js/theme-switcher.js' not in content:
        content = content.replace('</body>', '  <script src="js/theme-switcher.js"></script>\n</body>')
        
    if 'js/nav.js' not in content:
        content = content.replace('</body>', '  <script src="js/nav.js"></script>\n</body>')

    if content != original_content:
        with open(file_name, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"Fixed {file_name}")
