// SPDX-License-Identifier: GPL-2.0-only
// Local operational snapshot: never identities, raw records, network addresses or credentials.
const esc=value=>String(value??'Sin dato').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=v=>typeof v==='string'&&Number.isFinite(Date.parse(v))?new Intl.DateTimeFormat('es-AR',{timeZone:'America/Argentina/Mendoza',dateStyle:'short',timeStyle:'medium'}).format(new Date(v)):'Sin comprobación';
const count=v=>Number.isSafeInteger(v)&&v>=0?String(v):'Sin dato';
const LABELS={waiting:'Esperando primera captura',captured_locally:'Captura local completa',network_wait:'Sin ruta municipal',retry_wait:'Reintento programado',blocked:'Detenido para revisión',review_required:'Requiere revisión',disabled:'Deshabilitado',stopped:'Detenido'};
export function fleetOverview(config,summary,{pm10=null,desired='stopped',error=null}={}){
 const states=new Map((Array.isArray(summary?.clocks)?summary.clocks:[]).map(s=>[s.clockId,s]));
 const cards=config.clocks.map(c=>{const s=states.get(c.clockId)||{status:'waiting'};return `<article><span class="tag">${esc(LABELS[s.status]||'Estado no determinado')}</span><h2>${esc(c.label)}</h2><dl><dt>Última captura completa</dt><dd>${esc(date(s.lastCaptureAt))}</dd><dt>Registros únicos locales</dt><dd>${count(s.uniqueLocalRecords)}</dd><dt>Próximo intento</dt><dd>${esc(date(s.nextPollAt))}</dd><dt>Última observación</dt><dd>${esc(s.lastError||'Sin error informado')}</dd></dl><p class="note">Recepción en Neon: no configurada para este reloj. La cola queda conservada, separada de PM-10.</p></article>`;}).join('');
 const existing=pm10?`<article class="existing"><span class="tag">Colector existente conservado</span><h2>Edificio Viejo · PM-10</h2><dl><dt>Última captura</dt><dd>${esc(date(pm10.lastCaptureAt))}</dd><dt>Último acuse conservado</dt><dd>${esc(date(pm10.lastReceiptAt))}</dd><dt>Registros confirmados</dt><dd>${count(pm10.confirmedRecords)}</dd></dl><p class="note">Información de los archivos del colector ya instalado. Esta ampliación no lo inicia, detiene ni modifica.</p></article>`:'';
 return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="refresh" content="30"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'"><title>MuniControl · Central de relojes</title><style>
 *{box-sizing:border-box}body{margin:0;background:#edf3f3;color:#143b4d;font:15px/1.6 system-ui,sans-serif}main{max-width:1250px;margin:auto;padding:26px}header{padding:28px;border-radius:18px;background:#153b4b;color:white}h1{font-size:clamp(25px,4vw,38px);line-height:1.2;margin:10px 0}h2{font-size:20px;margin:12px 0}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,310px),1fr));gap:16px;margin:22px 0}article{background:white;border:1px solid #cbdcde;border-radius:15px;padding:22px;min-width:0}.tag{display:inline-block;padding:4px 9px;border-radius:6px;background:#eaf3f3;font-size:12px;font-weight:700}dl{margin:15px 0}dt{font-size:12px;color:#466876;margin-top:11px}dd{margin:0;overflow-wrap:anywhere;font-weight:650}.note{font-size:12px;color:#42606d}.alert{padding:18px 22px;background:#fff5df;border-left:5px solid #b8790d;border-radius:10px;margin-top:18px}.existing{border-top:4px solid #078479}footer{font-size:12px;color:#476571}small{font-size:12px}@media(max-width:600px){main{padding:14px}header{padding:21px}article{padding:18px}}
 </style></head><body><main><header><small>MUNICONTROL · LECTOR 4.1 · OPERACIÓN LOCAL</small><h1>Central de relojes</h1><p>Un software compartido. Identidad, captura y cola independientes por equipo.</p><small>Estado guardado: ${esc(date(summary?.updatedAt))} · Captura adicional: ${desired==='running'?'habilitada':'detenida tras el ciclo actual'}</small></header><div class="alert">Captura local no es recepción confirmada ni asistencia aprobada. El envío automático de los equipos adicionales debe quedar validado por conector y serie; nunca se mezcla con PM-10.${error?' Observación del supervisor: '+esc(error):''}</div><section class="grid">${existing}${cards}</section><footer>Este panel lee archivos locales y no consulta la red. Actualización visual cada 30 segundos; la fecha de cada evidencia indica su antigüedad. No incluye nombres, DNI, PIN ni datos biométricos. Windows debe permanecer encendido, con la sesión y la ruta municipal disponibles.</footer></main></body></html>`;
}
