import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {comparisonFixture} from './fixtures/position-comparison-synthetic.js';
import {budgetHash} from '../assets/annual-position-budget-model.js';
import {verifiedPositionComparison,positionComparisonRows,positionComparisonDocument,positionComparisonVisible} from '../assets/position-comparison-model.js';
import {verifiedPositionRunCapture} from '../assets/position-assignment-model.js';
import {reportCsv,reportPdf} from '../assets/report-document.js';
import {buildAdoptedPositionsInstallation,assertAdoptedPositionsDurability} from '../scripts/lib/adopted-positions-installation.mjs';
import {prepareAdoptedPositionsInstallation} from '../scripts/prepare-adopted-positions-installation.mjs';
const filters={active:'all',order:'number',view:'detailed'},commit='45c487d4036dbd0aeb46983e83103a5d3451e63e',read=p=>fs.readFileSync(new URL('../'+p,import.meta.url),'utf8');
async function fixture(numbers){const v=await comparisonFixture(numbers.length),c=v.captures[0];for(const [i,n] of numbers.entries()){for(const list of [v.employees,c.population.employees,c.positions.payload.employees,c.dimensions.payload.employees])list[i].employeeNumber=n;}c.population.version=await budgetHash(c.population.employees);for(const p of [c.positions.payload,c.dimensions.payload])p.populationVersion=c.population.version;c.positions.payloadSha256=await budgetHash(c.positions.payload);c.dimensions.payloadSha256=await budgetHash(c.dimensions.payload);return v;}
test('cargos conserva los legajos opacos completos y los ceros, sin coerción numérica',async()=>{const numbers=['A/3501','0901','901','0012345678901234567890123456789'],v=await fixture(numbers);await verifiedPositionComparison(v);await verifiedPositionRunCapture(v.captures[0].positions);assert.deepEqual(positionComparisonRows(v,filters).map(r=>r.employeeNumber),['0901','901',numbers[3],'A/3501']);assert.equal(reportPdf(positionComparisonDocument(v,filters)).length>1000,true);});
test('orden mixto es total y estable en todas las permutaciones; búsqueda no recorta CSV',async()=>{const numbers=['10','2A','2','A/3501','0901','901',...Array.from({length:45},(_,i)=>'B/'+i)],v=await fixture(numbers);await verifiedPositionComparison(v);const expected=positionComparisonRows(v,filters).map(r=>r.employeeNumber);for(let i=0;i<10;i++){v.employees.reverse();v.employees.push(v.employees.shift());assert.deepEqual(positionComparisonRows(v,filters).map(r=>r.employeeNumber),expected);}const d=positionComparisonDocument(v,filters);assert.equal(positionComparisonVisible(d,'A/3501').filtered,1);assert.equal(reportCsv(d).split('\r\n').length,53);assert.equal(positionComparisonVisible(d,'',3).rows.length,1);});
test('identificador largo usa caracteres Unicode y CSV seguro sin cambiar el original',async()=>{const number='='.concat('é'.repeat(63)),v=await fixture([number]);await verifiedPositionComparison(v);assert.equal(positionComparisonDocument(v,filters).rows[0][1],number);assert.ok(reportCsv(positionComparisonDocument(v,filters)).includes("'="));});
for(const n of ['',7,'X\nY','X\u0000Y','X\u0085Y','é'.repeat(65)])test('rechaza legajo propio inválido '+JSON.stringify(n),async()=>{const v=await fixture([n]);await assert.rejects(()=>verifiedPositionComparison(v));});
test('cada captura se liga a su población completa aun con identificador opaco',async()=>{const v=await fixture(['A/3501','0901','901']);v.captures[0].dimensions.payload.employees[0].employeeNumber='A/3502';v.captures[0].dimensions.payloadSha256=await budgetHash(v.captures[0].dimensions.payload);await assert.rejects(()=>verifiedPositionComparison(v),/identidad original/);});
test('adaptación presupuestaria cambia cinco cuerpos conservando el lector anterior, sin DML ni permisos nuevos',()=>{const b=buildAdoptedPositionsInstallation({read,sourceCommit:commit});assert.equal(b.connects,false);assert.equal(b.executesSql,false);assert.equal(b.migration.length,5);for(const s of b.migration){assert.match(s,/^CREATE OR REPLACE FUNCTION public\./);assert.doesNotMatch(s,/\b(?:GRANT|REVOKE|ALTER TABLE|TRUNCATE|UPDATE|DELETE)\b/);}assert.equal(b.dependencies.length,27);assert.ok(b.migration[2].includes('public.employment_adoption_application'));assert.ok(b.installation.join('\n').includes("to_jsonb(p)-'prosrc'"));assert.ok(b.installation.join('\n').includes('ADOPTED_POSITIONS_PARTIAL_STATE'));assert.equal(b.durableVerification[0],'SET TRANSACTION READ ONLY');});
for(const file of ['127-annual-position-budget.sql','128-own-position-assignments.sql','129-own-position-comparison.sql','138-adopted-fixed-novelties.sql'])test('un byte distinto impide adaptar '+file,()=>{assert.throws(()=>buildAdoptedPositionsInstallation({read:p=>read(p)+(p.endsWith('/'+file)?'\n':''),sourceCommit:commit}));});
test('durabilidad exige mismo destino, fuente y huellas completas',()=>{const b=buildAdoptedPositionsInstallation({read,sourceCommit:commit}),p={version:'adopted-positions-installation.v2',sourceCommit:commit,sourceHashes:b.sourceHashes,allChecksPassed:true,adaptedFunctions:5,newTables:0,newFunctions:0,permissionChanges:0,businessOperations:0,nominalRowsReturned:0,priorFingerprint:'a'.repeat(64),objectFingerprint:'b'.repeat(64)};assert.equal(assertAdoptedPositionsDurability({installed:p,durable:p,batch:b}).passed,true);for(const k of ['priorFingerprint','objectFingerprint','sourceCommit'])assert.throws(()=>assertAdoptedPositionsDurability({installed:p,durable:{...p,[k]:'c'.repeat(64)},batch:b}));});
test('revisión se ata sólo a los dos destinos existentes y no ejecuta SQL',()=>{const b=prepareAdoptedPositionsInstallation({read,sourceCommit:commit});assert.equal(b.targets.length,2);assert.equal(b.connects,false);assert.equal(b.executesSql,false);for(const t of b.targets){assert.ok(t.installation.join('\n').includes('current_database()'));assert.ok(t.installation.join('\n').includes('neon.project_id'));assert.equal(t.durableVerification[0],'SET TRANSACTION READ ONLY');assert.ok(t.installation.every(s=>!/^\s*(?:COMMIT|BEGIN|ROLLBACK)\b/.test(s)));}});
