import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {buildAdoptedOwnNoveltyInstallation,adoptedOwnNoveltyCapture,assertAdoptedOwnNoveltyDurability} from '../scripts/lib/adopted-own-novelties-installation.mjs';
const options={read:p=>fs.readFileSync(p,'utf8'),sourceCommit:'78c8b5bdc9f3dba5f328971014e6004b9a161bbe'};
import {prepareAdoptedOwnNoveltyInstallation} from '../scripts/prepare-adopted-own-novelties-installation.mjs';
test('prepared release fixes both existing destinations and begins durable verification read-only exactly once',()=>{const b=prepareAdoptedOwnNoveltyInstallation(options);assert.equal(b.connects,false);assert.equal(b.executesSql,false);assert.deepEqual(b.targets.map(t=>t.major),[17,18]);for(const t of b.targets){assert.ok(t.installation.some(s=>[t.projectId,t.branchId,t.endpointId,t.database,t.role].every(v=>s.includes(v))));assert.equal(t.durableVerification[0],'SET TRANSACTION READ ONLY');assert.equal(t.durableVerification.filter(s=>s==='SET TRANSACTION READ ONLY').length,1);assert.equal(t.sourceCommit,undefined);assert.equal(t.installation.at(-1),b.installation.at(-1));}});
test('composition retains adopted range authority and all approved bulk sources',()=>{const c=adoptedOwnNoveltyCapture(options.read);assert.equal(c.split('public.payroll_fixed_registry_range_v2(').length,3);assert.ok(c.includes("ctx||jsonb_build_object('certifiedBindingId',ctx->>'sourceBindingId')"));assert.ok(c.includes('public.payroll_fixed_registry_subject_v2'));assert.ok(c.includes('public.employment_adoption_application'));assert.ok(c.includes('native_batches:=public.own_novelty_sources_v1'));assert.ok(c.includes("'nativeBatches',native_batches"));assert.ok(c.includes('public.own_close_guard_v1'));assert.ok(!c.includes('public.native_employment_lifecycle_range_v1'));});
test('composition pins every prerequisite and updates only the exact readiness/capture bodies',()=>{const b=buildAdoptedOwnNoveltyInstallation(options);assert.equal(b.migration.filter(s=>s.startsWith('CREATE OR REPLACE FUNCTION public.')).length,2);assert.ok(b.ready.includes(b.capturePin.sha256));assert.ok(!b.ready.includes(b.operator.consumers.afterPins.find(p=>p.name==='own_run_capture_v1').sha256));assert.deepEqual(b.finalOperatorPins.slice(1),b.operator.pins.slice(1));assert.ok(b.installation.includes(b.novelty.priorAudit));assert.ok(b.installation.includes(b.novelty.objectsCheck));assert.ok(b.before.includes("'municipal_adoption_ready_v1'"));assert.ok(b.installation.some(s=>s.includes('ADOPTED_NOVELTY_PRIOR_FUNCTION_CHANGED')));assert.equal(Object.keys(b.sourceHashes).length,12);assert.ok(!b.migration.join('\n').includes('GRANT EXECUTE ON FUNCTION public.employment_adoption_decide'));});
test('unreviewed source definitions cannot be composed',()=>{assert.throws(()=>buildAdoptedOwnNoveltyInstallation({...options,read:p=>options.read(p)+(p.endsWith('130-own-bulk-novelties.sql')?'-- drift\n':'')}));assert.throws(()=>buildAdoptedOwnNoveltyInstallation({...options,sourceCommit:'invalid'}));});
test('durability binds both replacement bodies, effects, exact proof shape and all reviewed source hashes',()=>{const b=buildAdoptedOwnNoveltyInstallation(options),p={version:'adopted-own-novelties-installation.v1',sourceCommit:options.sourceCommit,sql130Sha256:b.novelty.sql130Sha256,allChecksPassed:true,beforeFingerprint:'a'.repeat(64),afterFingerprint:'a'.repeat(64),newObjectFingerprint:'b'.repeat(64),sourceHashes:b.sourceHashes,adoptedCaptureSha256:b.capturePin.sha256,operatorReadySha256:b.readyPin.sha256,adoptionWriterGranted:false,consumersAdapted:2,newTables:1,newFunctions:16,runtimeFacades:4,oldRowGuardsAdded:1,noveltyEvents:0,capabilityDefinitionsAdded:0,roleAssignmentsAdded:0,nominalRowsReturned:0},d=Object.fromEntries(Object.entries(p).filter(([k])=>k!=='beforeFingerprint'));assert.ok(assertAdoptedOwnNoveltyDurability({installed:p,durable:d,batch:b,sourceCommit:options.sourceCommit}).adoptedCapturePreserved);for(const change of [x=>x.adoptedCaptureSha256='c'.repeat(64),x=>x.operatorReadySha256='c'.repeat(64),x=>x.sourceHashes={},x=>x.adoptionWriterGranted=true,x=>x.roleAssignmentsAdded=1,x=>x.noveltyEvents=1,x=>x.oldRowGuardsAdded=0,x=>x.nominalRowsReturned=1,x=>x.afterFingerprint=x.beforeFingerprint='unknown',x=>x.extra='unreviewed']){const i=structuredClone(p);change(i);assert.throws(()=>assertAdoptedOwnNoveltyDurability({installed:i,durable:Object.fromEntries(Object.entries(i).filter(([k])=>k!=='beforeFingerprint')),batch:b,sourceCommit:options.sourceCommit}));}});
