import fs from 'node:fs';import path from 'node:path';import test from 'node:test';import assert from 'node:assert/strict';
import {buildAnnualBudgetInstallation,assertAnnualBudgetDurability,SQL127_SHA} from '../scripts/lib/annual-position-budget-installation.mjs';import {prepareAnnualBudgetInstallation} from '../scripts/prepare-annual-position-budget-installation.mjs';import {executeAnnualBudgetInstallation} from '../scripts/install-annual-position-budget.mjs';
const read=f=>fs.readFileSync(f,'utf8'),sourceCommit='9'.repeat(40);
test('lote conservador: 1 tabla vacía, 11 funciones, 3 fachadas y 2 definiciones sin asignar roles',()=>{const b=buildAnnualBudgetInstallation({read,sourceCommit});assert.equal(b.ownPins.length,11);assert.equal(b.ownPins.filter(p=>p.runtime).length,3);assert.ok(b.before.includes("''workforce.structure.prepare'',''workforce.structure.approve''"));assert.ok(!b.before.includes("''payroll.calculation.read''"));assert.match(b.before,/annual_position_budget_event/);assert.match(b.priorAudit,/SQL127_PRIOR_STATE_CHANGED/);assert.equal(b.sql127Sha256,SQL127_SHA);assert.ok(!b.installation.some(s=>/INSERT INTO public\.iam_role_capability|UPDATE public\.(employment_contract|person_identity)|grh_histolegajo/i.test(s)));});
test('un byte diferente impide generar el lote',()=>assert.throws(()=>buildAnnualBudgetInstallation({read:f=>read(f)+(f.includes('127-')?'\n':''),sourceCommit}),/Unreviewed SQL127/));
test('paquete incluye assets y SQL127; excluye fuentes privadas, respaldo y handoff',()=>{const rules=read('.vercelignore').split('\n').map(s=>s.trim()).filter(s=>s&&!s.startsWith('#')),included=f=>{let keep=true;for(const r of rules){const neg=r.startsWith('!'),p=neg?r.slice(1):r;if(p.endsWith('/')?f.startsWith(p):path.matchesGlob(f,p)||!p.includes('/')&&path.matchesGlob(path.basename(f),p))keep=neg;}return keep;};assert.equal(prepareAnnualBudgetInstallation({read:f=>{assert.ok(included(f),'Excluded: '+f);return read(f);},sourceCommit}).sql127Sha256,SQL127_SHA);for(const f of ['.handoff/sync-current.json','AGENTS.md','CODEX_TASK.md','MUNICONTROL_HANDOFF.md','.env.local','verification/result.json','source.sql.gz'])assert.equal(included(f),false);for(const f of ['assets/annual-position-budget-model.js','assets/annual-position-budget-panel.js','assets/annual-position-budget.css'])assert.ok(read('scripts/build-friendly.mjs').includes("'"+f+"'"));});
test('dos destinos existentes y revisión sin conexión ni ejecución',()=>{const b=prepareAnnualBudgetInstallation({read,sourceCommit});assert.equal(b.connects,false);assert.equal(b.executesSql,false);assert.deepEqual(b.targets.map(t=>t.major),[17,18]);assert.ok(b.targets.every(t=>t.preflight[0]==='SET TRANSACTION READ ONLY'));});
test('prueba de conservación y durabilidad debe coincidir exactamente',()=>{const installed={sourceCommit,sql127Sha256:SQL127_SHA,allChecksPassed:true,beforeFingerprint:'a',afterFingerprint:'a',newObjectFingerprint:'b'},durable={...installed};delete durable.beforeFingerprint;assertAnnualBudgetDurability({installed,durable,sourceCommit});for(const patch of [{newObjectFingerprint:'c'},{sourceCommit:'1'.repeat(40)},{afterFingerprint:'c'}])assert.throws(()=>assertAnnualBudgetDurability({installed,durable:{...durable,...patch},sourceCommit}));});
test('no cambia destino ni reintenta un commit incierto',async()=>{const batch=prepareAnnualBudgetInstallation({read,sourceCommit}),target=batch.targets[0];let calls=0,records=0;await assert.rejects(executeAnnualBudgetInstallation({batch,major:17,client:async()=>({target:{...target,host:'wrong.invalid'},sql:{transaction(){calls++;}}}),record(){}}),/DESTINATION_DRIFT/);assert.equal(calls,0);const sql={query:s=>s,transaction:async()=>{calls++;if(calls===1)return [];throw Error('Unknown COMMIT');}};await assert.rejects(executeAnnualBudgetInstallation({batch,major:17,client:async()=>({sql,target}),record(){records++;}}),/Unknown COMMIT/);assert.equal(calls,2);assert.equal(records,0);});
