import test from 'node:test';import assert from 'node:assert/strict';
import {createAnnualBudgetHandler} from '../api/internal-annual-position-budget.js';
import {command,receipt,bootstrap,uid,hash} from './fixtures/annual-position-budget-synthetic.js';
const caps=['workforce.employee.read','workforce.structure.read','workforce.structure.prepare','workforce.structure.approve'],principal={user:{email:'qa@example.invalid'},tenant:{source:'membership',id:uid(1),membershipId:uid(2),effectiveCapabilities:caps}},session={email:'qa@example.invalid',id:uid(3),version:1,releaseSha:'d'.repeat(40)};
const res=()=>({headers:{},setHeader(k,v){this.headers[k]=v;},status(n){this.statusCode=n;return this;},json(v){this.value=v;return this;}});
const request=()=>({method:'POST',url:'/api/internal-annual-position-budget',query:{},headers:{origin:'https://municipio.example','content-type':'application/json','idempotency-key':uid(9)},body:JSON.stringify({operation:'command',payload:command()})});
function setup(overrides={}){const calls=[],stats={connections:0};const handler=createAnnualBudgetHandler({env:{INTERNAL_APP_ORIGIN:'https://municipio.example'},requireAccess:async()=>({mode:'managed',principal}),sessionFor:()=>session,getSql:async()=>{stats.connections++;return {query:async(q,v)=>{calls.push({q,v});return [{result:receipt()}];}};},...overrides});return {handler,calls,stats};}
test('propuesta voluntaria usa contexto autenticado y no-store',async()=>{const a=setup(),out=res();await a.handler(request(),out);assert.equal(out.statusCode,201);assert.equal(a.calls.length,1);assert.equal(JSON.parse(a.calls[0].v[0]).actorSessionId,session.id);assert.match(out.headers['Cache-Control'],/no-store/);});
for(const [label,change]of [['origen',r=>r.headers.origin='https://otro.invalid'],['campos IAM',r=>r.body=JSON.stringify({operation:'command',payload:command({tenantId:uid(1)})})],['medio',r=>r.headers['content-type']='text/plain'],['JSON duplicado',r=>r.body='{"operation":"command","operati\\u006fn":"command"}'],['clave',r=>delete r.headers['idempotency-key']],['query repetida',r=>{r.method='GET';r.query={resource:'bootstrap',year:'2026'};r.url+='?resource=bootstrap&year=2026&year=2026';}],['UTF8',r=>r.body=Buffer.from([255])],['método',r=>r.method='DELETE']])test('rechaza '+label+' sin consultar SQL',async()=>{const a=setup(),r=request(),out=res();change(r);await a.handler(r,out);assert.ok(out.statusCode>=400);assert.equal(a.calls.length,0);});
test('revocación o sesión inválida: no lee bytes ni abre SQL',async()=>{for(const extra of [{requireAccess:async()=>({mode:'managed',principal:{...principal,tenant:{...principal.tenant,effectiveCapabilities:[]}}})},{sessionFor:()=>({...session,id:null})}]){const a=setup(extra),r=request(),out=res();let reads=0;Object.defineProperty(r,'body',{get(){reads++;throw Error('prohibido');}});await a.handler(r,out);assert.ok([401,403].includes(out.statusCode));assert.equal(reads,0);assert.equal(a.stats.connections,0);}});
test('consulta sin permiso de escritura; no permite proponer',async()=>{const a=setup({requireAccess:async()=>({mode:'managed',principal:{...principal,tenant:{...principal.tenant,effectiveCapabilities:caps.slice(0,2)}}})}),out=res();await a.handler(request(),out);assert.equal(out.statusCode,403);assert.equal(a.calls.length,0);const b=setup({getSql:async()=>({query:async()=>[{result:bootstrap()}]})}),r=request(),result=res();r.method='GET';r.query={resource:'bootstrap',year:'2026'};r.url+='?resource=bootstrap&year=2026';await b.handler(r,result);assert.equal(result.statusCode,200);});
test('fallos redacted y huellas incorrectas rechazadas',async()=>{for(const getSql of [async()=>({query:async()=>[{result:receipt(command(),{requestSha256:hash('f')})}]}),async()=>({query:async()=>{throw Error('private-secret');}})]){const a=setup({getSql}),out=res();await a.handler(request(),out);assert.equal(out.statusCode,503);assert.ok(!JSON.stringify(out.value).includes('private-secret'));}});
test('reenvío no crea un contenido diferente',async()=>{const a=setup({getSql:async()=>({query:async()=>[{result:receipt(command(),{replayed:true})}]})}),out=res();await a.handler(request(),out);assert.equal(out.statusCode,200);assert.equal(out.headers['Idempotency-Replayed'],'true');assert.deepEqual(out.value.data.body,command());});
