import assert from 'node:assert/strict';
import test from 'node:test';
import fs from 'node:fs';
import { normalizeClockOperationsQuery, getAttendanceClockOperations, assertClockOperationsResponse } from '../lib/internal-attendance-clock-operations.js';
import { createInternalAttendanceHandler } from '../api/internal-attendance.js';
const tenantId='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',memberId='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',sessionId='cccccccc-cccc-4ccc-8ccc-cccccccccccc',release='a'.repeat(40);
const principal={user:{email:'qa@example.test'},tenant:{source:'membership',id:tenantId,membershipId:memberId,certifiedReleaseSha:release}};
const session={id:sessionId,email:'qa@example.test',version:1,releaseSha:release};
const query=normalizeClockOperationsQuery();
function payload(){return {version:'clock-operations.v1',generatedAt:'2026-09-10T15:00:00Z',timezone:'America/Argentina/Mendoza',sites:[{key:'pm-10',label:'Edificio de prueba'}],site:{key:'pm-10',label:'Edificio de prueba'},filters:{from:'2026-09-10',to:'2026-09-10',anchoredToLatest:true},summary:{marks:1,people:1,mappedMarks:1,unmappedMarks:0,sourceRows:2,observedRows:1},collection:{status:'operator_snapshot',periodCoverageCertified:false,automaticCollectorVerified:false},records:[{ordinal:1,occurredAt:'2026-09-10T10:00:00Z',personLabel:'Persona 1A2B3C4D',legajo:null,method:'unknown',direction:'unknown'}],daily:[],hourly:[],observations:[],pagination:{page:1,pageSize:50,total:1,pages:1},nominalReadAllowed:false}}
function res(){return {headers:{},statusCode:200,setHeader(k,v){this.headers[k]=v},status(n){this.statusCode=n;return this},json(v){this.payload=v;return this}}}
function dependencies(extra={}){return {env:{NODE_ENV:'test',INTERNAL_CERTIFIED_DATA_CONTRACT_SHA:release},requireCompatibleInternalAccess:async()=>({mode:'managed',principal,session:{...session,mfa:true}}),getInternalSql:async()=>({query:async()=>[{result:payload()}]}),...extra}}
test('clock query defaults are explicit and bounded',()=>assert.deepEqual(query,{site:'pm-10',from:null,to:null,page:1,pageSize:50}));
for(const options of [{from:'2026-02-30',to:'2026-03-01'},{from:'2026-09-01'},{from:'2026-09-10',to:'2026-09-01'},{from:'2026-01-01',to:'2026-09-10'},{page:'1 OR 1=1'},{pageSize:101},{site:"pm-10'; DROP TABLE users--"},{page:0}])test('invalid clock query '+JSON.stringify(options),()=>assert.throws(()=>normalizeClockOperationsQuery(options),e=>e.status===400));
test('valid date interval including leap day',()=>assert.equal(normalizeClockOperationsQuery({from:'2024-02-29',to:'2024-03-01'}).from,'2024-02-29'));
test('clock reader sends only parameterized authorized coordinates',async()=>{let called;const result=await getAttendanceClockOperations({query:async(s,v)=>{called={s,v};return [{result:payload()}]}},principal,{},session);assert.equal(result.summary.marks,1);assert.match(called.s,/attendance_clock_operations_v1\(\$1/);assert.deepEqual(called.v,[session.email,sessionId,1,release,tenantId,memberId,'pm-10',null,null,1,50]);assert.ok(!called.s.includes(session.email))});
for(const changed of [{...session,email:'other@example.test'},{...session,id:'bad'},{...session,releaseSha:'b'.repeat(40)},{...session,version:0}])test('clock reader rejects invalid session '+JSON.stringify(changed),async()=>{await assert.rejects(()=>getAttendanceClockOperations({query(){throw new Error('SQL must not run')}},principal,{},changed),e=>e.status===401)});
for(const code of ['dni','rawAttendance','token','secret','identityHmac'])test('private field rejected '+code,()=>{const data=payload();data.records[0][code]='not-public';assert.throws(()=>assertClockOperationsResponse(data,query),e=>e.code==='ATTENDANCE_CONTRACT_DRIFT')});
test('snapshot reader never claims live telemetry',()=>{const data=payload();data.collection.automaticCollectorVerified=true;assert.throws(()=>assertClockOperationsResponse(data,query))});
test('snapshot reader never certifies coverage',()=>{const data=payload();data.collection.periodCoverageCertified=true;assert.throws(()=>assertClockOperationsResponse(data,query))});
test('site mismatch fails closed',()=>{const data=payload();data.site.key='other-site';assert.throws(()=>assertClockOperationsResponse(data,query))});
test('dates outside requested range fail closed',()=>{assert.throws(()=>assertClockOperationsResponse(payload(),{...query,from:'2026-08-01',to:'2026-08-31'}))});
test('unprivileged label cannot disclose a name',()=>{const data=payload();data.records[0].personLabel='Persona nominal';assert.throws(()=>assertClockOperationsResponse(data,query))});
test('privileged nominal label allowed only by SQL capability',()=>{const data=payload();data.nominalReadAllowed=true;data.records[0].personLabel='Nombre sintético';data.records[0].legajo='TEST-1';assert.equal(assertClockOperationsResponse(data,query),data)});
test('raw codes are not auto interpreted as entry or fingerprint',()=>{for(const key of ['method','direction']){const data=payload();data.records[0][key]=key==='method'?'fingerprint':'in';assert.throws(()=>assertClockOperationsResponse(data,query))}});
for(const [code,status]of [['ATTENDANCE_SESSION_INVALID',401],['ATTENDANCE_CAPABILITY_REQUIRED',403],['ATTENDANCE_RELEASE_NOT_CERTIFIED',503],['ATTENDANCE_BINDING_REQUIRED',503],['ATTENDANCE_SESSION_BUSY',409]])test('safe SQL status '+code,async()=>{await assert.rejects(()=>getAttendanceClockOperations({query:async()=>{throw new Error(code)}},principal,{},session),e=>e.status===status)});
test('missing migration returns actionable 503',async()=>{await assert.rejects(()=>getAttendanceClockOperations({query:async()=>{throw Object.assign(new Error('undefined function'),{code:'42883'})}},principal,{},session),e=>e.code==='ATTENDANCE_OPERATIONS_NOT_READY')});
test('HTTP route uses attendance capability and private cache headers',async()=>{let options;const handler=createInternalAttendanceHandler(dependencies({requireCompatibleInternalAccess:async(a,b,c)=>{options=c;return {mode:'managed',principal,session}}}));const response=res();await handler({method:'GET',query:{resource:'clock-operations'},headers:{}},response);assert.equal(response.statusCode,200);assert.equal(response.payload.summary.marks,1);assert.deepEqual(options.requiredCapabilities,['attendance.read']);assert.equal(options.allowLegacy,false);assert.equal(options.requireCertifiedDataBinding,true);assert.match(response.headers['Cache-Control'],/private, no-store/)});
test('HTTP request cannot select another tenant or membership',async()=>{const response=res();await createInternalAttendanceHandler(dependencies())({method:'GET',query:{resource:'clock-operations',tenantId:'other'},headers:{}},response);assert.equal(response.statusCode,400)});
test('HTTP duplicate query rejected',async()=>{const response=res();await createInternalAttendanceHandler(dependencies())({method:'GET',query:{resource:'clock-operations',site:['pm-10','pm-11']},headers:{}},response);assert.equal(response.statusCode,400)});
test('HTTP denied authentication never reaches operations SQL',async()=>{let count=0;const handler=createInternalAttendanceHandler(dependencies({requireCompatibleInternalAccess:async(_req,response)=>{response.status(401).json({ok:false});return null},getInternalSql:async()=>{count++;return null}}));const response=res();await handler({method:'GET',query:{resource:'clock-operations'},headers:{}},response);assert.equal(response.statusCode,401);assert.equal(count,0)});
test('HTTP membership is required even for clock snapshots',async()=>{const response=res();await createInternalAttendanceHandler(dependencies({requireCompatibleInternalAccess:async()=>({mode:'legacy'})}))({method:'GET',query:{resource:'clock-operations'},headers:{}},response);assert.equal(response.statusCode,403)});
test('HTML mounts behind existing auth shell and retains map linkage',()=>{const html=fs.readFileSync('relojes-marcaciones.html','utf8');assert.ok(html.indexOf('id="clockOperations"')>html.indexOf('id="appShell" hidden'));assert.match(html,/mc:attendance-site/);assert.match(html,/mc:attendance-ready/);assert.match(html,/Descargar esta página · CSV/);assert.match(html,/Sin impacto automático en nómina/)});
test('browser asset avoids HTML injection and durable nominal caching',()=>{const code=fs.readFileSync('assets/attendance-clock-operations.js','utf8');for(const forbidden of ['innerHTML','localStorage','sessionStorage','indexedDB'])assert.ok(!code.includes(forbidden));assert.match(code,/cache:'no-store'/);assert.match(code,/URL.revokeObjectURL/)});
