import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
import {readBudgetHistoricalEvidence,knownBudgetHistory,verifiedBudgetHistory} from '../assets/budget-historical-evidence.js';
const sha=s=>createHash('sha256').update(s).digest('hex'),id='11111111-1111-4111-8111-111111111111',tenant='22222222-2222-4222-8222-222222222222';
function fixture(){
 const source={version:'budget-position-source.v1',sourceSha256:'a'.repeat(64),logicalSha256:'b'.repeat(64),sourceDatabase:'qa_grh',sourceFooter:'2026-08-19 15:17:09',sourceTable:'histolegajo',company:'101',date:'2026-08-31',period:2026,month:8,type:'M',closedFlag:null,rows:[{number:'001',recordId:'1',role:'CARGO QA',structure:'11 - ESTRUCTURA QA',detail:'QA'},{number:'002',recordId:'2',role:'',structure:null,detail:null}]};
 const roster={version:'budget-payroll-roster.v1',tenantId:tenant,datasetId:id,date:source.date,type:source.type,total:2,sourceLabel:'Fuente sintética',closureStatus:'unknown',payloadHash:'c'.repeat(64),reportHash:'d'.repeat(64),official:false,rows:[{number:'001'},{number:'002'}]};
 const descriptor={...Object.fromEntries(['sourceSha256','logicalSha256','sourceDatabase','sourceFooter','company','date','period','month','type','closedFlag'].map(k=>[k,source[k]])),datasetId:id,payloadHash:roster.payloadHash,total:2,packageSha256:null};
 const encode=()=>{const bytes=new TextEncoder().encode(JSON.stringify(source));descriptor.packageSha256=sha(bytes);return bytes;};return{source,roster,descriptor,encode};
}
const execute=(f,bytes=f.encode())=>readBudgetHistoricalEvidence(bytes,f.roster,f.descriptor);
test('matched digest and complete literal population preserve missing fields without filling them',async()=>{const f=fixture(),r=await execute(f);assert.equal(verifiedBudgetHistory(r),r);assert.equal(r.rows[1].role,'');assert.equal(r.rows[1].structure,null);assert.equal(r.rows[0].number,'001');assert.ok(Object.isFrozen(r));assert.ok(Object.isFrozen(r.rows[0]));});
test('byte change is rejected before parsing nominal rows',async()=>{const f=fixture(),bytes=f.encode();bytes[0]=32;await assert.rejects(execute(f,bytes),{code:'HISTORY_HASH'});});
test('a matching row count does not replace exact membership',async()=>{const f=fixture();f.source.rows[1].number='003';await assert.rejects(execute(f),{code:'HISTORY_POPULATION'});});
test('equivalent numeric legajo is not silently substituted',async()=>{const f=fixture();f.source.rows[0].number='1';await assert.rejects(execute(f),{code:'HISTORY_POPULATION'});});
for(const key of ['number','recordId'])test('duplicate '+key+' is rejected',async()=>{const f=fixture();f.source.rows[1][key]=f.source.rows[0][key];await assert.rejects(execute(f),{code:'HISTORY_POPULATION'});});
for(const key of ['role','structure','detail'])test('control characters in '+key+' are rejected',async()=>{const f=fixture();f.source.rows[0][key]='QA\nDATA';await assert.rejects(execute(f),{code:'HISTORY_POPULATION'});});
for(const field of ['dni','name','amount','cuil'])test('unexpected private field '+field+' is refused',async()=>{const f=fixture();f.source.rows[0][field]='SYNTHETIC';await assert.rejects(execute(f),{code:'HISTORY_POPULATION'});});
for(const key of ['sourceSha256','logicalSha256','sourceDatabase','sourceFooter','company','date','period','month','type','closedFlag'])test('metadata mismatch '+key+' rejects even an internally rehashed file',async()=>{const f=fixture();f.source[key]=key==='period'?2025:key==='month'?7:key==='closedFlag'?1:'other';await assert.rejects(execute(f),{code:'HISTORY_CONTEXT'});});
for(const key of ['datasetId','payloadHash','date','type','total','closureStatus'])test('current authorized roster differs on '+key,async()=>{const f=fixture();if(key==='total'){f.roster.rows.push({number:'003'});f.roster.total++;}else f.roster[key]={datasetId:'33333333-3333-4333-8333-333333333333',payloadHash:'e'.repeat(64),date:'2026-07-31',type:'V',closureStatus:'closed'}[key];await assert.rejects(execute(f),{code:'HISTORY_CONTEXT'});});
test('more or fewer rows cannot become a complete population',async()=>{const f=fixture();f.source.rows.pop();await assert.rejects(execute(f),{code:'HISTORY_POPULATION'});});
test('unregistered dataset is never inferred from its month',async()=>{const f=fixture();assert.equal(knownBudgetHistory(f.roster),null);await assert.rejects(readBudgetHistoricalEvidence(f.encode(),f.roster),{code:'HISTORY_NOT_REGISTERED'});});
test('malformed UTF8 and JSON are rejected after a matching digest',async()=>{for(const bytes of [new Uint8Array([255]),new TextEncoder().encode('{')]){const f=fixture();f.descriptor.packageSha256=sha(bytes);await assert.rejects(execute(f,bytes),{code:'HISTORY_CONTRACT'});}});
for(const bytes of [new Uint8Array(),new Uint8Array(1500001),'text',null])test('size/type limit before processing',async()=>{const f=fixture();f.encode();await assert.rejects(execute(f,bytes),{code:'HISTORY_SIZE'});});
test('forged evidence and clones cannot enter the verified view',async()=>{const r=await execute(fixture());assert.throws(()=>verifiedBudgetHistory({...r}),{code:'HISTORY_UNVERIFIED'});assert.throws(()=>verifiedBudgetHistory({rows:[]}),{code:'HISTORY_UNVERIFIED'});});
for(const value of [false,2,'1',undefined])test('invalid declared closure '+String(value),async()=>{const f=fixture();f.descriptor.closedFlag=value;f.source.closedFlag=value;await assert.rejects(execute(f),{code:'HISTORY_CONTRACT'});});
test('input buffer mutation during hashing cannot replace verified content',async()=>{const f=fixture(),bytes=f.encode(),pending=execute(f,bytes);bytes.fill(32);assert.equal((await pending).rows.length,2);});

import {historyRows,historyCsv,historyPdf} from '../assets/budget-history-report.js';
test('history search preserves original strings and distinguishes null from empty',async()=>{const e=await execute(fixture());const original=JSON.stringify(e);assert.equal(historyRows(e,{query:'cargo qa'}).length,1);assert.equal(historyRows(e,{query:'002'}).length,1);assert.equal(historyRows(e,{query:'no coincide'}).length,0);assert.equal(JSON.stringify(e),original);const csv=historyCsv(e);assert.match(csv,/"001"/);assert.match(csv,/Vacío en origen/);assert.match(csv,/No informado/);});
test('CSV prevents formula execution without changing the stored source',async()=>{const f=fixture();f.source.rows[0].role='=SUM(A1:A2)';const e=await execute(f);assert.match(historyCsv(e),/"'=SUM/);assert.equal(e.rows[0].role,'=SUM(A1:A2)');});
test('CSV keeps complete selection, its date and the exact file fingerprint',async()=>{const f=fixture(),e=await execute(f),csv=historyCsv(e);assert.equal(csv.trim().split('\r\n').length,3);assert.equal((csv.match(new RegExp(e.descriptor.packageSha256,'g'))??[]).length,2);assert.match(csv,/2026-08-31/);});
test('PDF is generated only from verified evidence',async()=>{const e=await execute(fixture());const bytes=historyPdf(e);assert.ok(Buffer.from(bytes).toString('ascii').startsWith('%PDF-'));assert.throws(()=>historyPdf({...e}),{code:'HISTORY_UNVERIFIED'});});
test('PDF refuses text it cannot represent rather than replacing it',async()=>{const f=fixture();f.source.rows[0].role='漢字';const e=await execute(f);assert.throws(()=>historyPdf(e),{code:'HISTORY_TEXT_UNSUPPORTED'});assert.ok(historyCsv(e).includes('漢字'));});
for(const options of [{query:'x'.repeat(121)},{query:'bad\nline'},{query:null},{order:'name'},{order:'wrong'}])test('rejects unreviewed local filters '+JSON.stringify(options),async()=>{const e=await execute(fixture());assert.throws(()=>historyRows(e,options),{code:'HISTORY_FILTER'});});
test('report construction does not change source hashes or evidence rows',async()=>{const e=await execute(fixture()),before=JSON.stringify(e);historyPdf(e);historyCsv(e,{order:'role'});assert.equal(JSON.stringify(e),before);});
