import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
import {assessClockNetwork,ipv4,privateIpv4} from '../scripts/lib/clock-network-diagnostic.mjs';
import {renderNetworkRequest,main} from '../scripts/report-clock-network.mjs';
function sample(){return {schema:'clock-vpn-observation.v1',observedOn:'2026-09-18',timezone:'America/Argentina/Mendoza',sourceAddress:'10.9.0.6',vpnInterfaceIndex:12,vpnNextHop:'10.9.0.5',routes:['10.20.0.0/24'],probeLimitMs:3500,hardwareCommandsSent:false,routesChanged:false,evidenceSources:['synthetic unit test'],targets:[
 {code:'PM-01',name:'Sede QA conectada',ip:'10.20.0.10',port:4370,route:'10.20.0.0/24',nextHop:'10.9.0.5',interfaceIndex:12,test:'tcp_4370_connected'},
 {code:'PM-02',name:'Sede QA sin respuesta',ip:'10.20.0.11',port:4370,route:'10.20.0.0/24',nextHop:'10.9.0.5',interfaceIndex:12,test:'tcp_timeout'},
 {code:'PM-03',name:'Sede QA fuera VPN',ip:'192.168.3.10',port:4370,route:'0.0.0.0/0',nextHop:'192.168.1.1',interfaceIndex:6,test:'not_probed_outside_vpn'},
 {code:'PM-04',name:'Sede QA sin dirección',ip:null,port:4370,route:null,nextHop:null,interfaceIndex:null,test:'missing_address'}]};}
test('diagnosis separates routing, TCP availability and missing address without inventing operational reception',()=>{const x=sample(),copy=JSON.stringify(x),r=assessClockNetwork(x);assert.deepEqual(r.counts,{tcpReachable:1,vpnNoTcpResponse:1,outsideVpn:1,missingAddress:1});assert.ok(r.rows.every(t=>t.applicationVerified===false));assert.equal(JSON.stringify(x),copy);assert.equal(r.clockCommands,0);});
test('only RFC1918 ranges are private, not every 172 address',()=>{for(const ip of ['10.0.0.1','172.16.0.1','172.31.255.254','192.168.0.1'])assert.equal(privateIpv4(ip),true);for(const ip of ['172.15.255.254','172.32.0.1','100.64.0.1','198.51.100.1'])assert.equal(privateIpv4(ip),false);for(const ip of ['010.0.0.1','1.2.3.256','::1','1.2.3','1e2.0.0.1'])assert.throws(()=>ipv4(ip));});
test('a claimed public-path probe is rejected instead of recommending a broader scan',()=>{const x=sample();x.targets[2].test='tcp_timeout';assert.throws(()=>assessClockNetwork(x));});
for(const [label,patch] of [['different interface',x=>x.targets[0].interfaceIndex=6],['next hop drift',x=>x.targets[0].nextHop='10.9.0.1'],['unmatched network',x=>x.targets[0].route='10.21.0.0/24'],['ambiguous date',x=>x.observedOn='2026-02-30'],['duplicate PM',x=>x.targets[1].code='PM-01'],['duplicate IP',x=>x.targets[1].ip=x.targets[0].ip],['unknown extra field',x=>x.targets[0].credential='private'],['route change',x=>x.routesChanged=true]])test('reject untrustworthy observation: '+label,()=>{const x=sample();patch(x);assert.throws(()=>assessClockNetwork(x));});
test('IT request includes exact host destinations, missing mask qualifications and no request to publish clock ports',()=>{const x=sample(),txt=renderNetworkRequest(x,assessClockNetwork(x));assert.match(txt,/192\.168\.3\.10\/32/);assert.match(txt,/No solicitamos publicar los relojes/);assert.match(txt,/pool VPN/);assert.match(txt,/CGNAT/);assert.match(txt,/no acredita captura ni liquidación/);});
test('private report export does not overwrite existing notes and never opens a connection',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'clock-net-qa-'));try{const input=path.join(dir,'evidence.json'),output=path.join(dir,'request.md');await fs.writeFile(input,JSON.stringify(sample()));const r=await main(['--evidence',input,'--out',output]);assert.equal(r.networkChanges,0);const before=await fs.readFile(output,'utf8');await assert.rejects(main(['--evidence',input,'--out',output]));assert.equal(await fs.readFile(output,'utf8'),before);}finally{await fs.rm(dir,{recursive:true,force:true});}});
