import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {randomBytes} from 'node:crypto';
import {Outbox,rawRecords,captureRequest,enqueueCapture,deliver,cycle,validateConfig,acquireLock,readSecret} from '../services/pm10-collector/service.mjs';
import {collect} from '../services/pm10-collector/lector-fichadas.mjs';
import {sha256,validateCollectorRequest,validateCollectorReceipt} from '../lib/clock-collector-contract.js';
import {collectorPresentation} from '../assets/clock-collector-model.js';
import {dataSet,withClock,fakeKey} from './fixtures/collector-059/fixture.mjs';
const config={version:'0.59.0',endpoint:'https://municipio-junin-friendly.vercel.app/api/clock-collector',connectorKey:'junin-pm10-verified-snapshot',host:'172.100.97.131',port:4370,serial:'CQTU225360168',pollSeconds:60,stateDirectory:'/var/lib/test',credentialDirectory:'/run/creds',approved:true};
const token='synthetic-token-not-for-production-059',readAt='2026-09-12T18:00:00.000Z';
function payload(rows=rawRecords(dataSet(3))){return captureRequest(config,{records:rows,readAt,sourceSha256:sha256(dataSet(3)),pendingRecords:rows.length});}
function receipt(text,overrides={}){const j=JSON.parse(text);return {version:'clock-collector-receipt.v1',requestId:j.requestId,inputSha256:sha256(text),accepted:j.records.length,duplicates:0,observed:0,received:j.records.length,replayed:false,...overrides};}
function goodFetch(_url,options){return Promise.resolve(new Response(JSON.stringify({ok:true,receipt:receipt(options.body)}),{status:202}));}
async function boxTest(fn){const root=await fs.mkdtemp(path.join(os.tmpdir(),'mc059-'));const key=randomBytes(32);try{const box=new Outbox(root,key);await box.init();return await fn(box,key,root);}finally{await fs.rm(root,{recursive:true,force:true});}}
const report=raw=>({report:{status:'ATTENDANCE_DOWNLOADED_FOR_REVIEW',authenticationAccepted:true,attendanceTransferComplete:true,metadata:{serialNumber:config.serial},cleanup:{bufferReleaseConfirmed:true,exitConfirmed:true},finishedAt:readAt,transfer:{rawSha256:sha256(raw)},error:null},raw,parsed:{layout:'legacy-40-byte-candidate'}});
for(const change of [{approved:false},{host:'8.8.8.8'},{port:23},{serial:'WRONG'},{pollSeconds:1},{endpoint:'http://localhost'},{commkey:'1234'},{token:'secret'},{version:'unknown'}])test('configuration refuses unsafe override '+Object.keys(change)[0],()=>assert.throws(()=>validateConfig({...config,...change})));
test('approved pilot configuration retains exact host endpoint and interval',()=>assert.equal(validateConfig(config).pollSeconds,60));
for(const change of [{records:['zz']},{kind:null},{state:null},{requestId:null},{pendingRecords:'1'},{sourceSha256:null},{readAt:'2026-02-30T00:00:00.000Z'},{unexpected:1},{serial:null}])test('envelope rejects invalid '+Object.keys(change)[0],()=>assert.throws(()=>validateCollectorRequest({...payload(),...change})));
test('heartbeat reports no rows and cannot masquerade as a batch',()=>{assert.throws(()=>payload([]));});
test('raw framing only accepts complete 40-byte records',()=>{assert.equal(rawRecords(dataSet(3)).length,3);assert.throws(()=>rawRecords(Buffer.alloc(44)));assert.throws(()=>rawRecords(dataSet(3).subarray(0,43)));});
test('encrypted outbox survives restart and has no cleartext identifiers',()=>boxTest(async(box,key,root)=>{const j=payload();await box.enqueue(j);const [name]=await box.files();const bytes=await fs.readFile(path.join(root,'pending',name));assert.ok(!bytes.includes(Buffer.from('99000001')));assert.ok(!bytes.includes(Buffer.from(j.records[0])));const next=new Outbox(root,key);await next.init();assert.equal(await next.count(),3);assert.equal(await next.read(name),JSON.stringify(j));assert.equal(next.seen.size,3);}));
test('missing checkpoint after committed queue is reconstructed',()=>boxTest(async(box,key,root)=>{await box.enqueue(payload());await fs.unlink(path.join(root,'state.json'));const next=new Outbox(root,key);await next.init();assert.equal(next.seen.size,3);assert.equal(await next.count(),3);}));
test('tampered or wrong-key queue is not acknowledged',()=>boxTest(async(box,key,root)=>{await box.enqueue(payload());const next=new Outbox(root,randomBytes(32));await assert.rejects(next.init(),/SPOOL_CORRUPTED/);assert.equal((await box.files()).length,1);}));
test('mismatched receipt preserves queued evidence',()=>boxTest(async box=>{const j=payload();await box.enqueue(j);const [file]=await box.files(),text=await box.read(file);await assert.rejects(box.acknowledge(file,receipt(text,{requestId:'00000000-0000-4000-8000-000000000000'}),text),/RECEIPT/);assert.equal(await box.count(),3);}));
test('valid durable ACK removes batch, retains dedup checkpoint on restart',()=>boxTest(async(box,key,root)=>{const raw=dataSet(3);await enqueueCapture(box,config,report(raw));const [file]=await box.files(),text=await box.read(file);await box.acknowledge(file,receipt(text),text);assert.equal(await box.count(),0);const next=new Outbox(root,key);await next.init();assert.equal((await enqueueCapture(next,config,report(raw))).newRecords,0);assert.equal(await next.count(),0);}));
test('capture adds only changed record hash, not the entire buffer again',()=>boxTest(async box=>{assert.equal((await enqueueCapture(box,config,report(dataSet(3)))).newRecords,3);assert.equal((await enqueueCapture(box,config,report(dataSet(4)))).newRecords,1);assert.equal(await box.count(),4);}));
for(const tweak of [r=>r.report.metadata.serialNumber='WRONG',r=>r.report.attendanceTransferComplete=false,r=>r.report.cleanup.bufferReleaseConfirmed=false,r=>r.parsed.layout='other',r=>r.report.transfer.rawSha256='0'.repeat(64)])test('incomplete or mismatched physical capture never enqueued '+String(tweak),()=>boxTest(async box=>{const r=report(dataSet(3));tweak(r);await assert.rejects(enqueueCapture(box,config,r));assert.equal(await box.count(),0);}));
test('receiver retries cannot acknowledge HTTP or hash mismatches',async()=>{const text=JSON.stringify(payload());await assert.rejects(deliver(config,text,token,{fetchImpl:async()=>new Response('',{status:403})}),/BLOCK/);await assert.rejects(deliver(config,text,token,{fetchImpl:async()=>new Response(JSON.stringify({ok:true,receipt:receipt(text,{inputSha256:'0'.repeat(64)})}),{status:202})}),/RECEIPT/);});
test('one known key failure blocks instead of password iteration',()=>boxTest(async box=>{let reads=0;const options={credentials:async()=>token,fetchImpl:goodFetch,read:async()=>{reads++;return {report:{status:'AUTH_NOT_ACCEPTED'}};}};const r=await cycle(config,box,options);assert.equal(r.state,'blocked');assert.equal(reads,1);await assert.rejects(cycle(config,box,options),/PAUSED/);assert.equal(reads,1);}));
test('network outage preserves complete queued data for next cycle',()=>boxTest(async box=>{await assert.rejects(cycle(config,box,{credentials:async()=>token,read:async()=>report(dataSet(3)),fetchImpl:async()=>{throw Object.assign(new Error(),{code:'ECONNRESET'});}}));assert.equal(await box.count(),3);assert.equal(box.state.blocked,null);const r=await cycle(config,box,{credentials:async()=>token,read:async()=>report(dataSet(3)),fetchImpl:goodFetch});assert.equal(r.newRecords,0);assert.equal(r.pendingRecords,0);}));
test('receiver policy rejection blocks with queued evidence intact',()=>boxTest(async box=>{await assert.rejects(cycle(config,box,{credentials:async()=>token,read:async()=>report(dataSet(3)),fetchImpl:async()=>new Response('',{status:403})}),/BLOCK/);assert.equal(await box.count(),3);assert.equal(box.state.blocked,'RECEIVER_AUTH_OR_POLICY_BLOCK');}));
test('single instance lock prevents concurrent clock sessions',()=>boxTest(async(box,key,root)=>{const unlock=await acquireLock(root);await assert.rejects(acquireLock(root),/ALREADY_RUNNING/);await unlock();const second=await acquireLock(root);await second();}));
test('unsafe POSIX credential permissions rejected', {skip:process.platform==='win32'},()=>boxTest(async(box,key,root)=>{const f=path.join(root,'token');await fs.writeFile(f,token,{mode:0o644});await assert.rejects(readSecret(root,'token'),/PERMISSIONS/);await fs.chmod(f,0o600);assert.equal(await readSecret(root,'token'),token);}));
test('synthetic TCP clock through parser encrypted queue and validated receiver ACK',()=>withClock({count:3},async(port,commands)=>boxTest(async box=>{const result=await collect({host:'127.0.0.1',port,commKey:fakeKey(),approved:true,pacingMs:0,timeoutMs:500,totalMs:5000});await enqueueCapture(box,config,result);for(const f of await box.files()){const text=await box.read(f);const r=await deliver(config,text,token,{fetchImpl:goodFetch});await box.acknowledge(f,r,text);}assert.equal(await box.count(),0);assert.equal(box.seen.size,3);assert.equal(commands.filter(c=>c.code===1102).length,1);assert.ok(commands.every(c=>[1000,1102,11,50,201,1503,1504,1502,1001].includes(c.code)));})));
const status={ok:true,version:'clock-collector-status.v1',generatedAt:readAt,site:'pm-10',label:'PM-10',connectorState:'active',enabled:true,lastContactAt:readAt,lastReadAt:readAt,lastBatchAt:readAt,reportedState:'read_ok',pendingReported:0,captureLastAt:'2026-09-10T15:05:58.490Z',totals:{stored:0,normalized:0,observed:0},recent:[],payrollImpact:false};
for(const [changes,expected] of [[{connectorState:'suspended'},'paused'],[{enabled:false},'pending'],[{lastContactAt:null,lastReadAt:null},'pending'],[{lastContactAt:'2026-09-10T00:00:00.000Z'},'stale'],[{lastReadAt:'2026-09-10T00:00:00.000Z'},'warning'],[{pendingReported:4},'warning'],[{reportedState:'device_offline'},'warning'],[{reportedState:'blocked'},'blocked'],[{},'recent']])test('monitor distinguishes actual evidence state '+JSON.stringify(changes),()=>assert.equal(collectorPresentation({...status,...changes},Date.parse(readAt)).state,expected));
test('inconsistent counters fail instead of claiming online',()=>assert.throws(()=>collectorPresentation({...status,totals:{stored:10,normalized:8,observed:3}})));
