import test from 'node:test';import assert from 'node:assert/strict';
import {adoptionHistoryProof,readAdoptionHistory,AdoptionHistoryError} from '../lib/internal-employment-adoption-history.js';
import {employee,createInternalDataHandler} from '../api/internal-data.js';
import {proof,row,related,historySql,uid,binding,CONTRACT,TENANT,MEMBER,principal,session} from './fixtures/employment-adoption-history-synthetic.js';
import {readGrhConsumerSources,auditGrhPublicationConsumers,assertGrhConsumerCoverage} from '../scripts/lib/grh-publication-consumers.mjs';
import {buildAdoptionHistoryQa} from '../scripts/verify-employment-adoption-history-sql.mjs';
import {fileURLToPath} from 'node:url';
const expected={tenantId:TENANT,membershipId:MEMBER,contractId:CONTRACT};
const request={method:'GET',query:{resource:'employee',contractId:CONTRACT}};
const resolver=sql=>async id=>readAdoptionHistory(sql,principal,session,id,binding);
const response=()=>({headers:{},setHeader(k,v){this.headers[k]=v;},status(n){this.code=n;return this;},json(v){this.body=v;return this;}});
const handler=sql=>createInternalDataHandler({env:{FRIENDLY_GRH_SOURCE_DATABASE:binding.database,FRIENDLY_GRH_COMPANY_ID:String(binding.companyId)},requireCompatibleInternalAccess:async()=>({mode:'managed',principal}),actionMutationSession:()=>session,getInternalSql:async()=>sql,getActionCenterSql:async()=>sql,reportReadFailure:()=>{}});

test('closed SQL proof preserves opaque legajo and null/old civil dates without a new hire parser',()=>{
 const v=proof(),out=adoptionHistoryProof(v,expected);assert.deepEqual(out,v);assert.notEqual(out,v);v.contract.startDate='1888-02-29';assert.equal(adoptionHistoryProof(v,expected).contract.startDate,'1888-02-29');
});
for(const [label,change]of [
 ['additional payload',v=>v.rawIdentity={}],['missing identity fingerprint',v=>delete v.contract.identityReadVersion],['invalid date',v=>v.contract.startDate='2026-02-30'],['invalid cutoff',v=>v.history.cutoff='2026-01-01T24:00:00'],['scope company coercion',v=>v.scope.companyId='101'],['foreign origin',v=>v.history.origin='MUNICONTROL'],['unknown status',v=>v.contract.status='liquidated'],['invalid registration',v=>v.contract.registrationId='private'],['additional secret',v=>v.scope.secret='secret'],['missing source proof',v=>delete v.history.sourceSha256]
])test('malformed proof refuses '+label,()=>{const v=proof();change(v);assert.throws(()=>adoptionHistoryProof(v,expected),{code:'EMPLOYMENT_ADOPTION_HISTORY_INVALID'});});
for(const key of ['tenantId','membershipId','contractId'])test('proof is bound to '+key,()=>assert.throws(()=>adoptionHistoryProof(proof(),{...expected,[key]:uid(77)}),{status:409}));
test('RPC uses only validated session and exact UUID parameters and checks configured source',async()=>{
 const sql=historySql();assert.deepEqual(await resolver(sql)(CONTRACT),proof());assert.equal(sql.calls.length,1);assert.deepEqual(sql.calls[0].values,[JSON.stringify({actorEmail:session.email,actorSessionId:session.id,actorSessionVersion:session.version,releaseSha:session.releaseSha,tenantId:TENANT,membershipId:MEMBER}),CONTRACT]);
 for(const other of [{...binding,companyId:2},{...binding,database:'other'}])await assert.rejects(readAdoptionHistory(sql,principal,session,CONTRACT,other),{status:409});
});
test('canonical UUIDs accept uppercase links and arbitrary groups without a presumed UUID version',async()=>{
 const id='abcdefab-0000-0000-0000-abcdefabcdef',v=proof();v.contract.id=id;
 assert.equal(adoptionHistoryProof(v,{...expected,contractId:id.toUpperCase()}).contract.id,id);
 const detail={...row(),contractId:id},sql=historySql({detail,sourceRows:[],proofValue:v}),res=response();await handler(sql)({method:'GET',query:{resource:'employee',contractId:id.toUpperCase()}},res);assert.equal(res.code,200);assert.equal(sql.proofReads,2);assert.equal(res.body.data.contractId,id);
 const rpcSql=historySql({proofValue:v});await readAdoptionHistory(rpcSql,principal,session,id.toUpperCase(),binding);assert.equal(rpcSql.calls[0].values[1],id);
});
test('invalid session and read revocation execute no RPC',async()=>{
 const sql=historySql();await assert.rejects(readAdoptionHistory(sql,principal,{...session,email:'foreign@example.invalid'},CONTRACT),{status:401});
 await assert.rejects(readAdoptionHistory(sql,{...principal,tenant:{...principal.tenant,effectiveCapabilities:[]}},session,CONTRACT),{status:403});assert.equal(sql.calls.length,0);
});
for(const [error,status,code]of [['ACTION_SESSION_INVALID',401,'SESSION_INVALID'],['NATIVE_EMPLOYEE_FORBIDDEN',403,'FORBIDDEN'],['EMPLOYMENT_ADOPTION_HISTORY_SOURCE_CHANGED',409,'SOURCE_CHANGED'],['EMPLOYMENT_ADOPTION_HISTORY_NOT_FOUND',404,'NOT_FOUND'],['secret SQL unavailable',503,'INVALID']])test('RPC maps '+error+' without leaking database messages',async()=>{const sql=historySql({onProof:()=>Error(error)});await assert.rejects(resolver(sql)(CONTRACT),e=>e.status===status&&e.code==='EMPLOYMENT_ADOPTION_HISTORY_'+code&&!e.message.includes(error));});
test('adopted detail retains every returned relation and separates historical payroll/contact from current canonical status',async()=>{
 const sql=historySql(),relations=related(),r=await employee(sql,request,TENANT,{resolveAdoptionHistory:resolver(sql)});
 assert.equal(r.status,200);assert.equal(sql.proofReads,2);assert.equal(r.payload.data.legajo,'A/07');assert.equal(r.payload.data.recordOrigin,'MUNICONTROL');assert.equal(r.payload.data.activo,false);assert.equal(r.payload.data.liquidable,false);assert.equal(r.payload.data.payrollStatus,'not_liquidated');assert.equal(r.payload.data.administrativeStatus,'unknown');
 assert.deepEqual(r.payload.data.ausencias,relations.absences);assert.deepEqual(r.payload.data.licencias,relations.leaves);assert.deepEqual(r.payload.data.familiares,relations.family);assert.deepEqual(r.payload.data.movements,relations.movements);assert.equal(r.payload.data.movements[0].quantity,null);assert.equal(r.payload.data.movements[1].quantity,'0.0000');
 assert.equal(r.payload.data.history.employee.email,'historico@example.invalid');assert.equal(r.payload.data.email,undefined);assert.equal(r.payload.data.history.employee.statusSnapshot.payroll_status,'liquidated');assert.equal(r.payload.meta.history.readOnly,true);assert.equal(r.payload.meta.relationRowsComplete,true);assert.equal(Object.keys(r.payload.data).some(k=>k.startsWith('__')),false);
 assert.equal(r.payload.data.identityAssertions.some(x=>x.sourceSystem==='PERSONAS'),false);assert.equal(r.payload.data.sourceReferences.some(x=>x.sourceSystem==='PERSONAS'),false);
 const historyCall=sql.calls.find(x=>x.statement.includes('WHERE contract.person_id'));assert.deepEqual(historyCall.values,[row().canonicalPersonId,101,TENANT]);assert.match(historyCall.statement,/contract\.tenant_id=\$3::uuid/);
 for(const c of sql.calls)assert.doesNotMatch(c.statement,/\b(?:INSERT|UPDATE|DELETE|TRUNCATE|ALTER)\b/i);
});
test('fresh own hire keeps original short read without any history resolver or relation request',async()=>{const detail=row();detail.rawFields.native={registrationId:uid(2),legalReference:'Alta sintética',createdAt:'2026-10-01T12:00:00Z'};const sql=historySql({detail});const r=await employee(sql,request,TENANT,{resolveAdoptionHistory:()=>assert.fail('fresh hire must not read legacy history')});assert.equal(r.status,200);assert.equal(sql.calls.length,1);assert.deepEqual(r.payload.data.ausencias,[]);assert.equal(r.payload.meta.history,undefined);});
test('an unproven native marker cannot open historical relations',async()=>{const sql=historySql();await assert.rejects(employee(sql,request,TENANT),{code:'EMPLOYMENT_ADOPTION_HISTORY_UNAVAILABLE'});assert.equal(sql.calls.length,1);});
for(const key of ['readVersion','identityReadVersion','id','personId','legajo','registrationId'])test('a changed '+key+' suppresses all history reads',async()=>{const v=proof();v.contract[key]=key.endsWith('Version')?'f'.repeat(64):key==='legajo'?'other':uid(77);const sql=historySql();await assert.rejects(employee(sql,request,TENANT,{resolveAdoptionHistory:async()=>v}),{status:409});assert.equal(sql.calls.length,1);});
test('missing historical employee is reported as missing; duplicate correspondences fail closed',async()=>{for(const n of [0,2]){const relations=related();relations.archived=n?relations.archived.concat(relations.archived):[];const sql=historySql({relations});if(n)await assert.rejects(employee(sql,request,TENANT,{resolveAdoptionHistory:resolver(sql)}),{status:503});else{const r=await employee(sql,request,TENANT,{resolveAdoptionHistory:resolver(sql)});assert.equal(r.payload.data.history.employee,null);assert.deepEqual(r.payload.data.familiares,relations.family);}}});
test('year limits only relevant collections; opaque legajo is never parsed or interpolated',async()=>{const sql=historySql();await employee(sql,{query:{contractId:CONTRACT,recordYear:'2026'}},TENANT,{resolveAdoptionHistory:resolver(sql)});const c=sql.calls.find(x=>x.statement.includes('AS "absenceTotal"'));assert.deepEqual(c.values,[101,'A/07',CONTRACT,'2026-01-01','2027-01-01']);const family=sql.calls.find(x=>x.statement.includes('FROM grh_effective_family_v1 family'));assert.deepEqual(family.values,[101,'A/07']);assert.doesNotMatch(family.statement,/A\/07/);});
test('capped movements and events retain true totals and report an incomplete history',async()=>{const relations=related();relations.counts[0].movementTotal=31;relations.movements=Array.from({length:20},(_,i)=>({...relations.movements[0],sourceId:String(i)}));relations.counts[0].absenceTotal=57;relations.absences=Array.from({length:25},()=>relations.absences[0]);const sql=historySql({relations});const r=await employee(sql,request,TENANT,{resolveAdoptionHistory:resolver(sql)});assert.equal(r.payload.meta.relationRowsComplete,false);assert.equal(r.payload.meta.absenceTotal,57);assert.equal(r.payload.meta.movementTotal,31);assert.equal(r.payload.data.movements.length,20);});
for(const change of [r=>r.counts=[],r=>r.counts[0].absenceTotal=-1,r=>r.counts[0].absenceTotal=3,r=>r.absences=[]])test('missing or inconsistent counts never become a complete empty history '+change.toString(),async()=>{const relations=related();change(relations);const sql=historySql({relations});await assert.rejects(employee(sql,request,TENANT,{resolveAdoptionHistory:resolver(sql)}),{code:'EMPLOYMENT_ADOPTION_HISTORY_INCOMPLETE'});});
test('source/identity changes and revocation after relation reads suppress the entire response',async()=>{for(const code of ['NATIVE_EMPLOYEE_FORBIDDEN','ACTION_SESSION_INVALID','EMPLOYMENT_ADOPTION_HISTORY_SOURCE_CHANGED']){const sql=historySql({onProof:n=>n===2?Error(code):null});await assert.rejects(employee(sql,request,TENANT,{resolveAdoptionHistory:resolver(sql)}),AdoptionHistoryError);assert.equal(sql.proofReads,2);}const sql=historySql({proofValue:n=>{const v=proof();if(n===2)v.contract.identityReadVersion='f'.repeat(64);return v;}});await assert.rejects(employee(sql,request,TENANT,{resolveAdoptionHistory:resolver(sql)}),{status:409});});
for(const sourceRows of [[],[{token:'c'.repeat(64)}]])test('real GET handler reads adopted detail with '+(sourceRows.length?'remaining imported contracts':'zero imported contracts'),async()=>{const sql=historySql({sourceRows}),res=response();await handler(sql)(request,res);assert.equal(res.code,200);assert.equal(res.body.meta.currentEmploymentVerified,true);assert.equal(sql.proofReads,2);assert.match(res.headers['Cache-Control'],/private, no-store/);assert.equal(res.headers.Vary,'Cookie');assert.equal(sql.calls.some(c=>c.statement.includes('employment_lifecycle')),false);});
test('failed source sentinel is bypassed only for the exact proved adopted contract, never other resources',async()=>{for(const query of [{resource:'employee',contractId:'bad'},{resource:'employee',legajo:'A/07'},{resource:'employees'},{resource:'summary'}]){const sql=historySql({sourceRows:[]}),res=response();await handler(sql)({method:'GET',query},res);assert.notEqual(res.code,200);assert.equal(res.body.data,undefined);assert.equal(sql.proofReads,0);}});
test('lost proof after complete adoption returns an actionable error, with no nominal detail',async()=>{const sql=historySql({sourceRows:[],onProof:n=>n===2?Error('NATIVE_EMPLOYEE_FORBIDDEN'):null}),res=response();await handler(sql)(request,res);assert.equal(res.code,403);assert.equal(res.body.data,undefined);assert.doesNotMatch(JSON.stringify(res.body),/99999990|A\/07|historico/);});
test('registered history read sites still refuse a third unreviewed direct snapshot reference',async()=>{
 const sources=await readGrhConsumerSources(fileURLToPath(new URL('../',import.meta.url)));assertGrhConsumerCoverage(auditGrhPublicationConsumers(sources));
 sources['api/internal-data.js']=sources['api/internal-data.js'].replace('FROM employment_status_snapshot s WHERE','FROM employment_status_snapshot s JOIN employment_status_snapshot extra ON true WHERE');
 assert.throws(()=>assertGrhConsumerCoverage(auditGrhPublicationConsumers(sources)),{code:'GRH_CONSUMER_COVERAGE_INCOMPLETE'});
});
test('SQL history QA retains the original 615 checks and executes the read facade only after real synthetic adoption',()=>{
 for(const serverMajor of [17,18]){const qa=buildAdoptionHistoryQa({serverMajor});assert.equal(qa.report.checksPassed,636);assert.equal(qa.report.adoptionHistoryChecksPassed,21);assert.equal(qa.report.adoptionApplicationChecksPassed,45);assert.ok(qa.sql.indexOf('decision_result:=employment_adoption_decide_v1(checker,decision_body,decision_key)')<qa.sql.indexOf('history_proof:=employment_adoption_history_read_v1(maker'));assert.equal(qa.report.municipalRowsWritten,0);assert.equal(qa.report.concurrentConnectionCheck,false);}
});
