import assert from 'node:assert/strict';
import test from 'node:test';
import { employees,createInternalDataHandler } from '../api/internal-data.js';
import { pickerQuery,pickerResult } from '../assets/employee-picker-model.js';
const binding={database:'grh_qa',companyId:999};
const request=(search='Pérez')=>({method:'GET',query:Object.fromEntries(new URL(pickerQuery(search),'https://qa.invalid').searchParams)});
const row={contractId:'00000000-0000-4000-8000-000000000001',legajo:'1001',nombre:'Persona sintética',sector:'QA',convenio:'QA',activo:true,statusSnapshotDate:'2026-09-01',dni:'PRIVATE_NOT_RETURNED'};
function sqlMock(){const calls=[];return {calls,async query(sql,params){calls.push({sql,params});if(sql.includes('AS "sourceCutoffFrom"'))return [{sourceCutoffFrom:'2026-09-01',sourceCutoffTo:'2026-09-01'}];if(sql.includes('SELECT count(*)::int AS total FROM directory'))return [{total:1}];return [row];}};}
test('minimal active selector uses bound read queries and never returns DNI, CUIL or salary',async()=>{const sql=sqlMock(),result=await employees(sql,request(),binding);assert.equal(result.status,200);pickerResult(result.payload,1);assert.equal(sql.calls.length,3);for(const c of sql.calls){assert.deepEqual(c.params.slice(0,2),['grh_qa',999]);assert.doesNotMatch(c.sql,/\b(?:UPDATE|DELETE|INSERT)\b/);}const data=sql.calls.find(c=>c.sql.includes('LIMIT $'));assert.match(data.sql,/SELECT "contractId", legajo, nombre, sector, convenio, activo, "statusSnapshotDate" FROM directory/);assert.match(data.sql,/directory.activo IS TRUE/);assert.doesNotMatch(data.sql,/directory\.(dni|cuil) ILIKE/);assert.equal(JSON.stringify(result).includes('PRIVATE_NOT_RETURNED'),false);});
test('invalid view cannot query the database',async()=>{let calls=0;const sql={query:()=>{calls++;throw Error('unexpected')}};for(const q of [{...request().query,status:'all'},{...request().query,search:'a'},{...request().query,view:['novelty-selector']},{...request().query,sql:'SELECT'}]){const result=await employees(sql,{query:q},binding);assert.equal(result.status,400);}assert.equal(calls,0);});
test('unbound directory selector is unavailable instead of searching all sources',async()=>{let called=false;const result=await employees({query:()=>{called=true}},request(),null);assert.equal(result.status,400);assert.equal(called,false);});
test('selector wildcard and SQL-looking values remain bound literal search parameters',async()=>{const sql=sqlMock();await employees(sql,request("%_';--"),binding);const data=sql.calls.find(c=>c.sql.includes('LIMIT $'));assert.ok(data.params.some(p=>p==="%\\%\\_';--%"));assert.doesNotMatch(data.sql,/%_';--/);});
test('existing full directory behavior keeps previous search and response shape',async()=>{const sql=sqlMock();const q={resource:'employees',search:'QA',status:'administrative_active',includeFacets:'0',page:'1',limit:'20'};const result=await employees(sql,{query:q},binding);assert.equal(result.status,200);assert.ok(result.payload.operational);assert.equal(result.payload.version,undefined);const data=sql.calls.find(c=>c.sql.includes('LIMIT $'));assert.match(data.sql,/SELECT \* FROM directory/);assert.match(data.sql,/directory.dni ILIKE/);});
test('selector keeps mandatory managed access with workforce read capability and certified source',async()=>{let queried=false,options;const res={setHeader(){},status(){return this;},json(){return this;}};const handler=createInternalDataHandler({env:{},requireCompatibleInternalAccess:async(_req,_res,o)=>{options=o;return null;},getInternalSql:async()=>{queried=true;throw Error('not allowed');}});await handler(request(),res);assert.equal(queried,false);assert.deepEqual(options.requiredCapabilities,['workforce.employee.read']);assert.equal(options.requireCertifiedDataBinding,true);assert.equal(options.allowLegacy,false);});
