import test from 'node:test';import assert from 'node:assert/strict';
import {createFirmarJourney} from '../assets/firmar-journey.js';
const id=n=>`${String(n).padStart(8,'0')}-1111-4111-8111-111111111111`;
const NOW=Date.parse('2026-09-17T22:00:00.000Z');
const base=()=>({requestId:id(1),attemptId:id(2),expiresAt:new Date(NOW+25*60000).toISOString(),authorizationUrl:null,officialEmissionEnabled:false});
function setup(reply){let calls=0,closes=0;const states=[],navigations=[],j=createFirmarJourney({begin:async()=>{calls++;return reply;},readStatus:async()=>reply,onChange:v=>states.push(v),recoverAttempt:async()=>reply,openWindow:()=>({closed:false,opener:null,document:{title:'',createElement:()=>({}),body:{replaceChildren(){}}},location:{replace:u=>navigations.push(u)},close(){closes++;this.closed=true;}}),origin:'https://municipio-junin-friendly.vercel.app',now:()=>NOW,timer:()=>1,clearTimer:()=>{}});return{j,states,navigations,get calls(){return calls;},get closes(){return closes;}};}
for(const state of ['outcome_unknown','received_unverified','awaiting_receipt','cancelled','expired'])test('durable begin may return saved '+state+' without relaunching',async()=>{const t=setup({...base(),state});await t.j.start({requestId:id(1),expectedVersion:1});assert.equal(t.states.at(-1).state,state);assert.equal(t.calls,1);assert.equal(t.navigations.length,0);assert.ok(t.closes>=1);assert.equal(t.states.at(-1).canRetry,false);assert.equal(t.states.at(-1).officialEmissionEnabled,false);await assert.rejects(t.j.start({requestId:id(1),expectedVersion:1}));t.j.dispose();});
test('only a still-live authorization state opens official URL',async()=>{const u='https://tst.firmar.gob.ar/api/signatures/'+id(3),t=setup({...base(),state:'awaiting_authorization',authorizationUrl:u});await t.j.start({requestId:id(1),expectedVersion:1});assert.deepEqual(t.navigations,[u]);assert.equal(t.states.at(-1).state,'awaiting_authorization');t.j.dispose();});
test('expired launch URL cannot be opened despite an allowed host',async()=>{const t=setup({...base(),state:'awaiting_authorization',expiresAt:new Date(NOW-1000).toISOString(),authorizationUrl:'https://tst.firmar.gob.ar/api/signatures/'+id(3)});await t.j.start({requestId:id(1),expectedVersion:1});assert.equal(t.navigations.length,0);assert.equal(t.states.at(-1).canRetry,false);t.j.dispose();});
test('authorization URL hidden behind a receipt state is rejected',async()=>{const t=setup({...base(),state:'received_unverified',authorizationUrl:'https://tst.firmar.gob.ar/api/signatures/'+id(3)});await t.j.start({requestId:id(1),expectedVersion:1});assert.equal(t.navigations.length,0);assert.notEqual(t.states.at(-1).state,'received_unverified');t.j.dispose();});
import {createFirmarReturn} from '../assets/firmar-return.js';
test('temporary database contention keeps return token recoverable, without a signature resubmission',async()=>{const states=[],seen=[];let n=0;const c=createFirmarReturn({resolveReturn:async a=>{seen.push(a.returnState);if(!n++)throw Object.assign(Error('FIRMAR_BUSY'),{code:'FIRMAR_BUSY',status:409});return{requestId:id(1),attemptId:id(2),state:'return_bound',officialEmissionEnabled:false};},notifyHost:()=>{},onChange:s=>states.push(s),location:{hash:'#'+'A'.repeat(43),pathname:'/firmas/retorno'},history:{replaceState(){}},now:()=>NOW});await c.resume();assert.equal(states.at(-1).state,'return_retry');await c.resume();assert.equal(states.at(-1).state,'return_bound');assert.deepEqual(seen,['A'.repeat(43),'A'.repeat(43)]);c.dispose();});
