import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
import {normalizeWorkspaceQuery,checkWorkspaceData,sourceSelection,stateGroup} from '../assets/firmar-workspace-model.js';
import {createFirmarWorkspaceRepository,createFirmarWorkspaceHandler,workspaceContext} from '../lib/firmar-workspace.js';
import {createFirmarWorkspaceClient} from '../assets/firmar-workspace-client.js';
const id=n=>`${String(n).padStart(8,'0')}-1111-4111-8111-111111111111`,hash=b=>createHash('sha256').update(b).digest('hex');
const pdf=Buffer.from('%PDF-1.4\nTRANSPORT UNIT TEST ONLY\n%%EOF');const sha=hash(pdf);
const q={filter:'all',search:'',page:1,pageSize:10};
const row=(patch={})=>({requestId:id(4),title:'Informe de prueba',documentKind:'institutional.report',version:1,sourceVersionId:id(5),sourceSha256:sha,sourceBytes:pdf.length,createdAt:'2026-09-17T19:00:00.000Z',state:'prepared',attemptId:null,expiresAt:null,canReview:true,...patch});
const data=(patch={})=>({schema:'firmar-workspace.v1',checkedAt:'2026-09-17T19:00:00.000Z',query:{...q},counts:{all:1,pending:1,attention:0,received:0,cancelled:0},pagination:{page:1,pageSize:10,total:1,pages:1},documents:[row()],officialEmissionEnabled:false,...patch});
const context={actorEmail:'fd-one@example.invalid',actorSessionId:id(1),actorSessionVersion:1,membershipId:id(2),tenantId:id(3)};
const access=()=>({mode:'managed',principal:{user:{email:context.actorEmail},tenant:{id:context.tenantId,membershipId:context.membershipId,source:'membership'}},session:{id:context.actorSessionId,email:context.actorEmail,version:1}});
const env={FIRMAR_HTTP_PILOT_ENABLED:'true',FIRMAR_ENVIRONMENT:'test',FIRMAR_APP_ORIGIN:'https://municipio-junin-friendly.vercel.app',FIRMAR_TENANT_ID:context.tenantId};
const listUrl='/api/internal-firmar-workspace?'+new URLSearchParams({operation:'list',...q});
const sourceUrl='/api/internal-firmar-workspace?'+new URLSearchParams({operation:'source',requestId:id(4),version:1,sha256:sha});
function req(url=listUrl){return{method:'GET',url,headers:{'x-municontrol-intent':'signing-v1',origin:env.FIRMAR_APP_ORIGIN,'sec-fetch-site':'same-origin'}};}
function res(){return{headers:{},setHeader(k,v){this.headers[k.toLowerCase()]=v;},status(v){this.statusCode=v;return this;},json(x){this.headers['content-type']='application/json';this.body=x;return this;},end(x){this.body=x;return this;}};}
function harness(patch={}){const calls=[];return{calls,handler:createFirmarWorkspaceHandler({env,authorize:async()=>{calls.push('authorize');return access();},repositoryFor:async()=>({list:async(c,query)=>{calls.push('list');assert.deepEqual(c,context);assert.deepEqual(query,q);return data();},source:async(c,s)=>{calls.push('source');assert.deepEqual(c,context);assert.equal(s.sha256,sha);return pdf;}}),takeBudget:async()=>{calls.push('budget');return{allowed:true};},signingReady:()=>true,...patch})};}
test('normalized filters and counts model is not a pending simulation',()=>{assert.deepEqual(normalizeWorkspaceQuery(q),q);assert.equal(checkWorkspaceData({...data(),signingReady:false},q).counts.all,1);assert.equal(stateGroup('received_unverified'),'received');});
for(const patch of [{filter:'valid'},{page:0},{page:10000},{page:'01'},{pageSize:500},{search:' x '},{search:'a'.repeat(121)},{search:'\n'},{tenantId:id(9)}])test('invalid query '+Object.keys(patch),()=>assert.throws(()=>normalizeWorkspaceQuery({...q,...patch})));
for(const patch of [{officialEmissionEnabled:true},{signingReady:'yes'},{counts:{all:2,pending:1,attention:0,received:0,cancelled:0}},{documents:[]},{query:{...q,page:2}},{pagination:{page:1,pageSize:10,total:1,pages:2}},{documents:[row({state:'verified'})]},{documents:[row({sourceSha256:'wrong'})]},{documents:[row({canReview:false})]},{documents:[row({secret:'NO'})]}])test('invalid response '+Object.keys(patch),()=>assert.throws(()=>checkWorkspaceData({...data(),signingReady:false,...patch},q)));
test('cancellation before any attempt is represented without inventing an attempt',()=>{const x={...data(),documents:[row({state:'cancelled',canReview:false})],counts:{all:1,pending:0,attention:0,received:0,cancelled:1},signingReady:false};assert.equal(checkWorkspaceData(x,q).documents[0].attemptId,null);});
test('sub-millisecond creation order does not become a false id-sort mismatch',()=>{const x={...data(),documents:[row({requestId:id(4),createdAt:'2026-09-17T19:00:00.000800Z'}),row({requestId:id(5),createdAt:'2026-09-17T19:00:00.000700Z'})],counts:{all:2,pending:2,attention:0,received:0,cancelled:0},pagination:{...data().pagination,total:2},signingReady:false};assert.equal(checkWorkspaceData(x,q).documents.length,2);});
test('actor derived solely from verified session, no employment linkage',()=>assert.deepEqual(workspaceContext(access()),context));
for(const change of [x=>x.mode='legacy',x=>x.session.email='someone-else@example.invalid',x=>x.principal.tenant.source='override',x=>x.session.version=0])test('invalid actor rejects '+change,()=>{const x=access();change(x);assert.throws(()=>workspaceContext(x));});
test('valid list uses verified context and private response',async()=>{const t=harness(),r=res();await t.handler(req(),r);assert.equal(r.statusCode,200);assert.equal(r.body.data.signingReady,true);assert.deepEqual(t.calls,['authorize','budget','list']);assert.match(r.headers['cache-control'],/no-store/);assert.equal(r.headers['referrer-policy'],'no-referrer');assert.ok(!JSON.stringify(r.body).includes(context.actorEmail));});
test('source response returns exact prepared bytes, not a signed-document representation',async()=>{const t=harness(),r=res();await t.handler(req(sourceUrl),r);assert.equal(r.statusCode,200);assert.deepEqual(r.body,pdf);assert.equal(r.headers['content-type'],'application/pdf');assert.equal(r.headers['x-municontrol-source-sha256'],sha);assert.match(r.headers['content-disposition'],/documento-preparado.pdf/);assert.match(r.headers['content-security-policy'],/sandbox/);});
for(const change of [x=>x.method='POST',x=>x.headers.origin='https://other.invalid',x=>delete x.headers['x-municontrol-intent'],x=>x.headers['sec-fetch-site']='cross-site',x=>x.headers.range='bytes=0-9',x=>x.headers['content-length']='1',x=>x.body='{}',x=>x.url+='&page=2',x=>x.url+='&tenantId='+id(9),x=>x.query={operation:'list'},x=>x.headers['X-MuniControl-Intent']='signing-v1',x=>x.rawHeaders=['Origin','a','origin','b']])test('invalid read request never reaches SQL '+change,async()=>{const t=harness(),r=res(),x=req();change(x);await t.handler(x,r);assert.ok([400,403,405].includes(r.statusCode));assert.equal(t.calls.length,0);});
for(const changed of [{FIRMAR_HTTP_PILOT_ENABLED:'false'},{FIRMAR_ENVIRONMENT:'production'},{FIRMAR_APP_ORIGIN:'https://other.invalid'}])test('production and disabled pilot are refused '+Object.keys(changed),async()=>{const t=harness({env:{...env,...changed}}),r=res();await t.handler(req(),r);assert.equal(r.statusCode,503);assert.equal(t.calls.length,0);});
test('rate budget fail closed and does not select repository',async()=>{const t=harness({takeBudget:async()=>({allowed:false})}),r=res();await t.handler(req(),r);assert.equal(r.statusCode,429);assert.equal(r.headers['retry-after'],'60');assert.ok(!t.calls.includes('list'));});
test('cross-tenant session not substituted by supplied query',async()=>{const t=harness({authorize:async()=>({...access(),principal:{...access().principal,tenant:{...access().principal.tenant,id:id(99)}}})}),r=res();await t.handler(req(),r);assert.equal(r.statusCode,403);assert.equal(t.calls.length,0);});
test('repository uses parameterized facades, returns safe projection',async()=>{const calls=[];const repo=createFirmarWorkspaceRepository({query:async(sql,params)=>{calls.push({sql,params});return[{result:data()}];}});await repo.list(context,q);assert.equal(calls.length,1);assert.match(calls[0].sql,/\$1::jsonb/);assert.deepEqual(JSON.parse(calls[0].params[0]),context);assert.ok(!calls[0].sql.includes(context.actorEmail));});
test('corrupt prepared source cannot be delivered even when claimed hash matches selection',async()=>{const repo=createFirmarWorkspaceRepository({query:async()=>[{result:{requestId:id(4),version:1,sourceSha256:sha,pdfBase64:Buffer.from('%PDF-1.4 wrong').toString('base64')}}]});await assert.rejects(repo.source(context,{requestId:id(4),version:1,sha256:sha}));});
test('database error cannot leak a connection string or document',async()=>{const repo=createFirmarWorkspaceRepository({query:async()=>{throw Error('postgresql://SECRET@host/private');}});await assert.rejects(repo.list(context,q),e=>!e.message.includes('SECRET')&&e.code==='FIRMAR_WORKSPACE_UNAVAILABLE');});
function httpResponse(body,headers={}){return new Response(body,{status:200,headers:{'cache-control':'private, no-store',...headers}});}
const digest=b=>Promise.resolve(createHash('sha256').update(b).digest());
test('browser list validates server counts, projection and request echo',async()=>{let options;const c=createFirmarWorkspaceClient({fetchImpl:async(u,o)=>{options=o;return httpResponse(JSON.stringify({ok:true,data:{...data(),signingReady:false}}),{'content-type':'application/json'});},digest});assert.equal((await c.list(q)).documents.length,1);assert.equal(options.method,'GET');assert.equal(options.credentials,'same-origin');assert.equal(options.cache,'no-store');assert.equal(options.redirect,'error');});
test('browser verifies exact bytes and headers independently before exposing a PDF',async()=>{const c=createFirmarWorkspaceClient({fetchImpl:async()=>httpResponse(pdf,{'content-type':'application/pdf','content-length':String(pdf.length),'x-municontrol-source-sha256':sha,'x-municontrol-source-version':'1','x-municontrol-request-id':id(4)}),digest});assert.equal(hash(await c.source({requestId:id(4),version:1,sha256:sha})),sha);});
for(const patch of [{'x-municontrol-source-sha256':'0'.repeat(64)},{'content-length':'999'},{'content-type':'text/html'},{'x-municontrol-request-id':id(77)},{'cache-control':'public, max-age=3600'}])test('browser refuses inconsistent PDF headers '+Object.keys(patch),async()=>{const c=createFirmarWorkspaceClient({fetchImpl:async()=>httpResponse(pdf,{'content-type':'application/pdf','content-length':String(pdf.length),'x-municontrol-source-sha256':sha,'x-municontrol-source-version':'1','x-municontrol-request-id':id(4),...patch}),digest});await assert.rejects(c.source({requestId:id(4),version:1,sha256:sha}));});
test('browser abort during digest never exposes completed private bytes',async()=>{const controller=new AbortController();const c=createFirmarWorkspaceClient({fetchImpl:async()=>httpResponse(pdf,{'content-type':'application/pdf','content-length':String(pdf.length),'x-municontrol-source-sha256':sha,'x-municontrol-source-version':'1','x-municontrol-request-id':id(4)}),digest:async b=>{controller.abort();return digest(b);}});await assert.rejects(c.source({requestId:id(4),version:1,sha256:sha},{signal:controller.signal}),e=>e.name==='AbortError');});
