import test from 'node:test';import assert from 'node:assert/strict';
import {createFirmarHttpHandlers,readFirmarHttpJson,signingSessionContext} from '../lib/firmar-http.js';
import {createFirmarRuntime} from '../lib/firmar-http-runtime.js';
import {FirmarPersistenceError} from '../lib/firmar-durable-repository.js';
const id=n=>`${String(n).padStart(8,'0')}-1111-4111-8111-111111111111`,O='https://municipio-junin-friendly.vercel.app';
const env=()=>({FIRMAR_ENVIRONMENT:'test',FIRMAR_INTEGRATION_APPROVAL_REF:'SYNTHETIC-PILOT-NOT-ENROLLED',FIRMAR_API_USER:'fake',FIRMAR_API_SECRET:'fake-noncredential',FIRMAR_TENANT_ID:id(3),FIRMAR_CALLBACK_PROFILE:'pfdr-v13-object',FIRMAR_APP_ORIGIN:O,FIRMAR_CALLBACK_REGISTERED:'true',FIRMAR_DIRECT_ENABLED:'true',FIRMAR_HTTP_PILOT_ENABLED:'true'});
const access=()=>({mode:'managed',principal:{user:{email:'qa@example.invalid'},tenant:{id:id(3),membershipId:id(2),source:'membership'}},session:{email:'qa@example.invalid',id:id(1),version:1}});
const view=()=>({requestId:id(4),attemptId:id(6),expiresAt:new Date(Date.now()+1200000).toISOString(),state:'outcome_unknown',authorizationUrl:null,officialEmissionEnabled:false});
const response=()=>({headers:{},setHeader(k,v){this.headers[k.toLowerCase()]=v;},status(s){this.statusCode=s;return this;},json(b){this.body=b;return this;}});
const req=(op='begin')=>op==='callback'?{method:'POST',url:'/api/firmar-callback',headers:{'content-type':'application/json'},body:'{}'}:
 {method:op==='begin'||op==='return'?'POST':'GET',url:'/api/internal-firmar'+(op==='begin'||op==='return'?'':`?operation=${op}&requestId=${id(4)}${op==='status'?'&attemptId='+id(6):''}`),headers:{'x-municontrol-intent':'signing-v1',origin:O,'sec-fetch-site':'same-origin',...(op==='begin'||op==='return'?{'content-type':'application/json'}:{})},...(op==='begin'?{body:JSON.stringify({operation:'begin',requestId:id(4),expectedVersion:1,sourceSha256:'a'.repeat(64)})}:op==='return'?{body:JSON.stringify({operation:'return',state:'a'.repeat(42)+'A'})}:{})};
function setup(options={}){
 const calls=[],settings={...env(),...options.env};const result=options.result;
 const service={};for(const op of ['begin','prepared','status','recover','resolveReturn','receiveCallback'])service[op]=async args=>{calls.push({op,args});if(options.error)throw options.error;if(result)return result;return op==='prepared'?{requestId:id(4),version:1,sourceVersionId:id(5),sourceSha256:'a'.repeat(64),bytes:123,officialEmissionEnabled:false}:op==='resolveReturn'?{requestId:id(4),attemptId:id(6),state:'return_bound',officialEmissionEnabled:false}:op==='receiveCallback'?{outcome:'received_unverified',receiptId:id(9),providerAuthenticated:false,cryptographicValidation:'not_performed',officialEmissionEnabled:false,sha256:'x',replayed:false}:view();};
 const handlers=createFirmarHttpHandlers({env:settings,authorize:async(q,r)=>{calls.push({op:'auth'});if(options.noAuth){r.status(401).json({ok:false});return null;}return options.access??access();},serviceFor:async()=>{calls.push({op:'service'});return service;},takeBudget:async(scope,key)=>{calls.push({op:'budget',scope,key});return{allowed:options.budget!==false};},bodyDeadlineMs:options.deadline??12000});
 return {calls,handlers};
}
for(const operation of ['prepared','begin','recover','status','return'])test('authorized '+operation+' uses session-derived identity and no-store',async()=>{const t=setup(),r=response();await t.handlers.interactive(req(operation),r);assert.equal(r.statusCode,200);assert.match(r.headers['cache-control'],/no-store/);assert.equal(r.headers['x-frame-options'],'DENY');const call=t.calls.find(c=>c.op===({return:'resolveReturn'}[operation]||operation));assert.equal(call.args.context.actorEmail,'qa@example.invalid');assert.equal(call.args.context.tenantId,id(3));assert.ok(!JSON.stringify(r.body).includes('qa@example.invalid'));assert.ok(!JSON.stringify(r.body).includes('fake-noncredential'));if(operation==='begin')assert.equal(call.args.expectedSha256,'a'.repeat(64));});
for(const patch of [{FIRMAR_HTTP_PILOT_ENABLED:'false'},{FIRMAR_ENVIRONMENT:'production'},{FIRMAR_DIRECT_ENABLED:'false'},{FIRMAR_CALLBACK_REGISTERED:'false'},{FIRMAR_API_SECRET:''}])test('disabled gate does not read identity, DB or body '+Object.keys(patch),async()=>{for(const type of ['interactive','callback']){const t=setup({env:patch}),r=response(),q=req(type==='callback'?'callback':'begin');q.body=undefined;q[Symbol.asyncIterator]=async function*(){assert.fail('must not consume body');};await t.handlers[type](q,r);assert.equal(r.statusCode,503);assert.equal(t.calls.length,0);}});
for(const mutate of [q=>q.headers.origin='https://evil.invalid',q=>delete q.headers.origin,q=>q.headers.origin='null',q=>q.headers['sec-fetch-site']='same-site',q=>delete q.headers['x-municontrol-intent'],q=>q.headers['x-municontrol-intent']='wrong',q=>q.headers['Origin']=O,q=>q.headers.origin=[O],q=>q.rawHeaders=['Origin',O,'origin',O]])test('CSRF/ambiguous origin rejected '+mutate,async()=>{const t=setup(),q=req(),r=response();mutate(q);await t.handlers.interactive(q,r);assert.ok([400,403].includes(r.statusCode));assert.equal(t.calls.length,0);});
for(const url of ['/api/internal-firmar?state=secret','/api/internal-firmar?operation=begin','//evil.invalid/api/internal-firmar','/api/internal-firmar#secret','/api/internal-firmar\\anything','https://municipio-junin-friendly.vercel.app/api/internal-firmar'])test('query does not carry return secrets or override commands '+url,async()=>{const t=setup(),q=req(),r=response();q.url=url;await t.handlers.interactive(q,r);assert.equal(r.statusCode,400);assert.equal(t.calls.length,0);});
test('duplicate query or disagreement with parsed query is rejected',async()=>{for(const suffix of ['&requestId='+id(4),'']){const t=setup(),q=req('status'),r=response();q.url+=suffix;if(!suffix)q.query={operation:'status',requestId:id(99),attemptId:id(6)};await t.handlers.interactive(q,r);assert.equal(r.statusCode,400);assert.equal(t.calls.length,0);}});
for(const patch of [{tenantId:id(3)},{actorEmail:'fake@other.invalid'},{pdfBase64:'abc'},{approved:true},{operation:'emit'},{pin:'never-store'},{sourceSha256:'bad'},{expectedVersion:'1'}])test('browser cannot grant authority, supply PDF or emit '+Object.keys(patch),async()=>{const t=setup(),q=req(),r=response();q.body=JSON.stringify({...JSON.parse(q.body),...patch});await t.handlers.interactive(q,r);assert.equal(r.statusCode,400);assert.ok(!t.calls.some(c=>c.op==='service'));});
for(const patch of [{mode:'legacy'},{session:{...access().session,email:'other@example.invalid'}},{principal:{...access().principal,tenant:{...access().principal.tenant,source:'platform'}}},{principal:{...access().principal,tenant:{...access().principal.tenant,id:id(99)}}}])test('unbound actor rejected without signing or employee lookup '+Object.keys(patch),async()=>{const t=setup({access:{...access(),...patch}}),r=response();await t.handlers.interactive(req(),r);assert.ok([401,403].includes(r.statusCode));assert.ok(!t.calls.some(c=>c.op==='service'));});
test('anonymous request does not consume body or reach service',async()=>{const t=setup({noAuth:true}),q=req(),r=response();delete q.body;q[Symbol.asyncIterator]=async function*(){assert.fail('not read');};await t.handlers.interactive(q,r);assert.equal(r.statusCode,401);assert.deepEqual(t.calls,[{op:'auth'}]);});
test('persistent budget is required before body parsing, never derived from raw user headers',async()=>{for(const callback of [false,true]){const t=setup({budget:false}),q=req(callback?'callback':'begin'),r=response();delete q.body;q.headers['x-forwarded-for']='arbitrary';q[Symbol.asyncIterator]=async function*(){assert.fail('not read');};await t.handlers[callback?'callback':'interactive'](q,r);assert.equal(r.statusCode,429);assert.equal(r.headers['retry-after'],'60');assert.ok(!t.calls.some(c=>c.op==='service'));assert.equal(t.calls.at(-1).key,callback?id(3):id(3)+':'+id(2));}});
for(const header of [{'content-type':'text/plain'},{'content-type':'application/json; charset=latin1'},{'content-encoding':'gzip'},{'content-length':'030'},{'content-length':'-1'},{'content-length':'65536'},{'content-length':'30','transfer-encoding':'chunked'}])test('bounded envelope '+JSON.stringify(header),async()=>{const t=setup(),q=req(),r=response();Object.assign(q.headers,header);await t.handlers.interactive(q,r);assert.ok([400,413,415].includes(r.statusCode));assert.equal(t.calls.length,0);});
test('already parsed object is rejected: route must disable framework body parser',async()=>{const t=setup(),q=req(),r=response();q.body=JSON.parse(q.body);await t.handlers.interactive(q,r);assert.equal(r.statusCode,400);assert.ok(!t.calls.some(c=>c.op==='service'));});
test('UTF-8 is strict, empty/malformed JSON and dishonest Content-Length fail',async()=>{for(const body of [Buffer.from([0xff]),'[]','null','{',JSON.stringify({})]){const t=setup(),q=req(),r=response();q.body=body;q.headers['content-length']='7';await t.handlers.interactive(q,r);assert.equal(r.statusCode,400);assert.ok(!t.calls.some(c=>c.op==='service'));}});
test('stream overflow stops consuming immediately',async()=>{const q=req();delete q.body;let reads=0;q[Symbol.asyncIterator]=async function*(){reads++;yield Buffer.alloc(3073);reads++;assert.fail('second read');};const t=setup(),r=response();await t.handlers.interactive(q,r);assert.equal(r.statusCode,413);assert.equal(reads,1);});
test('slow body times out without calling service',async()=>{const t=setup({deadline:5}),q=req(),r=response();delete q.body;q[Symbol.asyncIterator]=()=>({next:()=>new Promise(()=>{}),return:()=>Promise.resolve({done:true})});await t.handlers.interactive(q,r);assert.equal(r.statusCode,408);assert.ok(!t.calls.some(c=>c.op==='service'));});
test('callback has no browser session, ignores no cookies and echoes no identifiers',async()=>{const t=setup(),r=response();await t.handlers.callback(req('callback'),r);assert.equal(r.statusCode,201);assert.ok(!t.calls.some(c=>c.op==='auth'));assert.deepEqual(Object.keys(r.body).sort(),['cryptographicValidation','officialEmissionEnabled','ok','outcome','providerAuthenticated']);assert.equal(r.body.cryptographicValidation,'not_performed');});
for(const header of [{cookie:'private-session'},{origin:O},{'sec-fetch-site':'same-origin'}])test('browser callback upload is denied '+Object.keys(header),async()=>{const t=setup(),r=response(),q=req('callback');Object.assign(q.headers,header);await t.handlers.callback(q,r);assert.equal(r.statusCode,400);assert.equal(t.calls.length,0);});
for(const code of ['FIRMAR_NOT_FOUND','FIRMAR_REQUEST_CANCELLED','FIRMAR_ATTEMPT_EXPIRED','FIRMAR_AUTHORITY_REQUIRED'])test('callback does not enumerate '+code,async()=>{const t=setup({error:new FirmarPersistenceError(code)}),r=response();await t.handlers.callback(req('callback'),r);assert.equal(r.statusCode,400);assert.equal(r.body.code,'FIRMAR_CALLBACK_INVALID');});
test('unrecognized exception never echoes secrets and never permits retry',async()=>{const t=setup({error:Error('password:private-DNI-doc-callback-token')}),r=response();await t.handlers.interactive(req(),r);assert.equal(r.statusCode,503);assert.ok(!JSON.stringify(r.body).includes('private'));assert.equal(r.body.safeToRetry,false);assert.equal(r.body.officialEmissionEnabled,false);});
test('runtime bypasses neither identity authentication nor persisted limiter',async()=>{const calls=[],r=response();const sql={query:async(statement,args)=>{calls.push({statement,args});throw Error('stop before data');}};const runtime=createFirmarRuntime({env:env(),requireAccess:async(q,r,options)=>{assert.equal(options.allowLegacy,false);assert.equal(options.requireDataPlaneReady,false);return access();},getSql:async()=>sql,limit:async(s,scope,hash,opts)=>{assert.equal(s,sql);assert.match(scope,/^firmar.http./);assert.match(hash,/^[a-f0-9]{64}$/);assert.equal(opts.windowSeconds,60);return{allowed:false};}});await runtime.interactive(req(),r);assert.equal(r.statusCode,429);assert.equal(calls.length,0);});
