import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
import {createFirmarPgRepository,firmarActorContext,checkedFirmarAttempt,checkedFirmarSource} from '../lib/firmar-durable-repository.js';
const id=n=>`${String(n).padStart(8,'0')}-1111-4111-8111-111111111111`,sha=x=>createHash('sha256').update(x).digest('hex');
const context=()=>({actorEmail:'signer@example.invalid',actorSessionId:id(1),actorSessionVersion:1,membershipId:id(2),tenantId:id(3)});
function source(){const pdf=Buffer.from('%PDF-1.4\nQA SYNTHETIC ENVELOPE - NOT A REAL SIGNED PDF\n%%EOF');const prefix='2099999999';const sum=[5,4,3,2,7,6,5,4,3,2].reduce((s,w,i)=>s+w*Number(prefix[i]),0);const d=11-sum%11;return{requestId:id(4),version:1,sourceVersionId:id(5),sourceSha256:sha(pdf),pdfBase64:pdf.toString('base64'),signerCuil:prefix+(d===11?0:d===10?9:d),sourceValidationRef:'synthetic-upstream-parser-reference',approvalRef:'synthetic-explicit-approval'};}
const view=()=>({requestId:id(4),attemptId:id(6),expiresAt:'2026-09-17T20:00:00.000Z',state:'outcome_unknown',authorizationUrl:null,officialEmissionEnabled:false});
const reservation=()=>({requestId:id(4),expectedVersion:1,attemptId:id(6),callbackTokenSha256:'a'.repeat(64),returnStateSha256:'b'.repeat(64),expiresAt:'2026-09-17T20:00:00.000Z'});
function client(value){const calls=[];return{calls,query:async(sql,params)=>{calls.push({sql,params});if(value instanceof Error)throw value;return[{result:value}];}};}
test('valid actor has exact immutable scope without a laboral record',()=>{assert.ok(Object.isFrozen(firmarActorContext(context())));assert.ok(!('employmentId' in context()));});
for(const patch of [{tenantId:id(3).toUpperCase()+'0'},{actorEmail:'Signer@example.invalid'},{actorEmail:' bad@example.invalid'},{actorSessionVersion:0},{actorSessionId:'not-a-session'},{isAdmin:true}])test('rejects incomplete or forged context '+Object.keys(patch),()=>assert.throws(()=>firmarActorContext({...context(),...patch})));
test('source uses stored bytes and independently checks content hash',async()=>{const x=source(),sql=client(x),r=await createFirmarPgRepository(sql).getPrepared(context(),id(4));assert.ok(Buffer.isBuffer(r.pdf));assert.equal(sha(r.pdf),x.sourceSha256);assert.ok(!('pdfBase64' in r));assert.ok(sql.calls[0].sql.includes('$1::jsonb'));assert.ok(!sql.calls[0].sql.includes(context().actorEmail));assert.equal(sql.calls[0].params[1],'source');});
for(const patch of [{requestId:id(99)},{sourceSha256:'0'.repeat(64)},{pdfBase64:'not base64'},{signerCuil:'11111111111'},{sourceValidationRef:''},{approvalRef:'no'},{version:2},{secret:'injected'}])test('unusable source never becomes approved '+Object.keys(patch),()=>assert.throws(()=>checkedFirmarSource({...source(),...patch},id(4))));
for(const patch of [{attemptId:id(99)},{officialEmissionEnabled:true},{state:'verified'},{authorizationUrl:'https://evil.invalid/steal'},{state:'awaiting_authorization',authorizationUrl:null},{state:'received_unverified',authorizationUrl:'https://firmar.gob.ar/api/signatures/'+id(9)},{expiresAt:'never'},{pdf:'data'}])test('response cannot change scope or pretend a verified signature '+Object.keys(patch),()=>assert.throws(()=>checkedFirmarAttempt({...view(),...patch},{requestId:id(4),attemptId:id(6)})));
test('expected attempt URL is accepted only while awaiting authorization',()=>{const v={...view(),state:'awaiting_authorization',authorizationUrl:'https://tst.firmar.gob.ar/api/signatures/'+id(9)};assert.equal(checkedFirmarAttempt(v,{requestId:id(4)}).authorizationUrl,v.authorizationUrl);});
test('reservation uses only token digests and immutable source version',async()=>{const sql=client({...view(),created:true}),input=reservation();await createFirmarPgRepository(sql).reserve(context(),input);assert.deepEqual(JSON.parse(sql.calls[0].params[2]),input);assert.equal(sql.calls[0].params[1],'reserve');});
test('duplicate reservation returns existing attempt, not caller-generated second ID',async()=>{const sql=client({...view(),created:false});const got=await createFirmarPgRepository(sql).reserve(context(),{...reservation(),attemptId:id(98)});assert.equal(got.attemptId,id(6));assert.equal(got.created,false);});
for(const patch of [{callbackTokenSha256:'bad'},{returnStateSha256:'a'.repeat(64)},{expectedVersion:0},{callbackToken:'secret'}])test('invalid reservation rejected before SQL '+Object.keys(patch),async()=>{const sql=client({...view(),created:true});await assert.rejects(createFirmarPgRepository(sql).reserve(context(),{...reservation(),...patch}));assert.equal(sql.calls.length,0);});
for(const [message,status] of [['FIRMAR_SESSION_INVALID',401],['FIRMAR_AUTHORITY_REQUIRED',403],['FIRMAR_BUSY',409],['FIRMAR_RETURN_EXPIRED',410],['FIRMAR_NOT_FOUND',404],['FIRMAR_QUARANTINE_FULL',507],['postgresql://secret:password@host/private DNI',503],['FIRMAR_NOT_FOUND; private context',503]])test('safe DB error mapping '+status+' '+message.slice(0,25),async()=>{const sql=client(Error(message));await assert.rejects(createFirmarPgRepository(sql).recover(context(),id(4)),e=>e.status===status&&e.safeToRetry===false&&!e.message.includes('private')&&!e.message.includes('password'));});
test('recovery is a single authorized query, never a provider request',async()=>{const sql=client(view());const r=await createFirmarPgRepository(sql).recover(context(),id(4));assert.equal(r.state,'outcome_unknown');assert.equal(sql.calls.length,1);assert.equal(sql.calls[0].params[1],'recover');});
test('return stores hashed state and exposes only bound request/attempt',async()=>{const r={requestId:id(4),attemptId:id(6),state:'return_bound',officialEmissionEnabled:false},sql=client(r);assert.deepEqual(await createFirmarPgRepository(sql).resolveReturn(context(),'b'.repeat(64)),r);assert.equal(sql.calls[0].params[1],'return');assert.deepEqual(JSON.parse(sql.calls[0].params[2]),{returnStateSha256:'b'.repeat(64)});});
test('receipt conflict is committed as a database event, then surfaced as conflict without returning bytes',async()=>{const pdf=Buffer.from('%PDF-1.4\nQA RETURNED CANDIDATE\n%%EOF'),sql=client({outcome:'receipt_conflict',officialEmissionEnabled:false});await assert.rejects(createFirmarPgRepository(sql).receive({callbackTokenSha256:'a'.repeat(64),outcome:'received_unverified',document:pdf,sha256:sha(pdf),providerAuthenticated:false,cryptographicValidation:'not_performed',officialEmissionEnabled:false}),e=>e.code==='FIRMAR_RECEIPT_CONFLICT'&&e.status===409);assert.ok(sql.calls[0].sql.includes('firmar_callback_quarantine_v1'));});
test('a success flag cannot elevate validation or provider authenticity',async()=>{const pdf=Buffer.from('%PDF-1.4\nQA RETURNED CANDIDATE\n%%EOF'),p={callbackTokenSha256:'a'.repeat(64),outcome:'received_unverified',document:pdf,sha256:sha(pdf),providerAuthenticated:false,cryptographicValidation:'not_performed',officialEmissionEnabled:false};for(const patch of [{providerAuthenticated:true},{cryptographicValidation:'valid'},{officialEmissionEnabled:true}]){const sql=client({});await assert.rejects(createFirmarPgRepository(sql).receive({...p,...patch}));assert.equal(sql.calls.length,0);}});
