import test from 'node:test';import assert from 'node:assert/strict';
import {loadFirmarSourcePdf} from '../assets/firmar-source-renderer.js';
const bytes=()=>new Uint8Array(Buffer.from('%PDF-1.4 synthetic transport envelope'));
function fixture(patch={}){let options,destroyed=0;const pages=[];const document={numPages:2,isPureXfa:false,getFieldObjects:async()=>null,getAttachments:async()=>null,getJSActions:async()=>null,getPage:async n=>{pages.push(n);return{getAnnotations:async()=>[],getJSActions:async()=>null};},...patch};const task={promise:Promise.resolve(document),destroy:async()=>{destroyed++;}};const importer=async()=>({GlobalWorkerOptions:{},getDocument:o=>{options=o;return task;}});return{importer,task,pages,get options(){return options;},get destroyed(){return destroyed;}};}
test('renderer loads only verified in-memory data and disables action evaluation',async()=>{const f=fixture(),original=bytes(),r=await loadFirmarSourcePdf(original,{pdfjsImporter:f.importer});assert.equal(r.pages,2);assert.equal(f.options.isEvalSupported,false);assert.equal(f.options.useWasm,false);assert.equal(f.options.disableAutoFetch,true);assert.equal(f.options.disableStream,true);assert.ok(!('url' in f.options));assert.notEqual(f.options.data,original);assert.deepEqual(f.pages,[1,2]);await r.destroy();assert.equal(f.destroyed,1);await r.destroy();assert.equal(f.destroyed,1);});
for(const [label,patch] of [['page limit',{numPages:31}],['no pages',{numPages:0}],['fields',{getFieldObjects:async()=>({name:[]})}],['attachments',{getAttachments:async()=>({file:{}})}],['document actions',{getJSActions:async()=>new Map([['OpenAction',[]]])}],['XFA',{isPureXfa:true}],['annotations',{getPage:async()=>({getAnnotations:async()=>[{}],getJSActions:async()=>null})}],['page actions',{getPage:async()=>({getAnnotations:async()=>[],getJSActions:async()=>new Map([['PageOpen',[]]])})}]])test('unsupported '+label+' cannot become reviewable',async()=>{const f=fixture(patch);await assert.rejects(loadFirmarSourcePdf(bytes(),{pdfjsImporter:f.importer}));assert.equal(f.destroyed,1);});
test('source too large never loads a parser',async()=>{let imports=0;await assert.rejects(loadFirmarSourcePdf(new Uint8Array(2097153),{pdfjsImporter:async()=>imports++}));assert.equal(imports,0);});
test('aborted import does not create a worker',async()=>{const f=fixture(),c=new AbortController();c.abort();await assert.rejects(loadFirmarSourcePdf(bytes(),{signal:c.signal,pdfjsImporter:f.importer}),e=>e.name==='AbortError');assert.equal(f.options,undefined);});
test('encrypted PDF never requests a password from the user',async()=>{const f=fixture();const r=await loadFirmarSourcePdf(bytes(),{pdfjsImporter:f.importer});f.task.onPassword();await new Promise(r=>setTimeout(r,0));assert.ok(f.destroyed>=1);await r.destroy();});
test('out-of-range page selection never asks the parser',async()=>{const f=fixture(),r=await loadFirmarSourcePdf(bytes(),{pdfjsImporter:f.importer});await assert.rejects(r.page(3));assert.deepEqual(f.pages,[1,2]);await r.destroy();await assert.rejects(r.page(1));});
