import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
import {firmarDirectReadiness,prepareFirmarBinding,submitFirmarPdf,firmarAuthorizationUrl,parseFirmarCallback,validSigningCuil} from '../lib/firmar-direct-provider.js';
const hash=v=>createHash('sha256').update(v).digest('hex');
const tenant='11111111-1111-4111-8111-111111111111',request='22222222-2222-4222-8222-222222222222',authorization='33333333-3333-4333-8333-333333333333';
const now=1789646400000,pdf=Buffer.from('%PDF-1.7\nsynthetic-not-a-signature\n%%EOF');
function cuil(seed='2012345678'){const sum=[5,4,3,2,7,6,5,4,3,2].reduce((s,w,i)=>s+w*+seed[i],0),d=11-sum%11;return seed+(d===11?0:d===10?9:d);}
function env(){return {FIRMAR_DIRECT_ENABLED:'true',FIRMAR_ENVIRONMENT:'test',FIRMAR_INTEGRATION_APPROVAL_REF:'QA-SYNTHETIC-ONLY',
 FIRMAR_API_USER:'synthetic-api-user',FIRMAR_API_SECRET:'synthetic-never-contact-provider',FIRMAR_TENANT_ID:tenant,
 FIRMAR_CALLBACK_PROFILE:'pfdr-v13-object',FIRMAR_APP_ORIGIN:'https://municipio-junin-friendly.vercel.app',FIRMAR_CALLBACK_REGISTERED:'true'};}
function binding(){let n=0;return prepareFirmarBinding({tenantId:tenant,requestId:request,sourceSha256:hash(pdf),signerCuil:cuil()}, {now:()=>now,random:()=>Buffer.alloc(32,++n)});}
function input(b=binding()){return {binding:b,pdf,sourceValidation:{validated:true,sha256:hash(pdf)},consent:{approved:true,requestId:request,sha256:hash(pdf)}};}
function json(value,options={}){return new Response(JSON.stringify(value),{status:200,headers:{'Content-Type':'application/json'},...options});}
function network({tokenResponse,signatureResponse,throwAt}={}){const calls=[];return {calls,fetchImpl:async(url,options)=>{calls.push({url,options});if(calls.length===throwAt)throw Error('Sensitive simulated transport error');return calls.length===1?(tokenResponse?.()??json({access_token:'synthetic-access-token',token_type:'bearer',expires_in:3600})):(signatureResponse?.()??new Response(null,{status:200,headers:{Location:'/firmador/api/signatures/'+authorization}}));}};}
const run=(i=input(),n=network(),e=env(),more={})=>submitFirmarPdf(i,{env:e,fetchImpl:n.fetchImpl,now:()=>now,...more});
test('unconfigured is fail-closed and readiness never emits credentials',async()=>{const e=env();e.FIRMAR_DIRECT_ENABLED='false';const r=firmarDirectReadiness(e);assert.equal(r.configured,false);assert.deepEqual(r.missing,['activation']);assert.ok(!JSON.stringify(r).includes(e.FIRMAR_API_SECRET));const n=network();await assert.rejects(run(input(),n,e),{code:'FIRMAR_CONFIGURATION_REQUIRED'});assert.equal(n.calls.length,0);});
test('public readiness is not proof of official enrollment or cryptographic validity',()=>{const r=firmarDirectReadiness(env());assert.equal(r.configured,true);assert.equal(r.institutionalAuthorizationVerified,false);assert.equal(r.officialEmissionEnabled,false);assert.equal(r.cryptographicValidation,'not_performed');});
for(const key of ['FIRMAR_ENVIRONMENT','FIRMAR_API_USER','FIRMAR_API_SECRET','FIRMAR_TENANT_ID','FIRMAR_INTEGRATION_APPROVAL_REF','FIRMAR_CALLBACK_PROFILE','FIRMAR_APP_ORIGIN','FIRMAR_CALLBACK_REGISTERED'])test('missing '+key+' blocks before network',async()=>{const e=env();delete e[key];const n=network();await assert.rejects(run(input(),n,e));assert.equal(n.calls.length,0);});
for(const patch of [{FIRMAR_ENVIRONMENT:'prod'}, {FIRMAR_API_USER:'user:evil'}, {FIRMAR_API_SECRET:'value\nheader'}, {FIRMAR_APP_ORIGIN:'https://other.invalid/'},{FIRMAR_APP_ORIGIN:'https://municipio-junin-friendly.vercel.app/?next=evil'},{FIRMAR_CALLBACK_PROFILE:'auto'}])test('unsafe setting '+Object.keys(patch),async()=>{const n=network();await assert.rejects(run(input(),n,{...env(),...patch}));assert.equal(n.calls.length,0);});
test('CUIL checksum is not a verification of identity',()=>{assert.equal(validSigningCuil(cuil()),true);assert.equal(validSigningCuil('00000000000'),false);assert.equal(validSigningCuil('20-12345678-0'),false);assert.equal(validSigningCuil(cuil().slice(0,-1)+((+cuil().at(-1)+1)%10)),false);});
test('separate high-entropy browser and callback values; bindings cannot be mutable',()=>{const b=binding();assert.notEqual(b.returnState,b.callbackToken);assert.equal(hash(b.callbackToken),b.callbackTokenSha256);assert.equal(hash(b.returnState),b.returnStateSha256);assert.ok(Object.isFrozen(b));assert.equal(Date.parse(b.expiresAt),now+1800000);});
test('broken randomness fails closed',()=>assert.throws(()=>prepareFirmarBinding({tenantId:tenant,requestId:request,sourceSha256:hash(pdf),signerCuil:cuil()},{now:()=>now,random:()=>Buffer.alloc(32,1)}),{code:'FIRMAR_RANDOM_FAILURE'}));
for(const change of [{tenantId:'33333333-3333-4333-8333-333333333333'}, {requestId:'not-id'}, {callbackToken:'guess'}, {returnStateSha256:'a'.repeat(64)}, {sourceSha256:'a'.repeat(64)}, {signerCuil:'00000000000'}, {expiresAt:new Date(now-1).toISOString()}, {expiresAt:new Date(now+1900000).toISOString()}, {extra:'ignored'}])test('source/binding mutation '+Object.keys(change),async()=>{const n=network();await assert.rejects(run(input({...binding(),...change}),n));assert.equal(n.calls.length,0);});
for(const change of [{sourceValidation:{validated:false,sha256:hash(pdf)}},{consent:{approved:false,requestId:request,sha256:hash(pdf)}},{consent:{approved:true,requestId:tenant,sha256:hash(pdf)}},{pdf:Buffer.from('PK\x03\x04 this is not a PDF')},{pdf:Buffer.alloc(2097153,1)}])test('only explicit approved validated PDF reaches FirmAR '+Object.keys(change),async()=>{const n=network();await assert.rejects(run({...input(),...change},n));assert.equal(n.calls.length,0);});
test('document travels server to server; result exposes no credentials, CUIL or callback secret',async()=>{const n=network(),i=input();const out=await run(i,n);assert.equal(n.calls.length,2);
 assert.equal(n.calls[0].url,'https://tst.firmar.gob.ar/ra/oauth/token?grant_type=client_credentials');assert.equal(n.calls[0].options.method,'POST');
 assert.equal(n.calls[1].url,'https://tst.firmar.gob.ar/firmador/api/signatures');assert.equal(n.calls[1].options.redirect,'error');assert.equal(n.calls[1].options.cache,'no-store');
 const body=JSON.parse(n.calls[1].options.body);assert.equal(body.type,'PDF');assert.equal(body.cuil,cuil());assert.equal(body.documento,pdf.toString('base64'));
 assert.deepEqual(body.metadata,{tipo:'firmar',token:i.binding.callbackToken});assert.ok(body.urlRedirect.endsWith('#'+i.binding.returnState));assert.ok(!body.urlRedirect.includes(cuil()));
 assert.equal(out.status,'awaiting_authorization');assert.equal(out.officialEmissionEnabled,false);for(const secret of [cuil(),i.binding.callbackToken,i.binding.returnState,env().FIRMAR_API_SECRET,'synthetic-access-token'])assert.ok(!JSON.stringify(out).includes(secret));});
for(const url of ['/api/signatures/'+authorization,'/firmador/api/signatures/'+authorization,'https://tst.firmar.gob.ar/firmador/api/signatures/'+authorization])test('documented safe authorization URL '+url,()=>assert.ok(firmarAuthorizationUrl(url,'https://tst.firmar.gob.ar').startsWith('https://tst.firmar.gob.ar/')));
for(const url of ['https://evil.invalid/api/signatures/'+authorization,'//tst.firmar.gob.ar/api/signatures/'+authorization,'javascript:alert(1)','https://tst.firmar.gob.ar@evil.invalid/','https://user@tst.firmar.gob.ar/api/signatures/'+authorization,'/api/signatures/'+authorization+'?next=evil','/api/signatures/'+authorization+'#x','/api/signatures/%2f'+authorization,'/ra/oauth/token','/api/signatures/not-an-id','https://firmar.gob.ar/api/signatures/'+authorization])test('untrusted Location '+url,()=>assert.throws(()=>firmarAuthorizationUrl(url,'https://tst.firmar.gob.ar')));
for(const opts of [{throwAt:1}, {tokenResponse:()=>json({error:'private'},{status:401})}, {tokenResponse:()=>json({access_token:'bad\nheader',expires_in:3600,token_type:'bearer'})},{tokenResponse:()=>new Response('<html>not json</html>')},{tokenResponse:()=>json({access_token:'x'.repeat(18000),expires_in:3600,token_type:'bearer'})}])test('OAuth failure never uploads PDF '+Object.keys(opts),async()=>{const n=network(opts);await assert.rejects(run(input(),n),e=>e instanceof Error&&!String(e).includes('private'));assert.equal(n.calls.length,1);});
for(const opts of [{throwAt:2},{signatureResponse:()=>new Response(null,{status:500})},{signatureResponse:()=>new Response(null,{status:200,headers:{Location:'https://evil.invalid/'}})},{signatureResponse:()=>new Response(null,{status:200})}])test('ambiguous submission does not auto retry '+Object.keys(opts),async()=>{const n=network(opts);await assert.rejects(run(input(),n),{code:'FIRMAR_SUBMISSION_OUTCOME_UNKNOWN'});assert.equal(n.calls.length,2);});
test('explicit provider rejection stays distinct from ambiguous upload',async()=>{const n=network({signatureResponse:()=>json({sensitive:'details'},{status:403})});await assert.rejects(run(input(),n),{code:'FIRMAR_SUBMISSION_REJECTED'});assert.equal(n.calls.length,2);});
test('abort before sending opens no network call',async()=>{const c=new AbortController();c.abort();const n=network();await assert.rejects(run(input(),n,env(),{signal:c.signal}),{code:'FIRMAR_CANCELLED'});assert.equal(n.calls.length,0);});
function callback(){return {documento:pdf.toString('base64'),metadata:{tipo:'firmar',token:binding().callbackToken},status:{success:true}};}
test('callback success is only unverified evidence and never approval',()=>{const r=parseFirmarCallback(callback());assert.equal(r.outcome,'received_unverified');assert.equal(r.cryptographicValidation,'not_performed');assert.equal(r.providerAuthenticated,false);assert.equal(r.officialEmissionEnabled,false);assert.deepEqual(r.document,pdf);assert.equal(r.sha256,hash(pdf));assert.ok(!JSON.stringify(r).includes(binding().callbackToken));});
test('array metadata is accepted only under explicitly selected SIU profile',()=>{const v=callback();v.metadata=[v.metadata];assert.throws(()=>parseFirmarCallback(v));assert.equal(parseFirmarCallback(v,{profile:'siu-array-single'}).outcome,'received_unverified');v.metadata.push(v.metadata[0]);assert.throws(()=>parseFirmarCallback(v,{profile:'siu-array-single'}));});
for(const patch of [{status:true},{status:{success:'true'}},{status:{success:true,verified:true}},{metadata:{tipo:'firmar',token:'public-id'}},{documento:'UEsDBA=='},{documento:pdf.toString('base64')+'\n'},{documento:'A'.repeat(2796205)},{msg:'should not be reflected'},{tenant:tenant}])test('callback ambiguity/rejection '+Object.keys(patch),()=>assert.throws(()=>parseFirmarCallback({...callback(),...patch})));
test('provider-reported failure does not destroy, overwrite or validate a document',()=>{const c=callback();c.status={success:false};delete c.documento;c.msg='Sensitive upstream error';const r=parseFirmarCallback(c);assert.equal(r.outcome,'provider_reported_failure');assert.equal(r.providerAuthenticated,false);assert.equal(r.officialEmissionEnabled,false);assert.ok(!JSON.stringify(r).includes('Sensitive'));});
