import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {createFirmarJourney,verifyFirmarJourneyStatus} from '../assets/firmar-journey.js';
import {createFirmarReturn,takeFirmarReturnState,verifyFirmarReturnBinding} from '../assets/firmar-return.js';
const requestId='11111111-1111-4111-8111-111111111111',attemptId='22222222-2222-4222-8222-222222222222';
const origin='https://municipio-junin-friendly.vercel.app',now=1789646400000;
const response=()=>({requestId,attemptId,state:'awaiting_authorization',authorizationUrl:'https://tst.firmar.gob.ar/api/signatures/'+attemptId,expiresAt:new Date(now+1800000).toISOString(),officialEmissionEnabled:false});
const status=state=>({requestId,attemptId,state,officialEmissionEnabled:false});
const valid=()=>({...status('verified'),documentSha256:'a'.repeat(64),validation:{signatureIntegrity:true,certificateTrust:true,signerMatches:true,sourceMatches:true,temporalPolicySatisfied:true,requiredSignaturesComplete:true}});
const settle=()=>new Promise(r=>setImmediate(r));
function fixture(opts={}){
 const events=[],timers=new Map(),calls=[],popups=[];let seq=0;
 const journey=createFirmarJourney({origin,now:()=>now,timer:(fn,ms)=>{const id=++seq;timers.set(id,{fn,ms});return id;},clearTimer:id=>timers.delete(id),onChange:e=>events.push(e),openWindow:()=>{calls.push('open');if(opts.blocked)return null;const p={closed:false,opener:{},document:{title:'',createElement:()=>({}),body:{replaceChildren(){}}},location:{replace:u=>calls.push(['navigate',u])},close(){this.closed=true;},focus(){calls.push('focus');}};popups.push(p);return p;},
 begin:async a=>{calls.push('begin');return opts.begin?opts.begin(a):response();},readStatus:async a=>{calls.push('read');return opts.readStatus?opts.readStatus(a):status('awaiting_authorization');},
 recoverAttempt:async a=>{calls.push('recover');return opts.recover?opts.recover(a):response();},...opts.extra});
 return {journey,events,timers,calls,popups,tick:async()=>{const e=timers.entries().next().value;if(e){timers.delete(e[0]);e[1].fn();await settle();}}};
}
test('blocked-window link survives every status refresh',async()=>{const f=fixture({blocked:true});await f.journey.start({requestId,expectedVersion:1});for(let i=0;i<3;i++){await f.tick();assert.equal(f.events.at(-1).sameTabUrl,response().authorizationUrl);}assert.equal(f.calls.filter(x=>x==='begin').length,1);f.journey.dispose();});
test('closing signer permits reopening the same attempt, not resending PDF',async()=>{const f=fixture();await f.journey.start({requestId,expectedVersion:1});f.popups[0].closed=true;await f.tick();assert.equal(f.events.at(-1).sameTabUrl,response().authorizationUrl);assert.equal(f.journey.focusAuthorization(),true);assert.equal(f.calls.filter(x=>x==='begin').length,1);assert.equal(f.popups.length,2);assert.deepEqual(f.calls.filter(x=>Array.isArray(x)),[['navigate',response().authorizationUrl],['navigate',response().authorizationUrl]]);f.journey.dispose();});
test('lost response is recovered by request without starting another provider operation',async()=>{const f=fixture({begin:async()=>{throw {code:'FIRMAR_SUBMISSION_OUTCOME_UNKNOWN'};}});await f.journey.start({requestId,expectedVersion:1});assert.equal(f.events.at(-1).canRecover,true);await f.journey.recover();assert.equal(f.events.at(-1).attemptId,attemptId);assert.equal(f.calls.filter(x=>x==='begin').length,1);assert.equal(f.calls.filter(x=>x==='open').length,1);f.journey.dispose();});
test('unclassified network error is uncertain and cannot submit twice',async()=>{const f=fixture({begin:async()=>{throw Error('network');}});await f.journey.start({requestId,expectedVersion:1});assert.equal(f.events.at(-1).state,'outcome_unknown');await assert.rejects(f.journey.start({requestId,expectedVersion:1}));f.journey.dispose();});
for(const change of [{requestId:attemptId},{authorizationUrl:'https://attacker.invalid'},{officialEmissionEnabled:true}])test('bad reply cannot open provider or enable repeat '+Object.keys(change),async()=>{const f=fixture({begin:async()=>({...response(),...change})});await f.journey.start({requestId,expectedVersion:1});assert.ok(f.journey.busy);assert.equal(f.events.at(-1).canRetry,false);assert.equal(f.calls.filter(Array.isArray).length,0);f.journey.dispose();});
test('explicit authorized no-submission proof permits retry',async()=>{const f=fixture({begin:async()=>{throw {code:'FIRMAR_NOT_SUBMITTED',safeToRetry:true};}});await f.journey.start({requestId,expectedVersion:1});assert.equal(f.journey.busy,false);assert.equal(f.events.at(-1).canRetry,true);f.journey.dispose();});
test('a missing recovered attempt does not grant a new submission',async()=>{const f=fixture({begin:async()=>{throw Error('network');},recover:async()=>null});await f.journey.start({requestId,expectedVersion:1});await f.journey.recover();assert.equal(f.journey.busy,true);assert.equal(f.events.at(-1).state,'outcome_unknown');f.journey.dispose();});
test('recovery is single-flight and session loss ignores late response',async()=>{let resolve;const f=fixture({begin:async()=>{throw Error('network');},recover:()=>new Promise(r=>resolve=r)});await f.journey.start({requestId,expectedVersion:1});const p=f.journey.recover();await f.journey.recover();assert.equal(f.calls.filter(x=>x==='recover').length,1);f.journey.sessionLost();resolve(response());await p;assert.equal(f.events.at(-1).state,'session_lost');assert.equal(f.events.at(-1).requestId,null);});
for(const code of [401,403])test('recovery authorization failure clears request '+code,async()=>{const f=fixture({begin:async()=>{throw Error('network');},recover:async()=>{throw {status:code};}});await f.journey.start({requestId,expectedVersion:1});await f.journey.recover();assert.equal(f.events.at(-1).state,'session_lost');assert.equal(f.events.at(-1).sameTabUrl,null);});
test('document received removes obsolete authorization and regressions cannot restore it',async()=>{let state='received_unverified';const f=fixture({blocked:true,readStatus:async()=>status(state)});await f.journey.start({requestId,expectedVersion:1});await f.tick();assert.equal(f.events.at(-1).sameTabUrl,null);state='awaiting_authorization';await f.tick();assert.equal(f.events.at(-1).state,'received_unverified');assert.equal(f.journey.focusAuthorization(),false);f.journey.dispose();});
test('completed attempt is not polled forever on focus or stale return messages',async()=>{const f=fixture({readStatus:async()=>valid()});await f.journey.start({requestId,expectedVersion:1});await f.tick();const n=f.calls.length;f.journey.refresh();f.journey.notice({origin,data:{type:'municontrol:firmar-return',attemptId}});await settle();assert.equal(f.calls.length,n);assert.equal(f.events.at(-1).officialEmissionEnabled,false);f.journey.dispose();});
test('page reload restores attempt without launching windows or uploading',async()=>{const f=fixture();f.journey.resume({...response()});await settle();assert.equal(f.calls.filter(x=>x==='begin'||x==='open').length,0);assert.equal(f.events.at(-1).sameTabUrl,response().authorizationUrl);f.journey.dispose();});
test('expired authorization cannot be reopened even when backend state is pending',async()=>{const f=fixture();f.journey.resume({...response(),expiresAt:new Date(now-1).toISOString()});await settle();assert.equal(f.events.at(-1).sameTabUrl,null);assert.equal(f.journey.focusAuthorization(),false);f.journey.dispose();});
test('verification is not administrative approval and requires every proof',()=>{for(const k of Object.keys(valid().validation)){const v=valid();v.validation[k]=false;assert.throws(()=>verifyFirmarJourneyStatus(v,{requestId,attemptId}));}assert.equal(verifyFirmarJourneyStatus(valid(),{requestId,attemptId}).officialEmissionEnabled,false);});
function returning(opts={}){const events=[],notices=[],order=[];let resolver=opts.resolve|| (async()=>({requestId,attemptId,state:'return_bound',officialEmissionEnabled:false}));const ctrl=createFirmarReturn({location:{hash:'#'+'A'.repeat(43),pathname:'/firmas/retorno',search:'',...opts.location},history:{replaceState:()=>order.push('stripped')},resolveReturn:async p=>{order.push('resolve');return resolver(p);},notifyHost:n=>notices.push(n),onChange:e=>events.push(e),now:()=>now});return{ctrl,events,notices,order};}
test('return removes fragment before server call and sends only a refresh hint',async()=>{const f=returning();await f.ctrl.resume();assert.deepEqual(f.order,['stripped','resolve']);assert.deepEqual(f.notices,[{type:'municontrol:firmar-return',attemptId}]);assert.equal(f.events.at(-1).state,'return_bound');assert.equal(f.events.at(-1).officialEmissionEnabled,false);f.ctrl.dispose();});
for(const hash of ['#invalid','#'+'A'.repeat(43)+'?x=1','#%41'.repeat(43),''])test('invalid fragment scrubbed without resolution '+hash.slice(0,10),async()=>{const f=returning({location:{hash}});await f.ctrl.resume();assert.deepEqual(f.order,['stripped']);assert.equal(f.events[0].state,'invalid_return');});
test('query tokens rejected even with well-shaped fragment',async()=>{const f=returning({location:{search:'?state=secret'}});await f.ctrl.resume();assert.deepEqual(f.order,['stripped']);});
for(const patch of [{attemptId:'invalid'},{requestId:attemptId,state:'verified'},{officialEmissionEnabled:true},{state:'approved'}])test('return must be server-bound, never signed-success '+Object.keys(patch),()=>assert.throws(()=>verifyFirmarReturnBinding({requestId,attemptId,state:'return_bound',officialEmissionEnabled:false,...patch})));
test('extra remote URL and success fields are discarded',()=>{const v=verifyFirmarReturnBinding({requestId,attemptId,state:'return_bound',officialEmissionEnabled:false,url:'https://evil.invalid',success:true});assert.deepEqual(Object.keys(v).sort(),['attemptId','officialEmissionEnabled','requestId','state']);});
test('return retries are bounded and cannot cause a provider submit',async()=>{const f=returning({resolve:async()=>{throw Error('network');}});for(let i=0;i<7;i++)await f.ctrl.resume();assert.equal(f.order.filter(x=>x==='resolve').length,3);assert.equal(f.events.at(-1).state,'return_expired');});
test('late return response after unmount emits no request or channel message',async()=>{let resolve;const f=returning({resolve:()=>new Promise(r=>resolve=r)});const p=f.ctrl.resume();f.ctrl.dispose();resolve({requestId,attemptId,state:'return_bound',officialEmissionEnabled:false});await p;assert.equal(f.notices.length,0);assert.equal(f.events.at(-1).state,'resolving_return');});
for(const status of [401,403,404,409,410])test('return failure does not announce signature or reveal binding '+status,async()=>{const f=returning({resolve:async()=>{throw {status};}});await f.ctrl.resume();assert.equal(f.notices.length,0);assert.equal(f.events.at(-1).requestId,undefined);assert.ok(['session_lost','invalid_return'].includes(f.events.at(-1).state));});
test('return and journey contain no provider fetch, credentials, storage or embedded signer',()=>{for(const file of ['firmar-journey.js','firmar-return.js']){const text=fs.readFileSync(new URL('../assets/'+file,import.meta.url),'utf8');assert.doesNotMatch(text,/\bfetch\s*\(|localStorage\.|sessionStorage\.|<iframe|innerHTML\s*=|password\s*:/);}});
