import test from 'node:test';import assert from 'node:assert/strict';
import {grhFileRequest,grhPreview,grhWriteAttempt,grhReceipt,grhAmount} from '../assets/payroll-grh-import-model.js';
import {reviewGrhImport,prepareGrhImport} from '../lib/internal-grh-import.js';
import {fixture,id,principal,session} from './fixtures/grh-import-synthetic.js';
async function reviewed(count=2){const f=fixture(count),e=await grhFileRequest(Buffer.from(f.payload.contentBase64,'base64'),{concept:f.payload.concept,periodMonth:f.payload.periodMonth});const p=(await reviewGrhImport(f.readSql,f.runtime,principal(),session(),f.payload)).data;return{f,e,p};}
const envelope=data=>({ok:true,replayed:false,data});
test('browser model binds the full file, not the current display page',async()=>{const{e,p}=await reviewed(60),r=grhPreview(envelope(p),e);assert.equal(r.outputRows,60);assert.equal(r.rows.at(-1).rowOrdinal,60);assert.ok(Object.isFrozen(r.rows[0]));});
for(const change of [p=>p.rows.pop(),p=>p.inputRows++,p=>p.resolvedRows--,p=>p.totalAmountCents='1',p=>p.rows[0].amountCents='1',p=>p.rows[0].dni='99000888',p=>p.rows[0].sourceLines=[99],p=>p.rows[0].contractId=id(999),p=>p.sourceSha256='e'.repeat(64),p=>p.concept='615',p=>p.periodMonth='2026-09-01',p=>p.payrollCalculated=true,p=>p.persistencePerformed=true,p=>p.readyToPrepare=false])test('inconsistent server preview is rejected: '+String(change),async()=>{const{e,p}=await reviewed();change(p);assert.throws(()=>grhPreview(envelope(p),e));});
test('ambiguous identity cannot become a selected first candidate on the client',async()=>{const f=fixture();f.state.records.push({...f.state.records[0],contractId:id(888),legajo:'2000'});const e=await grhFileRequest(Buffer.from(f.payload.contentBase64,'base64'),{concept:'614',periodMonth:'2026-08-01'});const p=(await reviewGrhImport(f.readSql,f.runtime,principal(),session(),f.payload)).data;assert.equal(grhPreview(envelope(p),e).readyToPrepare,false);p.rows[0].contractId=p.rows[0].candidates[0].contractId;p.rows[0].status='resolved';p.readyToPrepare=true;p.resolvedRows=1;assert.throws(()=>grhPreview(envelope(p),e));});
test('a write attempt preserves the same immutable body and key',async()=>{const{e,p}=await reviewed(),a=grhWriteAttempt(e,grhPreview(envelope(p),e),id(99),'scope');const before=a.body;assert.ok(Object.isFrozen(a));assert.throws(()=>{a.key=id(98);});assert.equal(a.body,before);assert.equal(JSON.parse(before).payload.previewToken,p.previewToken);assert.equal(JSON.parse(before).command,'grhPrepare');});
test('receipt verifies all saved rows, target identities and exact amounts',async()=>{const{f,e,p}=await reviewed(12);f.payload.previewToken=p.previewToken;const result=await prepareGrhImport(f.readSql,f.runtime,principal(),session(),f.payload,id(99));const r=await grhReceipt(envelope(result.data),e,p);assert.equal(r.savedRows,12);assert.equal(r.omittedRows,0);assert.equal(r.batch.status,'draft');assert.equal(r.payrollCalculated,false);});
for(const change of [r=>r.savedRows--,r=>r.batch.rows.pop(),r=>r.batch.rows[0].amountCents='1',r=>r.batch.rows[0].employmentContractId=id(999),r=>r.semanticSha256='e'.repeat(64),r=>r.batch.status='approved',r=>r.batch.payrollCalculated=true])test('bad receipt never certifies completion: '+String(change),async()=>{const{f,e,p}=await reviewed();f.payload.previewToken=p.previewToken;const result=await prepareGrhImport(f.readSql,f.runtime,principal(),session(),f.payload,id(99));change(result.data);await assert.rejects(grhReceipt(envelope(result.data),e,p));});
test('exact-cent formatting does not round or infer a missing amount',()=>{assert.equal(grhAmount('12345'),'$ 123,45');assert.equal(grhAmount('0'),'$ 0,00');assert.equal(grhAmount(null),'—');});
