import test from 'node:test';import assert from 'node:assert/strict';
import {verifyCommittedGrhCandidate,assertCandidateIdentity,assertCandidateCounts,CANDIDATE_TARGET} from '../scripts/verify-grh-candidate-commit.mjs';
const options={versionId:'11111111-1111-4111-8111-111111111111',payloadSha256:'a'.repeat(64),expectedCounts:{payrollRuns:624,payrollSnapshot:847,movements:495237,payrollMonthly:216411,employmentReconciliation:2452}};
const identity=()=>({...CANDIDATE_TARGET,database:'neondb',read_only:'on'});
function client(changes={}){const calls=[];const db={calls,async query(text,params){calls.push({text,params});
 if(changes.errorAt&&text.includes(changes.errorAt))throw Error('DATABASE_FAILURE');
 if(text.startsWith('BEGIN')||text.startsWith('SET')||text==='ROLLBACK')return{rows:[]};
 if(text.includes("current_setting('neon.project_id'"))return{rows:[{...identity(),...changes.identity}]};
 if(text.includes('FROM public.grh_core_source_version v'))return{rows:changes.missing?[]:[{id:options.versionId,payload_sha256:options.payloadSha256,source_profile:'grh-junin-2026-09-10',source_cutoff:'2026-09-10 15:17:30',baseline_cutoff:'2026-08-06 18:15:21',payroll_date:'2026-09-10',sealed_at:'2026-09-19 12:00:00+00',prior_transaction:true,baseline_still_published:true,...changes.version}]};
 if(text.includes('grh_core_source_version_rows_v1($1')){const n=options.expectedCounts[params[1]];return{rows:[{rows:n,unique_keys:n,review_only:true,...changes.counts}]};}
 if(text.includes('has_table_privilege'))return{rows:[{versions_read:false,deltas_read:false,seals_read:false,reader_execute:false,...changes.rights}]};
 throw Error('UNEXPECTED_SQL');}};return db;}
test('committed candidate is checked using a read-only snapshot and explicit version',async()=>{const c=client(),report=await verifyCommittedGrhCandidate(c,options);assert.equal(report.committedPreviously,true);assert.equal(report.databaseWrites,0);assert.equal(report.productionSwitchAuthorized,false);assert.equal(report.entities.movements.rows,495237);assert.equal(c.calls[0].text,'BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY');assert.equal(c.calls.at(-1).text,'ROLLBACK');const reads=c.calls.filter(q=>q.text.includes('grh_core_source_version_rows_v1($1'));assert.equal(reads.length,5);assert.ok(reads.every(q=>q.params[0]===options.versionId));});
test('invalid identifiers and counts fail before a connection is used',async()=>{for(const patch of [{versionId:'latest'},{payloadSha256:'bad'},{expectedCounts:{}},{expectedCounts:{...options.expectedCounts,movements:-1}}]){const c=client();await assert.rejects(verifyCommittedGrhCandidate(c,{...options,...patch}));assert.equal(c.calls.length,0);}});
test('the original production branch is never a candidate verification target',()=>{assert.throws(()=>assertCandidateIdentity({...identity(),project:'noisy-poetry-54471701',branch:'br-plain-dust-acpjgebb'}));assert.throws(()=>assertCandidateIdentity({...identity(),database:'postgres'}));assert.throws(()=>assertCandidateIdentity({...identity(),read_only:'off'}));});
test('missing seal, altered package, uncommitted transaction or changed baseline fail closed',async()=>{
 for(const changes of [{missing:true},{version:{payload_sha256:'b'.repeat(64)}},{version:{prior_transaction:false}},{version:{baseline_still_published:false}},{version:{source_profile:'other'}}]){const c=client(changes);await assert.rejects(verifyCommittedGrhCandidate(c,options));assert.equal(c.calls.at(-1).text,'ROLLBACK');}
});
test('counts, uniqueness and review-only status cannot be coerced',()=>{for(const patch of [{rows:'2'},{rows:-1},{unique_keys:1},{review_only:false},{review_only:null}])assert.throws(()=>assertCandidateCounts({rows:2,unique_keys:2,review_only:true,...patch},2));assert.throws(()=>assertCandidateCounts({rows:2,unique_keys:2,review_only:true},3));});
test('unexpected runtime read grants are treated as an exposure, not a successful import',async()=>{for(const right of ['versions_read','deltas_read','seals_read','reader_execute']){const c=client({rights:{[right]:true}});await assert.rejects(verifyCommittedGrhCandidate(c,options),/CANDIDATE_RUNTIME_EXPOSURE/);assert.equal(c.calls.at(-1).text,'ROLLBACK');}});
test('wrong branch stops before any source entity is queried',async()=>{const c=client({identity:{branch:'br-other'}});await assert.rejects(verifyCommittedGrhCandidate(c,options));assert.equal(c.calls.some(q=>q.text.includes('FROM public.grh_core_source_version v')),false);});
test('query failures still close the read-only transaction',async()=>{const c=client({errorAt:'grh_core_source_version_rows_v1($1'});await assert.rejects(verifyCommittedGrhCandidate(c,options),/DATABASE_FAILURE/);assert.equal(c.calls.at(-1).text,'ROLLBACK');});
test('verifier does not request schema, record, privilege or source mutations',async()=>{const c=client();await verifyCommittedGrhCandidate(c,options);for(const q of c.calls)assert.doesNotMatch(q.text,/\b(INSERT|UPDATE|DELETE|TRUNCATE|ALTER|CREATE|DROP|GRANT|REVOKE)\b/);});
