import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
import {cleanWorkSave,cleanWorkMetadata,workQuery,workDay,strictWorkJson,blankWork,workReceipt} from '../assets/legal-work-model.js';
import {workOperation,workContext} from '../lib/internal-legal-work.js';
import {createLegalWorkHandler} from '../api/internal-legal-work.js';
import {legalWorkRequest} from '../assets/legal-work-client.js';
const id=n=>`${String(n).padStart(8,'0')}-1111-4111-8111-111111111111`,scopeFor=x=>createHash('sha256').update(JSON.stringify(workContext(x.principal,x.session))).digest('hex');
const access=(canManage=true)=>({mode:'managed',session:{id:id(3),version:1,email:'qa@example.invalid'},principal:{user:{email:'qa@example.invalid'},tenant:{id:id(1),membershipId:id(2),source:'membership',effectiveCapabilities:['legal.norm.read',...(canManage?['legal.norm.register']:[])]}}});
const sample=()=>({...blankWork(id(2)),metadata:{title:'Informe de seguimiento institucional',reference:'Expediente de ensayo',responsibleId:id(2),targetDate:'2026-09-22',nextStep:'Revisar los antecedentes',status:'pending'},note:'Apertura de un asunto sintético'});
const receipt={version:'legal-work.v1',id:id(4),code:'AJ-2026-00001',recordVersion:1,replayed:false};
test('clean draft preserves figures and requires an explicit next step and responsible',()=>{const x=sample();x.metadata.title='  Revisar NO descontar 25,5 %  ';const y=cleanWorkSave(x);assert.equal(y.metadata.title,'Revisar NO descontar 25,5 %');assert.equal(x.metadata.title.startsWith(' '),true);});
for(const patch of [{id:id(4)},{expectedVersion:1},{note:''},{metadata:{...sample().metadata,status:'closed'}},{tenantId:id(8)},{expectedVersion:100}])test('invalid create rejected '+Object.keys(patch),()=>assert.throws(()=>cleanWorkSave({...sample(),...patch})));
for(const patch of [{responsibleId:''},{title:'<script>'},{targetDate:'2026-02-30'},{status:'approved'},{nextStep:''},{title:'a'.repeat(161)},{nextStep:'x'.repeat(301)}])test('invalid metadata rejected '+Object.keys(patch),()=>assert.throws(()=>cleanWorkMetadata({...sample().metadata,...patch})));
test('close and reopen preserve record identity and expected version',()=>{const x={...sample(),id:id(4),expectedVersion:2,metadata:{...sample().metadata,status:'closed',nextStep:''}};assert.equal(cleanWorkSave(x).metadata.nextStep,'');assert.equal(cleanWorkSave({...x,metadata:{...x.metadata,status:'in_progress',nextStep:'Reabrir para verificar'}}).expectedVersion,2);});
test('dates and query bounds are explicit; legal deadline is never computed',()=>{assert.ok(workDay('2024-02-29'));assert.ok(workDay(''));assert.equal(workDay('2025-02-29'),false);const q={q:'  100 %  ',status:'waiting',mine:true,page:1};assert.equal(workQuery(q).q,'100 %');for(const patch of [{page:0},{page:1001},{status:'overdue'},{mine:'true'}])assert.throws(()=>workQuery({...q,...patch}));});
for(const text of ['{"id":null,"id":"other"}','{"a":{"b":1,"b":2}}','{"a":1,"\\u0061":2}','{broken'])test('duplicate or malformed JSON rejected '+text,()=>assert.throws(()=>strictWorkJson(text)));
test('same label in different JSON objects is not a duplicate',()=>assert.deepEqual(strictWorkJson('{"a":{"id":1},"b":{"id":2}}'),{a:{id:1},b:{id:2}}));
test('receipt cannot falsely acknowledge another version or formal approval',()=>{assert.equal(workReceipt(receipt),receipt);for(const patch of [{recordVersion:0},{id:'any'},{code:'EXP-123'},{officialApproved:true}])assert.throws(()=>workReceipt({...receipt,...patch}));});
test('repository parameterizes tenant context, payload and idempotency key',async()=>{let statement,args;const sql={query:async(s,a)=>{statement=s;args=a;return[{result:receipt}];}};const a=access();await workOperation(sql,a.principal,a.session,'save',sample(),id(5));assert.match(statement,/\$1::jsonb/);assert.ok(!statement.includes('qa@example'));assert.equal(JSON.parse(args[0]).membershipId,id(2));assert.equal(args[3],id(5));});
test('database error maps to safe status without leaking a DSN',async()=>{const a=access();await assert.rejects(workOperation({query:async()=>{throw Error('postgresql://SECRET@host');}},a.principal,a.session,'detail',{id:id(4)}),e=>e.status===503&&!e.message.includes('SECRET'));});
function res(){return{headers:{},setHeader(k,v){this.headers[k.toLowerCase()]=v;},status(s){this.statusCode=s;return this;},json(b){this.body=b;return this;}};}
function req(method='GET',query={resource:'bootstrap'}){return{method,url:'/api/internal-legal-work'+(query?'?'+new URLSearchParams(query):''),query:query||{},headers:{'x-municontrol-intent':'legal-work-v1','x-legal-work-scope':scopeFor(access()),'content-type':'application/json',origin:'https://municipio-junin-friendly.vercel.app','idempotency-key':id(5)}};}
function handler(a=access(),out=receipt){let calls=0;return{handler:createLegalWorkHandler({env:{IDENTITY_APP_ORIGIN:'https://municipio-junin-friendly.vercel.app'},authorize:async()=>a,getSql:async()=>({query:async()=>{calls++;return[{result:out}];}})}),calls:()=>calls};}
test('GET bootstrap exposes one session-bound scope, not credentials',async()=>{const h=handler(access(),{version:'legal-work.v1',canManage:true}),r=res();await h.handler(req(),r);assert.equal(r.statusCode,200);assert.equal(r.body.data.scope,scopeFor(access()));assert.match(r.headers['cache-control'],/no-store/);});
test('one explicit create reaches the SQL facade with a validated scope',async()=>{const h=handler(),r=res(),q=req('POST',null);q.body=sample();await h.handler(q,r);assert.equal(r.statusCode,201);assert.equal(h.calls(),1);assert.deepEqual(r.body.data,receipt);});
test('read-only profile cannot save even with a valid UI scope',async()=>{const a=access(false),h=handler(a),r=res(),q=req('POST',null);q.headers['x-legal-work-scope']=scopeFor(a);q.body=sample();await h.handler(q,r);assert.equal(r.statusCode,403);assert.equal(h.calls(),0);});
for(const change of [q=>q.headers['x-legal-work-scope']='a'.repeat(64),q=>q.headers['x-municontrol-intent']='wrong',q=>q.url+='?tenant='+id(1),q=>q.headers['idempotency-key']='invalid',q=>q.body=JSON.stringify(sample()).replace('"note":','"note":"first","note":')])test('ambiguous or changed request denied before SQL '+change,async()=>{const h=handler(),r=res(),q=req('POST',null);q.body=sample();change(q);await h.handler(q,r);assert.ok(r.statusCode>=400);assert.equal(h.calls(),0);});
test('client keeps idempotency key and never retries implicitly after a connection error',async()=>{let calls=0;await assert.rejects(legalWorkRequest(null,{scope:'x',body:sample(),key:id(5),fetchImpl:async(_u,o)=>{calls++;assert.equal(o.headers['Idempotency-Key'],id(5));assert.equal(o.redirect,'error');throw Error('network');}}));assert.equal(calls,1);});
test('client rejects wrong envelope and accepts validated durable receipts only',async()=>{const response=x=>new Response(JSON.stringify(x),{headers:{'content-type':'application/json','cache-control':'private, no-store'}});assert.deepEqual(await legalWorkRequest(null,{body:sample(),key:id(5),fetchImpl:async()=>response({ok:true,data:receipt})}),receipt);await assert.rejects(legalWorkRequest(null,{body:sample(),key:id(5),fetchImpl:async()=>response({ok:true,data:{...receipt,recordVersion:0}})}));});
