import test from 'node:test';import assert from 'node:assert/strict';
import {followupReview,reviewFieldText} from '../assets/legal-followup-review.js';
const ID='11111111-1111-4111-8111-111111111111',NORM='22222222-2222-4222-8222-222222222222';
const body=()=>({id:null,normId:NORM,normVersion:1,expectedVersion:0,title:'Revisar antecedentes',status:'open',dueDate:'2026-09-30',note:'Nota de ensayo',reason:'Alta documentada de ensayo'});
function original(){const d=body(),event={version:1,title:d.title,status:d.status,dueDate:d.dueDate,note:d.note,reason:d.reason,recordedBy:'qa@example.invalid',recordedAt:'2026-09-19T12:00:00Z'};return{id:ID,normId:NORM,normVersion:1,currentNormVersion:2,...event,history:[{...event}]};}
const update=patch=>({...body(),id:ID,expectedVersion:1,...patch});
test('creation review displays every field and identifies unpersisted revision one',()=>{const r=followupReview(body());assert.equal(r.isNew,true);assert.equal(r.nextRevision,1);assert.equal(r.changeCount,4);assert.ok(r.fields.every(f=>f.before===null));assert.equal(r.body.reason,body().reason);});
test('state change exposes original and proposed labels without changing task or source',()=>{const old=original(),value=update({status:'done'}),r=followupReview(value,old);assert.equal(r.nextRevision,2);assert.equal(r.normVersion,1);assert.equal(r.changeCount,1);assert.equal(r.fields.find(f=>f.key==='status').before,'open');assert.equal(reviewFieldText('status','done'),'Resuelto');assert.equal(old.status,'open');assert.equal(value.status,'done');});
test('cancellation and reopening are revisions, not deletion or legal decisions',()=>{const old=original();assert.equal(followupReview(update({status:'cancelled'}),old).nextRevision,2);old.status='done';old.history[0].status='done';assert.equal(followupReview(update({status:'open'}),old).fields.find(f=>f.key==='status').changed,true);});
test('all 2000 note characters and long reasons remain visible in review',()=>{const value={...body(),note:'x'.repeat(2000),reason:'Motivo '+ 'y'.repeat(490)},r=followupReview(value);assert.equal(r.fields.find(f=>f.key==='note').after.length,2000);assert.equal(r.body.reason,value.reason);});
test('clearing a date or note is explicit and not confused with an unchanged field',()=>{const r=followupReview(update({dueDate:'',note:''}),original());assert.equal(r.changeCount,2);assert.equal(reviewFieldText('dueDate',''),'Sin fecha objetivo');assert.equal(reviewFieldText('note',''),'Sin nota de trabajo');assert.equal(reviewFieldText('title',null),'No existía');});
test('changing the reason alone cannot create a phantom revision',()=>{assert.throws(()=>followupReview(update({reason:'Otro motivo sin cambios'}),original()),/No hay cambios/);});
test('a stale or different task, normative source or version is not reviewable as the same original',()=>{for(const change of [{id:NORM},{normId:ID},{normVersion:2},{expectedVersion:2}])assert.throws(()=>followupReview(update({note:'Cambio',...change}),original()));});
test('creation and update cannot swap their original context',()=>{assert.throws(()=>followupReview(body(),original()));assert.throws(()=>followupReview(update({note:'Cambio'})));});
test('broken documentary history cannot be used as trustworthy original content',()=>{for(const change of [o=>o.history=[],o=>o.history[0].note='Texto distinto',o=>o.recordedAt='invalid']){const old=original();change(old);assert.throws(()=>followupReview(update({note:'Cambio'}),old));}});
test('authority injection and invalid state/date fail through the existing contract',()=>{for(const patch of [{tenantId:'external'},{status:'approved'},{dueDate:'2026-02-30'},{reason:''},{note:'x'.repeat(2001)}])assert.throws(()=>followupReview({...body(),...patch}));});
test('case, accents and whitespace inside text remain genuine changes',()=>{for(const note of ['nota de ensayo','Nota  de ensayo','Nota de ensáyo'])assert.equal(followupReview(update({note}),original()).changeCount,1);});
test('original and caller draft are not mutated; review body cannot drift after confirmation',()=>{const old=original(),value=update({note:'Texto nuevo'}),a=JSON.stringify(old),b=JSON.stringify(value),review=followupReview(value,old);value.note='Otra edición';assert.equal(review.body.note,'Texto nuevo');assert.equal(JSON.stringify(old),a);assert.ok(Object.isFrozen(review.body));assert.ok(Object.isFrozen(review.fields));assert.ok(Object.isFrozen(review.fields[0]));assert.notEqual(JSON.stringify(value),b);});
test('field presentation distinguishes optional absence from legal status inference',()=>{assert.equal(reviewFieldText('dueDate','2026-09-30'),'30/09/2026');assert.equal(reviewFieldText('status','cancelled'),'Cancelado');assert.equal(reviewFieldText('note','Línea uno\nLínea dos'),'Línea uno\nLínea dos');});
