import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {normalizeContractCommand,verifyContractResponse,nextContractStates} from '../assets/legal-contracts-model.js';
import {createLegalContractsHandler} from '../api/internal-legal-contracts.js';
import {access,session,ID,TENANT,MEMBER} from './fixtures/legal-registry-synthetic.js';
const CONTRACT='dddddddd-dddd-4ddd-8ddd-dddddddddddd',CASE='eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee',KEY='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
const createBody=()=>({command:'create',number:'C-001',year:2026,contractType:'servicio',title:'Servicio sintético',object:'Prestación sintética para ensayo contractual',counterparties:[{name:'Proveedor SA',role:'provider',taxId:'30712345678'}],currency:'ARS',amountMinor:123456,startDate:'2026-10-01',endDate:'2026-12-31',approvalReference:'Decreto 1/2026',responsibleId:MEMBER,matterId:ID,caseId:CASE,reason:'Alta sintética documentada'});
const history=()=>[{revision:1,state:'registered',title:'Servicio sintético',object:'Prestación sintética para ensayo contractual',counterparties:[{name:'Proveedor SA',role:'provider',taxId:'30712345678'}],currency:'ARS',amountMinor:123456,startDate:'2026-10-01',endDate:'2026-12-31',approvalReference:'Decreto 1/2026',responsibleId:MEMBER,responsibleLabel:session.email,matterId:ID,caseId:CASE,reason:'Alta sintética documentada',recordedBy:session.email,recordedAt:'2026-09-20T16:00:00Z'}];
const record=()=>({id:CONTRACT,number:'C-001',year:2026,contractType:'servicio',revision:1,state:'registered',title:'Servicio sintético',object:'Prestación sintética para ensayo contractual',counterparties:[{name:'Proveedor SA',role:'provider',taxId:'30712345678'}],currency:'ARS',amountMinor:123456,startDate:'2026-10-01',endDate:'2026-12-31',approvalReference:'Decreto 1/2026',responsible:{id:MEMBER,label:session.email,eligible:true},matterId:ID,caseId:CASE,reason:'Alta sintética documentada',recordedBy:session.email,recordedAt:'2026-09-20T16:00:00Z',history:history()});
const receipt=()=>({version:'legal-contract-receipt.v1',id:CONTRACT,revision:1,state:'registered',replayed:false});

test('create contract normalizes external number and preserves reviewed parties/money',()=>{const b={...createBody(),number:' c-001 '};const n=normalizeContractCommand(b);assert.equal(n.number,'C-001');assert.equal(n.amountMinor,123456);assert.equal(n.counterparties[0].taxId,'30712345678');});
test('invalid CUIT, role, date order and hidden tenant are rejected',()=>{for(const p of [{counterparties:[{name:'X SA',role:'provider',taxId:'123'}]},{counterparties:[{name:'X SA',role:'bad',taxId:''}]},{startDate:'2026-12-31',endDate:'2026-10-01'},{tenantId:TENANT}])assert.throws(()=>normalizeContractCommand({...createBody(),...p}));});
test('currency NONE forbids amount while monetary contracts require integer minor units',()=>{assert.equal(normalizeContractCommand({...createBody(),currency:'NONE',amountMinor:null}).amountMinor,null);assert.throws(()=>normalizeContractCommand({...createBody(),currency:'NONE',amountMinor:1}));assert.throws(()=>normalizeContractCommand({...createBody(),amountMinor:1.5}));});
test('revise and set_state are separate commands',()=>{const base={command:'revise',id:CONTRACT,expectedRevision:1,state:'registered',title:'Servicio sintético',object:'Objeto corregido',counterparties:createBody().counterparties,currency:'ARS',amountMinor:123456,startDate:'2026-10-01',endDate:'2026-12-31',approvalReference:'Decreto 1/2026',responsibleId:MEMBER,matterId:ID,caseId:CASE,reason:'Corrección documentada'};assert.equal(normalizeContractCommand(base).command,'revise');assert.equal(normalizeContractCommand({...base,command:'set_state',state:'under_review'}).state,'under_review');});
test('transition graph is explicit and does not infer legal validity',()=>{assert.deepEqual(nextContractStates('registered'),['under_review','cancelled']);assert.deepEqual(nextContractStates('active'),['under_review','closed','cancelled']);assert.deepEqual(nextContractStates('closed'),['active']);});
test('detail requires full contiguous history',()=>{const d={version:'legal-contract-detail.v1',canManage:true,record:record()};assert.equal(verifyContractResponse('detail',d).record.id,CONTRACT);d.record.history=[];assert.throws(()=>verifyContractResponse('detail',d));});

const res=()=>({headers:{},setHeader(k,v){this.headers[k]=v;},status(n){this.statusCode=n;return this;},json(v){this.value=v;return this;}});
const post=x=>({method:'POST',url:'/',query:{},headers:{origin:'https://municipio-junin-friendly.vercel.app','content-type':'application/json','idempotency-key':KEY},body:JSON.stringify(x)});
const get=q=>({method:'GET',url:'/?'+new URLSearchParams(q),query:q,headers:{}});
function setup({principal=access(),value=receipt(),error=null}={}){const calls=[];let contract;const handler=createLegalContractsHandler({env:{NODE_ENV:'production',IDENTITY_APP_ORIGIN:'https://municipio-junin-friendly.vercel.app'},authorize:async(_q,r,c)=>{contract=c;if(!principal){r.status(401).json({ok:false});return null;}return principal;},getSql:async()=>({query:async(sql,args)=>{calls.push({sql,args});if(error)throw error;return[{result:value}];}})});return{handler,calls,get contract(){return contract;}};}
test('save derives tenant and actor from managed membership',async()=>{const t=setup(),r=res();await t.handler(post(createBody()),r);assert.equal(r.statusCode,201);assert.equal(t.calls[0].sql,'SELECT public.legal_contract_operation_v1($1::jsonb,$2::text,$3::jsonb,$4::uuid) AS result');const [ctx,op,payload,key]=t.calls[0].args;assert.equal(op,'save');assert.equal(key,KEY);assert.equal(JSON.parse(ctx).tenantId,TENANT);assert.equal(JSON.parse(ctx).membershipId,MEMBER);assert.deepEqual(JSON.parse(payload),createBody());assert.deepEqual(t.contract.requiredCapabilities,['legal.norm.read','legal.norm.register']);});
test('reader can list/detail/bootstrap but cannot write',async()=>{const bootstrap={version:'legal-contract-bootstrap.v1',canManage:false,matterId:ID,candidates:[],cases:[{id:CASE,number:'1234-A',year:2026,subject:'Expediente'}]},detail={version:'legal-contract-detail.v1',canManage:false,record:record()},list={version:'legal-contract-list.v1',canManage:false,total:0,page:1,pageSize:25,rows:[]};for(const [q,value]of [[{resource:'bootstrap',matterId:ID},bootstrap],[{resource:'detail',id:CONTRACT},detail],[{resource:'list',q:'',state:'',page:'1'},list]]){const t=setup({principal:access(['legal.norm.read']),value}),r=res();await t.handler(get(q),r);assert.equal(r.statusCode,200);}const w=setup({principal:access(['legal.norm.read'])}),wr=res();await w.handler(post(createBody()),wr);assert.equal(wr.statusCode,403);assert.equal(w.calls.length,0);});
test('anonymous, legacy and unrelated capabilities never reach SQL',async()=>{for(const p of [null,{...access(),mode:'legacy'},access(['payroll.read'])]){const t=setup({principal:p}),r=res();await t.handler(get({resource:'list',q:'',state:'',page:'1'}),r);assert.ok([401,403].includes(r.statusCode));assert.equal(t.calls.length,0);}});
test('same-origin JSON and UUID-v4 key are mandatory',async()=>{for(const h of [{origin:'https://other.invalid'},{'content-type':'text/plain'},{'idempotency-key':'bad'}]){const req=post(createBody());Object.assign(req.headers,h);const t=setup(),r=res();await t.handler(req,r);assert.ok([403,415,422].includes(r.statusCode));assert.equal(t.calls.length,0);}});
test('contract workflow errors are actionable without SQL leakage',async()=>{for(const [m,status,part]of [['CONTRACT_DUPLICATE',409,'existe'],['CONTRACT_VERSION_CONFLICT',409,'cambió'],['private SQL',503,'confirmar']]){const t=setup({error:Error(m)}),r=res();await t.handler(post(createBody()),r);assert.equal(r.statusCode,status);assert.match(r.value.error,new RegExp(part,'i'));assert.doesNotMatch(r.value.error,/private SQL/);}});
test('migration versions contracts and separates fiche edits from administrative state',()=>{const s=fs.readFileSync('scripts/migrations/086-legal-contracts.sql','utf8');assert.match(s,/legal_contract_revision_immutable/);assert.match(s,/CONTRACT_STATE_IMMUTABLE/);assert.match(s,/CONTRACT_FIELDS_IMMUTABLE/);assert.match(s,/legal_matter_case_link/);assert.match(s,/counterparties jsonb/);assert.match(s,/amount_minor bigint/);assert.doesNotMatch(s,/\b(?:payroll_|salary_|liquidation_)/i);assert.equal((s.match(/CREATE TABLE public\.legal_contract \(/g)||[]).length,1);assert.equal((s.match(/CREATE FUNCTION public\.legal_contract_operation_v1/g)||[]).length,1);});
