import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {normalizeCaseActionDraft,verifyCaseActionResponse} from '../assets/legal-case-actions-model.js';import {createLegalCaseActionsHandler} from '../api/internal-legal-case-actions.js';import {access,session,TENANT,MEMBER} from './fixtures/legal-registry-synthetic.js';
const CASE='dddddddd-dddd-4ddd-8ddd-dddddddddddd',DOC='eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee',KEY='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
const body=()=>({caseId:CASE,expectedCaseRevision:1,expectedSequence:0,actionType:'constancia',fromArea:'Jurídica',toArea:'',description:'Se deja constancia sintética',documentId:null,reason:'Registro sintético documentado'});
const list=()=>({version:'legal-case-action-list.v1',case:{id:CASE,number:'1234-A',year:2026,state:'open',revision:1,subject:'Expediente sintético'},canManage:true,currentArea:'Jurídica',lastSequence:0,documents:[],rows:[]});
const receipt=()=>({version:'legal-case-action-receipt.v1',caseId:CASE,sequence:1,areaAfter:'Jurídica',replayed:false});
test('constancia keeps current area and exact sequence contract',()=>assert.deepEqual(normalizeCaseActionDraft(body()),body()));
test('pase requires a distinct destination',()=>{const p={...body(),actionType:'pase',toArea:'Contaduría'};assert.equal(normalizeCaseActionDraft(p).toArea,'Contaduría');assert.throws(()=>normalizeCaseActionDraft({...p,toArea:'Jurídica'}));});
test('non-pase cannot smuggle a destination or invalid document',()=>{assert.throws(()=>normalizeCaseActionDraft({...body(),toArea:'Tesorería'}));assert.throws(()=>normalizeCaseActionDraft({...body(),documentId:'bad'}));});
test('list requires contiguous descending timeline',()=>{const d=list();d.lastSequence=1;d.rows=[{sequence:1,actionType:'constancia',fromArea:'Jurídica',toArea:'',description:'Constancia sintética',document:null,reason:'Registro sintético',recordedBy:session.email,recordedAt:'2026-09-20T12:00:00Z'}];assert.equal(verifyCaseActionResponse('list',d).lastSequence,1);d.rows[0].sequence=2;assert.throws(()=>verifyCaseActionResponse('list',d));});
const res=()=>({headers:{},setHeader(k,v){this.headers[k]=v;},status(n){this.statusCode=n;return this;},json(v){this.value=v;return this;}}),post=x=>({method:'POST',url:'/',query:{},headers:{origin:'https://municipio-junin-friendly.vercel.app','content-type':'application/json','idempotency-key':KEY},body:JSON.stringify(x)}),get=q=>({method:'GET',url:'/?'+new URLSearchParams(q),query:q,headers:{}});
function setup({principal=access(),value=receipt(),error=null}={}){const calls=[];let contract;const handler=createLegalCaseActionsHandler({env:{NODE_ENV:'production',IDENTITY_APP_ORIGIN:'https://municipio-junin-friendly.vercel.app'},authorize:async(_q,r,c)=>{contract=c;if(!principal){r.status(401).json({ok:false});return null;}return principal;},getSql:async()=>({query:async(sql,args)=>{calls.push({sql,args});if(error)throw error;return[{result:value}];}})});return{handler,calls,get contract(){return contract;}};}
test('save derives tenant and actor from managed session',async()=>{const t=setup(),r=res();await t.handler(post(body()),r);assert.equal(r.statusCode,201);assert.equal(JSON.parse(t.calls[0].args[0]).tenantId,TENANT);assert.equal(JSON.parse(t.calls[0].args[0]).membershipId,MEMBER);assert.deepEqual(t.contract.requiredCapabilities,['legal.norm.read','legal.norm.register']);});
test('reader can inspect timeline but cannot write',async()=>{const t=setup({principal:access(['legal.norm.read']),value:{...list(),canManage:false}}),r=res();await t.handler(get({resource:'list',caseId:CASE}),r);assert.equal(r.statusCode,200);const w=setup({principal:access(['legal.norm.read'])}),wr=res();await w.handler(post(body()),wr);assert.equal(wr.statusCode,403);assert.equal(w.calls.length,0);});
test('anonymous and unrelated capability never reach SQL',async()=>{for(const p of [null,access(['payroll.read'])]){const t=setup({principal:p}),r=res();await t.handler(get({resource:'list',caseId:CASE}),r);assert.ok([401,403].includes(r.statusCode));assert.equal(t.calls.length,0);}});
test('same-origin JSON and idempotency key are mandatory',async()=>{for(const h of [{origin:'https://other.invalid'},{'content-type':'text/plain'},{'idempotency-key':'bad'}]){const req=post(body());Object.assign(req.headers,h);const t=setup(),r=res();await t.handler(req,r);assert.ok([403,415,422].includes(r.statusCode));assert.equal(t.calls.length,0);}});
test('workflow conflicts are actionable without SQL leakage',async()=>{for(const [m,status,part]of [['CASE_ACTION_SEQUENCE_CONFLICT',409,'reciente'],['CASE_ACTION_AREA_CONFLICT',409,'área'],['private SQL',503,'confirmar']]){const t=setup({error:Error(m)}),r=res();await t.handler(post(body()),r);assert.equal(r.statusCode,status);assert.match(r.value.error,new RegExp(part,'i'));assert.doesNotMatch(r.value.error,/private SQL/);}});
test('migration derives current area from passes and never rewrites history',()=>{const s=fs.readFileSync('scripts/migrations/085-legal-case-actions.sql','utf8');assert.match(s,/action_type='pase'/);assert.match(s,/ORDER BY a\.sequence DESC LIMIT 1/);assert.match(s,/legal_case_action_immutable/);assert.match(s,/expectedSequence/);assert.match(s,/document_id/);assert.doesNotMatch(s,/\b(?:payroll_|salary_|liquidation_)/i);});
