import test from 'node:test';
import assert from 'node:assert/strict';
import {blankLegalDraft,legalDraftFingerprint,legalDraftChanged,normalizeLegalDraft} from '../assets/legal-registry-model.js';
function valid(){const d=blankLegalDraft();d.identity.number='1';d.metadata.title='Norma de prueba';d.metadata.sourceReference='Archivo sint?tico';d.reason='Registro sint?tico';d.document={filename:'fuente.pdf',sha256:'a'.repeat(64),contentBase64:'AA=='};return d;}
test('un formulario nuevo intacto no se considera editado',()=>{const d=blankLegalDraft();assert.equal(legalDraftChanged(d,legalDraftFingerprint(d)),false);assert.equal(legalDraftChanged(null,''),false);});
test('detectar cambio y reversi?n sin persistir el borrador',()=>{const d=valid(),base=legalDraftFingerprint(d);d.metadata.title+=' modificado';assert.equal(legalDraftChanged(d,base),true);d.metadata.title='Norma de prueba';assert.equal(legalDraftChanged(d,base),false);});
for(const field of ['title','topics','summary','sourceReference','issueDate','publicationDate','effectiveDate','stage'])test('cambio documental '+field,()=>{const d=valid(),base=legalDraftFingerprint(d);d.metadata[field]+='X';assert.equal(legalDraftChanged(d,base),true);});
test('identidad, motivo, art?culos y archivo pertenecen al borrador',()=>{for(const change of [d=>d.identity.number='2',d=>d.reason+='X',d=>d.metadata.articles.push({label:'1',text:'Texto',page:1}),d=>d.document.filename='otro.pdf',d=>d.document.sha256='b'.repeat(64)]){const d=valid(),base=legalDraftFingerprint(d);change(d);assert.equal(legalDraftChanged(d,base),true);}});
for(const [key,value,field] of [['label','','articleLabel2'],['text','','articleText2'],['page',0,'articlePage2'],['label','Art. 1','articleLabel2']])test('el error del tercer art?culo apunta a '+field,()=>{const d=valid();d.metadata.articles=[1,2,3].map(n=>({label:'Art. '+n,text:'Texto completo',page:1}));d.metadata.articles[2][key]=value;assert.throws(()=>normalizeLegalDraft(d),e=>e.field===field);});
test('falta de PDF enfoca el control real',()=>{const d=valid();d.document=null;assert.throws(()=>normalizeLegalDraft(d),e=>e.field==='pdf');});
test('el orden de propiedades no produce cambios falsos',()=>{const d=valid(),base=legalDraftFingerprint(d);d.identity={year:d.identity.year,number:d.identity.number,issuer:d.identity.issuer,kind:d.identity.kind};assert.equal(legalDraftChanged(d,base),false);});
