import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {normalizeCaseDocumentDraft,verifyCaseDocumentResponse,CASE_DOCUMENT_LIMIT} from '../assets/legal-case-documents-model.js';import {createLegalCaseDocumentsHandler} from '../api/internal-legal-case-documents.js';import {access,session,TENANT,MEMBER} from './fixtures/legal-registry-synthetic.js';
const CASE='dddddddd-dddd-4ddd-8ddd-dddddddddddd',DOC='eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee',SERIES='ffffffff-ffff-4fff-8fff-ffffffffffff',KEY='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
const body=()=>({caseId:CASE,kind:'original',title:'Antecedente sintético',sourceReference:'Mesa de Entradas',supersedesId:null,document:{filename:'antecedente.pdf',contentBase64:'JVBERi0xLjQK',sha256:'a'.repeat(64),pages:1},reason:'Alta documental sintética'}),list=()=>({version:'legal-case-document-list.v1',case:{id:CASE,number:'1234-A',year:2026,state:'open',revision:1,subject:'Expediente sintético'},canManage:true,storageBytes:0,storageLimitBytes:CASE_DOCUMENT_LIMIT,rows:[]}),receipt=()=>({version:'legal-case-document-receipt.v1',id:DOC,caseId:CASE,seriesId:SERIES,documentVersion:1,replayed:false});
test('upload contract binds case, kind, provenance and exact PDF metadata',()=>assert.deepEqual(normalizeCaseDocumentDraft(body()),body()));
test('upload rejects hidden authority, bad PDF and unsafe metadata',()=>{for(const p of [{tenantId:TENANT},{kind:'contrato'},{title:'<x>'},{sourceReference:'x'},{document:{...body().document,filename:'x.txt'}},{document:{...body().document,pages:31}}])assert.throws(()=>normalizeCaseDocumentDraft({...body(),...p}));});
test('new version references prior UUID',()=>assert.equal(normalizeCaseDocumentDraft({...body(),supersedesId:DOC}).supersedesId,DOC));
test('list verifies bounded storage metadata',()=>{const d=list();d.rows=[{id:DOC,seriesId:SERIES,version:1,supersedesId:null,kind:'original',title:'Antecedente sintético',sourceReference:'Mesa de Entradas',filename:'antecedente.pdf',sha256:'a'.repeat(64),bytes:100,pages:1,reason:'Alta documental sintética',recordedBy:session.email,recordedAt:'2026-09-20T12:00:00Z',isLatest:true}];assert.equal(verifyCaseDocumentResponse('list',d).rows.length,1);});
const res=()=>({headers:{},setHeader(k,v){this.headers[k]=v;},status(n){this.statusCode=n;return this;},json(v){this.value=v;return this;}}),post=x=>({method:'POST',url:'/',query:{},headers:{origin:'https://municipio-junin-friendly.vercel.app','content-type':'application/json','idempotency-key':KEY},body:JSON.stringify(x)}),get=q=>({method:'GET',url:'/?'+new URLSearchParams(q),query:q,headers:{}});
function setup({principal=access(),value=receipt(),error=null}={}){const calls=[];let contract;const handler=createLegalCaseDocumentsHandler({env:{NODE_ENV:'production',IDENTITY_APP_ORIGIN:'https://municipio-junin-friendly.vercel.app'},authorize:async(_q,r,c)=>{contract=c;if(!principal){r.status(401).json({ok:false});return null;}return principal;},getSql:async()=>({query:async(sql,args)=>{calls.push({sql,args});if(error)throw error;return[{result:value}];}})});return{handler,calls,get contract(){return contract;}};}
test('save derives tenant and actor',async()=>{const t=setup(),r=res();await t.handler(post(body()),r);assert.equal(r.statusCode,201);assert.equal(JSON.parse(t.calls[0].args[0]).tenantId,TENANT);assert.equal(JSON.parse(t.calls[0].args[0]).membershipId,MEMBER);assert.deepEqual(t.contract.requiredCapabilities,['legal.norm.read','legal.norm.register']);});
test('reader can list/download but not upload',async()=>{const t=setup({principal:access(['legal.norm.read']),value:{...list(),canManage:false}}),r=res();await t.handler(get({resource:'list',caseId:CASE}),r);assert.equal(r.statusCode,200);const w=setup({principal:access(['legal.norm.read'])}),wr=res();await w.handler(post(body()),wr);assert.equal(wr.statusCode,403);assert.equal(w.calls.length,0);});
test('anonymous and unrelated access never reach SQL',async()=>{for(const p of [null,access(['payroll.read'])]){const t=setup({principal:p}),r=res();await t.handler(get({resource:'list',caseId:CASE}),r);assert.ok([401,403].includes(r.statusCode));assert.equal(t.calls.length,0);}});
test('same-origin JSON and UUID key mandatory',async()=>{for(const h of [{origin:'https://other.invalid'},{'content-type':'text/plain'},{'idempotency-key':'bad'}]){const req=post(body());Object.assign(req.headers,h);const t=setup(),r=res();await t.handler(req,r);assert.ok([403,415,422].includes(r.statusCode));assert.equal(t.calls.length,0);}});
test('migration is immutable and capacity bounded',()=>{const s=fs.readFileSync('scripts/migrations/084-legal-case-documents.sql','utf8');assert.match(s,/2097152/);assert.match(s,/16777216/);assert.match(s,/legal_case_document_immutable/);assert.match(s,/supersedes_document_id/);assert.doesNotMatch(s,/\b(?:payroll_|salary_|liquidation_)/i);});
