import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {filterLegalAlerts,legalAlertCategory,legalAlertCounts,verifyLegalAlertCenterResponse} from '../assets/legal-alert-center-model.js';
const F='dddddddd-dddd-4ddd-8ddd-dddddddddddd',N='eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee',O='ffffffff-ffff-4fff-8fff-ffffffffffff',C='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
const follow=(p={})=>({sourceType:'followup',itemId:F,itemVersion:2,title:'Revisar ordenanza',dueDate:'2026-09-21',status:'open',responsibleLabel:'',sourceId:N,sourceVersion:1,sourceKind:'ordenanza',sourceNumber:'9000',sourceYear:2026,sourceTitle:'Norma sintética',recordedAt:'2026-09-20T20:00:00Z',...p});
const obligation=(p={})=>({sourceType:'contract_obligation',itemId:O,itemVersion:1,title:'Entrega técnica',dueDate:'2026-09-25',status:'open',responsibleLabel:'responsable@example.invalid',sourceId:C,sourceVersion:1,sourceKind:'servicio',sourceNumber:'C-001',sourceYear:2026,sourceTitle:'Contrato sintético',recordedAt:'2026-09-20T21:00:00Z',...p});
const payload=rows=>({version:'legal-alert-center.v1',today:'2026-09-21',timezone:'America/Argentina/Mendoza',limit:1500,population:rows.length,revision:'a'.repeat(64),rows});
test('unified alert response verifies both supported sources',()=>assert.equal(verifyLegalAlertCenterResponse(payload([follow(),obligation()])).population,2));
test('historical norms retain the registry year range without breaking the whole center',()=>{for(const sourceYear of [1700,1899,2200])assert.equal(verifyLegalAlertCenterResponse(payload([follow({sourceYear})])).population,1);for(const sourceYear of [1699,2201])assert.throws(()=>verifyLegalAlertCenterResponse(payload([follow({sourceYear})])));assert.throws(()=>verifyLegalAlertCenterResponse(payload([obligation({sourceYear:1899})])));});
test('alerts reject impossible dates, unknown statuses, duplicates and excess fields',()=>{
 for(const row of [follow({dueDate:'2026-02-31'}),follow({dueDate:'2026-13-01'}),follow({status:'fulfilled_observed'}),obligation({status:'done'}),obligation({sourceVersion:101}),follow({privateNote:'unexpected'})])assert.throws(()=>verifyLegalAlertCenterResponse(payload([row])));
 assert.throws(()=>verifyLegalAlertCenterResponse({...payload([]),today:'2026-02-29'}));assert.throws(()=>verifyLegalAlertCenterResponse(payload([follow(),follow()])));
 assert.equal(verifyLegalAlertCenterResponse(payload([follow({dueDate:'2028-02-29'})])).population,1);
});
test('date windows handle year boundaries, undated items and closed past items',()=>{assert.equal(legalAlertCategory(follow({dueDate:'2027-01-07'}),'2026-12-31'),'next7');assert.equal(legalAlertCategory(follow({dueDate:'2027-01-08'}),'2026-12-31'),'later');assert.equal(legalAlertCategory(follow({dueDate:''}),'2026-12-31'),'undated');assert.equal(legalAlertCategory(follow({dueDate:'2026-01-01',status:'cancelled'}),'2026-12-31'),'resolved');});
test('unified categories remain descriptive rather than legal conclusions',()=>{assert.equal(legalAlertCategory(follow({dueDate:'2026-09-20'}),'2026-09-21'),'past');assert.equal(legalAlertCategory(follow(),'2026-09-21'),'today');assert.equal(legalAlertCategory(obligation(),'2026-09-21'),'next7');assert.equal(legalAlertCategory(obligation({status:'fulfilled_observed'}),'2026-09-21'),'resolved');});
test('counts stay exclusive and source filter is explicit',()=>{const rows=[follow(),obligation()];const c=legalAlertCounts(rows,'2026-09-21');assert.equal(c.all,2);assert.equal(c.today,1);assert.equal(c.next7,1);assert.equal(filterLegalAlerts(rows,'2026-09-21',{source:'followup'}).length,1);assert.equal(filterLegalAlerts(rows,'2026-09-21',{query:'tecnica'}).length,1);});
test('migration is bounded read-only and excludes inferred conclusions',()=>{const s=fs.readFileSync('scripts/migrations/089-legal-alert-center.sql','utf8');assert.equal(s.split('CREATE FUNCTION public.legal_alert_center_v1').length-1,1);assert.equal(s.includes('legal_norm_context_v1(p,false)'),true);assert.equal(s.includes('population>1500'),true);assert.equal(s.includes('America/Argentina/Mendoza'),true);assert.doesNotMatch(s,/\b(?:INSERT|UPDATE|DELETE)\b/i);assert.equal(s.includes('no private notes, actor emails, inferred deadlines or legal conclusions'),true);});
