import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {normalizeMatterCommand,verifyMatterResponse,commandForState,MATTER_STATES} from '../assets/legal-matters-model.js';
import {createLegalMattersHandler} from '../api/internal-legal-matters.js';
import {access,session,ID,TENANT,MEMBER} from './fixtures/legal-registry-synthetic.js';

const MATTER='dddddddd-dddd-4ddd-8ddd-dddddddddddd',PERSON='eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee',KEY='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
const source={kind:'ordenanza',issuer:'HCD',number:'9000',year:2026,title:'Norma sintética',currentVersion:2};
const history=()=>[{revision:1,state:'assigned',responsibleId:PERSON,responsibleLabel:'responsable@example.invalid',nextAction:'Revisar antecedentes',targetDate:'2026-09-30',observations:'',evidenceArticleLabel:'',evidenceNote:'',reason:'Alta de asunto de ensayo',recordedBy:session.email,recordedAt:'2026-09-20T10:00:00Z'}];
const record=()=>({id:MATTER,normId:ID,normVersion:1,revision:1,state:'assigned',matterType:'revision_normativa',title:'Revisar norma sintética',owningArea:'Jurídica',responsible:{id:PERSON,label:'responsable@example.invalid',eligible:true},nextAction:'Revisar antecedentes',targetDate:'2026-09-30',observations:'',evidenceArticleLabel:'',evidenceNote:'',reason:'Alta de asunto de ensayo',recordedBy:session.email,recordedAt:'2026-09-20T10:00:00Z',source,history:history()});
const detail=()=>({version:'legal-matter-detail.v1',today:'2026-09-20',canManage:true,record:record(),candidates:[{id:PERSON,label:'responsable@example.invalid'}],sourceArticles:['Artículo 1']});
const createBody=()=>({command:'create',sourceNormId:ID,sourceNormVersion:1,matterType:'revision_normativa',title:'Revisar norma sintética',owningArea:'Jurídica',responsibleId:PERSON,nextAction:'Revisar antecedentes',targetDate:'2026-09-30',reason:'Alta de asunto de ensayo'});
const transition=(command='start_review')=>({command,id:MATTER,expectedRevision:1,responsibleId:PERSON,owningArea:'Jurídica',nextAction:'Continuar revisión técnica',targetDate:'2026-09-30',observations:'',evidenceArticleLabel:'',evidenceNote:'',reason:'Avance documentado de ensayo'});
const receipt=(state='assigned')=>({version:'legal-matter-receipt.v1',id:MATTER,revision:1,state,replayed:false});

test('create command binds an exact norm revision and validated responsible',()=>{const b=createBody(),before=JSON.stringify(b);assert.deepEqual(normalizeMatterCommand(b),b);assert.equal(JSON.stringify(b),before);});
test('create rejects hidden authority, invalid source, unsafe text and missing next action',()=>{for(const patch of [{tenantId:TENANT},{sourceNormId:'bad'},{responsibleId:'bad'},{title:'<x>'},{nextAction:''},{targetDate:'2026-02-30'},{reason:'x'}])assert.throws(()=>normalizeMatterCommand({...createBody(),...patch}));});
test('return requires observations and no response evidence',()=>{const b={...transition('return'),observations:'Falta acreditar la publicación de la norma'};assert.equal(normalizeMatterCommand(b).command,'return');for(const patch of [{observations:''},{evidenceNote:'Prueba indebida'},{evidenceArticleLabel:'Artículo 1'}])assert.throws(()=>normalizeMatterCommand({...b,...patch}));});
test('respond requires evidence and may cite an article label',()=>{const b={...transition('respond'),evidenceArticleLabel:'Artículo 1',evidenceNote:'La respuesta se funda en el artículo indicado'};assert.equal(normalizeMatterCommand(b).evidenceArticleLabel,'Artículo 1');assert.throws(()=>normalizeMatterCommand({...b,evidenceNote:''}));});
test('close and cancel cannot leave a next action',()=>{for(const command of ['close','cancel']){const b={...transition(command),nextAction:''};assert.equal(normalizeMatterCommand(b).nextAction,'');assert.throws(()=>normalizeMatterCommand({...b,nextAction:'Todavía hacer algo'}));}});
test('active transitions expose only the documented command graph',()=>{assert.deepEqual(commandForState('assigned'),['start_review','reassign','cancel']);assert.deepEqual(commandForState('returned'),['respond','reassign','cancel']);assert.deepEqual(commandForState('closed'),['reopen']);assert.throws(()=>commandForState('invented'));});
test('detail verifies source, responsible, history and exact article evidence',()=>{assert.equal(verifyMatterResponse('detail',detail()).record.id,MATTER);const d=detail();d.record.evidenceArticleLabel='Artículo inexistente';d.record.history[0].evidenceArticleLabel='Artículo inexistente';assert.throws(()=>verifyMatterResponse('detail',d));});
test('detail cannot expose candidates to a read-only result',()=>{const d=detail();d.canManage=false;assert.throws(()=>verifyMatterResponse('detail',d));d.candidates=[];assert.equal(verifyMatterResponse('detail',d).canManage,false);});
test('list counts reconcile exactly and duplicate cards are rejected',()=>{const row={id:MATTER,revision:1,state:'assigned',matterType:'revision_normativa',title:'Revisar norma sintética',owningArea:'Jurídica',responsibleLabel:'responsable@example.invalid',nextAction:'Revisar antecedentes',targetDate:'2026-09-30',normId:ID,normVersion:1,source,recordedAt:'2026-09-20T10:00:00Z'};const d={version:'legal-matter-list.v1',today:'2026-09-20',canManage:true,total:1,page:1,pageSize:25,counts:{assigned:1,inReview:0,returned:0,responded:0,reviewed:0,closed:0,cancelled:0},rows:[row]};assert.equal(verifyMatterResponse('list',d).total,1);assert.throws(()=>verifyMatterResponse('list',{...d,total:2}));assert.throws(()=>verifyMatterResponse('list',{...d,total:2,counts:{...d.counts,assigned:2},rows:[row,row]}));});

const res=()=>({headers:{},setHeader(k,v){this.headers[k]=v;},status(n){this.statusCode=n;return this;},json(v){this.value=v;return this;}});
const post=body=>({method:'POST',url:'/',query:{},headers:{origin:'https://municipio-junin-friendly.vercel.app','content-type':'application/json','idempotency-key':KEY},body:JSON.stringify(body)});
const get=q=>({method:'GET',url:'/?'+new URLSearchParams(q),query:q,headers:{}});
function setup({principal=access(),value=receipt(),error=null}={}){const calls=[];let contract;const handler=createLegalMattersHandler({env:{NODE_ENV:'production',IDENTITY_APP_ORIGIN:'https://municipio-junin-friendly.vercel.app'},authorize:async(_q,r,c)=>{contract=c;if(!principal){r.status(401).json({ok:false});return null;}return principal;},getSql:async()=>({query:async(sql,args)=>{calls.push({sql,args});if(error)throw error;return[{result:value}];}})});return{handler,calls,get contract(){return contract;}};}
test('save derives actor and municipality from managed session',async()=>{const t=setup(),r=res();await t.handler(post(createBody()),r);assert.equal(r.statusCode,201);assert.equal(t.calls.length,1);const [context,op,payload,key]=t.calls[0].args;assert.equal(op,'save');assert.equal(key,KEY);assert.equal(JSON.parse(context).tenantId,TENANT);assert.equal(JSON.parse(context).membershipId,MEMBER);assert.equal(JSON.parse(context).actorEmail,session.email);assert.deepEqual(JSON.parse(payload),createBody());assert.deepEqual(t.contract.requiredCapabilities,['legal.norm.read','legal.norm.register']);assert.equal(t.contract.allowLegacy,false);assert.match(r.headers['Cache-Control'],/private.*no-store/);});
test('reader may list/detail but never save or recover write receipts',async()=>{for(const [query,value] of [[{resource:'detail',id:MATTER},detail()],[{resource:'list',q:'',state:'',page:'1'}, {version:'legal-matter-list.v1',today:'2026-09-20',canManage:false,total:0,page:1,pageSize:25,counts:{assigned:0,inReview:0,returned:0,responded:0,reviewed:0,closed:0,cancelled:0},rows:[]}]] ){const t=setup({principal:access(['legal.norm.read']),value}),r=res();await t.handler(get(query),r);assert.equal(r.statusCode,200);}for(const req of [post(createBody()),get({resource:'attempt',key:KEY})]){const t=setup({principal:access(['legal.norm.read'])}),r=res();await t.handler(req,r);assert.equal(r.statusCode,403);assert.equal(t.calls.length,0);}});
test('anonymous, legacy and unrelated access never reach SQL',async()=>{for(const principal of [null,{...access(),mode:'legacy'},access(['payroll.read'])]){const t=setup({principal}),r=res();await t.handler(get({resource:'detail',id:MATTER}),r);assert.ok([401,403].includes(r.statusCode));assert.equal(t.calls.length,0);}});
test('query cannot inject tenant, actor, duplicate keys or arbitrary pagination',async()=>{for(const req of [get({resource:'detail',id:MATTER,tenantId:TENANT}),{...get({resource:'detail',id:MATTER}),url:'/?resource=detail&id='+MATTER+'&id='+MATTER},get({resource:'list',q:'',state:'',page:'201'})]){const t=setup(),r=res();await t.handler(req,r);assert.equal(r.statusCode,422);assert.equal(t.calls.length,0);}});

test('same-origin JSON and UUID-v4 idempotency are mandatory for writes',async()=>{for(const headers of [{origin:'https://other.invalid'},{'content-type':'text/plain'},{'idempotency-key':'bad'}]){const req=post(createBody());Object.assign(req.headers,headers);const t=setup(),r=res();await t.handler(req,r);assert.ok([403,415,422].includes(r.statusCode));assert.equal(t.calls.length,0);}});
test('unexpected body fields and duplicate JSON cannot widen authority',async()=>{for(const body of [JSON.stringify({...createBody(),tenantId:TENANT}),'{"command":"create","command":"cancel"}']){const t=setup(),r=res(),req=post(createBody());req.body=body;await t.handler(req,r);assert.equal(r.statusCode,422);assert.equal(t.calls.length,0);}});
test('mismatched confirmation is unavailable rather than accepted',async()=>{for(const value of [null,{...receipt(),id:ID},{...receipt(),revision:0},{...receipt(),replayed:'true'}]){const t=setup({value}),r=res();await t.handler(post({...transition(),id:MATTER}),r);assert.equal(r.statusCode,503);assert.equal(r.value.data,undefined);}});
test('workflow conflicts are explicit without exposing database details',async()=>{for(const [message,status,part] of [['MATTER_VERSION_CONFLICT',409,'cambió'],['MATTER_EVIDENCE_NOT_FOUND',422,'artículo'],['private SQL path',503,'confirmar']]){const t=setup({error:Error(message)}),r=res();await t.handler(post(createBody()),r);assert.equal(r.statusCode,status);assert.match(r.value.error,new RegExp(part,'i'));assert.doesNotMatch(r.value.error,/private SQL/);}});
test('migration is append-only, tenant-scoped, source-versioned and has no payroll effects',()=>{const sql=fs.readFileSync('scripts/migrations/082-legal-matters.sql','utf8');assert.match(sql,/FOREIGN KEY\(tenant_id,norm_id,norm_version\)[\s\S]*legal_norm_revision/);assert.match(sql,/legal_matter_event_immutable/);assert.match(sql,/legal_norm_context_v1\(p,op IN \('save','attempt'\)\)/);assert.match(sql,/legal_coordination_member_v1\(t,target\)/);assert.match(sql,/MATTER_VERSION_CONFLICT/);assert.match(sql,/MATTER_EVIDENCE_NOT_FOUND/);assert.doesNotMatch(sql,/\b(?:payroll_|salary_|liquidation_)/i);assert.match(sql,/REVOKE ALL ON public\.legal_matter,public\.legal_matter_event/);});
test('migration enforces review-return-response-reviewed-close states without automatic legal validity',()=>{const sql=fs.readFileSync('scripts/migrations/082-legal-matters.sql','utf8');for(const state of ['assigned','in_review','returned','responded','reviewed','closed','cancelled'])assert.ok(sql.includes("'"+state+"'"));for(const command of ['start_review','return','respond','mark_reviewed','close','cancel','reopen','reassign'])assert.ok(sql.includes("'"+command+"'"));assert.doesNotMatch(sql,/legalStatus.*vigente|derogad[ao]/i);});
