import test from 'node:test';import assert from 'node:assert/strict';
import {articleRecord,articleQuery,literalArticleMatches,filterArticles,articleReference,selectedArticleText,sameArticleVersion} from '../assets/legal-article-workspace.js';
import {record} from './fixtures/legal-registry-synthetic.js';
const sample=()=>{const r=record();r.metadata.articles=[{label:'Artículo 1',page:1,text:'NO corresponde el descuento del 25,5 % en el año señalado. Fiscalización según resolución.'},{label:'Anexo A',page:1,text:'Mantener los símbolos [a+b]. No son una expresión regular.'}];return r;};
test('literal search ignores vowel accents/case but preserves exact offsets and ñ',()=>{
 const text='🙂 FISCALIZACIO\u0301N del año. Fiscalización final.';const m=literalArticleMatches(text,'fiscalizacion');assert.equal(m.count,2);assert.equal(m.ranges.map(([a,b])=>text.slice(a,b)).join('|'),'FISCALIZACIO\u0301N|Fiscalización');assert.equal(literalArticleMatches(text,'ano').count,0);assert.equal(literalArticleMatches(text,'AÑO').count,1);
});
test('query syntax is literal, bounded, and never evaluated as regex or markup',()=>{
 assert.equal(literalArticleMatches('texto [a+b] \n<script> test','[a+b]').count,1);assert.equal(literalArticleMatches('texto [a+b]','.*').count,0);assert.equal(articleQuery('  25,5 %  '),'25,5 %');
 for(const q of [null,'a'.repeat(161),'x\n'])assert.throws(()=>articleQuery(q));
});
test('dense matches remain fully counted without creating unbounded highlights',()=>{const m=literalArticleMatches('a'.repeat(1000),'a');assert.equal(m.count,1000);assert.equal(m.ranges.length,120);assert.equal(m.truncated,true);});
test('article filters retain original positions, figures and all unmodified text',()=>{const r=sample(),before=JSON.stringify(r);const rows=filterArticles(r,'25,5 %');assert.equal(rows.length,1);assert.equal(rows[0].index,0);assert.equal(rows[0].matches,1);assert.equal(filterArticles(r,'anexo')[0].index,1);assert.equal(filterArticles(r,'no existe').length,0);assert.equal(JSON.stringify(r),before);});
test('stable internal citations bind record/version/source page, not current row position',()=>{const r=sample();const ref=articleReference(r,1);assert.match(ref.path,/version=1#articulo-2$/);assert.match(ref.text,/Anexo A.*página 1/);assert.throws(()=>articleReference(r,2));});
test('downloaded selection keeps exact articles in source order and states historic version',()=>{const r=sample();r.currentVersion=2;const text=selectedArticleText(r,[1,0]);assert.ok(text.indexOf(r.metadata.articles[0].text)<text.indexOf(r.metadata.articles[1].text));assert.ok(text.includes('NO corresponde el descuento del 25,5 %'));assert.match(text,/versión documental histórica/);assert.ok(text.includes(r.document.sha256));assert.match(text,/No es un dictamen, copia certificada/);});
test('selection refuses repeats, nonexistent articles and over thirty entries',()=>{const r=sample();for(const ids of [[],[0,0],[2],[-1],['0'],Array.from({length:31},(_,n)=>n)])assert.throws(()=>selectedArticleText(r,ids));});
test('access revalidation must agree on version, current version and every selected-source text',()=>{const r=sample(),copy=structuredClone(r);assert.equal(sameArticleVersion(r,copy),true);for(const changed of [{currentVersion:2},{document:{...r.document,sha256:'f'.repeat(64)}},{metadata:{...r.metadata,articles:[{...r.metadata.articles[0],text:'Otra transcripción.'}]}}])assert.equal(sameArticleVersion(r,{...copy,...changed}),false);});
test('malformed source projections are rejected without assuming a valid source',()=>{for(const patch of [{version:0},{currentVersion:0},{id:'unknown'},{document:{...record().document,pages:0}},{metadata:{...record().metadata,articles:[{label:'Artículo',page:2,text:'No cabe.'}]}}])assert.throws(()=>articleRecord({...record(),...patch}));});
