import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {normalizeRelationCommand,verifyRelationResponse} from '../assets/legal-norm-relations-model.js';
import {createLegalNormRelationsHandler} from '../api/internal-legal-norm-relations.js';
import {access,session,TENANT,MEMBER} from './fixtures/legal-registry-synthetic.js';
const A='dddddddd-dddd-4ddd-8ddd-dddddddddddd',B='eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee',R='ffffffff-ffff-4fff-8fff-ffffffffffff',KEY='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
const source={id:A,version:2,currentVersion:2,kind:'ordenanza',issuer:'HCD',number:'100',year:2026,title:'Norma fuente',articles:[{label:'Artículo 2',text:'Texto fuente',page:1}]};
const target={id:B,version:1,currentVersion:1,kind:'decreto',issuer:'EJECUTIVO',number:'20',year:2026,title:'Norma destino',articles:[{label:'Artículo 1',text:'Texto destino',page:1}]};
const create=()=>({command:'create',sourceNormId:A,sourceVersion:2,targetNormId:B,targetVersion:1,relationType:'modifies',sourceArticleLabel:'Artículo 2',targetArticleLabel:'Artículo 1',basisNote:'La versión fuente declara expresamente la modificación indicada.',reason:'Relación revisada por Jurídica'});
const receipt=()=>({version:'legal-norm-relation-receipt.v1',id:R,sequence:1,status:'declared',replayed:false});
test('relation create pins exact source and target versions',()=>assert.deepEqual(normalizeRelationCommand(create()),create()));
test('self relation, invalid type and unsafe basis fail closed',()=>{for(const p of [{targetNormId:A},{relationType:'automatic_repeal'},{basisNote:'x'},{tenantId:TENANT}])assert.throws(()=>normalizeRelationCommand({...create(),...p}));});
test('status change is separate from relation semantics',()=>assert.equal(normalizeRelationCommand({command:'set_status',id:R,expectedSequence:1,status:'cancelled',reason:'Relación dejada sin efecto por revisión'}).status,'cancelled'));
test('bootstrap and target responses require exact versions/articles',()=>{assert.equal(verifyRelationResponse('bootstrap',{version:'legal-norm-relation-bootstrap.v1',canManage:true,source,targets:[{id:B,kind:'decreto',issuer:'EJECUTIVO',number:'20',year:2026,currentVersion:1,title:'Norma destino'}]}).source.version,2);assert.equal(verifyRelationResponse('target',{version:'legal-norm-relation-target.v1',target}).target.version,1);});
const res=()=>({headers:{},setHeader(k,v){this.headers[k]=v;},status(n){this.statusCode=n;return this;},json(v){this.value=v;return this;}});
const post=x=>({method:'POST',url:'/',query:{},headers:{origin:'https://municipio-junin-friendly.vercel.app','content-type':'application/json','idempotency-key':KEY},body:JSON.stringify(x)});
const get=q=>({method:'GET',url:'/?'+new URLSearchParams(q),query:q,headers:{}});
function setup({principal=access(),value=receipt(),error=null}={}){const calls=[];let contract;const handler=createLegalNormRelationsHandler({env:{NODE_ENV:'production',IDENTITY_APP_ORIGIN:'https://municipio-junin-friendly.vercel.app'},authorize:async(_q,r,c)=>{contract=c;if(!principal){r.status(401).json({ok:false});return null;}return principal;},getSql:async()=>({query:async(sql,args)=>{calls.push({sql,args});if(error)throw error;return[{result:value}];}})});return{handler,calls,get contract(){return contract;}};}
test('save derives tenant and actor from managed membership',async()=>{const t=setup(),r=res();await t.handler(post(create()),r);assert.equal(r.statusCode,201);assert.equal(t.calls[0].sql,'SELECT public.legal_norm_relation_operation_v1($1::jsonb,$2::text,$3::jsonb,$4::uuid) AS result');const [ctx,op,payload,key]=t.calls[0].args;assert.equal(op,'save');assert.equal(key,KEY);assert.equal(JSON.parse(ctx).tenantId,TENANT);assert.equal(JSON.parse(ctx).membershipId,MEMBER);assert.deepEqual(JSON.parse(payload),create());assert.deepEqual(t.contract.requiredCapabilities,['legal.norm.read','legal.norm.register']);});
test('reader may bootstrap/list/target/detail but cannot write or recover receipt',async()=>{const values=[
 [{resource:'bootstrap',sourceNormId:A,sourceVersion:'2'},{version:'legal-norm-relation-bootstrap.v1',canManage:false,source,targets:[{id:B,kind:'decreto',issuer:'EJECUTIVO',number:'20',year:2026,currentVersion:1,title:'Norma destino'}]}],
 [{resource:'target',normId:B,version:'1'},{version:'legal-norm-relation-target.v1',target}],
 [{resource:'list',normId:A},{version:'legal-norm-relation-list.v1',normId:A,canManage:false,rows:[]}],
 [{resource:'detail',id:R},{version:'legal-norm-relation-detail.v1',id:R,history:[{sequence:1,status:'declared',relationType:'modifies',sourceArticleLabel:'Artículo 2',targetArticleLabel:'Artículo 1',basisNote:'Fundamento revisado',reason:'Alta revisada',recordedBy:session.email,recordedAt:'2026-09-21T12:00:00Z'}]}]
 ];for(const[q,value]of values){const t=setup({principal:access(['legal.norm.read']),value}),r=res();await t.handler(get(q),r);assert.equal(r.statusCode,200);}for(const req of [post(create()),get({resource:'attempt',key:KEY})]){const t=setup({principal:access(['legal.norm.read'])}),r=res();await t.handler(req,r);assert.equal(r.statusCode,403);assert.equal(t.calls.length,0);}});
test('anonymous, legacy and unrelated capabilities never reach SQL',async()=>{for(const p of [null,{...access(),mode:'legacy'},access(['payroll.read'])]){const t=setup({principal:p}),r=res();await t.handler(get({resource:'list',normId:A}),r);assert.ok([401,403].includes(r.statusCode));assert.equal(t.calls.length,0);}});
test('query injection, cross-origin and bad idempotency fail before SQL',async()=>{const bad=[get({resource:'list',normId:A,tenantId:TENANT}),post(create()),post(create())];bad[1].headers.origin='https://other.invalid';bad[2].headers['idempotency-key']='bad';for(const req of bad){const t=setup(),r=res();await t.handler(req,r);assert.ok([403,422].includes(r.statusCode));assert.equal(t.calls.length,0);}});
test('workflow errors are actionable without SQL internals',async()=>{for(const[m,status,part]of [['RELATION_ARTICLE_NOT_FOUND',422,'artículo'],['RELATION_DUPLICATE',409,'declarada'],['private SQL',503,'confirmar']]){const t=setup({error:Error(m)}),r=res();await t.handler(post(create()),r);assert.equal(r.statusCode,status);assert.match(r.value.error,new RegExp(part,'i'));assert.doesNotMatch(r.value.error,/private SQL/);}});
test('migration is append-only exact-revision and never infers repeal',()=>{const s=fs.readFileSync('scripts/migrations/090-legal-norm-relations.sql','utf8');assert.equal((s.match(/CREATE TABLE public\.legal_norm_relation \(/g)||[]).length,1);assert.equal((s.match(/CREATE FUNCTION public\.legal_norm_relation_operation_v1/g)||[]).length,1);assert.match(s,/source_norm_version/);assert.match(s,/target_norm_version/);assert.match(s,/legal_norm_relation_event_immutable/);assert.match(s,/article_exists_v1/);assert.equal(s.includes('never infer legal status, repeal or validity automatically'),true);assert.doesNotMatch(s,/auto.*repeal|infer.*repeal/i);});
