import test from 'node:test';import assert from 'node:assert/strict';
import {createLegalFollowupHandler,followupBody} from '../api/internal-legal-followups.js';
import {access,session,ID,TENANT,MEMBER} from './fixtures/legal-registry-synthetic.js';
const KEY='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
const body=()=>({id:null,normId:ID,normVersion:1,expectedVersion:0,title:'Revisar antecedente',dueDate:'2026-09-30',status:'open',note:'Ensayo',reason:'Registro de ensayo'});
const reply=()=>({version:'legal-followup.v1',id:ID,recordVersion:1,replayed:false});
const res=()=>({headers:{},statusCode:0,setHeader(k,v){this.headers[k]=v;},status(n){this.statusCode=n;return this;},json(v){this.value=v;return this;}});
const get=(q={resource:'list',normId:ID})=>({method:'GET',url:'/?'+new URLSearchParams(q),query:q,headers:{}});
const post=()=>({method:'POST',url:'/',query:{},headers:{origin:'https://municipio-junin-friendly.vercel.app','content-type':'application/json','idempotency-key':KEY},body:JSON.stringify(body())});
function setup({principal=access(),value=reply(),error=null}={}){const calls=[];let contract;const handler=createLegalFollowupHandler({env:{NODE_ENV:'production',IDENTITY_APP_ORIGIN:'https://municipio-junin-friendly.vercel.app'},authorize:async(_req,r,c)=>{contract=c;if(!principal){r.status(401).json({ok:false});return null;}return principal;},getSql:async()=>({query:async(text,args)=>{calls.push({text,args});if(error)throw error;return[{result:value}];}})});return{handler,calls,get contract(){return contract;}};}
test('save binds session, municipality and idempotency key; no supplied identity',async()=>{const t=setup(),r=res();await t.handler(post(),r);assert.equal(r.statusCode,201);const [ctx,op,data,key]=t.calls[0].args;assert.equal(op,'save');assert.equal(key,KEY);assert.equal(JSON.parse(ctx).tenantId,TENANT);assert.equal(JSON.parse(ctx).membershipId,MEMBER);assert.equal(JSON.parse(ctx).actorEmail,session.email);assert.deepEqual(JSON.parse(data),body());assert.equal(t.contract.allowLegacy,false);assert.deepEqual(t.contract.requiredCapabilities,['legal.norm.read','legal.norm.register']);assert.match(r.headers['Cache-Control'],/private.*no-store/);});
test('reader can list but cannot save or inspect write receipts',async()=>{const value={version:'legal-followup.v1',normId:ID,today:'2026-09-19',canManage:false,rows:[],limit:100};const t=setup({principal:access(['legal.norm.read']),value}),r=res();await t.handler(get(),r);assert.equal(r.statusCode,200);for(const req of [post(),get({resource:'attempt',key:KEY})]){const s=setup({principal:access(['legal.norm.read'])}),x=res();await s.handler(req,x);assert.equal(x.statusCode,403);assert.equal(s.calls.length,0);}});
test('anonymous, legacy and unrelated sessions never reach SQL',async()=>{for(const principal of [null,{...access(),mode:'legacy'},access(['payroll.read'])]){const t=setup({principal}),r=res();await t.handler(get(),r);assert.ok([401,403].includes(r.statusCode));assert.equal(t.calls.length,0);}});
test('query scope, duplicate keys and unknown fields are rejected',async()=>{for(const req of [get({resource:'list',normId:ID,tenantId:TENANT}),get({resource:'list',normId:'bad'}),{...get(),url:get().url+'&normId='+ID},{...post(),query:{resource:'save'},url:'/?resource=save'}]){const t=setup(),r=res();await t.handler(req,r);assert.equal(r.statusCode,422);assert.equal(t.calls.length,0);}});
test('POST requires same-origin JSON and UUID v4 idempotency key',async()=>{for(const headers of [{origin:'https://other.invalid'},{'content-type':'text/plain'},{'idempotency-key':'invalid'}]){const q=post();Object.assign(q.headers,headers);const t=setup(),r=res();await t.handler(q,r);assert.ok([403,415,422].includes(r.statusCode));assert.equal(t.calls.length,0);}});
test('payload identity injection, duplicate JSON and oversized body fail',async()=>{for(const text of [JSON.stringify({...body(),tenantId:TENANT}),'"title":"a"','{"id":null,"id":"x"}',JSON.stringify({...body(),note:'x'.repeat(17000)})]){const t=setup(),r=res();await t.handler({...post(),body:text},r);assert.equal(r.statusCode,422);assert.equal(t.calls.length,0);}});
test('malformed or mismatched responses are not accepted as confirmation',async()=>{for(const value of [null,{...reply(),recordVersion:0},{...reply(),replayed:'true'}]){const t=setup({value}),r=res();await t.handler(post(),r);assert.equal(r.statusCode,503);assert.equal(r.value.data,undefined);}const t=setup({value:{version:'legal-followup.v1',normId:KEY,today:'2026-09-19',canManage:false,rows:[],limit:100}}),r=res();await t.handler(get(),r);assert.equal(r.statusCode,503);});
test('version conflict is explicit and database internals are not exposed',async()=>{for(const [message,status,part]of [['FOLLOWUP_VERSION_CONFLICT',409,'cambió'],['private SQL credential detail',503,'confirmar']]){const t=setup({error:Error(message)}),r=res();await t.handler(post(),r);assert.equal(r.statusCode,status);assert.ok(r.value.error.includes(part));assert.ok(!r.value.error.includes(message));}});
test('replayed receipts retain id and do not pretend a new creation',async()=>{const t=setup({value:{...reply(),replayed:true}}),r=res();await t.handler(post(),r);assert.equal(r.statusCode,200);assert.equal(r.headers['Idempotency-Replayed'],'true');});
