import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {contractAgendaCategory,contractAgendaCounts,filterContractAgenda,verifyContractAgendaResponse} from '../assets/legal-contract-agenda-model.js';
const A='dddddddd-dddd-4ddd-8ddd-dddddddddddd',C='eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee';
const row=(patch={})=>({id:A,sequence:1,status:'open',obligationType:'milestone',title:'Hito sintético',clauseLocator:'Cláusula 4.2',sourcePage:7,dueDate:'2026-09-21',dueBasis:'Fecha revisada',currency:'ARS',amountMinor:123400,unit:'hito',responsibleLabel:'responsable@example.invalid',evidenceDocumentId:null,recordedAt:'2026-09-20T20:00:00Z',contractId:C,contractNumber:'C-001',contractYear:2026,contractType:'servicio',contractRevision:2,contractState:'active',contractTitle:'Contrato sintético',...patch});
const payload=rows=>({version:'legal-contract-agenda.v1',today:'2026-09-21',timezone:'America/Argentina/Mendoza',limit:1000,population:rows.length,revision:'a'.repeat(64),rows});
test('agenda contract verifies exact bounded rows',()=>assert.equal(verifyContractAgendaResponse(payload([row()])).rows.length,1));
test('agenda categories distinguish dates from observed outcomes',()=>{assert.equal(contractAgendaCategory(row({dueDate:'2026-09-20'}),'2026-09-21'),'past');assert.equal(contractAgendaCategory(row(),'2026-09-21'),'today');assert.equal(contractAgendaCategory(row({dueDate:'2026-09-25'}),'2026-09-21'),'next7');assert.equal(contractAgendaCategory(row({dueDate:'2026-10-30'}),'2026-09-21'),'later');assert.equal(contractAgendaCategory(row({dueDate:''}),'2026-09-21'),'undated');assert.equal(contractAgendaCategory(row({status:'fulfilled_observed'}),'2026-09-21'),'resolved');});
test('counts are exclusive and search is accent-insensitive',()=>{const rows=[row(),row({id:'ffffffff-ffff-4fff-8fff-ffffffffffff',title:'Garantía técnica',dueDate:''})];const c=contractAgendaCounts(rows,'2026-09-21');assert.equal(c.all,2);assert.equal(c.today,1);assert.equal(c.undated,1);assert.equal(filterContractAgenda(rows,'2026-09-21','all','garantia').length,1);});
test('migration is one read-only facade over reviewed obligation dates',()=>{const s=fs.readFileSync('scripts/migrations/088-legal-contract-agenda.sql','utf8');assert.equal((s.match(/CREATE FUNCTION public\\.legal_contract_agenda_v1/g)||[]).length,1);assert.match(s,/legal_norm_context_v1\\(p,false\\)/);assert.match(s,/LIMIT 1000/);assert.match(s,/America\\/Argentina\\/Mendoza/);assert.doesNotMatch(s,/\\b(?:INSERT|UPDATE|DELETE)\\b/i);assert.match(s,/no inferred due dates or legal breach conclusions/);});
