import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {normalizeCaseCommand,verifyCaseResponse,CASE_STATES} from '../assets/legal-expedients-model.js';
import {createLegalExpedientsHandler} from '../api/internal-legal-expedients.js';
import {access,session,ID,TENANT,MEMBER} from './fixtures/legal-registry-synthetic.js';

const CASE='dddddddd-dddd-4ddd-8ddd-dddddddddddd',PERSON='eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee',KEY='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
const hist=()=>[{revision:1,state:'open',subject:'Expediente sintético',originArea:'Jurídica',responsibleId:PERSON,responsibleLabel:'responsable@example.invalid',reason:'Alta sintética documentada',recordedBy:session.email,recordedAt:'2026-09-20T12:00:00Z'}];
const record=(history=hist())=>({id:CASE,number:'1234-A',year:2026,revision:1,state:'open',subject:'Expediente sintético',originArea:'Jurídica',responsible:{id:PERSON,label:'responsable@example.invalid',eligible:true},reason:'Alta sintética documentada',recordedBy:session.email,recordedAt:'2026-09-20T12:00:00Z',matters:[{id:ID,title:'Asunto sintético',state:'assigned',revision:1,normId:KEY,normVersion:1}],history});
const detail=()=>({version:'legal-case-detail.v1',canManage:true,record:record(),candidates:[{id:PERSON,label:'responsable@example.invalid'}]});
const createBody=()=>({command:'create',matterId:ID,number:'1234-A',year:2026,subject:'Expediente sintético',originArea:'Jurídica',responsibleId:PERSON,reason:'Alta sintética documentada'});
const receipt=()=>({version:'legal-case-receipt.v1',id:CASE,revision:1,state:'open',replayed:false});

test('create normalizes number and binds matter/responsible',()=>{const d={...createBody(),number:' 1234-a '};assert.equal(normalizeCaseCommand(d).number,'1234-A');});
test('create rejects client authority, bad ids, bad year and unsafe text',()=>{for(const patch of [{tenantId:TENANT},{matterId:'bad'},{responsibleId:'bad'},{year:1899},{subject:'<x>'},{originArea:''},{reason:'x'}])assert.throws(()=>normalizeCaseCommand({...createBody(),...patch}));});
test('revision commands preserve immutable external number/year',()=>{const b={command:'revise',id:CASE,expectedRevision:1,subject:'Nueva carátula',originArea:'Jurídica',responsibleId:PERSON,reason:'Corrección documentada'};assert.equal(normalizeCaseCommand(b).command,'revise');assert.throws(()=>normalizeCaseCommand({...b,number:'otro'}));});
test('detail verifies one linked matter and contiguous history',()=>{assert.equal(verifyCaseResponse('detail',detail()).record.id,CASE);const d=detail();d.record.history=[];assert.throws(()=>verifyCaseResponse('detail',d));});
test('for-matter summary may omit case history but never matter link',()=>{const r=record(null),d={version:'legal-case-for-matter.v1',matterId:ID,canManage:true,rows:[r]};assert.equal(verifyCaseResponse('for_matter',d).rows.length,1);d.rows[0].matters=[];assert.throws(()=>verifyCaseResponse('for_matter',d));});
test('read-only detail cannot enumerate candidates',()=>{const d=detail();d.canManage=false;assert.throws(()=>verifyCaseResponse('detail',d));d.candidates=[];assert.equal(verifyCaseResponse('detail',d).canManage,false);});
test('list verifies paging and duplicate identities',()=>{const row={id:CASE,number:'1234-A',year:2026,revision:1,state:'open',subject:'Expediente sintético',originArea:'Jurídica',responsibleLabel:'responsable@example.invalid',recordedAt:'2026-09-20T12:00:00Z'},d={version:'legal-case-list.v1',canManage:true,total:1,page:1,pageSize:25,rows:[row]};assert.equal(verifyCaseResponse('list',d).total,1);assert.throws(()=>verifyCaseResponse('list',{...d,rows:[row,row]}));});

const res=()=>({headers:{},setHeader(k,v){this.headers[k]=v;},status(n){this.statusCode=n;return this;},json(v){this.value=v;return this;}});
const get=q=>({method:'GET',url:'/?'+new URLSearchParams(q),query:q,headers:{}});
const post=body=>({method:'POST',url:'/',query:{},headers:{origin:'https://municipio-junin-friendly.vercel.app','content-type':'application/json','idempotency-key':KEY},body:JSON.stringify(body)});
function setup({principal=access(),value=receipt(),error=null}={}){const calls=[];let contract;const handler=createLegalExpedientsHandler({env:{NODE_ENV:'production',IDENTITY_APP_ORIGIN:'https://municipio-junin-friendly.vercel.app'},authorize:async(_q,r,c)=>{contract=c;if(!principal){r.status(401).json({ok:false});return null;}return principal;},getSql:async()=>({query:async(sql,args)=>{calls.push({sql,args});if(error)throw error;return[{result:value}];}})});return{handler,calls,get contract(){return contract;}};}
test('save derives municipality and actor from managed access',async()=>{const t=setup(),r=res();await t.handler(post(createBody()),r);assert.equal(r.statusCode,201);assert.equal(t.calls[0].sql,'SELECT public.legal_case_operation_v1($1::jsonb,$2::text,$3::jsonb,$4::uuid) AS result');const [ctx,op,body,key]=t.calls[0].args;assert.equal(op,'save');assert.equal(key,KEY);assert.equal(JSON.parse(ctx).tenantId,TENANT);assert.equal(JSON.parse(ctx).membershipId,MEMBER);assert.equal(JSON.parse(ctx).actorEmail,session.email);assert.deepEqual(JSON.parse(body),createBody());assert.deepEqual(t.contract.requiredCapabilities,['legal.norm.read','legal.norm.register']);assert.equal(t.contract.allowLegacy,false);assert.match(r.headers['Cache-Control'],/private.*no-store/);});
test('reader lists and opens cases but cannot mutate or recover a write',async()=>{for(const [q,value] of [[{resource:'detail',id:CASE},{...detail(),canManage:false,candidates:[]}],[{resource:'list',q:'',state:'',page:'1'},{version:'legal-case-list.v1',canManage:false,total:0,page:1,pageSize:25,rows:[]}],[{resource:'for_matter',matterId:ID},{version:'legal-case-for-matter.v1',matterId:ID,canManage:false,rows:[]}]] ){const t=setup({principal:access(['legal.norm.read']),value}),r=res();await t.handler(get(q),r);assert.equal(r.statusCode,200);}for(const req of [post(createBody()),get({resource:'attempt',key:KEY})]){const t=setup({principal:access(['legal.norm.read'])}),r=res();await t.handler(req,r);assert.equal(r.statusCode,403);assert.equal(t.calls.length,0);}});
test('anonymous, legacy and unrelated access never reach SQL',async()=>{for(const principal of [null,{...access(),mode:'legacy'},access(['payroll.read'])]){const t=setup({principal}),r=res();await t.handler(get({resource:'detail',id:CASE}),r);assert.ok([401,403].includes(r.statusCode));assert.equal(t.calls.length,0);}});
test('query rejects injected tenant, duplicates and invalid paging before SQL',async()=>{for(const req of [get({resource:'detail',id:CASE,tenantId:TENANT}),{...get({resource:'detail',id:CASE}),url:'/?resource=detail&id='+CASE+'&id='+CASE},get({resource:'list',q:'',state:'',page:'201'})]){const t=setup(),r=res();await t.handler(req,r);assert.equal(r.statusCode,422);assert.equal(t.calls.length,0);}});
test('same-origin JSON and UUID-v4 idempotency are mandatory',async()=>{for(const h of [{origin:'https://other.invalid'},{'content-type':'text/plain'},{'idempotency-key':'bad'}]){const req=post(createBody());Object.assign(req.headers,h);const t=setup(),r=res();await t.handler(req,r);assert.ok([403,415,422].includes(r.statusCode));assert.equal(t.calls.length,0);}});
test('unexpected body fields and duplicate JSON cannot widen authority',async()=>{for(const body of [JSON.stringify({...createBody(),tenantId:TENANT}),'{"command":"create","command":"close"}']){const req=post(createBody());req.body=body;const t=setup(),r=res();await t.handler(req,r);assert.equal(r.statusCode,422);assert.equal(t.calls.length,0);}});
test('mismatched receipt is unavailable rather than accepted',async()=>{for(const value of [null,{...receipt(),revision:0},{...receipt(),replayed:'true'}]){const t=setup({value}),r=res();await t.handler(post({...createBody()}),r);assert.equal(r.statusCode,503);assert.equal(r.value.data,undefined);}});
test('expected workflow errors are sanitized and actionable',async()=>{for(const [message,status,part] of [['CASE_DUPLICATE',409,'existe'],['CASE_VERSION_CONFLICT',409,'cambió'],['private SQL detail',503,'confirmar']]){const t=setup({error:Error(message)}),r=res();await t.handler(post(createBody()),r);assert.equal(r.statusCode,status);assert.match(r.value.error,new RegExp(part,'i'));assert.doesNotMatch(r.value.error,/private SQL/);}});
test('migration is append-only, matter-linked and does not store document bytes',()=>{const sql=fs.readFileSync('scripts/migrations/083-legal-expedients.sql','utf8');assert.match(sql,/FOREIGN KEY\(tenant_id,matter_id\) REFERENCES public\.legal_matter/);assert.match(sql,/legal_matter_case_link_immutable/);assert.match(sql,/legal_norm_context_v1\(p,op IN \('save','attempt'\)\)/);assert.match(sql,/legal_coordination_member_v1\(t,target\)/);assert.doesNotMatch(sql,/\b(bytea|content_base64|document_content)\b/i);assert.match(sql,/REVOKE ALL ON public\.legal_case,public\.legal_case_event,public\.legal_matter_case_link/);});
