import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {buildMunicipalAdoptionOperatorInstallation,assertMunicipalAdoptionDurability} from '../scripts/lib/municipal-adoption-operator-installation.mjs';
import {municipalAdoptionDetail,municipalAdoptionQueue,municipalAdoptionCommand,municipalAdoptionAttempt} from '../assets/municipal-adoption-operator-model.js';
import {sealAdoptionReview,adoptionReviewHash} from '../assets/employment-adoption-review-model.js';
import {preparationBody,preparationEnvelope,principal as maker,session,attemptKey} from './fixtures/employment-adoption-preparation-synthetic.js';
import {reviewRaw,reviewId} from './fixtures/employment-adoption-review-synthetic.js';
import {municipalAdoptionOperation,municipalAdoptionError} from '../lib/internal-municipal-adoption.js';
import {createMunicipalAdoptionHandler} from '../api/internal-municipal-adoption.js';
const version='municipal-adoption-operator.v1',principal={...maker,tenant:{...maker.tenant,effectiveCapabilities:['workforce.employee.read','employee.record.approve']}},clone=v=>structuredClone(v);
async function detail(){const body=await preparationBody(),p=(await preparationEnvelope(body)).receipt,review=await sealAdoptionReview(reviewRaw());return{version,scope:{...review.scope},proposal:p,body,review,reviewVersion:'d'.repeat(64),current:true,applicationAvailable:true};}
async function command(){const d=await detail();return{reviewVersion:d.reviewVersion,review:{proposalId:d.proposal.proposalId,proposalVersion:d.proposal.proposalVersion,sourceContextVersion:d.proposal.sourceContextVersion,catalogVersion:d.proposal.catalogVersion,decision:'approve',reason:'Revisión independiente exclusivamente sintética QA'},reviewConfirmed:true};}
async function attempt(){const d=await detail(),b=await command();return{version,scope:d.scope,requestKey:attemptKey,bodySha256:await adoptionReviewHash(b),receipt:{...d.proposal,operation:'review',status:'approved',decidedAt:'2026-10-06T12:00:00Z',effects:{...d.proposal.effects,contractsAdopted:d.proposal.total}}};}
test('complete source/body/proposal match across more than two pages',async()=>{const v=await municipalAdoptionDetail(await detail());assert.ok(v.body.rows.length>50);assert.equal(v.body.rows.length,v.review.total);assert.ok(Object.isFrozen(v.body));});
for(const[label,change]of [['missing contract',v=>v.body.rows.pop()],['reordered contract',v=>v.body.rows.reverse()],['different scope',v=>v.scope.bindingId=reviewId(90001)],['wrong selection',v=>v.body.selectionVersion='f'.repeat(64)],['undeclared jurisdiction',v=>v.body.rows[0].jurisdictionCode='99'],['extra sealed evidence',v=>v.facts=[]],['application unavailable',v=>v.applicationAvailable=false]])test('rejects '+label,async()=>{const d=clone(await detail());change(d);await assert.rejects(()=>municipalAdoptionDetail(d));});
test('queue includes complete history and identifies own proposals',async()=>{const d=await detail(),v=municipalAdoptionQueue({version,scope:d.scope,total:1,rows:[{proposal:d.proposal,independent:false}]});assert.equal(v.rows[0].independent,false);assert.throws(()=>municipalAdoptionQueue({...clone(v),total:2}));assert.throws(()=>municipalAdoptionQueue({...clone(v),rows:[...clone(v.rows),...clone(v.rows)],total:2}));});
for(const[label,change]of [['confirmation absent',b=>delete b.reviewConfirmed],['confirmation false',b=>b.reviewConfirmed=false],['partial decision',b=>b.review.decision='partial'],['formula reason',b=>b.review.reason='<script>alert</script>'],['source rows injected',b=>b.rows=[]],['seal mismatch',b=>b.reviewVersion='x']])test('command refuses '+label,async()=>{const b=await command();change(b);assert.throws(()=>municipalAdoptionCommand(b));});
test('receipt binds exact saved content, attempt key and effects',async()=>{const r=await attempt(),b=await command();assert.equal((await municipalAdoptionAttempt(r,{key:attemptKey,body:b})).receipt.status,'approved');await assert.rejects(()=>municipalAdoptionAttempt({...r,bodySha256:'a'.repeat(64)},{key:attemptKey,body:b}));await assert.rejects(()=>municipalAdoptionAttempt({...r,receipt:{...r.receipt,effects:{...r.receipt.effects,payrollCalculated:true}}}));await assert.rejects(()=>municipalAdoptionAttempt(r,{key:reviewId(90002)}));});
test('server binds actual session and exact parameterized SQL without leaking raw seal',async()=>{const d=await detail(),calls=[];const data=await municipalAdoptionOperation({query:(q,v)=>{calls.push([q,v]);return[{result:{version,scope:{...d.scope,tenantId:principal.tenant.id,membershipId:principal.tenant.membershipId},total:0,rows:[]}}];}},principal,session,'queue');assert.equal(data.total,0);assert.match(calls[0][0],/^SELECT public.municipal_adoption_queue_v1\(\$1::jsonb\)/);assert.equal(JSON.parse(calls[0][1][0]).actorEmail,session.email);});
test('missing permission is refused before SQL; stale session does not become another actor',async()=>{let calls=0;const sql={query:()=>{calls++;}};await assert.rejects(()=>municipalAdoptionOperation(sql,maker,session,'queue'),e=>e.status===403);await assert.rejects(()=>municipalAdoptionOperation(sql,principal,{...session,email:'another@example.invalid'},'queue'),e=>e.status===401);assert.equal(calls,0);});
test('SQL failures are actionable and hide sensitive details',()=>{for(const[s,status]of [['EMPLOYMENT_ADOPTION_SELF_REVIEW',403],['EMPLOYMENT_ADOPTION_UNSEALED',409],['EMPLOYMENT_ADOPTION_ALREADY_DECIDED',409],['ADOPTED_CONSUMERS_AFTER_METADATA',503]]){const e=municipalAdoptionError(Error(s+' private person 99000000'));assert.equal(e.status,status);assert.ok(!e.message.includes('99000000'));}});
function http(options={}){let calls=0;const res={headers:{},setHeader(k,v){this.headers[k]=v;},status(v){this.statusCode=v;return this;},json(v){this.payload=v;return this;}},handler=createMunicipalAdoptionHandler({env:{INTERNAL_APP_ORIGIN:'https://municipio.example'},sessionFor:()=>session,requireAccess:()=>({mode:options.mode??'managed',principal:options.principal??principal}),getSql:()=>({query:async()=>{calls++;return[{result:options.result??await attempt()}];}})});return{res,handler,calls:()=>calls};}
const post=async()=>({method:'POST',url:'/api/internal-municipal-adoption',query:{},headers:{origin:'https://municipio.example','sec-fetch-site':'same-origin','content-type':'application/json','idempotency-key':attemptKey},body:JSON.stringify({operation:'command',payload:await command()})});
test('HTTP command rejects preparation-only authority before SQL',async()=>{const h=http({principal:maker});await h.handler(await post(),h.res);assert.equal(h.res.statusCode,403);assert.equal(h.calls(),0);});
test('HTTP command requires managed authority and cannot accept a legacy session',async()=>{const h=http({mode:'legacy'});await h.handler(await post(),h.res);assert.equal(h.res.statusCode,403);assert.equal(h.calls(),0);});
for(const[label,edit,status]of [['cross-site',r=>r.headers.origin='https://evil.example',403],['extra query',r=>{r.query.search='crop';r.url+='?search=crop';},400],['duplicate query',r=>{r.url+='?resource=queue&resource=queue';r.query={resource:'queue'};r.method='GET';},400],['wrong operation',r=>r.body='{"operation":"propose","payload":{}}',400],['key absent',r=>delete r.headers['idempotency-key'],428],['oversized',r=>r.headers['content-length']='2097153',413]])test('HTTP refuses '+label,async()=>{const r=await post();edit(r);const h=http();await h.handler(r,h.res);assert.equal(h.res.statusCode,status);assert.equal(h.calls(),0);});
test('installation requires complete adapters and conserves private writer/security objects',()=>{const b=buildMunicipalAdoptionOperatorInstallation({read:p=>fs.readFileSync(p,'utf8'),sourceCommit:'747d5a2e9a96c76eff9b6fc19effb4ca7dd6b54f'});assert.equal(b.pins.length,5);assert.equal(b.pins.filter(p=>p.runtime).length,4);assert.ok(b.definitions[0].includes('ADOPTED_CONSUMERS_AFTER_METADATA'));assert.ok(b.definitions[0].includes('ADOPTION_INSTALL_FUNCTION_METADATA'));assert.ok(!b.migration.at(-1).includes('employment_adoption_decide_v1'));assert.ok(b.before.includes("p.relkind IN ('r','p')")&&b.before.includes("'roles'"));assert.ok(!b.before.includes("p.proname LIKE 'native_leave_%'"));assert.ok(b.audit.includes('PRIOR_STATE_CHANGED'));assert.ok(b.state.includes('repeatable read'));assert.ok(!/CREATE TABLE|CREATE ROLE|ALTER ROLE|DISABLE TRIGGER/.test(b.migration.join('\n')));});
test('durability compares exact reviewed functions, source and retained state, not a success flag',()=>{const sourceCommit='747d5a2e9a96c76eff9b6fc19effb4ca7dd6b54f',batch=buildMunicipalAdoptionOperatorInstallation({read:p=>fs.readFileSync(p,'utf8'),sourceCommit}),p={version:'municipal-adoption-installation.v1',sourceCommit,sourceHashes:batch.consumers.sourceHashes,functionPins:batch.pins,mode:'first',allChecksPassed:true,newFunctions:5,runtimeFacades:4,newTables:0,roleAssignmentsAdded:0,nominalRowsReturned:0,privateWriterGranted:false,priorFingerprint:'a'.repeat(64),objectsFingerprint:'b'.repeat(64)};assert.ok(assertMunicipalAdoptionDurability({installed:p,durable:{...p,mode:'verify'},batch,sourceCommit}).passed);for(const edit of [v=>v.priorFingerprint='c'.repeat(64),v=>v.functionPins[0].sha256='c'.repeat(64),v=>v.privateWriterGranted=true,v=>v.unreviewed=true,v=>v.sourceHashes={}]){const d=clone(p);edit(d);assert.throws(()=>assertMunicipalAdoptionDurability({installed:p,durable:d,batch,sourceCommit}));}});
test('a forged saved acknowledgement is sanitized by the operation before it can be presented',async()=>{const r=await attempt(),body=await command();r.scope.tenantId=principal.tenant.id;r.scope.membershipId=principal.tenant.membershipId;r.bodySha256='f'.repeat(64);await assert.rejects(()=>municipalAdoptionOperation({query:()=>[{result:r}]},principal,session,'command',{key:attemptKey,body}),e=>e.code==='EMPLOYMENT_ADOPTION_CONTRACT_INVALID'&&e.status===503);});
test('raw HTTP bytes preserve duplicate-property rejection before SQL',async()=>{const r=await post(),h=http();r.body=r.body.replace('"reviewConfirmed":true','"reviewConfirmed":false,"reviewConfirmed":true');await h.handler(r,h.res);assert.equal(h.res.statusCode,400);assert.equal(h.calls(),0);});
