import test from 'node:test';
import assert from 'node:assert/strict';
import {salaryBulkPlan} from '../assets/native-salary-bulk-model.js';
import {salaryItems,salaryRowKey,salarySerialized} from '../assets/native-salary-catalog-model.js';
import {row} from './fixtures/native-salary-synthetic.js';

const selected=rows=>rows.map(before=>({key:salaryRowKey(before),before:structuredClone(before)}));
const update=(patch={})=>({unit:'units',precision:2,value:'12.50',ruleReference:'Respaldo sintético de actualización, no norma municipal',...patch});
const full=()=>salaryItems(Array.from({length:90},(_,n)=>row({agreementCode:String(n%3+1),code:String(550+Math.floor(n/3)),label:'Definición sintética '+n,value:n%2?'0.00':null})));

test('actualiza 30 selecciones de tres convenios conservando las90 filas de todas las páginas',()=>{
 const all=full(),choices=all.filter(item=>Number(item.code)%3===0),original=salarySerialized(all),plan=salaryBulkPlan(all,selected(choices),update());
 assert.equal(plan.items.length,90);assert.equal(plan.selectedCount,30);assert.equal(plan.changes.length,30);assert.equal(new Set(plan.changes.map(change=>change.after.agreementCode)).size,3);
 const keys=new Set(choices.map(salaryRowKey));for(const item of plan.items){const before=all.find(candidate=>salaryRowKey(candidate)===salaryRowKey(item));assert.deepEqual(item,keys.has(salaryRowKey(item))?{...before,value:'12.50',ruleReference:update().ruleReference}:before);}
 assert.equal(salarySerialized(all),original);assert.deepEqual(choices,all.filter(item=>Number(item.code)%3===0));
});
test('una búsqueda posterior no reduce la selección ni el conjunto completo',()=>{const all=full(),choices=selected(all.filter(item=>['550','551','552'].includes(item.code))),visible=all.filter(item=>item.code==='579');assert.equal(visible.length,3);const plan=salaryBulkPlan(all,choices,update());assert.equal(plan.changes.length,9);assert.equal(plan.items.length,90);});
test('preserva unidad, precisión, fechas, naturaleza, dependencias e historia desactivada',()=>{const auxiliary=row({code:'88',nature:'auxiliary',validFrom:'2026-09'}),concept=row({code:'95',dependencies:[salaryRowKey(auxiliary)]}),archived=row({code:'95',validFrom:'2026-08',validUntil:'2026-08',active:false}),all=salaryItems([auxiliary,concept,archived]);const plan=salaryBulkPlan(all,selected([concept]),update());assert.deepEqual(plan.items.find(item=>salaryRowKey(item)===salaryRowKey(archived)),archived);assert.deepEqual(plan.changes[0].after,{...concept,value:'12.50',ruleReference:update().ruleReference});});
for(const [value,precision]of [[null,2],['0.00',2],['0',0],['999999999999999999.12345678',8],['-12.500',3]])test('valor declarado exacto '+String(value),()=>{const item=row({precision,value:value===null?'0.00':null}),plan=salaryBulkPlan([item],selected([item]),update({precision,value}));assert.equal(plan.changes[0].after.value,value);});
for(const [label,patch]of [['valor numérico',{value:12.5}],['exponente',{value:'1e9'}],['miles',{value:'1,000.00'}],['comas sin normalizar',{value:'12,50'}],['precisión incompleta',{value:'12.5'}],['cero negativo',{value:'-0.00'}],['vacío accidental',{value:''}],['unidad omitida',{unit:''}],['decimales omitidos',{precision:null}],['precisión texto',{precision:'2'}],['decimal supuesto',{precision:3,value:'12.500'}],['unidad convertida',{unit:'hours'}],['respaldo omitido',{ruleReference:''}],['respaldo con control',{ruleReference:'QA\nreferencia'}],['campo extra',{formula:'rejected'}]])test('rechaza '+label+' sin aplicar un subconjunto',()=>{const all=full(),before=salarySerialized(all);assert.throws(()=>salaryBulkPlan(all,selected(all),update(patch)));assert.equal(salarySerialized(all),before);});
test('una sola fila con otra unidad invalida todo el conjunto',()=>{const all=salaryItems([row(),row({code:'44',unit:'hours'})]);assert.throws(()=>salaryBulkPlan(all,selected(all),update()),/unidad y precisión/);});
test('una sola fila con otra precisión invalida todo el conjunto',()=>{const all=salaryItems([row(),row({code:'44',precision:3})]);assert.throws(()=>salaryBulkPlan(all,selected(all),update()),/unidad y precisión/);});
test('el cero explícito es admitido en escalas y no informado es rechazado',()=>{const scale=row({kind:'scale',categoryCode:'6',nature:null,unit:'money',value:'10.00'});assert.equal(salaryBulkPlan([scale],selected([scale]),update({unit:'money',value:'0.00'})).items[0].value,'0.00');assert.throws(()=>salaryBulkPlan([scale],selected([scale]),update({unit:'money',value:null})),/escala requiere/);});
test('si cambia una seleccionada se invalida la previa entera',()=>{const all=full(),choices=selected(all.slice(0,3)),changed=all.map((item,n)=>n===1?{...item,label:'Definición corregida sintética'}:item);assert.throws(()=>salaryBulkPlan(changed,choices,update()),/Cambió una fila/);});
test('no admite filas inexistentes, repetidas, desactivadas o selección vacía',()=>{const all=full(),one=selected(all.slice(0,1));for(const selections of [[],[...one,...one],selected([row({code:'999'})]),[{...one[0],key:'other'}],[{...one[0],extra:true}]])assert.throws(()=>salaryBulkPlan(all,selections,update()));const archived=row({active:false});assert.throws(()=>salaryBulkPlan([archived],selected([archived]),update()),/desactivada/);});
test('un cambio no seleccionado debe conservarse exactamente dentro del borrador',()=>{const all=full(),choices=selected(all.slice(0,2)),last=all.at(-1),changed=all.map(item=>salaryRowKey(item)===salaryRowKey(last)?{...item,label:'Cambio individual anterior a la actualización'}:item),plan=salaryBulkPlan(changed,choices,update());assert.deepEqual(plan.items.find(item=>salaryRowKey(item)===salaryRowKey(last)),changed.at(-1));});
test('informa seleccionadas sin cambio y rechaza propuestas idénticas',()=>{const a=row({value:'12.50',ruleReference:update().ruleReference}),b=row({code:'44'}),plan=salaryBulkPlan([a,b],selected([a,b]),update());assert.equal(plan.selectedCount,2);assert.equal(plan.changes.length,1);assert.equal(plan.unchangedSelectedCount,1);assert.throws(()=>salaryBulkPlan([a],selected([a]),update()),/no producen cambios/);});
test('1000 seleccionadas se conservan completas, sin truncar, y1001 se rechazan',()=>{const all=salaryItems(Array.from({length:1000},(_,n)=>row({code:String(n+1)}))),plan=salaryBulkPlan(all,selected(all),update());assert.equal(plan.items.length,1000);assert.equal(plan.changes.length,1000);assert.throws(()=>salaryBulkPlan([...all,row({code:'1001'})],selected(all),update()),/1000/);});
test('valida el catálogo entero incluso si el error está fuera de la selección',()=>{const all=full(),choices=selected(all.slice(0,2));all[89].precision=null;assert.throws(()=>salaryBulkPlan(all,choices,update()));});
