import test from 'node:test';
import assert from 'node:assert/strict';
import {lifecycleIntervals,lifecycleActivity,lifecycleAfter,lifecycleProposalInput,validateLifecycleBootstrap,validateLifecycleProposal} from '../assets/native-employment-lifecycle-model.js';
import {reviewedLifecycleAttempt,assertLifecycleAttemptFresh,assertLifecycleAttemptReceipt} from '../assets/native-employment-lifecycle-review.js';
import {employmentLifecycleOperation,employmentLifecycleError} from '../lib/internal-employment-lifecycle.js';
import {buildNativeEmploymentLifecycleQa} from '../scripts/verify-native-employment-lifecycle-sql.mjs';
import {principal as basePrincipal,session} from './fixtures/native-employee-synthetic.js';
import {lifecycleFixture,CONTRACT,ID} from './fixtures/native-employment-lifecycle-synthetic.js';
const principal={...basePrincipal,tenant:{...basePrincipal.tenant,effectiveCapabilities:['workforce.employee.read','employee.record.propose','employee.record.approve']}};
test('inclusive termination and reentry preserve every original interval and input object',()=>{
 const original=[{startDate:'2026-09-21',endDate:null}],copy=structuredClone(original),closed=lifecycleAfter(original,'terminate','2026-10-01'),reentered=lifecycleAfter(closed,'reenter','2026-11-01');
 assert.deepEqual(original,copy);assert.deepEqual(reentered,[{startDate:'2026-09-21',endDate:'2026-10-01'},{startDate:'2026-11-01',endDate:null}]);
 for(const [date,status]of [['2026-09-20','pending_start'],['2026-10-01','active'],['2026-10-02','pending_start'],['2026-11-01','active']])assert.equal(lifecycleActivity(reentered,date),status);
 assert.equal(lifecycleActivity(closed,'2026-10-02'),'inactive');
});
for(const [label,rows,move,date]of [
 ['reentry without termination',[{startDate:'2026-09-21',endDate:null}],'reenter','2026-11-01'],
 ['second termination',[{startDate:'2026-09-21',endDate:'2026-10-01'}],'terminate','2026-11-01'],
 ['termination before hire',[{startDate:'2026-09-21',endDate:null}],'terminate','2026-09-20'],
 ['same-day overlapping reentry',[{startDate:'2026-09-21',endDate:'2026-10-01'}],'reenter','2026-10-01'],
 ['invalid civil date',[{startDate:'2026-09-21',endDate:null}],'terminate','2026-02-30'],
])test('movement refuses '+label,()=>assert.throws(()=>lifecycleAfter(rows,move,date)));
for(const rows of [[],[{startDate:'2026-10-01',endDate:'2026-09-21'}],[{startDate:'2026-09-21',endDate:null},{startDate:'2026-11-01',endDate:null}],[{startDate:'2026-09-21',endDate:'2026-10-01'},{startDate:'2026-10-01',endDate:null}],[{startDate:'2026-09-21',endDate:null,reason:'not allowed'}]])test('history refuses invalid/overlapping shape '+JSON.stringify(rows),()=>assert.throws(()=>lifecycleIntervals(rows)));
test('a same-day hire and inclusive termination is an explicit one-day interval',()=>assert.equal(lifecycleActivity(lifecycleAfter([{startDate:'2026-10-01',endDate:null}],'terminate','2026-10-01'),'2026-10-01'),'active'));
test('history cap rejects extra reentry without truncating any previous interval',()=>{const rows=Array.from({length:51},(_,i)=>({startDate:`${1900+i}-01-01`,endDate:`${1900+i}-12-31`}));assert.equal(lifecycleIntervals(rows).length,51);assert.throws(()=>lifecycleAfter(rows,'reenter','1951-01-01'));assert.equal(rows.length,51);});
test('closed payload normalizes municipal text while refusing identity or nominal edits',()=>{const f=lifecycleFixture();f.body.payload.reason='  Decisio\u0301n sintética válida  ';assert.equal(lifecycleProposalInput(f.body.payload).reason,'Decisión sintética válida');for(const patch of [{tenantId:ID},{dni:'99999999'},{contractId:'5001'},{date:'2026-2-01'},{reason:'<script>contenido</script>'}])assert.throws(()=>lifecycleProposalInput({...f.body.payload,...patch}));});
test('bootstrap and detail never accept a missing interval or a fabricated status',()=>{const f=lifecycleFixture();assert.equal(validateLifecycleBootstrap(f.bootstrap,CONTRACT),f.bootstrap);assert.equal(validateLifecycleProposal(f.envelope,CONTRACT,ID),f.envelope);const bad=structuredClone(f.bootstrap);bad.employment.status='inactive';assert.throws(()=>validateLifecycleBootstrap(bad,CONTRACT));const detail=structuredClone(f.envelope);detail.proposal.after.intervals=[];assert.throws(()=>validateLifecycleProposal(detail,CONTRACT,ID));});
test('review references are detached, frozen and cannot be forged by cloning',()=>{const f=lifecycleFixture(),attempt=reviewedLifecycleAttempt(f.body,f.bootstrap,null,ID);f.body.payload.date='2026-10-02';assert.equal(attempt.body.payload.date,'2026-10-01');assert.throws(()=>attempt.bootstrap.employment.intervals.push({startDate:'2026-11-01',endDate:null}),TypeError);assert.throws(()=>assertLifecycleAttemptFresh(structuredClone(attempt),f.bootstrap,null),{code:'RESPONSE_INVALID'});});
for(const movement of ['terminate','reenter'])for(const [operation,decision]of [['propose','approve'],['review','approve'],['review','reject']])test('complete '+movement+' '+operation+' '+decision+' receipt is verified',()=>{const f=lifecycleFixture(operation,decision,movement),attempt=reviewedLifecycleAttempt(f.body,f.bootstrap,operation==='review'?f.proposal:null,ID);assert.equal(assertLifecycleAttemptFresh(attempt,f.bootstrap,operation==='review'?f.proposal:null),attempt);assert.equal(assertLifecycleAttemptReceipt(f.receipt,attempt,f.envelope,f.current),f.receipt);});
for(const [label,mutate]of [
 ['scope',b=>b.scopeVersion='c'.repeat(64)],['identity',b=>b.subject.employeeName='OTRA PERSONA SINTÉTICA'],['permission',b=>b.permissions.canPropose=false],['version',b=>b.employment.version='f'.repeat(64)],['earlier interval',b=>b.employment.intervals[0].startDate='2026-09-20'],
])test('fresh check blocks '+label+' drift before any write',()=>{const f=lifecycleFixture(),attempt=reviewedLifecycleAttempt(f.body,f.bootstrap,null,ID);mutate(f.bootstrap);assert.throws(()=>assertLifecycleAttemptFresh(attempt,f.bootstrap,null),{code:'REVIEW_CHANGED'});});
test('passing municipal midnight alone does not change the immutable reviewed movement',()=>{const f=lifecycleFixture(),attempt=reviewedLifecycleAttempt(f.body,f.bootstrap,null,ID);f.bootstrap.employment.today='2026-10-03';assert.equal(assertLifecycleAttemptFresh(attempt,f.bootstrap,null),attempt);});
for(const [label,mutate]of [
 ['other contract',f=>f.receipt.contractId=ID],['other proposal',f=>f.receipt.proposalId=CONTRACT],['payroll effect',f=>f.receipt.payrollModified=true],['wrong revision',f=>f.receipt.revision=3],['wrong hash',f=>f.receipt.employmentVersion='f'.repeat(64)],['different termination',f=>{f.saved.date='2026-10-02';f.saved.after.intervals[0].endDate='2026-10-02';}],['review reason',f=>f.saved.review.reason='Otro motivo sintético de revisión'],
])test('bad approval '+label+' cannot publish an applied event',()=>{const f=lifecycleFixture('review'),attempt=reviewedLifecycleAttempt(f.body,f.bootstrap,f.proposal,ID);mutate(f);assert.throws(()=>assertLifecycleAttemptReceipt(f.receipt,attempt,f.envelope,f.current));});
test('backend authority and commands remain parameterized with no client tenant or identity lookup',async()=>{const f=lifecycleFixture(),calls=[],sql={query:async(q,v)=>{calls.push({q,v});return[{result:f.receipt}];}};await employmentLifecycleOperation(sql,principal,session,'propose',{body:f.body.payload,key:ID});assert.match(calls[0].q,/native_employment_lifecycle_propose_v1\(\$1::jsonb,\$2::jsonb,\$3::uuid\)/);assert.doesNotMatch(calls[0].q,/5001|999999|SINTÉTICA/);assert.equal(JSON.parse(calls[0].v[0]).tenantId,principal.tenant.id);assert.equal(calls[0].v[2],ID);});
test('backend rejects mismatched acknowledgement and redacts unknown database errors',async()=>{const f=lifecycleFixture();f.receipt.employmentVersion='f'.repeat(64);await assert.rejects(employmentLifecycleOperation({query:async()=>[{result:f.receipt}]},principal,session,'propose',{body:f.body.payload,key:ID}),{status:503});assert.equal(employmentLifecycleError(Error('NATIVE_EMPLOYMENT_LIFECYCLE_DATES_INVALID')).status,422);assert.doesNotMatch(employmentLifecycleError(Error('password=private SELECT datos')).message,/private|SELECT|password/);});
test('PG17/18 generator stays disposable, retains the published guards and installs no productive nominal mutation',()=>{for(const serverMajor of ['17','18']){const qa=buildNativeEmploymentLifecycleQa({serverMajor,requireConcurrency:true});assert.equal(qa.report.lifecycleChecksPassed,38);assert.match(qa.sql,/native_employment_lifecycle_qa/);assert.match(qa.sql,/RESTORE_LIFECYCLE_FIXTURES/);assert.match(qa.lockSql,/native-employment-lifecycle:v1:/);assert.doesNotMatch(qa.sql,/INSERT INTO public\.native_employment_lifecycle/);assert.ok(qa.report.migration110Sha256.length===64);}});
