import test from 'node:test';
import assert from 'node:assert/strict';
import {salaryEffectivePlan} from '../assets/native-salary-effective-model.js';
import {salaryItems,salaryRowKey,salarySerialized} from '../assets/native-salary-catalog-model.js';
import {row} from './fixtures/native-salary-synthetic.js';
const selected=rows=>rows.map(before=>({key:salaryRowKey(before),before:structuredClone(before)}));
const update=(patch={})=>({unit:'money',precision:2,value:'1200.00',ruleReference:'Resolución sintética para vigencia futura, no municipal',...patch});
const base=()=>row({code:'88',unit:'money',value:'1000.00'});
const dependent=(source=base(),patch={})=>row({code:'95',unit:'percent',value:'50.00',dependencies:[salaryRowKey(source)],...patch});

test('inicia vigencia sin reemplazar valores o respaldo históricos y reubica dependencias de distinta unidad',()=>{
 const first=base(),second=dependent(first),third=dependent(second,{code:'96',unit:'hours',value:'12.50'}),untouched=row({code:'55'}),input=salaryItems([first,second,third,untouched]),snapshot=salarySerialized(input);
 const plan=salaryEffectivePlan(input,selected([first]),update(),'2026-11');
 assert.equal(plan.items.length,7);assert.equal(plan.selectedCount,1);assert.equal(plan.relatedDefinitionsCount,2);assert.equal(plan.newDefinitionsCount,3);assert.equal(plan.changes.length,6);assert.equal(salarySerialized(input),snapshot);
 for(const prior of [first,second,third]){const old=plan.items.find(item=>salaryRowKey(item)===salaryRowKey(prior)),next=plan.items.find(item=>item.code===prior.code&&item.validFrom==='2026-11');assert.deepEqual(old,{...prior,validUntil:'2026-10'});assert.equal(next.value,prior===first?'1200.00':prior.value);assert.equal(next.ruleReference,prior===first?update().ruleReference:prior.ruleReference);assert.equal(next.unit,prior.unit);assert.equal(next.precision,prior.precision);assert.equal(next.nature,prior.nature);assert.deepEqual(next.dependencies,prior.dependencies.map(key=>key.replace(/2026-10$/,'2026-11')));}
 assert.deepEqual(plan.items.find(item=>item.code==='55'),untouched);
});
test('conserva fecha final explícita, valores nulos y definiciones inactivas',()=>{const first=base(),second=dependent(first,{value:null,validUntil:'2027-03'}),past=dependent(first,{code:'96',validUntil:'2026-10'}),inactive=dependent(first,{code:'97',active:false});const plan=salaryEffectivePlan([first,second,past,inactive],selected([first]),update(),'2026-11');assert.equal(plan.newDefinitionsCount,2);assert.equal(plan.items.find(item=>item.code==='95'&&item.validFrom==='2026-11').validUntil,'2027-03');assert.equal(plan.items.find(item=>item.code==='95'&&item.validFrom==='2026-11').value,null);assert.deepEqual(plan.items.find(item=>item.code==='96'),past);assert.deepEqual(plan.items.find(item=>item.code==='97'),inactive);});
test('fecha de enero cierra diciembre sin depender de zona horaria',()=>{const first=base();const plan=salaryEffectivePlan([first],selected([first]),update(),'2027-01');assert.equal(plan.previousUntil,'2026-12');assert.equal(plan.items.find(item=>item.validFrom==='2026-10').validUntil,'2026-12');});
test('un mismo valor puede iniciar nueva vigencia sin alterar la historia',()=>{const first=base();const plan=salaryEffectivePlan([first],selected([first]),update({value:first.value,ruleReference:first.ruleReference}),'2026-11');assert.equal(plan.changes.length,2);assert.ok(plan.items.every(item=>item.value==='1000.00'));});
test('múltiples convenios y filtros conservan todo el catálogo y las referencias propias',()=>{const rows=salaryItems(['1','4','6'].flatMap(agreementCode=>{const first=base();first.agreementCode=agreementCode;return [first,dependent(first,{agreementCode}),row({agreementCode,code:'77'})];}));const choices=rows.filter(item=>item.code==='88');const plan=salaryEffectivePlan(rows,selected(choices),update(),'2026-11');assert.equal(plan.items.length,15);assert.equal(plan.relatedDefinitionsCount,3);assert.equal(plan.changes.length,12);assert.ok(plan.items.filter(item=>item.code==='77').every(item=>item.validFrom==='2026-10'&&item.validUntil===null));});
test('más de una página de cambios conserva las90 definiciones y genera las90 nuevas',()=>{const rows=salaryItems(Array.from({length:90},(_,number)=>row({code:String(number+1),unit:'money'})));const plan=salaryEffectivePlan(rows,selected(rows),update(),'2026-11');assert.equal(plan.items.length,180);assert.equal(plan.changes.length,180);assert.equal(plan.newDefinitionsCount,90);assert.equal(plan.items.filter(item=>item.validUntil==='2026-10').length,90);});
test('una escala conserva clase, precisión y límite final declarado',()=>{const first=row({kind:'scale',nature:null,categoryCode:'6',unit:'money',value:'999999999999999999.12345678',precision:8,validUntil:'2027-06'});const plan=salaryEffectivePlan([first],selected([first]),update({precision:8,value:'0.00000000'}),'2026-11');const next=plan.items.find(item=>item.validFrom==='2026-11');assert.equal(next.categoryCode,'6');assert.equal(next.value,'0.00000000');assert.equal(next.validUntil,'2027-06');assert.equal(plan.items.find(item=>item.validFrom==='2026-10').value,first.value);});
for(const value of ['',null,202611,'2026-13','2100-01','2026-1','2026-11-01','2026-10','2026-09'])test('rechaza vigencia inválida o sin tramo anterior: '+String(value),()=>{const first=base();assert.throws(()=>salaryEffectivePlan([first],selected([first]),update(),value));});
test('no prolonga una vigencia que ya terminó',()=>{const first=base();first.validUntil='2026-10';assert.throws(()=>salaryEffectivePlan([first],selected([first]),update(),'2026-11'),/no contiene un tramo/);});
test('dependiente ya previsto conserva fecha y valor, y su nueva referencia aparece en la revisión completa',()=>{const first=base(),second=dependent(first,{validFrom:'2026-12'}),third=dependent(second,{code:'96',validFrom:'2027-01'});const plan=salaryEffectivePlan([first,second,third],selected([first]),update(),'2026-11');assert.equal(plan.items.length,4);assert.equal(plan.newDefinitionsCount,1);assert.equal(plan.relinkedFutureDefinitionsCount,1);assert.equal(plan.relatedDefinitionsCount,1);assert.equal(plan.changes.length,3);assert.deepEqual(plan.items.find(item=>item.code==='95'),{...second,dependencies:['concept:1::88:2026-11']});assert.deepEqual(plan.items.find(item=>item.code==='96'),third);});
test('un intervalo futuro independiente se conserva entero sin solapamiento',()=>{const first={...base(),validUntil:'2026-12'},future={...base(),validFrom:'2027-01'};const plan=salaryEffectivePlan([first,future],selected([first]),update(),'2026-11');assert.equal(plan.items.length,3);assert.deepEqual(plan.items.find(item=>item.validFrom==='2027-01'),future);assert.equal(plan.items.find(item=>item.validFrom==='2026-11').validUntil,'2026-12');});
test('nuevo inicio que chocaría con una definición futura rechaza el conjunto',()=>{const first={...base(),validUntil:'2026-12'},future={...base(),validFrom:'2027-01'};assert.throws(()=>salaryEffectivePlan([first,future],selected([first]),update(),'2027-01'),/no contiene un tramo/);});
test('filas seleccionadas cambiadas y dobles se rechazan sin generar versión',()=>{const first=base(),choices=selected([first]);assert.throws(()=>salaryEffectivePlan([{...first,value:'999.00'}],choices,update(),'2026-11'),/Cambió una fila/);assert.throws(()=>salaryEffectivePlan([first],[...choices,...choices],update(),'2026-11'),/más de una vez/);});
for(const patch of [{value:1200},{value:'1.2'},{value:'1e3'},{value:'1,200.00'},{unit:'hours'},{precision:3},{ruleReference:''},{formula:'eval'}])test('rechaza cambio inválido sin tocar fechas: '+JSON.stringify(patch),()=>{const first=base();assert.throws(()=>salaryEffectivePlan([first],selected([first]),update(patch),'2026-11'));assert.equal(first.validUntil,null);});
test('capacidad incluye antecedentes y nuevos períodos sin recorte',()=>{const rows=salaryItems(Array.from({length:500},(_,number)=>row({code:String(number+1),unit:'money'})));assert.equal(salaryEffectivePlan(rows,selected(rows),update(),'2026-11').items.length,1000);const extra=row({code:'501',unit:'money'});assert.throws(()=>salaryEffectivePlan([...rows,extra],selected([...rows,extra]),update(),'2026-11'),/1002/);});
test('dependientes adicionales cuentan contra el límite completo',()=>{const rows=salaryItems(Array.from({length:999},(_,number)=>row({code:String(number+1),unit:'money'})));const second=dependent(rows[0],{code:'9999'});assert.throws(()=>salaryEffectivePlan([...rows,second],selected([rows[0]]),update(),'2026-11'),/1002/);});
