import test from 'node:test';
import assert from 'node:assert/strict';
import {createNativeSalaryHandler} from '../api/internal-native-salary.js';
import {body,receipt,bootstrap,uid} from './fixtures/native-salary-synthetic.js';
const caps=['workforce.employee.read','payroll.parameter.read','payroll.parameter.prepare','payroll.parameter.approve'];
const principal={user:{email:'qa@example.invalid'},tenant:{source:'membership',id:uid(1),membershipId:uid(2),effectiveCapabilities:caps}},session={email:'qa@example.invalid',id:uid(3),version:1,releaseSha:'d'.repeat(40)};
const response=()=>({headers:{},setHeader(k,v){this.headers[k]=v;},status(n){this.statusCode=n;return this;},json(v){this.value=v;return this;}});
const request=()=>({method:'POST',url:'/api/internal-native-salary',query:{},headers:{origin:'https://municipio.example','content-type':'application/json','idempotency-key':uid(9)},body:JSON.stringify({operation:'command',payload:body()})});
function setup(overrides={}){const calls=[],stats={connections:0};const handler=createNativeSalaryHandler({env:{INTERNAL_APP_ORIGIN:'https://municipio.example'},requireAccess:async()=>({mode:'managed',principal}),sessionFor:()=>session,getSql:async()=>{stats.connections++;return{query:async(q,v)=>{calls.push({q,v});return[{result:receipt()}];}};},...overrides});return{handler,calls,stats};}
test('guardado voluntario pasa identidad autenticada, nunca atributos del cliente',async()=>{const{handler,calls}=setup(),res=response();await handler(request(),res);assert.equal(res.statusCode,201);assert.equal(calls.length,1);assert.equal(JSON.parse(calls[0].v[0]).actorSessionId,session.id);});
test('revocación y sesión inválida no leen bytes ni abren conexión',async()=>{for(const override of [{requireAccess:async()=>({mode:'managed',principal:{...principal,tenant:{...principal.tenant,effectiveCapabilities:[]}}})},{sessionFor:()=>({...session,id:null})}]){let reads=0;const{handler,stats}=setup(override),req=request(),res=response();Object.defineProperty(req,'body',{get(){reads++;throw Error('prohibido');}});await handler(req,res);assert.ok([401,403].includes(res.statusCode));assert.equal(reads,0);assert.equal(stats.connections,0);}});
for(const [label,change]of [['origen',r=>r.headers.origin='https://otro.invalid'],['campos IAM',r=>r.body=JSON.stringify({operation:'command',payload:body({tenantId:uid(1)})})],['medio',r=>r.headers['content-type']='text/plain'],['JSON duplicado',r=>r.body='{"operation":"command","operati\\u006fn":"command"}'],['clave',r=>delete r.headers['idempotency-key']],['query repetida',r=>{r.method='GET';r.query={resource:'bootstrap'};r.url+='?resource=bootstrap&resource=bootstrap';}],['bytes UTF8',r=>r.body=Buffer.from([0xff])],['método',r=>r.method='DELETE']])test('rechaza '+label+' sin escribir',async()=>{const{handler,calls}=setup(),r=request(),res=response();change(r);await handler(r,res);assert.ok(res.statusCode>=400);assert.equal(calls.length,0);});
test('sólo consulta no permite preparar y read endpoint exige ambos permisos',async()=>{const p={...principal,tenant:{...principal.tenant,effectiveCapabilities:caps.slice(0,2)}},a=setup({requireAccess:async()=>({mode:'managed',principal:p})}),res=response();await a.handler(request(),res);assert.equal(res.statusCode,403);assert.equal(a.calls.length,0);const b=setup({getSql:async()=>({query:async()=>[{result:bootstrap()}]})}),r=request(),out=response();r.method='GET';r.query={resource:'bootstrap'};r.url+='?resource=bootstrap';await b.handler(r,out);assert.equal(out.statusCode,200);assert.equal(out.value.data.catalog.items.length,0);});
