import test from 'node:test';
import assert from 'node:assert/strict';
import {nativeLeavePayload,nativeLeaveFitsEmployment,nativeLeaveAllocations,nativeLeaveProfile,nativeLeaveBalances,nativeLeaveCanReserve,nativeLeaveConflicts,nativeLeaveTransition,NATIVE_LEAVE_POLICY_VERSION} from '../assets/native-leave-model.js';

const id=n=>String(n).padStart(8,'0')+'-0000-4000-8000-000000000000';
const annual=patch=>({reasonCode:'19',policyVersionId:NATIVE_LEAVE_POLICY_VERSION,policyRuleId:'annual-ordinary',startsOn:'2026-10-01',endsOn:'2026-10-02',durationUnit:'calendar_day',startsAtLocal:null,endsAtLocal:null,confidentiality:'standard',employeeNote:null,...patch});
const minutes=patch=>annual({reasonCode:'13',policyRuleId:'lactation',durationUnit:'minute',endsOn:'2026-10-01',startsAtLocal:'09:00',endsAtLocal:'09:30',confidentiality:'restricted',...patch});
const profile=patch=>({reasonCode:'19',year:2026,durationUnit:'calendar_day',mode:'confirmed',entitledUnits:20,legalReference:'Resolución sintética QA',reason:'Saldo declarado sintético y revisable.',...patch});
const request=(n,status,payload=annual())=>({id:id(n),status,payload});
const balance=(p,r)=>nativeLeaveBalances(p,r,{complete:true});

test('solicitud nativa conserva todos los valores y no inventa observación, importe o saldo',()=>{const input=annual(),before=structuredClone(input),out=nativeLeavePayload(input);assert.deepEqual(out,input);assert.deepEqual(input,before);assert.equal(Object.isFrozen(out),true);assert.equal(out.employeeNote,null);});
for(const patch of [{name:'otra persona'},{amount:0},{confidentiality:'restricted',employeeNote:'dato clínico'},{policyVersionId:'otra versión'},{policyRuleId:'health'},{reasonCode:'95'},{reasonCode:'999'},{startsOn:'2026-02-30'},{endsOn:'2026-09-30'},{endsOn:'2027-10-04'},{durationUnit:'hour'},{startsAtLocal:'09:00'}])test('rechaza campos, regla, unidad o fecha no verificables '+JSON.stringify(patch),()=>assert.throws(()=>nativeLeavePayload(annual(patch))));
test('minutos exactos no se convierten a porcentajes u horas decimales',()=>{assert.equal(nativeLeaveAllocations(minutes())[0].units,30);assert.equal(nativeLeaveAllocations(minutes({endsAtLocal:'10:30'}))[0].units,90);});
for(const patch of [{reasonCode:'19',policyRuleId:'annual-ordinary'},{endsAtLocal:'09:00'},{endsAtLocal:'08:59'},{startsAtLocal:'24:00'},{endsOn:'2026-10-02'}])test('minutos requieren el motivo y rango existentes '+JSON.stringify(patch),()=>assert.throws(()=>nativeLeavePayload(minutes(patch))));
test('el último día laboral es inclusivo y la solicitud no puede unir dos períodos separados',()=>{const intervals=[{startDate:'2026-01-01',endDate:'2026-10-01'},{startDate:'2026-11-01',endDate:null}];assert.equal(nativeLeaveFitsEmployment(annual({endsOn:'2026-10-01'}),intervals),true);assert.equal(nativeLeaveFitsEmployment(annual(),intervals),false);assert.equal(nativeLeaveFitsEmployment(annual({endsOn:'2026-11-02'}),intervals),false);assert.equal(nativeLeaveFitsEmployment(annual({startsOn:'2026-11-01',endsOn:'2026-11-02'}),intervals),true);});
test('asigna todos los días del cambio de año y febrero bisiesto sin cortar la solicitud',()=>{assert.deepEqual(nativeLeaveAllocations(annual({startsOn:'2026-12-30',endsOn:'2027-01-02'})).map(p=>[p.year,p.units]),[[2026,2],[2027,2]]);assert.equal(nativeLeaveAllocations(annual({startsOn:'2028-02-28',endsOn:'2028-03-01'}))[0].units,3);});
test('saldo cero declarado, no aplicable y no informado mantienen semánticas distintas',()=>{const zero=balance([profile({entitledUnits:0})],[])[0];assert.equal(zero.availableUnits,0);assert.equal(nativeLeaveCanReserve(annual(),[zero]),false);const absent=balance([],[request(1,'draft')])[0];assert.equal(absent.availableUnits,null);assert.equal(absent.mode,'unavailable');assert.equal(nativeLeaveCanReserve(annual(),[absent]),false);const na=balance([profile({mode:'not_applicable',entitledUnits:null})],[])[0];assert.equal(na.availableUnits,null);assert.equal(nativeLeaveCanReserve(annual(),[na]),true);});
for(const patch of [{entitledUnits:null},{entitledUnits:-1},{entitledUnits:1.5},{mode:'not_applicable',entitledUnits:0},{mode:'unavailable'},{legalReference:''},{reason:'corto'},{durationUnit:'minute'}])test('la declaración de saldo exige cantidad/unidad y respaldo explícitos '+JSON.stringify(patch),()=>assert.throws(()=>nativeLeaveProfile(profile(patch))));
test('reserva al enviar y debita licencias aprobadas una sola vez; rechazo/cancelación liberan',()=>{const states=['draft','submitted','approved','rejected','cancelled'];for(const status of states){const row=balance([profile()],[request(1,status)])[0];assert.equal(row.reservedUnits,status==='submitted'?2:0);assert.equal(row.approvedUnits,status==='approved'?2:0);assert.equal(row.availableUnits,['submitted','approved'].includes(status)?18:20);}});
test('las dos partes de un cambio de año requieren derechos suficientes',()=>{const p=annual({startsOn:'2026-12-30',endsOn:'2027-01-02'});assert.equal(nativeLeaveCanReserve(p,balance([profile()],[])),false);assert.equal(nativeLeaveCanReserve(p,balance([profile(),profile({year:2027,entitledUnits:2})],[])),true);assert.equal(nativeLeaveCanReserve(p,balance([profile(),profile({year:2027,entitledUnits:1})],[])),false);});
test('la consulta de saldo exige historial completo y no duplica una solicitud ni derechos',()=>{assert.throws(()=>nativeLeaveBalances([profile()],[]),e=>e.code==='INCOMPLETE');assert.throws(()=>balance([profile(),profile()],[]),e=>e.code==='CONFLICT');assert.throws(()=>balance([profile()],[request(1,'approved'),request(1,'approved')]),e=>e.code==='CONTRACT_INVALID');assert.throws(()=>balance([profile({entitledUnits:1})],[request(1,'approved')]),e=>e.code==='BALANCE_CONFLICT');});
test('el saldo incluye todas las solicitudes, no una página o resultado buscado',()=>{const rows=Array.from({length:75},(_,n)=>request(n+1,'approved',annual({endsOn:'2026-10-01'})));const total=balance([profile({entitledUnits:100})],rows)[0];assert.equal(total.approvedUnits,75);assert.equal(total.availableUnits,25);});
test('superposición no depende del motivo; borradores y rechazos no reservan fechas',()=>{assert.deepEqual(nativeLeaveConflicts(annual(),[request(1,'submitted'),request(2,'approved'),request(3,'draft'),request(4,'cancelled')]),[id(1),id(2)]);});
test('minutos contiguos no se superponen; un día completo sí incluye ese intervalo',()=>{assert.deepEqual(nativeLeaveConflicts(minutes(),[request(1,'approved',minutes({startsAtLocal:'09:30',endsAtLocal:'10:00'}))]),[]);assert.deepEqual(nativeLeaveConflicts(minutes(),[request(1,'approved',minutes({startsAtLocal:'09:29',endsAtLocal:'10:00'}))]),[id(1)]);assert.deepEqual(nativeLeaveConflicts(minutes(),[request(2,'approved',annual())]),[id(2)]);});
test('revisión y cancelación aprobada conservan la separación de funciones y validación humana',()=>{assert.equal(nativeLeaveTransition('draft','submit'),'submitted');assert.equal(nativeLeaveTransition('draft','update_draft'),'draft');assert.throws(()=>nativeLeaveTransition('submitted','approve'),e=>e.code==='SELF_REVIEW');assert.throws(()=>nativeLeaveTransition('submitted','approve',{independent:true,evidenceStatus:'received',manualValidationConfirmed:true}),e=>e.code==='EVIDENCE_REQUIRED');assert.equal(nativeLeaveTransition('submitted','approve',{independent:true,evidenceStatus:'verified',manualValidationConfirmed:true}),'approved');assert.equal(nativeLeaveTransition('submitted','reject',{independent:true}),'rejected');assert.throws(()=>nativeLeaveTransition('approved','cancel'),e=>e.code==='SELF_REVIEW');assert.equal(nativeLeaveTransition('approved','cancel',{independent:true}),'cancelled');assert.throws(()=>nativeLeaveTransition('rejected','approve'),e=>e.code==='STATE_INVALID');});
