import test from 'node:test';
import assert from 'node:assert/strict';
import {PassThrough} from 'node:stream';
import {createNativeLeaveHandler} from '../api/internal-native-leave.js';
import {nativeLeaveOperation,NATIVE_LEAVE_MAX_BYTES,nativeLeaveFingerprint} from '../lib/internal-native-leave.js';
import {nativeLeaveCommand,validateNativeLeaveBootstrap,validateNativeLeaveReceipt} from '../assets/native-leave-contract.js';
import {ID,CONTRACT,principal,session,command,receipt,bootstrap,annual,profile,entity,withRows} from './fixtures/native-leave-synthetic.js';

const response=()=>({headers:{},setHeader(k,v){this.headers[k]=v;},status(code){this.statusCode=code;return this;},json(payload){this.payload=payload;return this;}});
const request=(body=command())=>({method:'POST',url:'/api/internal-native-leave',query:{},headers:{origin:'https://municipio.example','sec-fetch-site':'same-origin','content-type':'application/json','idempotency-key':ID},body:JSON.stringify({operation:'command',payload:body})});
const get=q=>({method:'GET',url:'/api/internal-native-leave?'+new URLSearchParams(q),query:q,headers:{}});
function setup(options={}){const sql={calls:[],async query(query,values){this.calls.push({query,values});return[{result:options.result??receipt()}];}},stats={connections:0};const handler=createNativeLeaveHandler({env:{INTERNAL_APP_ORIGIN:'https://municipio.example'},sessionFor:()=>session,requireAccess:async(_req,res,gates)=>{stats.gates=gates;if(options.anonymous){res.status(401).json({ok:false});return null;}return options.access??{mode:'managed',principal};},getSql:async()=>{stats.connections++;return sql;}});return{handler,sql,stats};}

test('la API guarda sólo mediante la fachada nativa autenticada y devuelve recibo privado',async()=>{const{handler,sql,stats}=setup(),res=response();await handler(request(),res);assert.equal(res.statusCode,201);assert.match(res.headers['Cache-Control'],/no-store/);assert.equal(sql.calls.length,1);assert.match(sql.calls[0].query,/public\.native_leave_command_v1/);assert.equal(stats.gates.requireCertifiedDataBinding,true);assert.equal(stats.gates.allowLegacy,false);assert.deepEqual(stats.gates.requiredCapabilities,['workforce.employee.read','actions.read']);const ctx=JSON.parse(sql.calls[0].values[0]);assert.equal(ctx.membershipId,principal.tenant.membershipId);assert.equal(ctx.actorEmail,principal.user.email);});
test('un permiso de área específico alcanza el gate de API; SQL sigue verificando su alcance',async()=>{const actor={...principal,tenant:{...principal.tenant,effectiveCapabilities:['workforce.employee.read','actions.read','leave.request.area.create']}},res=response(),{handler}=setup({access:{mode:'managed',principal:actor}});await handler(request(),res);assert.equal(res.statusCode,201);});
test('crear empleados no concede permisos de solicitud y una sesión inválida no consume cuerpo',async()=>{for(const caps of [['workforce.employee.read','employee.record.create'],['workforce.employee.read','actions.read']]){const{handler,sql}=setup({access:{mode:'managed',principal:{...principal,tenant:{...principal.tenant,effectiveCapabilities:caps}}}}),res=response();await handler(request(),res);assert.equal(res.statusCode,403);assert.equal(sql.calls.length,0);}
 let reads=0,connections=0;const req=request(),res=response();Object.defineProperty(req,'body',{get(){reads++;throw Error('no leer');}});const handler=createNativeLeaveHandler({env:{INTERNAL_APP_ORIGIN:'https://municipio.example'},requireAccess:async()=>({mode:'managed',principal}),sessionFor:()=>{throw Object.assign(Error(),{code:'ACTION_SESSION_INVALID'});},getSql:async()=>{connections++;}});await handler(req,res);assert.equal(res.statusCode,401);assert.equal(reads,0);assert.equal(connections,0);
});
for(const[label,mutate]of[
 ['otro origen',r=>r.headers.origin='https://otro.invalid'],['medio incorrecto',r=>r.headers['content-type']='text/plain'],['tamaño declarado',r=>r.headers['content-length']=String(NATIVE_LEAVE_MAX_BYTES+1)],['query duplicada',r=>{r.method='GET';r.query={resource:'bootstrap',contractId:CONTRACT};r.url+='?'+new URLSearchParams(r.query)+'&contractId='+CONTRACT;}],['municipio del cliente',r=>{r.query={tenantId:ID};r.url+='?tenantId='+ID;}],['método',r=>r.method='DELETE'],['clave ausente',r=>delete r.headers['idempotency-key']],['nombre JSON duplicado',r=>r.body='{"operation":"command","operati\\u006fn":"command","payload":{}}'],['UTF8 inválido',r=>r.body=Buffer.from([0xff])],['operación desconocida',r=>r.body=JSON.stringify({operation:'approve',payload:command()})],['bytes sin longitud',r=>r.body=' '.repeat(NATIVE_LEAVE_MAX_BYTES)+r.body],['permiso declarado',r=>r.body=JSON.stringify({operation:'command',payload:command({actorEmail:'otro@example.invalid'})})],
])test('la API rechaza '+label+' antes de escribir',async()=>{const{handler,sql}=setup(),req=request(),res=response();mutate(req);await handler(req,res);assert.ok(res.statusCode>=400);assert.equal(sql.calls.length,0);});
test('anónimo no lee los bytes y recuperación consulta el mismo contrato y clave',async()=>{const a=setup({anonymous:true}),req=request(),res=response();Object.defineProperty(req,'body',{get(){throw Error('no leer');}});await a.handler(req,res);assert.equal(res.statusCode,401);assert.equal(a.stats.connections,0);const b=setup({result:receipt(command(),{replayed:true})}),out=response();await b.handler(get({resource:'attempt',contractId:CONTRACT,key:ID}),out);assert.equal(out.statusCode,200);assert.equal(out.headers['Idempotency-Replayed'],'true');assert.deepEqual(b.sql.calls[0].values.slice(1),[CONTRACT,ID]);});
test('un objeto de sesión incompleto también se rechaza antes de leer bytes o abrir SQL',async()=>{let reads=0,connections=0;const req=request(),res=response();Object.defineProperty(req,'body',{get(){reads++;throw Error('no leer');}});const handler=createNativeLeaveHandler({env:{INTERNAL_APP_ORIGIN:'https://municipio.example'},requireAccess:async()=>({mode:'managed',principal}),sessionFor:()=>({...session,id:null}),getSql:async()=>{connections++;}});await handler(req,res);assert.equal(res.statusCode,401);assert.equal(reads,0);assert.equal(connections,0);});
test('el lector conserva bytes originales y rechaza nombres duplicados en streaming',async()=>{const req=request(),stream=new PassThrough();let reads=0;Object.defineProperty(req,'body',{get(){reads++;throw Error();}});req.on=(n,l)=>stream.on(n,l);req.read=()=>null;req.complete=true;const{handler,sql}=setup(),res=response(),done=handler(req,res);stream.end(Buffer.from('{"operation":"command","payload":{"command":"create","comm\\u0061nd":"approve"}}'));await done;assert.equal(reads,0);assert.equal(res.statusCode,400);assert.equal(sql.calls.length,0);});
test('el recibo compara todos los campos y el hash exacto del cuerpo original',async()=>{for(const patch of [{requestSha256:'f'.repeat(64)},{payrollModified:true},{entityVersion:2},{command:'submit',status:'submitted'},{payload:annual({endsOn:'2026-10-03'})}])await assert.rejects(nativeLeaveOperation({query:async()=>[{result:receipt(command(),patch)}]},principal,session,'command',{body:command(),key:ID}),e=>e.code==='NATIVE_LEAVE_CONTRACT_INVALID');const reordered=Object.fromEntries(Object.entries(command()).reverse());assert.equal(nativeLeaveFingerprint(reordered),nativeLeaveFingerprint(command()));const r=await nativeLeaveOperation({query:async()=>[{result:receipt()}]},principal,session,'command',{body:reordered,key:ID});assert.equal(r.status,'draft');});
test('la consulta completa incluye más de una página y verifica todos los saldos',()=>{const requests=Array.from({length:75},(_,n)=>entity(String(n+1).padStart(8,'0')+'-0000-4000-8000-000000000000',annual({endsOn:'2026-10-01'}),['create','submit','approve']));const p=entity(ID,profile({entitledUnits:100}),['profile_propose','profile_approve'],'profile'),b=withRows(requests,[p]);assert.equal(validateNativeLeaveBootstrap(b,CONTRACT).requests.length,75);assert.equal(b.balances[0].availableUnits,25);for(const alter of [v=>v.complete=false,v=>v.requests=v.requests.slice(0,25),v=>v.balances[0].approvedUnits=0,v=>v.requests[0].history[1].status='rejected',v=>v.requests[0].history[2].payload.endsOn='2026-10-02']){const v=structuredClone(b);alter(v);assert.throws(()=>validateNativeLeaveBootstrap(v,CONTRACT),e=>e.code==='CONTRACT_INVALID');}});
test('una aprobación restringida no acepta evidencia no requerida ni cambios posteriores del caso',()=>{const p=annual({reasonCode:'13',policyRuleId:'lactation',confidentiality:'restricted'}),row=entity(ID,p,['create','submit','approve']),b=withRows([row],[]);row.history[2].evidenceStatus='not_required';assert.throws(()=>validateNativeLeaveBootstrap(b,CONTRACT));row.history[2].evidenceStatus='verified';row.history[1].payload.reasonCode='19';assert.throws(()=>validateNativeLeaveBootstrap(b,CONTRACT));});
test('declarar saldo exige documento, otra revisión y no transmite atributos IAM',()=>{const p=command({command:'profile_propose',payload:profile(),reason:'Propuesta sintética con respaldo municipal'});assert.equal(nativeLeaveCommand(p).payload.entitledUnits,20);assert.throws(()=>nativeLeaveCommand({...p,tenantId:ID}));const r=command({command:'profile_approve',entityId:ID,expectedVersion:1,payload:null,reason:'Revisión independiente de saldo sintético'});assert.throws(()=>nativeLeaveCommand(r),e=>e.code==='EVIDENCE_REQUIRED');assert.equal(nativeLeaveCommand({...r,manualValidationConfirmed:true}).command,'profile_approve');});
