import test from 'node:test';
import assert from 'node:assert/strict';
import {createOwnLiquidationHandler} from '../api/internal-own-payroll-liquidation.js';
import {OWN_LIQ_REVIEW,OWN_LIQ_CANCEL,OWN_LIQ_READ} from '../assets/own-payroll-liquidation-model.js';
import {detail,command,receipt} from './fixtures/own-payroll-liquidation-synthetic.js';
import {uid,hash} from './fixtures/own-payroll-program-synthetic.js';
const p={user:{email:'qa@example.invalid'},tenant:{source:'membership',id:uid(50),membershipId:uid(51),effectiveCapabilities:OWN_LIQ_REVIEW}},session={email:'qa@example.invalid',id:uid(52),version:1,releaseSha:'d'.repeat(40)};
const res=()=>({headers:{},setHeader(k,v){this.headers[k]=v;},status(n){this.statusCode=n;return this;},json(v){this.value=v;return this;}}),req=()=>({method:'POST',url:'/api/internal-own-payroll-liquidation',query:{},headers:{origin:'https://municipio.example','content-type':'application/json','idempotency-key':uid(9)},body:JSON.stringify({operation:'command',payload:command()})});
function setup(caps=OWN_LIQ_REVIEW,value=receipt()){const calls=[],stats={connect:0};return {calls,stats,handler:createOwnLiquidationHandler({env:{INTERNAL_APP_ORIGIN:'https://municipio.example'},requireAccess:async()=>({mode:'managed',principal:{...p,tenant:{...p.tenant,effectiveCapabilities:caps}}}),sessionFor:()=>session,getSql:async()=>{stats.connect++;return {query:async(q,v)=>{calls.push({q,v});return [{result:value}];}};}})};}
test('revisor confirma sin preparar; identidad/tenant se derivan exclusivamente de la sesión',async()=>{const a=setup(),r=res();await a.handler(req(),r);assert.equal(r.statusCode,201);assert.match(a.calls[0].q,/own_liquidation_command/);assert.deepEqual(JSON.parse(a.calls[0].v[1]),command());assert.equal(JSON.parse(a.calls[0].v[0]).membershipId,p.tenant.membershipId);assert.ok(r.headers['Cache-Control'].includes('no-store'));});
test('revocación de cada capacidad impide conectar y leer el cuerpo privado',async()=>{for(const cap of OWN_LIQ_REVIEW){const a=setup(OWN_LIQ_REVIEW.filter(c=>c!==cap)),request=req(),r=res();let reads=0;Object.defineProperty(request,'body',{get(){reads++;throw Error('Body must remain unread');}});await a.handler(request,r);assert.equal(r.statusCode,403,cap);assert.equal(a.stats.connect,0);assert.equal(reads,0);}});
test('preparador puede cancelar pero no confirmar ni anular',async()=>{const a=setup(OWN_LIQ_CANCEL),r=res();await a.handler(req(),r);assert.equal(r.statusCode,403);assert.equal(a.stats.connect,0);});
for(const[label,change]of [['otro origen',r=>r.headers.origin='https://evil.invalid'],['JSON ambiguo',r=>r.body='{"operation":"command","operati\\u006fn":"command"}'],['importe cliente',r=>r.body=JSON.stringify({operation:'command',payload:{...command(),amount:'1'}})],['filtro cliente',r=>r.body=JSON.stringify({operation:'command',payload:{...command(),search:'1001'}})],['sin revisión',r=>r.body=JSON.stringify({operation:'command',payload:command({reviewConfirmed:false})})],['tipo de medio',r=>r.headers['content-type']='text/plain'],['sin clave',r=>delete r.headers['idempotency-key']],['UTF8 inválido',r=>r.body=Buffer.from([255])],['método',r=>r.method='DELETE'],['consulta duplicada',r=>{r.method='GET';r.query={resource:'bootstrap'};r.url+='?resource=bootstrap&resource=bootstrap';}]])test('rechaza '+label+' antes de una decisión SQL',async()=>{const a=setup(),request=req(),r=res();change(request);await a.handler(request,r);assert.ok(r.statusCode>=400);assert.equal(a.calls.length,0);});
test('GET de resultado ajeno exige permiso nominal; bootstrap conserva metadatos completos sin identidad',async()=>{const data={version:'own-liquidation-bootstrap.v1',scopeVersion:hash('a'),runs:[],complete:true};for(const resource of ['bootstrap','detail']){const a=setup(OWN_LIQ_READ,resource==='bootstrap'?data:detail()),r=res(),request=req();request.method='GET';request.query=resource==='bootstrap'?{resource}:{resource,id:detail().id};request.url+='?'+new URLSearchParams(request.query);await a.handler(request,r);assert.equal(r.statusCode,resource==='bootstrap'?200:403);}});
test('replay autenticado devuelve 200 y el recibo íntegro',async()=>{const a=setup(OWN_LIQ_REVIEW,receipt({replayed:true})),r=res();await a.handler(req(),r);assert.equal(r.statusCode,200);assert.equal(r.headers['Idempotency-Replayed'],'true');assert.equal(r.value.data.affected.length,2);});
