import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {buildOwnLiquidationInstallation,assertOwnLiquidationDurability,SQL124_SHA} from '../scripts/lib/own-payroll-liquidation-installation.mjs';
import {prepareOwnLiquidationInstallation} from '../scripts/prepare-own-payroll-liquidation-installation.mjs';
import {executeOwnLiquidationInstallation} from '../scripts/install-own-payroll-liquidation.mjs';
const sourceCommit='d'.repeat(40),read=f=>fs.readFileSync(f,'utf8'),proof={sourceCommit,sql124Sha256:SQL124_SHA,allChecksPassed:true,eventRows:0,newTables:1,newFunctions:10,runtimeFacades:4,capabilityDefinitionsAdded:1,roleAssignmentsAdded:0,nominalRowsReturned:0,priorTableCount:194,beforeFingerprint:'a'.repeat(64),afterFingerprint:'a'.repeat(64),newObjectFingerprint:'b'.repeat(64)};
test('SQL124 exacto agrega una tabla vacía y cuatro fachadas; preserva todas las filas, roles y funciones anteriores',()=>{const b=buildOwnLiquidationInstallation({read,sourceCommit});assert.equal(b.ownPins.length,10);assert.equal(b.ownPins.filter(p=>p.runtime).length,4);assert.equal(b.prerequisitePins.length,29);assert.match(b.before,/to_jsonb\(r\)/);assert.match(b.before,/pg_auth_members/);assert.match(b.before,/own_liquidation_%/);assert.ok(!b.before.includes("p.proname LIKE 'native_leave_%'"));assert.equal(b.installation.filter(s=>/^INSERT INTO public\./.test(s)).length,1);});
test('un borrador modificado no puede convertirse en lote instalable',()=>{assert.throws(()=>buildOwnLiquidationInstallation({sourceCommit,read:f=>read(f)+(f.includes('124-')?'\n-- changed':'')}),/Unreviewed SQL124/);});
test('generación no conecta y fija ambas bases existentes; durabilidad exige datos originales iguales',()=>{const b=prepareOwnLiquidationInstallation({read,sourceCommit});assert.equal(b.connects,false);assert.equal(b.executesSql,false);assert.equal(b.targets.length,2);for(const t of b.targets){assert.match(t.installation[6],/neon.project_id/);assert.ok(t.preflight.includes('SET TRANSACTION READ ONLY'));}assert.equal(assertOwnLiquidationDurability({installed:proof,durable:proof,sourceCommit}).passed,true);for(const patch of [{eventRows:1},{roleAssignmentsAdded:1},{afterFingerprint:'c'.repeat(64)},{newObjectFingerprint:'c'.repeat(64)}])assert.throws(()=>assertOwnLiquidationDurability({installed:proof,durable:{...proof,...patch},sourceCommit}));});
test('instalador no reintenta COMMIT incierto ni permite otro destino',async()=>{const b=prepareOwnLiquidationInstallation({read,sourceCommit}),target=b.targets[0],calls=[];const client=async()=>({target,sql:{query:s=>s,transaction:async(s,o)=>{calls.push(o);if(!o.readOnly)throw Error('Uncertain commit');return [];}}});await assert.rejects(executeOwnLiquidationInstallation({batch:b,major:17,client,record:()=>{throw Error('Cannot claim installed');}}),/Uncertain commit/);assert.equal(calls.filter(o=>!o.readOnly).length,1);await assert.rejects(executeOwnLiquidationInstallation({batch:b,major:17,client:async()=>({target:{...target,host:'wrong.invalid'}}),record:()=>{}}),/DESTINATION_DRIFT/);});
