import test from 'node:test';import assert from 'node:assert/strict';
import {createOwnReceiptHandler} from '../api/internal-own-payroll-receipts.js';
import {OWN_RECEIPT_READ,OWN_RECEIPT_PREPARE,OWN_RECEIPT_SELF} from '../assets/own-payroll-receipt-model.js';
import {receiptCommand,receiptEvent,receiptPreview,receiptSelf} from './fixtures/own-payroll-receipt-synthetic.js';import {uid} from './fixtures/own-payroll-program-synthetic.js';
import {receiptError} from '../lib/internal-own-payroll-receipts.js';
const p={user:{email:'qa@example.invalid'},tenant:{source:'membership',id:uid(50),membershipId:uid(51),effectiveCapabilities:OWN_RECEIPT_PREPARE}},session={email:p.user.email,id:uid(52),version:1,releaseSha:'d'.repeat(40)};
const req=()=>({method:'POST',url:'/api/internal-own-payroll-receipts',query:{},headers:{origin:'http://localhost:8080','content-type':'application/json','idempotency-key':uid(9)},body:JSON.stringify({operation:'command',payload:receiptCommand()})});
const res=()=>({headers:{},statusCode:0,setHeader(k,v){this.headers[k]=v;},status(n){this.statusCode=n;return this;},json(v){this.body=v;return this;}});
function setup(caps=OWN_RECEIPT_PREPARE,value=receiptEvent()){const calls=[],stats={connect:0},handler=createOwnReceiptHandler({env:{INTERNAL_APP_ORIGIN:'http://localhost:8080'},requireAccess:async()=>({mode:'managed',principal:{...p,tenant:{...p.tenant,effectiveCapabilities:caps}}}),sessionFor:()=>session,getSql:async()=>{stats.connect++;return{query:async(q,v)=>{calls.push({q,v});return[{result:value}];}};}});return{handler,calls,stats};}
test('preparación toma identidad de sesión y ningún importe del cliente',async()=>{const a=setup(),r=res();await a.handler(req(),r);assert.equal(r.statusCode,201);assert.match(a.calls[0].q,/own_receipt_command/);assert.equal(JSON.parse(a.calls[0].v[0]).membershipId,p.tenant.membershipId);assert.deepEqual(JSON.parse(a.calls[0].v[1]),receiptCommand());assert.match(r.headers['Cache-Control'],/no-store/);});
test('cada capacidad nominal revocada impide leer el formulario y conectar',async()=>{for(const cap of OWN_RECEIPT_READ){const a=setup(OWN_RECEIPT_PREPARE.filter(c=>c!==cap)),request=req(),r=res();Object.defineProperty(request,'body',{get(){throw Error('Body must remain unread');}});await a.handler(request,r);assert.equal(r.statusCode,403,cap);assert.equal(a.stats.connect,0);}});
test('permiso específico revocado no escribe ni cambia el intento',async()=>{const a=setup(OWN_RECEIPT_READ),r=res();await a.handler(req(),r);assert.equal(r.statusCode,403);assert.equal(a.stats.connect,0);});
for(const [label,change]of [['origen ajeno',r=>r.headers.origin='https://evil.invalid'],['importe cliente',r=>r.body=JSON.stringify({operation:'command',payload:{...receiptCommand(),amount:'1'}})],['JSON ambiguo',r=>r.body='{"operation":"command","operati\\u006fn":"command"}'],['medio inválido',r=>r.headers['content-type']='text/plain'],['UTF8 inválido',r=>r.body=Buffer.from([255])],['sin clave',r=>delete r.headers['idempotency-key']],['método',r=>r.method='DELETE'],['URL duplicada',r=>{r.method='GET';r.query={resource:'self'};r.url+='?resource=self&resource=self';}]])test('rechaza '+label+' sin escritura',async()=>{const a=setup(),request=req(),r=res();change(request);await a.handler(request,r);assert.ok(r.statusCode>=400);assert.equal(a.calls.length,0);});
test('previa es lectura del negocio aunque usa POST y conserva todos los registros',async()=>{const a=setup(OWN_RECEIPT_READ,receiptPreview()),r=res(),request=req();request.body=JSON.stringify({operation:'preview',params:receiptPreview().snapshot.params});await a.handler(request,r);assert.equal(r.statusCode,200);assert.match(a.calls[0].q,/own_receipt_preview/);assert.equal(r.body.data.snapshot.recordCount,35);});
test('consulta propia requiere sólo sus capacidades y jamás un identificador aportado',async()=>{const a=setup(OWN_RECEIPT_SELF,receiptSelf()),r=res(),request=req();request.method='GET';request.query={resource:'self'};request.url+='?resource=self';await a.handler(request,r);assert.equal(r.statusCode,200);assert.equal(a.calls[0].v.length,1);assert.match(a.calls[0].q,/own_receipt_self/);for(const field of ['dni','legajo','contractId','personId','id']){const b=setup(OWN_RECEIPT_SELF,receiptSelf()),bad=res();await b.handler({...request,query:{resource:'self',[field]:'1'},url:request.url+'&'+field+'=1'},bad);assert.equal(bad.statusCode,400);assert.equal(b.calls.length,0);}});
test('confirmación corrupta se rechaza; replay conserva el mismo intento',async()=>{const a=setup(OWN_RECEIPT_PREPARE,{...receiptEvent(),replayed:true}),r=res();await a.handler(req(),r);assert.equal(r.statusCode,200);assert.equal(r.headers['Idempotency-Replayed'],'true');const b=setup(OWN_RECEIPT_PREPARE,{...receiptEvent(),bodySha256:'f'.repeat(64)}),bad=res();await b.handler(req(),bad);assert.equal(bad.statusCode,503);});
test('revocación SQL de una capacidad del cierre devuelve 403',()=>{const error=receiptError(Error('OWN_CLOSE_FORBIDDEN'));assert.equal(error.status,403);assert.equal(error.code,'OWN_RECEIPT_FORBIDDEN');});
