import test from 'node:test';import assert from 'node:assert/strict';
import {createOwnImputationHandler} from '../api/internal-own-payroll-imputation.js';
import {IMPUTATION_READ,IMPUTATION_CAPS} from '../lib/internal-own-payroll-imputation.js';
import {imputationWorkspaceFixture} from './fixtures/own-payroll-imputation-synthetic.js';
const uid=n=>`bbbbbbbb-0000-4000-8000-${String(n).padStart(12,'0')}`;
const principal={user:{email:'qa@example.invalid'},tenant:{source:'membership',id:uid(1),membershipId:uid(2),effectiveCapabilities:[...IMPUTATION_READ,...IMPUTATION_CAPS.propose,...IMPUTATION_CAPS.approve]}};
const session={email:'qa@example.invalid',id:uid(3),version:1,releaseSha:'d'.repeat(40)};
const response=()=>({headers:{},setHeader(k,v){this.headers[k]=v;},status(v){this.statusCode=v;return this;},json(v){this.value=v;return this;}});
async function setup(overrides={}){const f=await imputationWorkspaceFixture(),calls=[],stats={connections:0};const handler=createOwnImputationHandler({env:{INTERNAL_APP_ORIGIN:'https://municipio.example'},requireAccess:async()=>({mode:'managed',principal}),sessionFor:()=>session,getSql:async()=>{stats.connections++;return{query:async(q,v)=>{calls.push({q,v});return[{result:f.receipt}];}};},...overrides});const req={method:'POST',url:'/api/internal-own-payroll-imputation',query:{},headers:{origin:'https://municipio.example','content-type':'application/json','idempotency-key':f.receipt.requestKey},body:JSON.stringify({operation:'command',payload:f.body})};return {f,calls,stats,handler,req};}
test('envío voluntario conserva referencias de revisión, sesión real y ausencia de asientos/pagos',async()=>{const a=await setup(),res=response();await a.handler(a.req,res);assert.equal(res.statusCode,201);assert.equal(a.calls.length,1);assert.deepEqual(res.value.data.body,a.f.body);assert.equal(JSON.parse(a.calls[0].v[0]).actorSessionId,session.id);assert.equal(res.value.data.accountingPosted,false);assert.match(res.headers['Cache-Control'],/no-store/);});
for(const [label,change]of [['origen ajeno',r=>r.headers.origin='https://otro.invalid'],['query duplicada',r=>{r.method='GET';r.query={resource:'attempt',key:uid(9)};r.url+='?resource=attempt&resource=attempt&key='+uid(9);}],['JSON duplicado',r=>r.body='{"operation":"command","operati\\u006fn":"command"}'],['clave ausente',r=>delete r.headers['idempotency-key']],['clave normalizada',r=>r.headers['idempotency-key']=r.headers['idempotency-key'].toUpperCase()],['UTF8 inválido',r=>r.body=Buffer.from([255])],['DELETE',r=>r.method='DELETE'],['contenido libre',r=>{const b=JSON.parse(r.body);b.payload.actorEmail='forged@example.invalid';r.body=JSON.stringify(b);}],['JSON parseado',r=>r.body=JSON.parse(r.body)]])test('rechaza '+label+' sin SQL ni escritura',async()=>{const a=await setup(),res=response();change(a.req);await a.handler(a.req,res);assert.ok(res.statusCode>=400);assert.equal(a.calls.length,0);});
test('revocación/sesión inválida retiran acceso antes de leer bytes y conectar SQL',async()=>{for(const override of [{requireAccess:async()=>({mode:'managed',principal:{...principal,tenant:{...principal.tenant,effectiveCapabilities:[]}}})},{sessionFor:()=>({...session,id:null})}]){const a=await setup(override),res=response();let reads=0;Object.defineProperty(a.req,'body',{get(){reads++;throw Error('Forbidden');}});await a.handler(a.req,res);assert.ok([401,403].includes(res.statusCode));assert.equal(reads,0);assert.equal(a.stats.connections,0);}});
test('consultas completas verifican hashes, grupo/año y período de la respuesta',async()=>{const f=await imputationWorkspaceFixture();for(const [q,value,change]of [[{resource:'bootstrap',period:f.boot.period,liquidationType:f.boot.liquidationType},f.boot,x=>x.period='2026-11'],[{resource:'source',id:f.source.group.groupId,fiscalYear:'2026'},f.preview,x=>x.allocation.rows.pop()],[{resource:'detail',id:f.detail.proposal.id},f.detail,x=>x.body.reason='Contenido alterado sintético']])for(const bad of [false,true]){const data=structuredClone(value);if(bad)change(data);const a=await setup({getSql:async()=>({query:async()=>[{result:data}]})}),res=response();Object.assign(a.req,{method:'GET',query:q,url:'/api/internal-own-payroll-imputation?'+new URLSearchParams(q)});await a.handler(a.req,res);assert.equal(res.statusCode,bad?503:200);}});
test('recuperación es sólo GET y verifica el mismo cuerpo/clave ante respuesta perdida',async()=>{const f=await imputationWorkspaceFixture(),a=await setup({getSql:async()=>({query:async()=>[{result:{...f.receipt,replayed:true}}]})}),res=response();Object.assign(a.req,{method:'GET',query:{resource:'attempt',key:f.receipt.requestKey},url:'/api/internal-own-payroll-imputation?resource=attempt&key='+f.receipt.requestKey});await a.handler(a.req,res);assert.equal(res.statusCode,200);assert.equal(res.headers['Idempotency-Replayed'],'true');assert.deepEqual(res.value.data.body,f.body);});
test('errores SQL no filtran datos privados ni se convierten en éxito',async()=>{for(const [code,status]of [['REOPENED',409],['SOURCE_CHANGED',409],['INDEPENDENT_REQUIRED',403],['REVIEW_REQUIRED',422],['LIMIT',422],['NOT_FOUND',404],['BUSY',409],['database-private-secret',503]]){const a=await setup({getSql:async()=>({query:async()=>{throw Error(code==='database-private-secret'?code:'IMPUTATION_'+code);}})}),res=response();await a.handler(a.req,res);assert.equal(res.statusCode,status);assert.ok(!JSON.stringify(res.value).includes('private-secret'));}});
