import test from 'node:test';import assert from 'node:assert/strict';
import {createOwnAnnulHandler} from '../api/internal-own-payroll-annulment.js';import {OWN_ANNUL_ACCESS} from '../assets/own-payroll-annulment-model.js';
import {annulDetail,annulCommand,annulReceipt} from './fixtures/own-payroll-annulment-synthetic.js';import {uid} from './fixtures/own-payroll-program-synthetic.js';
const principal={user:{email:'qa@example.invalid'},tenant:{source:'membership',id:uid(50),membershipId:uid(51),effectiveCapabilities:OWN_ANNUL_ACCESS}},session={email:'qa@example.invalid',id:uid(52),version:1,releaseSha:'d'.repeat(40)};
const res=()=>({headers:{},setHeader(k,v){this.headers[k]=v;},status(n){this.statusCode=n;return this;},json(v){this.value=v;return this;}}),req=()=>({method:'POST',url:'/api/internal-own-payroll-annulment',query:{},headers:{origin:'https://municipio.example','content-type':'application/json','idempotency-key':uid(11)},body:JSON.stringify({operation:'command',payload:annulCommand()})});
function setup(caps=OWN_ANNUL_ACCESS,value=annulReceipt()){const calls=[],stats={connect:0};return {calls,stats,handler:createOwnAnnulHandler({env:{INTERNAL_APP_ORIGIN:'https://municipio.example'},requireAccess:async()=>({mode:'managed',principal:{...principal,tenant:{...principal.tenant,effectiveCapabilities:caps}}}),sessionFor:()=>session,getSql:async()=>{stats.connect++;return {query:async(q,v)=>{calls.push({q,v});return [{result:value}];}};}})};}
test('POST consolidado deriva identidad de sesión y registra una sola llamada SQL, sin exigir preparar',async()=>{const a=setup(),r=res();await a.handler(req(),r);assert.equal(r.statusCode,201);assert.equal(a.calls.length,1);assert.match(a.calls[0].q,/own_annul_command_v1/);assert.deepEqual(JSON.parse(a.calls[0].v[1]),annulCommand());assert.equal(JSON.parse(a.calls[0].v[0]).membershipId,principal.tenant.membershipId);assert.match(r.headers['Cache-Control'],/no-store/);});
test('revocación de cada capacidad rechaza antes de leer el formulario o conectar',async()=>{for(const cap of OWN_ANNUL_ACCESS){const a=setup(OWN_ANNUL_ACCESS.filter(c=>c!==cap)),request=req(),r=res();let reads=0;Object.defineProperty(request,'body',{get(){reads++;throw Error('Private body must remain unread');}});await a.handler(request,r);assert.equal(r.statusCode,403,cap);assert.equal(a.stats.connect,0);assert.equal(reads,0);}});
for(const[label,change]of [['otro origen',r=>r.headers.origin='https://evil.invalid'],['JSON ambiguo',r=>r.body='{"operation":"command","operati\\u006fn":"command"}'],['importe cliente',r=>r.body=JSON.stringify({operation:'command',payload:{...annulCommand(),amount:'1'}})],['filtro cliente',r=>r.body=JSON.stringify({operation:'command',payload:{...annulCommand(),search:'1001'}})],['sin revisión',r=>r.body=JSON.stringify({operation:'command',payload:{...annulCommand(),reviewConfirmed:false}})],['tipo de medio',r=>r.headers['content-type']='text/plain'],['sin clave',r=>delete r.headers['idempotency-key']],['UTF8 inválido',r=>r.body=Buffer.from([255])],['método',r=>r.method='DELETE'],['consulta duplicada',r=>{r.method='GET';r.query={resource:'detail',period:'2026-10',liquidationType:'monthly'};r.url+='?'+new URLSearchParams(r.query)+'&period=2026-10';}]])test('rechaza '+label+' sin una decisión SQL',async()=>{const a=setup(),request=req(),r=res();change(request);await a.handler(request,r);assert.ok(r.statusCode>=400);assert.equal(a.calls.length,0);});
test('GET verifica todas las capturas, período/tipo exactos y replay completo',async()=>{const d=annulDetail();for(const mismatch of [false,true]){const a=setup(OWN_ANNUL_ACCESS,d),r=res(),q={resource:'detail',period:mismatch?'2026-11':'2026-10',liquidationType:'monthly'};await a.handler({method:'GET',query:q,url:'/api/internal-own-payroll-annulment?'+new URLSearchParams(q)},r);assert.equal(r.statusCode,mismatch?503:200);}const a=setup(OWN_ANNUL_ACCESS,{...annulReceipt(),replayed:true}),r=res();await a.handler(req(),r);assert.equal(r.statusCode,200);assert.equal(r.headers['Idempotency-Replayed'],'true');assert.equal(r.value.data.affected.length,41);});
