import test from 'node:test';import assert from 'node:assert/strict';
import {reconciliationFixture,approvedReconciliationFixture} from './fixtures/own-payroll-reconciliation-synthetic.js';
import {accountingHash} from '../assets/own-payroll-accounting-model.js';
import {journalStateHashValue} from '../assets/own-payroll-journal-model.js';
import {compareReconciliation,prepareReconciliation,reconciliationTable,reconciliationDocument,reconciliationCommand,reconciliationDetail,reconciliationBootstrap,reconciliationStateHashValue,decideReconciliation,reconciliationAttempt,reconciliationReceipt,reconciliationCsv} from '../assets/own-payroll-reconciliation-model.js';
test('referencias Unicode conservan longitud exacta y rechazan espacios de borde o sustitución UTF8',async()=>{
 const f=await reconciliationFixture(2),d={...f.document,reference:'🧾🧾',issuerReference:'🧾'.repeat(40)};assert.equal(reconciliationDocument(d).issuerReference.length,80);assert.equal((await compareReconciliation(f.source,d)).ready,true);
 for(const reference of['\u00a0Documento sintético','Documento sintético\ufeff','🧾'.repeat(91),'Referencia \ud800'])assert.throws(()=>reconciliationDocument({...d,reference}));
});

test('comparación completa conserva todas las cuentas y renglones, sin tolerancia ni pago',async()=>{
 const f=await reconciliationFixture(35),c=await compareReconciliation(f.source,f.document);assert.ok(c.accounts.length>25);assert.equal(c.documentLineCount,f.document.lines.length);assert.equal(c.sourceEntryCount,f.source.journal.journal.entries.length);assert.ok(c.accounts.every(r=>r.status==='balanced'));assert.equal(c.ready,true);assert.equal(c.paymentExecuted,false);assert.equal(c.externalAcceptance,false);assert.equal(c.totals.differenceDebit,'0.00');assert.deepEqual(c.accounts.flatMap(r=>r.sourceEntryOrdinals).sort((a,b)=>a-b),f.source.journal.journal.entries.map(e=>e.ordinal));assert.deepEqual(c.accounts.flatMap(r=>r.documentLineOrdinals).sort((a,b)=>a-b),f.document.lines.map(e=>e.ordinal));
});
test('un centavo diferente en la última página bloquea todo el documento aunque ambos totales estén balanceados',async()=>{
 const f=await reconciliationFixture();f.document.lines.at(-1).debit='0.01';f.document.lines.at(-2).credit='0.01';const c=await compareReconciliation(f.source,f.document);assert.equal(c.ready,false);assert.ok(c.accounts.some(r=>r.status==='different'));await assert.rejects(prepareReconciliation(f.source,f.document,'Fundamento exclusivamente sintético'),/todas las diferencias/);
});
test('cuentas ausentes y extra conservan null; un documento balanceado no las convierte en coincidencias',async()=>{
 const f=await reconciliationFixture();const original=f.document.lines.at(-1).accountReference;f.document.lines.at(-1).accountReference='CUENTA-AJENA-QA';const c=await compareReconciliation(f.source,f.document),extra=c.accounts.find(r=>r.status==='extra'),missing=c.accounts.find(r=>r.accountReference===original);assert.ok(extra);assert.equal(extra.expectedDebit,null);assert.equal(extra.differenceDebit,null);assert.equal(missing.status,'missing');assert.equal(missing.declaredCredit,null);assert.equal(c.ready,false);
});
test('importes no informados nunca se completan como cero, incluso si el resto coincide',async()=>{
 const f=await reconciliationFixture();f.document.lines.at(-1).debit=null;const c=await compareReconciliation(f.source,f.document);assert.equal(c.totals.declaredDebit,null);assert.equal(c.totals.differenceDebit,null);assert.deepEqual(c.lineIssues,[{ordinal:f.document.lines.length,code:'debit_missing'}]);assert.equal(c.accounts.at(-1).status,'incomplete');assert.equal(c.ready,false);await assert.rejects(prepareReconciliation(f.source,f.document,'Fundamento exclusivamente sintético'));
 f.document.lines.at(-1).debit='0.0000';const explicit=await compareReconciliation(f.source,f.document);assert.equal(explicit.lineIssues.length,0);assert.equal(explicit.accounts.at(-1).declaredDebit,'0.0000');
});
test('desbalance documental y documento sin filas son incidencias globales, no filas omitidas',async()=>{
 const f=await reconciliationFixture(2);f.document.lines[0].debit='123456.78';const c=await compareReconciliation(f.source,f.document);assert.deepEqual(c.globalIssues,['document_unbalanced']);assert.equal(c.documentLineCount,f.document.lines.length);assert.equal(c.ready,false);f.document.lines=[];const empty=await compareReconciliation(f.source,f.document);assert.deepEqual(empty.globalIssues,['document_empty']);assert.equal(empty.totals.declaredDebit,null);assert.equal(empty.ready,false);
});
test('los renglones repetidos de una cuenta se suman exactamente y conservan todos sus ordinales y escalas',async()=>{
 const f=await reconciliationFixture(2);const r=f.document.lines.find(r=>r.debit!=='0'),value=r.debit;r.debit='0.0050';f.document.lines.push({ordinal:f.document.lines.length+1,accountReference:r.accountReference,debit:value,credit:'0.0000'},{ordinal:f.document.lines.length+2,accountReference:r.accountReference,debit:'0.0050',credit:'0.0000'});const c=await compareReconciliation(f.source,f.document);const a=c.accounts.find(a=>a.accountReference===r.accountReference);assert.equal(a.differenceDebit,'0.0100');assert.ok(a.documentLineOrdinals.includes(f.document.lines.length));assert.equal(c.ready,false);
});
test('tabla de Excel exige encabezados y separador explícitos y no quita miles, ceros o filas internas',()=>{
 const v='Cuenta\tDebe\tHaber\r\n"=SUM(1;2)"\t12,3400\t0\r\nCUENTA-QA\t\t12,34\r\n';const rows=reconciliationTable(v,',');assert.equal(rows[0].accountReference,'=SUM(1;2)');assert.equal(rows[0].debit,'12.3400');assert.equal(rows[1].debit,null);
 for(const [v,s]of [['Cuenta\tDebe\tHaber\nA\t1,234.56\t0',','],['Cuenta\tDebe\tHaber\nA\t1,23\t0','.'],['Cuenta\tDebe\tHaber\nA\t1e2\t0','.'],['Cuenta\tDebe\tHaber\nA\t01.23\t0','.'],['Cuenta\tDebe\tHaber\n\nA\t1\t0','.'],['Cuenta\tDebe\tHaber\nA\t1\t0',''],['Cuenta\tDebe\tHaber\n"A\t1\t0','.']])assert.throws(()=>reconciliationTable(v,s));
});
test('duplicados/permutación de ordinal, dato libre y fecha inexistente rechazan el documento',async()=>{
 const f=await reconciliationFixture(2);for(const change of [d=>d.lines[0].ordinal=2,d=>d.lines.reverse(),d=>d.lines[0].amount='999',d=>d.date='2026-02-30',d=>d.actorPersonId='injected',d=>d.lines[0].debit='-0',d=>d.lines[0].debit='-1']){const d=structuredClone(f.document);change(d);assert.throws(()=>reconciliationDocument(d));}
 const body=await prepareReconciliation(f.source,f.document,'Fundamento exclusivamente sintético');assert.throws(()=>reconciliationCommand({...body,command:'pay'}));assert.throws(()=>reconciliationCommand({...body,journalId:'nombre o DNI'}));
});
test('propuesta/asiento revertido/captura alterada nunca habilitan una constancia nueva',async()=>{
 const f=await reconciliationFixture(2);for(const change of [s=>{s.journal.status='reversed';s.journal.reversedBy='cccccccc-0000-4000-8000-000000099999';},s=>s.journal.journal.entries[0].amount='999.99',s=>s.complete=false]){const s=structuredClone(f.source);change(s);s.journal.stateVersion=await accountingHash(journalStateHashValue(s.journal));await assert.rejects(compareReconciliation(s,f.document));}
 // A posted historical accounting record stays verifiable after its old allocation changes.
 f.source.journal.sourceCurrent=false;assert.equal((await compareReconciliation(f.source,f.document)).ready,true);
});
test('decisión independiente y retiro preservan el cuerpo original; fuente cambiada impide aprobar',async()=>{
 const f=await approvedReconciliationFixture(2);await reconciliationDetail(f.detail);reconciliationBootstrap(f.boot);const withdrawal=await decideReconciliation(f.boot,f.detail,'withdraw','Retiro exclusivamente sintético de la constancia');assert.equal(withdrawal.command,'withdraw');assert.deepEqual(withdrawal.document,f.document);assert.equal(f.detail.status,'approved');
 const pending=structuredClone(f.detail);pending.id=pending.proposalId;pending.status='pending';pending.decision=null;pending.sourceCurrent=false;pending.stateVersion=await accountingHash(reconciliationStateHashValue(pending));const boot=structuredClone(f.boot);Object.assign(boot.reconciliations[0],{id:pending.id,status:'pending',decision:null});await assert.rejects(decideReconciliation(boot,pending,'approve','Decisión exclusivamente sintética'),/asiento cambió/);assert.equal((await decideReconciliation(boot,pending,'reject','Rechazo exclusivamente sintético')).command,'reject');boot.permissions.canReview=false;await assert.rejects(decideReconciliation(boot,pending,'reject','Rechazo exclusivamente sintético'),/otra identidad/);
});
test('detalle detecta cuentas, documentos o decisiones alterados aun cuando se reescriba una huella aislada',async()=>{
 const f=await approvedReconciliationFixture(2);for(const change of [d=>d.comparison.accounts[0].declaredDebit='9999',d=>d.body.document.lines[0].debit='9999',d=>d.source.journal.journal.entries[0].accountReference='OTRA',d=>{d.status='withdrawn';d.withdrawal=null;}]){const d=structuredClone(f.detail);change(d);d.requestSha256=await accountingHash(d.body);d.stateVersion=await accountingHash(reconciliationStateHashValue(d));await assert.rejects(reconciliationDetail(d));}
});
test('intento congelado conserva cuerpo/clave y recuperación no acredita pago o aceptación externa',async()=>{
 const f=await reconciliationFixture(2),body=await prepareReconciliation(f.source,f.document,'Fundamento exclusivamente sintético'),key='cccccccc-0000-4000-8000-000000090009',attempt=reconciliationAttempt(key,body,'acceso-sintetico');assert.ok(Object.isFrozen(attempt.body.document.lines[0]));assert.throws(()=>attempt.body.document.lines[0].debit='9999');
 const receipt={version:body.version,eventId:key,proposalId:key,requestKey:key,requestSha256:await accountingHash(body),body,status:'pending',comparisonSha256:body.comparisonSha256,sourceVersion:body.sourceVersion,replayed:true,accountingReconciled:false,paymentExecuted:false,externalAcceptance:false};await reconciliationReceipt(receipt,attempt);for(const change of [r=>r.paymentExecuted=true,r=>r.externalAcceptance=true,r=>r.requestKey='cccccccc-0000-4000-8000-000000090010']){const r=structuredClone(receipt);change(r);await assert.rejects(reconciliationReceipt(r,attempt));}
});
test('CSV conserva todas las cuentas y texto literal seguro; revocación del asiento o retiro no habilitan descarga',async()=>{
 const f=await approvedReconciliationFixture(35),csv=await reconciliationCsv(f.detail),rows=csv.split('\r\n');assert.equal(rows.filter(r=>r.startsWith('"\'Cuenta";')).length,f.detail.comparison.accounts.length);assert.equal(rows.filter(r=>r.startsWith('"\'Asiento";')).length,f.source.journal.journal.entries.length);assert.equal(rows.filter(r=>r.startsWith('"\'Documento";')).length,f.document.lines.length);assert.ok(csv.includes(f.detail.comparisonSha256));f.detail.sourceCurrent=false;await assert.rejects(reconciliationCsv(f.detail),/vigente/);
 const safe=await approvedReconciliationFixture(2);safe.document.reference='=HYPERLINK("qa";"literal")';safe.detail.body=await prepareReconciliation(safe.source,safe.document,'Fundamento exclusivamente sintético');safe.detail.requestSha256=await accountingHash(safe.detail.body);safe.detail.comparison=await compareReconciliation(safe.source,safe.document);safe.detail.comparisonSha256=safe.detail.body.comparisonSha256;safe.detail.stateVersion=await accountingHash(reconciliationStateHashValue(safe.detail));assert.ok((await reconciliationCsv(safe.detail)).includes('"\'=HYPERLINK(""qa"";""literal"")"'));
});
