import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {ownNoveltyCommand,ownNoveltyBatch,ownNoveltyBootstrap,ownNoveltyReceipt,prepareOwnNoveltyReview,ownNoveltyCsv} from '../assets/own-payroll-novelties-model.js';
import {verifyOwnNoveltyHashes,ownNoveltyHash} from '../lib/internal-own-payroll-novelties.js';
import {prepareOwnPayrollInput} from '../lib/own-payroll-approved-input.js';
import {createOwnPayrollSnapshot} from '../lib/own-payroll-snapshot.js';
import {ownNoveltyCaptureSql} from '../scripts/lib/own-novelties-sql.mjs';
import {prepare,batch,bootstrap,receipt,row} from './fixtures/own-payroll-novelties-synthetic.js';
import {approvedSources} from './fixtures/own-payroll-approved-synthetic.js';
import {validateMonthlyInputRow} from '../assets/payroll-native-monthly-model.js';

test('own bulk preserves opaque employee numbers, prefixes and 64 Unicode code points through review, receipt and CSV',()=>{
 const numbers=['A/3501','0901','901','0','á'.repeat(64)],body=prepare(numbers.length),boot=bootstrap(numbers.length);
 numbers.forEach((n,i)=>{body.rows[i].legajo=n;boot.subjects[i].legajo=n;});
 const review=prepareOwnNoveltyReview(boot,body);assert.deepEqual(review.body.rows.map(r=>r.legajo),numbers);
 const stored=batch(numbers.length);numbers.forEach((n,i)=>{stored.rows[i].values.legajo=n;stored.rows[i].subject.legajo=n;});
 stored.rowsSha256=ownNoveltyHash(stored.rows.map(({values,subject})=>({values,subject})));verifyOwnNoveltyHashes(stored);
 const r=receipt(body);r.snapshot={...stored,status:'draft',revision:1,decidedBy:null,approvals:[]};
 ownNoveltyReceipt(r,{key:r.requestKey,body});assert.equal(r.requestSha256,ownNoveltyHash(body));
 const csv=ownNoveltyCsv(stored);for(const n of numbers)assert.ok(csv.includes('"'+n+'"'));
 const {contractId,identityToken,...legacy}=body.rows[0];assert.throws(()=>validateMonthlyInputRow(legacy,body.periodMonth));
 const changed=structuredClone(boot);changed.subjects[1].legajo='901';assert.throws(()=>prepareOwnNoveltyReview(changed,body),/Cambió un legajo/);
});
test('opaque own numbers never waive controls, complete row validation or identity binding',()=>{
 for(const number of ['',123,'x'.repeat(65),'á'.repeat(65),'A\n1','A\u00851',null]){const body=prepare(1);body.rows[0].legajo=number;assert.throws(()=>ownNoveltyCommand(body));}
 for(const mutate of [r=>r.conceptSourceId='A',r=>r.quantityDecimal='1e2',r=>r.amountCents='20.5',r=>{r.amountCents=null;r.quantityDecimal=null;},r=>r.adjustmentMonth='2026-11-01',r=>r.forced=true,r=>r.legalInstrument='x'.repeat(161)]){const body=prepare(1);body.rows[0].legajo='A/3501';mutate(body.rows[0]);assert.throws(()=>ownNoveltyCommand(body));}
 const body=prepare(1),boot=bootstrap(1);body.rows[0].legajo='A/3501';boot.subjects[0].legajo='A/3501';body.rows[0].identityToken='a'.repeat(64);assert.throws(()=>prepareOwnNoveltyReview(boot,body),/Cambió un legajo/);
});
test('one complete native batch includes 759 rows, seven types, exact values and frozen body',()=>{for(const payrollType of ['monthly','first_fortnight','sac','vacation','supplementary','final','other']){const command=ownNoveltyCommand(prepare(759,{payrollType}));assert.equal(command.rows.length,759);assert.ok(Object.isFrozen(command.rows));assert.equal(command.rows.at(-1).rowOrdinal,759);}const b=prepare(2);b.rows[0].quantityDecimal='0.000000';b.rows[0].amountCents=null;b.rows[1].amountCents='0';const result=ownNoveltyCommand(b);assert.equal(result.rows[0].quantityDecimal,'0');assert.equal(result.rows[0].amountCents,null);assert.equal(result.rows[1].amountCents,'0');});
test('global capacity, no missing values, repeated business keys and ordinal gaps fail complete batch',()=>{for(const mutate of [v=>v.rows.push(...Array(10000).fill(v.rows[0])),v=>v.rows[1]={...v.rows[0],rowOrdinal:2},v=>v.rows[1].rowOrdinal=4,v=>v.rows[0].amountCents=null,v=>v.rows[0].quantityDecimal='-0',v=>v.rows[0].identityToken='unknown',v=>v.rows[0].extra='x',v=>v.reviewConfirmed=false,v=>v.rows[0].forced=true]){const v=prepare(2);mutate(v);assert.throws(()=>ownNoveltyCommand(v));}});
test('native review rechecks complete identities and never depends on page/search',()=>{const boot=bootstrap(61),body=prepare(61);assert.equal(prepareOwnNoveltyReview(boot,body).rows.length,61);const changed=structuredClone(boot);changed.subjects[60].identityToken='a'.repeat(64);assert.throws(()=>prepareOwnNoveltyReview(changed,body),/Cambió un legajo/);assert.throws(()=>ownNoveltyBootstrap({...boot,complete:false}));});
test('immutable receipt preserves original body/status/revision even after another decision',()=>{const body=prepare(),r=receipt(body);assert.equal(ownNoveltyReceipt(r,{key:r.requestKey,body}).snapshot.status,'draft');assert.throws(()=>ownNoveltyReceipt({...r,snapshot:batch()},{key:r.requestKey,body}));assert.throws(()=>ownNoveltyReceipt(r,{key:r.requestKey,body:prepare(1)}));});
test('all CSV rows retain exact strings, null and zero, with quoted formula-safe cells',()=>{const b=batch(61);b.rows[0].values.quantityDecimal='-10.25';b.rows[0].values.amountCents='0';b.rowsSha256=ownNoveltyHash(b.rows.map(({values,subject})=>({values,subject})));const csv=ownNoveltyCsv(b);assert.equal(csv.split('\r\n').length,63);assert.ok(csv.includes('"61";"1061"'));assert.ok(csv.includes('"\'-10.25";"0"'));b.rows[60].identityCurrent=false;assert.throws(()=>ownNoveltyCsv(b));});
test('hash corruption, missing original row and independent reviewer mismatch fail',()=>{const b=batch(61);verifyOwnNoveltyHashes(b);b.rows[60].values.amountCents='2001';assert.throws(()=>verifyOwnNoveltyHashes(b));assert.throws(()=>ownNoveltyBatch({...batch(),decidedBy:batch().preparedBy}));assert.throws(()=>ownNoveltyBatch({...batch(),rowCount:1}));});
test('forced amounts require two distinct independent reviewers; one review stays pending',()=>{const b=batch();for(const r of b.rows){r.values.forced=true;r.values.observation='Fundamento forzado sintético QA';}b.rowsSha256=ownNoveltyHash(b.rows.map(({values,subject})=>({values,subject})));assert.throws(()=>ownNoveltyBatch(b));const pending={...b,status:'submitted',decidedBy:null};ownNoveltyBatch(pending);const final={...b,approvals:[...b.approvals,{personId:'10000000-0000-4000-8000-000000021005',membershipId:'10000000-0000-4000-8000-000000021006'}]};final.decidedBy=final.approvals.at(-1);ownNoveltyBatch(final);assert.throws(()=>ownNoveltyBatch({...final,approvals:[final.approvals[0],final.approvals[0]]}));});
test('own calculation consumes complete new source with all/one legajo scopes and exact null-zero rules',()=>{const data=approvedSources(2);data.monthly={complete:true,batches:[],nativeBatches:[batch()]};const input=prepareOwnPayrollInput(data);assert.equal(input.employees.length,2);assert.equal(input.employees[0].inputs.find(i=>i.key==='addition').value,'20.00000000');const all=createOwnPayrollSnapshot(input);assert.equal(all.result.employeeCount,2);const selected=structuredClone(data);selected.population.employees=selected.population.employees.slice(0,1);selected.selection={kind:'contracts',values:[selected.population.employees[0].contractId]};selected.monthly.nativeBatches[0].rows[1].identityCurrent=false;const one=prepareOwnPayrollInput(selected);assert.equal(one.employees.length,1);assert.notEqual(one.sourceVersions.novelties,input.sourceVersions.novelties);assert.equal(selected.monthly.nativeBatches[0].rowCount,2);});
test('new sources never waive stale selected identity, forced/retroactive rules or unused concepts',()=>{for(const change of [b=>b.rows[0].identityCurrent=false,b=>b.rows[0].values.adjustmentMonth='2026-09-01',b=>{b.rows[0].values.forced=true;b.rows[0].values.observation='Fundamento QA ficticio';},b=>b.rows[0].values.conceptSourceId='999']){const data=approvedSources(2),b=batch();change(b);b.rowsSha256=ownNoveltyHash(b.rows.map(({values,subject})=>({values,subject})));data.monthly={complete:true,batches:[],nativeBatches:[b]};assert.throws(()=>prepareOwnPayrollInput(data));}});
test('capture extends only complete source assembly; body, key, replay, CPU and result contracts preserved',()=>{const read=f=>fs.readFileSync(new URL('../'+f,import.meta.url),'utf8');const derived=ownNoveltyCaptureSql(read);assert.ok(derived.includes('own_novelty_sources_v1'));assert.ok(derived.includes("'nativeBatches',native_batches"));const migration=read('scripts/migrations/130-own-bulk-novelties.sql');assert.ok(migration.endsWith(derived));assert.throws(()=>ownNoveltyCaptureSql(f=>read(f).replace("batches jsonb:='[]';","batches jsonb:='[]';batches jsonb:='[]';")));});
