import test from 'node:test';import assert from 'node:assert/strict';
import {createOwnCloseHandler} from '../api/internal-own-payroll-close.js';
import {OWN_CLOSE_WRITE,OWN_CLOSE_NOMINAL} from '../assets/own-payroll-close-model.js';
import {closeDetail,closeCommand,closeReceipt} from './fixtures/own-payroll-close-synthetic.js';import {uid} from './fixtures/own-payroll-program-synthetic.js';
const p={user:{email:'qa@example.invalid'},tenant:{source:'membership',id:uid(50),membershipId:uid(51),effectiveCapabilities:OWN_CLOSE_WRITE}},session={email:'qa@example.invalid',id:uid(52),version:1,releaseSha:'d'.repeat(40)};
const res=()=>({headers:{},setHeader(k,v){this.headers[k]=v;},status(n){this.statusCode=n;return this;},json(v){this.value=v;return this;}}),req=()=>({method:'POST',url:'/api/internal-own-payroll-close',query:{},headers:{origin:'https://municipio.example','content-type':'application/json','idempotency-key':uid(9)},body:JSON.stringify({operation:'command',payload:closeCommand()})});
function setup(caps=OWN_CLOSE_WRITE,value=closeReceipt()){const calls=[],stats={connect:0};return {calls,stats,handler:createOwnCloseHandler({env:{INTERNAL_APP_ORIGIN:'https://municipio.example'},requireAccess:async()=>({mode:'managed',principal:{...p,tenant:{...p.tenant,effectiveCapabilities:caps}}}),sessionFor:()=>session,getSql:async()=>{stats.connect++;return {query:async(q,v)=>{calls.push({q,v});return [{result:value}];}};}})};}
test('cierre deriva actor y destino de la sesión; no acepta totales del cliente',async()=>{const a=setup(),r=res();await a.handler(req(),r);assert.equal(r.statusCode,201);assert.equal(a.calls.length,1);assert.match(a.calls[0].q,/own_close_command/);assert.deepEqual(JSON.parse(a.calls[0].v[1]),closeCommand());assert.equal(JSON.parse(a.calls[0].v[0]).membershipId,p.tenant.membershipId);assert.match(r.headers['Cache-Control'],/no-store/);});
test('revocar cualquiera de las capacidades impide leer el cuerpo privado o conectar',async()=>{for(const cap of OWN_CLOSE_WRITE){const a=setup(OWN_CLOSE_WRITE.filter(c=>c!==cap)),request=req(),r=res();let reads=0;Object.defineProperty(request,'body',{get(){reads++;throw Error('Unread');}});await a.handler(request,r);assert.equal(r.statusCode,403,cap);assert.equal(a.stats.connect,0);assert.equal(reads,0);}});
for(const[label,change]of [['origen ajeno',r=>r.headers.origin='https://evil.invalid'],['JSON ambiguo',r=>r.body='{"operation":"command","operati\\u006fn":"command"}'],['importe cliente',r=>r.body=JSON.stringify({operation:'command',payload:{...closeCommand(),amount:'1'}})],['filtro cliente',r=>r.body=JSON.stringify({operation:'command',payload:{...closeCommand(),search:'1001'}})],['sin revisión',r=>r.body=JSON.stringify({operation:'command',payload:closeCommand({reviewConfirmed:false})})],['medio inválido',r=>r.headers['content-type']='text/plain'],['sin clave',r=>delete r.headers['idempotency-key']],['UTF8 inválido',r=>r.body=Buffer.from([255])],['método',r=>r.method='DELETE'],['consulta duplicada',r=>{r.method='GET';r.query={resource:'attempt',key:uid(9)};r.url+='?resource=attempt&resource=attempt&key='+uid(9);}]])test('rechaza '+label+' antes de escribir',async()=>{const a=setup(),request=req(),r=res();change(request);await a.handler(request,r);assert.ok(r.statusCode>=400);assert.equal(a.calls.length,0);});
test('consulta completa no escribe; una selección period/type distinta invalida la respuesta',async()=>{for(const period of [closeDetail().period,'2026-11']){const a=setup(OWN_CLOSE_NOMINAL,closeDetail()),r=res(),request=req();request.method='GET';request.query={resource:'detail',period,liquidationType:closeDetail().liquidationType};request.url+='?'+new URLSearchParams(request.query);await a.handler(request,r);assert.equal(r.statusCode,period===closeDetail().period?200:503);assert.match(a.calls[0].q,/own_close_detail/);}});
test('replay mantiene el histórico y devuelve 200; integridad corrupta no confirma al cliente',async()=>{const a=setup(OWN_CLOSE_WRITE,closeReceipt({replayed:true})),r=res();await a.handler(req(),r);assert.equal(r.statusCode,200);assert.equal(r.headers['Idempotency-Replayed'],'true');const bad=setup(OWN_CLOSE_WRITE,closeReceipt({snapshotSha256:'f'.repeat(64)})),b=res();await bad.handler(req(),b);assert.equal(b.statusCode,503);});
