import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {fixedReviewGroupDraft,fixedReviewGroupEligible,fixedGroupReceipt,fixedGroupUnchanged} from '../assets/payroll-fixed-groups-model.js';
import {prepareFixedGroup,fixedGroupResponse} from '../lib/internal-payroll-fixed-groups.js';import {createInternalPayrollFixedGroupsHandler} from '../api/internal-payroll-fixed-groups.js';
import {fixedFixture,fixedApprovedRecord,fixedNativeSubject,fixedUuid as uuid,fixedEffects} from './fixtures/payroll-fixed-novelties-synthetic.js';
import {prepareFixedReviewGroupsInstallation} from '../scripts/prepare-fixed-review-groups-installation.mjs';import {assertFixedReviewGroupsDurability} from '../scripts/lib/fixed-review-groups-installation.mjs';import {buildFixedReviewGroupsQa} from '../scripts/verify-payroll-fixed-review-groups-sql.mjs';
const rows=()=>{const f=fixedFixture();f.state.records=Array.from({length:45},(_,i)=>fixedApprovedRecord(i));f.state.records[25].subject=fixedNativeSubject();for(const r of f.state.records)f.mutate('propose',{recordId:r.id,expectedVersion:2,contractId:r.subject.contractId,legajo:r.subject.legajo,identityToken:r.subject.identityToken,operation:r===f.state.records[1]?'annul':'set',values:r===f.state.records[1]?null:{...r.approved.values,conceptSourceId:'614'},reason:'Propuesta de ensayo'},uuid(60000+f.state.sequence));f.state.role='reviewer';return f.list(null).rows;};
const draft=()=>fixedReviewGroupDraft(rows(),'approve','Cotejo conjunto documentado');
const receipt=p=>({version:'payroll-fixed-review-group.v1',groupId:uuid(990),key:uuid(777),requestSha256:'a'.repeat(64),total:p.items.length,duplicate:false,decision:p.decision,effects:{...fixedEffects},rows:p.items.map(r=>({version:'payroll-fixed-receipt.v1',command:'review',recordId:r.recordId,proposalId:r.proposalId,recordVersion:r.expectedVersion+1,duplicate:false}))});
test('45 complete mixed proposals keep exact original proposal/version; no values or identity supplied by decision',()=>{const r=rows(),p=draft();assert.equal(p.items.length,45);assert.deepEqual(prepareFixedGroup(p,'review'),p);assert.ok(Object.isFrozen(p.items[44]));r.forEach((row,i)=>assert.deepEqual(p.items[i],{recordId:row.id,proposalId:row.pending.id,expectedVersion:3}));assert.equal(r[1].pending.operation,'annul');assert.equal(r[25].subject.origin,'MUNICONTROL');});
test('ineligible/self-authored, duplicate, missing, max history and invalid decisions reject whole group',()=>{const r=rows()[0];for(const bad of [{...r,identityCurrent:false},{...r,pending:null},{...r,pending:{...r.pending,canReview:false}},{...r,version:200}]){assert.equal(fixedReviewGroupEligible(bad),false);assert.throws(()=>fixedReviewGroupDraft([r,bad],'approve','Cotejo documentado'));}assert.throws(()=>fixedReviewGroupDraft([r,r],'reject','Cotejo documentado'));assert.throws(()=>fixedReviewGroupDraft([],'reject','Cotejo documentado'));assert.throws(()=>fixedReviewGroupDraft([r],'annul','Cotejo documentado'));assert.throws(()=>fixedReviewGroupDraft([r],'reject','x'));assert.equal(fixedReviewGroupDraft([{...r,version:199}],'reject','Cotejo documentado').items[0].expectedVersion,199);});
test('decision receipt cannot substitute outcome, proposal, order, count or payroll effects',()=>{const p=draft(),d=receipt(p);assert.deepEqual(fixedGroupReceipt({ok:true,data:d},d.key,p),d);assert.deepEqual(fixedGroupResponse(d,{key:d.key,payload:p,command:'review'}),d);for(const change of [r=>r.decision='reject',r=>r.rows[0].proposalId=uuid(99),r=>r.rows.reverse(),r=>r.rows.pop(),r=>r.effects.payrollCalculated=true,r=>r.rows[0].recordVersion++,r=>r.version='payroll-fixed-correction-group.v1']){const b=structuredClone(d);change(b);assert.throws(()=>fixedGroupReceipt({ok:true,data:b},d.key,p));assert.throws(()=>fixedGroupResponse(b,{key:d.key,payload:p,command:'review'}));}});
test('same-version proposal content/authority drift invalidates complete review',()=>{const r=rows();assert.equal(fixedGroupUnchanged(r,{rows:structuredClone(r)},true),true);for(const edit of [x=>x[44].pending.values.quantityDecimal='2',x=>x[44].pending.reason='Otro motivo',x=>x[44].pending.canReview=false,x=>x[44].subject.identityToken='b'.repeat(64)]){const f=structuredClone(r);edit(f);assert.equal(fixedGroupUnchanged(r,{rows:f},true),false);}});
test('review API requires approval instead of preparation; exact parameterized transaction and scoped recovery',async()=>{const p=draft(),d=receipt(p),caps=['payroll.novelty.read','payroll.novelty.nominal.read','payroll.fixed.approve'],req={method:'POST',query:{},headers:{origin:'https://municipio.example','content-type':'application/json','idempotency-key':d.key},body:{command:'review',payload:p}};
 const run=async(request,authority=caps,result=d)=>{const calls=[],session={id:uuid(900),email:'reviewer@example.invalid',version:1,releaseSha:'a'.repeat(40)},handler=createInternalPayrollFixedGroupsHandler({env:{INTERNAL_APP_ORIGIN:'https://municipio.example'},requireCompatibleInternalAccess:async()=>({mode:'managed',principal:{user:{email:session.email},tenant:{source:'membership',id:uuid(1),membershipId:uuid(3),certifiedReleaseSha:session.releaseSha,effectiveCapabilities:authority}}}),actionMutationSession:()=>session,getInternalSql:async()=>({query:async(sql,args)=>{calls.push({sql,args});return[{result}];}})},'review'),res={setHeader(){},status(code){this.code=code;return this;},json(body){this.body=body;return this;}};await handler(request,res);return {calls,res};};
 const good=await run(req);assert.equal(good.res.code,201);assert.equal(good.calls.length,1);assert.match(good.calls[0].sql,/review_group_decide_v1\(\$1::jsonb,\$2::jsonb,\$3::uuid\)/);assert.deepEqual(JSON.parse(good.calls[0].args[1]),p);
 for(const authority of [[],caps.slice(0,2),[...caps.slice(0,2),'payroll.fixed.prepare']]){const b=await run(req,authority);assert.equal(b.res.code,403);assert.equal(b.calls.length,0);}
 for(const bad of [{...req,headers:{...req.headers,origin:'https://foreign.example'}},{...req,body:{command:'correct',payload:p}},{...req,body:{command:'review',payload:{...p,decision:'annul'}}},{...req,body:{command:'review',payload:{...p,items:[{...p.items[0],values:{}}]}}}]){const b=await run(bad);assert.ok(b.res.code>=400);assert.equal(b.calls.length,0);}
 const recovered=await run({method:'GET',query:{resource:'attempt',key:d.key}},caps,{...d,duplicate:true});assert.equal(recovered.res.code,200);assert.match(recovered.calls[0].sql,/review_group_attempt_v1/);
});
test('SQL119 exact additive installation pins the093 independent reviewer; durability preserves everything',()=>{const commit='a'.repeat(40),b=prepareFixedReviewGroupsInstallation({read:f=>fs.readFileSync(f,'utf8'),sourceCommit:commit});assert.equal(b.prerequisitePins.length,9);assert.equal(b.prerequisitePins.find(p=>p.name==='payroll_fixed_registry_review_v1').sha256,'a8a0818269be117ad3e6045d8ac98c638f01f6404e239f89e7987469db3a48b1');assert.equal(b.ownPins.length,3);assert.ok(!b.before.includes("p.proname LIKE 'payroll_fixed_correction_group_%'"));const installed={sourceCommit:commit,sqlSha256:b.sqlSha256,allChecksPassed:true,functions119:3,runtimeFacades:2,eventRows:0,nominalRowsReturned:0,priorTableCount:100,beforeFingerprint:'b'.repeat(64),afterFingerprint:'b'.repeat(64),newObjectFingerprint:'c'.repeat(64)},durable={...installed};delete durable.beforeFingerprint;assert.equal(assertFixedReviewGroupsDurability({installed,durable,sourceCommit:commit}).ok,true);assert.throws(()=>assertFixedReviewGroupsDurability({installed,durable:{...durable,eventRows:1},sourceCommit:commit}));});
test('SQL QA retains273 prior checks and embeds exact119 on PG17/18',()=>{for(const serverMajor of [17,18]){const qa=buildFixedReviewGroupsQa({serverMajor});assert.equal(qa.report.correctionGroupChecksPassed,36);assert.equal(qa.report.groupChecksPassed,30);assert.equal(qa.report.checksPassed,273+qa.report.reviewGroupChecksPassed);const exact=fs.readFileSync('scripts/migrations/119-fixed-novelty-review-groups.sql','utf8').replaceAll('public.',qa.schema+'.').replaceAll(qa.schema+'.digest(','public.digest(').replaceAll('SET search_path=pg_catalog,public,pg_temp','SET search_path=pg_catalog,'+qa.schema+',public,pg_temp');assert.ok(qa.sql.includes("EXECUTE '"+exact.replaceAll("'","''")+"';"));}});
