import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {junin638Line,junin638Txt,junin638Filename,JUNIN638_LAYOUT} from '../assets/payroll-junin-638.js';
import {fixedJunin638Data} from '../assets/payroll-fixed-novelties-model.js';
import {validateFixedResponse} from '../lib/internal-payroll-fixed-novelties.js';
import {fixedFixture,fixedApprovedRecord,fixedEffects,fixedUuid as uuid} from './fixtures/payroll-fixed-novelties-synthetic.js';
import {draft as nativeDraft} from './fixtures/native-employee-synthetic.js';
const period='2026-09-01',dni=nativeDraft().dni;
const sourceFormat={id:1,name:'Formato Junin',filename:'amaru.txt',dniStart:5,dniLength:8,amountStart:44,amountLength:11};
const format={recordBytes:55,lineEnding:'CRLF',trailingLineEnding:false};
const make=()=>{const f=fixedFixture(),record=fixedApprovedRecord(1,{conceptSourceId:'638',quantityDecimal:null,amountCents:'250000',validFrom:period,validTo:null});f.state.records.push(record);const list=f.list(period);return{record,list,payload:{version:'payroll-fixed-junin638.v1',periodMonth:period,snapshotToken:list.snapshotToken,concept:'638',receiver:'AMARU',sourceFormat,format,rows:[{recordId:record.id,version:record.version,proposalId:record.approved.id,contractId:record.subject.contractId,dni,amountCents:'250000'}],total:1,effects:fixedEffects}};};

test('Formato Junín usa exactamente DNI posición 5/8 e importe posición 44/11',()=>{const {payload}=make(),line=junin638Line(payload.rows[0]);assert.equal(line.length,55);const text=new TextDecoder().decode(line);assert.equal(text.slice(0,5),'     ');assert.equal(text.slice(5,13),dni.padStart(8,'0'));assert.equal(text.slice(13,44),' '.repeat(31));assert.equal(text.slice(44),'00002500.00');assert.deepEqual(JUNIN638_LAYOUT,{recordBytes:55,dniStart:5,dniLength:8,amountStart:44,amountLength:11});});
test('nombre de archivo es el registrado por GRH',()=>assert.equal(junin638Filename(),'amaru.txt'));
test('TXT usa CRLF entre registros y nunca al EOF',()=>{const {payload}=make();payload.rows.push({...payload.rows[0],recordId:uuid(81),proposalId:uuid(82),contractId:uuid(83),dni:'12345678',amountCents:'1'});payload.total=2;const bytes=junin638Txt(payload);assert.equal(bytes.length,112);assert.deepEqual([...bytes.slice(55,57)],[13,10]);assert.notDeepEqual([...bytes.slice(-2)],[13,10]);assert.equal(new TextDecoder().decode(bytes).slice(-11),'00000000.01');});
test('DNI e importe inválidos fallan cerrado',()=>{for(const bad of ['','00000','1234','123456789','12A45678']){const {payload}=make();payload.rows[0].dni=bad;assert.throws(()=>junin638Txt(payload),/DNI_INVALID/);}for(const amount of ['-1','10000000000','1.2']){const {payload}=make();payload.rows[0].amountCents=amount;assert.throws(()=>junin638Txt(payload),/AMOUNT_INVALID/);}});
test('frontend liga 638 al snapshot aprobado exacto',()=>{const {payload,list}=make();assert.doesNotThrow(()=>fixedJunin638Data({ok:true,data:payload},list));for(const change of [p=>p.snapshotToken='b'.repeat(64),p=>p.concept='639',p=>p.sourceFormat.dniStart=3,p=>p.format.recordBytes=56,p=>p.rows[0].recordId=uuid(99)]){const altered=structuredClone(payload);change(altered);assert.throws(()=>fixedJunin638Data({ok:true,data:altered},list));}});
test('contrato del servidor valida el layout fuente',()=>{const {payload,list}=make();assert.doesNotThrow(()=>validateFixedResponse(payload,'junin638',{periodMonth:list.periodMonth,snapshotToken:list.snapshotToken}));const bad=structuredClone(payload);bad.sourceFormat.filename='otro.txt';assert.throws(()=>validateFixedResponse(bad,'junin638',{periodMonth:list.periodMonth,snapshotToken:list.snapshotToken}));});
test('migración 108 sólo exporta concepto 638 y usa DNI canónico',()=>{const sql=fs.readFileSync(new URL('../scripts/migrations/108-payroll-fixed-junin638.sql',import.meta.url),'utf8');assert.match(sql,/payroll_fixed_registry_export_v1\(p_context,p_period,p_snapshot\)/);assert.match(sql,/payroll\.novelty\.export/);assert.match(sql,/conceptSourceId.*638/s);assert.match(sql,/pi\.dni/);assert.match(sql,/'Formato Junin'/);assert.match(sql,/'amaru\.txt'/);assert.match(sql,/'dniStart',5/);assert.match(sql,/'amountStart',44/);assert.doesNotMatch(sql,/pi\.cuil|pi\.full_name/);assert.match(sql,/REVOKE ALL ON FUNCTION/);assert.doesNotMatch(sql,/\b(?:INSERT INTO|UPDATE|DELETE FROM|TRUNCATE|ALTER TABLE|DROP TABLE)\b/i);});
test('analizador externo se presenta como validador, no como exportador 638',()=>{const html=fs.readFileSync(new URL('../nomina-control.html',import.meta.url),'utf8');assert.match(html,/TXT 638 AMARU/);assert.match(html,/no exporta descuentos/);assert.match(html,/novedades-nomina\.html#fixedNovelties/);});
