import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
import {authorizedCipherUrl,fetchAuthorizedCipher,publicDeliveryReceipt} from '../lib/payroll-private-transfer.js';
import {createPayrollSourceDeliveryHandler} from '../api/payroll-source-delivery.js';
const url='https://sdmntprbrazilsouth.oaiusercontent.com/files/00000000-0000-4000-8000-000000000000/raw?sig=synthetic';
const cipher=Buffer.alloc(64,7),jobId='10000000-0000-4000-8000-000000000000';
const descriptor={state:'authorized',sourceUrl:url,cipherBytes:cipher.length,cipherSha256:createHash('sha256').update(cipher).digest('hex')};
const receipt={datasetId:jobId,statements:1,lines:2,replayed:false,payrollModified:false};
function response(){return{headers:{},setHeader(k,v){this.headers[k]=v},status(n){this.code=n;return this},json(x){this.payload=x;return this}}}
for(const bad of ['http://localhost/a','https://127.0.0.1/files/a/raw','https://sdmntprbrazilsouth.oaiusercontent.com.evil.invalid/files/a/raw',url.replace('https://','https://user:pass@'),url.replace('/files/','/other/'),url+'#secret',url.replace('.com/','.com:8443/'),'file:///etc/passwd','data:text/plain,hello'])test('remote fetch rejects unapproved location '+bad.split('?')[0],()=>assert.throws(()=>authorizedCipherUrl(bad)));
test('remote fetch validates whole cipher before delivery',async()=>{const actual=await fetchAuthorizedCipher(descriptor,async (u,options)=>{assert.equal(u,url);assert.equal(options.redirect,'error');return new Response(cipher,{headers:{'Content-Length':String(cipher.length)}})});assert.deepEqual(actual,cipher)});
for(const value of [Buffer.alloc(63,7),Buffer.alloc(65,7),Buffer.alloc(64,8)])test('incomplete/extra/wrong cipher rejected '+value.length+':'+value[0],async()=>assert.rejects(fetchAuthorizedCipher(descriptor,async()=>new Response(value))));
test('invalid length never fetches',async()=>{let called=false;await assert.rejects(fetchAuthorizedCipher({...descriptor,cipherBytes:1048577},async()=>{called=true}));assert.equal(called,false)});
test('wrong content-length rejected',async()=>assert.rejects(fetchAuthorizedCipher(descriptor,async()=>new Response(cipher,{headers:{'content-length':'1000'}}))));
test('source URL and cryptographic fields never included in receipt',()=>assert.deepEqual(publicDeliveryReceipt({...receipt,passphrase:'synthetic',sourceUrl:url,cipher}),{ok:true,...receipt}));
test('pull only fetches database-authorized location and returns counters',async()=>{const statements=[];const res=response();await createPayrollSourceDeliveryHandler({getSql:async()=>({query:async(sql,params)=>{statements.push(sql);assert.equal(params[0],jobId);if(statements.length===1)return[{result:descriptor}];assert.equal(params[1],'\\x'+cipher.toString('hex'));return[{result:receipt}]}}),fetchImpl:async()=>new Response(cipher)})({method:'POST',headers:{'content-type':'application/json'},body:{jobId,mode:'pull'}},res);assert.equal(res.code,200);assert.equal(statements.length,2);assert.deepEqual(res.payload,{ok:true,...receipt})});
test('already applied job is not fetched or imported again',async()=>{let count=0;const res=response();await createPayrollSourceDeliveryHandler({getSql:async()=>({query:async()=>{count++;return[{result:{state:'applied',receipt}}]}}),fetchImpl:()=>{throw Error('must not fetch')}})({method:'POST',headers:{'content-type':'application/json'},body:{jobId,mode:'pull'}},res);assert.equal(res.code,200);assert.equal(res.payload.replayed,true);assert.equal(count,1)});
test('unauthorized ID never fetches or returns metadata',async()=>{const res=response();await createPayrollSourceDeliveryHandler({getSql:async()=>({query:async()=>{throw Error('private database message')}}),fetchImpl:()=>{throw Error('must not fetch')}})({method:'POST',headers:{'content-type':'application/json'},body:{jobId,mode:'pull'}},res);assert.equal(res.code,403);assert.deepEqual(res.payload,{ok:false,code:'DELIVERY_DENIED'})});
for(const extra of [{sourceUrl:url},{passphrase:'test'},{cipher:cipher.toString('base64')}])test('caller cannot override job source or key '+Object.keys(extra),async()=>{const res=response();let called=false;await createPayrollSourceDeliveryHandler({getSql:()=>{called=true}})({method:'POST',headers:{'content-type':'application/json'},body:{jobId,mode:'pull',...extra}},res);assert.equal(res.code,400);assert.equal(called,false)});
test('wrong hash does not invoke delivery SQL',async()=>{let count=0;const res=response();await createPayrollSourceDeliveryHandler({getSql:async()=>({query:async()=>{count++;return[{result:descriptor}]}}),fetchImpl:async()=>new Response(Buffer.alloc(64,4))})({method:'POST',headers:{'content-type':'application/json'},body:{jobId,mode:'pull'}},res);assert.equal(res.code,403);assert.equal(count,1)});
