import test from 'node:test';import assert from 'node:assert/strict';
import {decodeNoveltyInput,reviewNoveltyInput,noveltyInputTemplate} from '../assets/payroll-novelty-txt.js';
import {normalizePayrollNoveltyDraft} from '../lib/internal-payroll-novelty.js';
import {NoveltyReviewError,NOVELTY_CSV_HEADER} from '../assets/payroll-novelty-review.js';
const month='2026-09-01',encoder=new TextEncoder();
function parse(values,ordinal,period){const [legajo,conceptSourceId,,adjustment,quantity,amount]=values;let cents=null;if(amount!==''){const m=/^(-?)(\d+)(?:\.(\d{1,2}))?$/.exec(amount);if(!m)throw Error('Importe inválido');cents=((m[1]? -1n:1n)*(BigInt(m[2])*100n+BigInt((m[3]||'').padEnd(2,'0')))).toString();}
 const r={rowOrdinal:1,legajo,conceptSourceId,costCenterSourceId:null,adjustmentMonth:adjustment||null,quantityDecimal:quantity||null,amountCents:cents,movementType:null,legalInstrument:null,observation:null,forced:false};
 return {...normalizePayrollNoveltyDraft({sourceMode:'individual',periodMonth:period,payrollType:'monthly',rows:[r]}).rows[0],rowOrdinal:ordinal};}
const opts=(patch={})=>({format:'columns',layout:'both',separator:'semicolon',header:false,decimal:'point',scale:2,concept:'44',...patch});
const review=(raw,options=opts())=>reviewNoveltyInput(raw,parse,month,options);
const fixed=(patch={})=>opts({format:'fixed',recordWidth:18,idStart:1,idLength:8,valueStart:9,valueLength:10,valueKind:'amount',...patch});
test('TXT extension with exact CSV content follows the unchanged ten-column contract',()=>{const raw=NOVELTY_CSV_HEADER.join(';')+'\r\n1001;44;;;1;;;;;NO\r\n';const text=decodeNoveltyInput(encoder.encode(raw),{name:'novedades.TXT'});const rows=review(text,{format:'csv'});assert.equal(rows[0].quantityDecimal,'1');assert.equal(rows[0].amountCents,null);});
for(const [separator,char]of [['semicolon',';'],['tab','\t'],['pipe','|']])test('explicit '+separator+' maps units and money without conflating them',()=>{
 const rows=review(['00001001','044','12.50','100.01'].join(char),opts({separator}));assert.equal(rows[0].legajo,'1001');assert.equal(rows[0].conceptSourceId,'44');assert.equal(rows[0].quantityDecimal,'12.50');assert.equal(rows[0].amountCents,'10001');
});
for(const [layout,raw,expected]of [['quantity','1001;44;25',{quantityDecimal:'25',amountCents:null}],['amount','1001;638;25.01',{quantityDecimal:null,amountCents:'2501'}],['commonQuantity','1001;25',{conceptSourceId:'44',quantityDecimal:'25',amountCents:null}],['commonAmount','1001;25.01',{conceptSourceId:'44',quantityDecimal:null,amountCents:'2501'}]])test('column layout '+layout,()=>{const r=review(raw,opts({layout}))[0];for(const [key,value]of Object.entries(expected))assert.equal(r[key],value);});
test('missing amount remains null while an explicit zero is preserved',()=>{const r=review('1001;44;1;\n1002;44;1;0');assert.equal(r[0].amountCents,null);assert.equal(r[1].amountCents,'0');});
test('comma decimals require explicit selection and keep cents exact',()=>{assert.equal(review('1001;638;;0012,34',opts({decimal:'comma'}))[0].amountCents,'1234');assert.throws(()=>review('1001;638;;12,34'),NoveltyReviewError);});
test('implicit decimals require a declared scale and do not evaluate a salary formula',()=>{const r=review('1001;44;2500;',opts({decimal:'implied',scale:2}))[0];assert.equal(r.quantityDecimal,'25.00');assert.equal(r.amountCents,null);});
for(const raw of ['1001;44;1;1.234,56','1001;44;1;1,234.56','1001;44;1;1e3','1001;44;1;0.001','1001;44;1;-0.00','1001;44;;','1001;44;+1;','1001;44;1;=SUM(1)'])test('rejects ambiguous or unsafe value '+raw,()=>assert.throws(()=>review(raw),NoveltyReviewError));
test('header is accepted only when selected and exactly matches its layout',()=>{assert.equal(review('legajo;concepto;unidades;importe_ars\n1001;44;1;',opts({header:true})).length,1);assert.throws(()=>review('legajo;concepto;unidades;importe_ars\n1001;44;1;'),NoveltyReviewError);assert.throws(()=>review('concepto;legajo;unidades;importe_ars\n44;1001;1;',opts({header:true})),NoveltyReviewError);});
test('RETRO uses legajo offsets 0/8 and explicit money offsets 8/10',()=>{const text='00001001'+ '0000123.45';assert.equal(text.length,18);const r=review(text+'\r\n',{format:'retro',concept:'678'})[0];assert.equal(r.legajo,'1001');assert.equal(r.conceptSourceId,'678');assert.equal(r.quantityDecimal,null);assert.equal(r.amountCents,'12345');});
test('custom fixed positions require ASCII width and preserve leading field padding',()=>{const r=review(' 001001 '+'    123.45',fixed())[0];assert.equal(r.legajo,'1001');assert.equal(r.amountCents,'12345');});
test('fixed unit value cannot become currency implicitly',()=>{const r=review('000010010000025000',fixed({valueKind:'quantity',decimal:'implied',scale:2}))[0];assert.equal(r.quantityDecimal,'250.00');assert.equal(r.amountCents,null);});
for(const patch of [{recordWidth:0},{idStart:0},{idLength:21},{valueStart:5},{valueStart:17},{valueLength:31},{recordWidth:1.5},{valueKind:'dni'}])test('rejects invalid fixed mapping '+JSON.stringify(patch),()=>assert.throws(()=>review('00001001'+'0000123.45',fixed(patch)),NoveltyReviewError));
for(const raw of ['00001001'+'0000123,45','00001001'+'0000000123'+'EXTRA','00001001'+'0000123.45'+' ','00001001'+'0000123.45'+'\n\n','00001001'+'0000123.4é'])test('RETRO rejects a nonmatching complete record',()=>assert.throws(()=>review(raw,{format:'retro',concept:'678'}),NoveltyReviewError));
test('fixed mapping does not discard content outside selected fields',()=>assert.throws(()=>review('X000010010000123.45',fixed({recordWidth:19,idStart:2,valueStart:10})),NoveltyReviewError));
test('file name never chooses a concept',()=>{assert.throws(()=>review('000010010000123.45',{format:'retro',concept:''}),NoveltyReviewError);});
test('canonical aliases are detected as duplicates, not counted twice',()=>{try{review('00001001;044;1;\n1001;44;2;');assert.fail();}catch(e){assert.ok(e instanceof NoveltyReviewError);assert.equal(e.issues.length,1);assert.equal(e.issues[0].line,2);assert.match(e.issues[0].message,/Duplica la fila 1/);}});
test('every invalid row is reported; no partially accepted array is returned',()=>{try{review('legajo;concepto;unidades;importe_ars\nx;44;1;\n1001;44;1;\n1001;44;2;\n1003;44;;',opts({header:true}));assert.fail();}catch(e){assert.ok(e instanceof NoveltyReviewError);assert.equal(e.rowCount,4);assert.deepEqual(e.issues.map(r=>r.line),[2,4,5]);}});
test('2000-row boundary and exact 20-digit identifiers remain lossless',()=>{const r=review(Array.from({length:2000},(_,i)=>String(99999999999999000000n+BigInt(i))+';44;1;').join('\n'));assert.equal(r.length,2000);assert.equal(r[1999].legajo,'99999999999999001999');assert.throws(()=>review(Array.from({length:2001},(_,i)=>`${i+1};44;1;`).join('\n')),NoveltyReviewError);});
for(const raw of ['', '1001;44;1;\n\n1002;44;1;', '1001\t44\t1\t', '1001;44;1;\u202e'])test('blank rows, wrong separator or hidden formatting do not silently pass',()=>assert.throws(()=>review(raw),NoveltyReviewError));
for(const [encoding,bytes,expected]of [['utf-8',encoder.encode('\ufeffEspaña'),'España'],['windows-1252',new Uint8Array([69,115,112,97,241,97]),'España']])test('explicit '+encoding+' decoding',()=>assert.equal(decodeNoveltyInput(bytes,{name:'QA.txt',encoding}),expected));
for(const bytes of [new Uint8Array(),new Uint8Array([0]),new Uint8Array([255]),new Uint8Array([255,254,65,0]),new Uint8Array(480*1024+1),encoder.encode('bad\ufffd')])test('bad bytes and oversized file rejected without replacement',()=>assert.throws(()=>decodeNoveltyInput(bytes,{name:'QA.txt'})));
for(const name of ['data.xlsx','data.txt.exe','data.pdf',''])test('unsupported extension '+name,()=>assert.throws(()=>decodeNoveltyInput(encoder.encode('content'),{name})));
test('UTF8 bytes are never interpreted as ANSI without an explicit choice',()=>assert.throws(()=>decodeNoveltyInput(new Uint8Array([241]),{name:'QA.txt'})));
test('templates contain only the selected header, no person or sample salary',()=>{assert.equal(noveltyInputTemplate('csv'),NOVELTY_CSV_HEADER.join(';')+'\r\n');assert.equal(noveltyInputTemplate('columns',opts({layout:'commonAmount',separator:'tab'})),'legajo\timporte_ars\r\n');assert.throws(()=>noveltyInputTemplate('retro'));});
test('successful TXT conversion meets the unmodified server batch contract',()=>{const r=review('00001001;044;1;\n00001002;638;;-123.45');const batch=normalizePayrollNoveltyDraft({sourceMode:'bulk',periodMonth:month,payrollType:'monthly',rows:r});assert.equal(batch.summary.rowCount,2);assert.equal(batch.rows[1].amountCents,'-12345');assert.equal(batch.payrollCalculated,false);assert.equal(batch.persistencePerformed,false);});
test('input text and settings are not mutated',()=>{const o=opts(),before=JSON.stringify(o),raw='1001;44;1;';review(raw,o);assert.equal(JSON.stringify(o),before);assert.equal(raw,'1001;44;1;');});
