import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {validatePm10Payload,assertPm10Receipt,pm10Hash,receivePm10} from '../lib/internal-pm10-reception.js';
import {assertPm10Status,getPm10Status} from '../lib/internal-pm10-status.js';
const uuid='a1111111-1111-4111-8111-111111111111',sha='a'.repeat(40);
function payload(){const bytes=Buffer.alloc(40,1),rh=pm10Hash(bytes),sh='a'.repeat(64);return {version:'pm10-delivery.v1',serial:'CQTU225360168',batchId:pm10Hash(sh+':'+rh),snapshotSha256:sh,recordsSha256:rh,totalRecords:1,partStart:0,snapshotRecordCount:1,capturedAt:'2026-09-13T09:00:00.000Z',ordinals:[1],partSha256:rh,recordsBase64:bytes.toString('base64')};}
function receipt(p){return {version:'pm10-receipt.v1',receiptId:uuid,batchId:p.batchId,partStart:p.partStart,partSha256:p.partSha256,snapshotSha256:p.snapshotSha256,count:1,newCanonical:1,duplicates:0,observed:0,receivedAt:'2026-09-13T09:10:00.000Z',persisted:true,payrollModified:false,replayed:false};}
test('part and receipt obey receiver contract',()=>{const p=payload(),r=receipt(p);assert.equal(validatePm10Payload(p),p);assert.equal(assertPm10Receipt(r,p),r);});
for(const change of [{tenantId:uuid},{serial:'wrong'},{capturedAt:'2026-02-30T09:00:00.000Z'},{capturedAt:'2026-09-13'},{totalRecords:2},{partStart:1},{recordsBase64:'YWJj'},{partSha256:'f'.repeat(64)},{ordinals:[0]},{ordinals:[1,2]},{ordinals:['1']},{snapshotRecordCount:0},{totalRecords:104858},{recordsSha256:'0'.repeat(64)}])test('receiver rejects mutated input '+Object.keys(change),()=>assert.throws(()=>validatePm10Payload({...payload(),...change})));
test('receiver SQL is parameterized and emits only verified counters',async()=>{const p=payload(),r=receipt(p);let called=0;const out=await receivePm10({query:async(sql,args)=>{called++;assert.match(sql,/attendance_pm10_receive_v1/);assert.equal(args[0],'qa-connector');assert.equal(args[1],'b'.repeat(64));assert.deepEqual(JSON.parse(args[2]),p);assert.equal(args[3],sha);return[{result:r}];}},'qa-connector','b'.repeat(64),p,sha);assert.deepEqual(out,r);assert.equal(called,1);});
for(const [message,status] of [['PM10_AUTH_DENIED',401],['PM10_BUSY',409],['PM10_PAYLOAD_INVALID',400],['PM10_IDEMPOTENCY_CONFLICT',409],['PM10_BINDING_REQUIRED',503],['unrecognized private error with DNI',503]])test('database failure does not leak payload '+message.split(' ')[0],async()=>{await assert.rejects(receivePm10({query:async()=>{throw Error(message);}},'qa-connector','b'.repeat(64),payload(),sha),e=>e.status===status&&!e.message.includes('DNI'));});
function status(){return{version:'pm10-status.v1',checkedAt:'2026-09-13T09:00:00.000Z',connectorState:'suspended',baselineRecords:111,summary:{receipts:0,newMarks:0,observations:0,knownRecords:0,lastReceivedAt:null,lastCapturedAt:null},records:[],nominalReadAllowed:false,physicalClockVerified:false,payrollModified:false};}
test('status keeps suspended setup distinct from physical verification',()=>assert.equal(assertPm10Status(status()).connectorState,'suspended'));
for(const change of [{physicalClockVerified:true},{payrollModified:true},{baselineRecords:-1},{connectorState:'online'},{records:[{personLabel:'Private identity'}]},{summary:{receipts:0}}])test('status rejects misleading or malformed output '+Object.keys(change),()=>assert.throws(()=>assertPm10Status({...status(),...change})));
test('no nominal permission means no name or legajo in output',()=>{const x=status();x.records=[{occurredAt:null,receivedAt:x.checkedAt,personLabel:'A real name',legajo:'1',state:'observed',issueCodes:['timestamp_invalid'],punchCode:0,verificationCode:1}];assert.throws(()=>assertPm10Status(x));x.records[0].personLabel='Identidad reservada';x.records[0].legajo=null;assert.equal(assertPm10Status(x),x);});
test('reader rejects invalid principal without touching SQL',async()=>{let calls=0;await assert.rejects(getPm10Status({query:async()=>calls++},{},{}));assert.equal(calls,0);});
test('migration never activates a connector or grants raw table reads',()=>{const s=fs.readFileSync('scripts/migrations/055-pm10-continuous-reception.sql','utf8');assert.doesNotMatch(s,/SET status\s*=\s*'active'/i);assert.match(s,/REVOKE ALL ON attendance_pm10_receipt,attendance_pm10_record FROM PUBLIC,municontrol_actions_runtime_app/);assert.match(s,/'clock-v1:'/);assert.match(s,/'zk40-v1:'/);assert.match(s,/attendance_clock_snapshot_row/);assert.match(s,/clock-owner-import:/);assert.doesNotMatch(s,/CREATE TABLE[^;]*(?:dni|fingerprint_template)/i);});
