import test from 'node:test';import assert from 'node:assert/strict';
import {createPm10Receiver} from '../api/attendance-pm10.js';import {createInternalAttendanceHandler} from '../api/internal-attendance.js';
import {pm10Hash} from '../lib/internal-pm10-reception.js';
const token='q'.repeat(43),release='a'.repeat(40),connector='qa-pm10-connector';
const tid='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',mid='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',sid='cccccccc-cccc-4ccc-8ccc-cccccccccccc';
function body(){const data=Buffer.alloc(40,1),rh=pm10Hash(data),sh='a'.repeat(64);return{version:'pm10-delivery.v1',serial:'CQTU225360168',batchId:pm10Hash(sh+':'+rh),snapshotSha256:sh,recordsSha256:rh,snapshotRecordCount:1,totalRecords:1,partStart:0,capturedAt:'2026-09-13T09:00:00.000Z',partSha256:rh,ordinals:[1],recordsBase64:data.toString('base64')};}
function request(){return{method:'POST',headers:{authorization:'Bearer '+token,'x-pm10-connector':connector,'content-type':'application/json'},query:{},body:body()};}
function res(){return{headers:{},setHeader(k,v){this.headers[k]=v;},status(n){this.code=n;return this;},json(p){this.payload=p;return this;}};}
for(const tweak of [r=>r.method='GET',r=>delete r.headers.authorization,r=>r.headers.authorization='Bearer short',r=>r.headers.origin='https://example.invalid',r=>r.headers['content-type']='text/plain',r=>r.query={tenant:tid},r=>r.body={...r.body,secret:'x'},r=>r.headers['content-length']='65537'])test('invalid HTTP request reaches no SQL '+tweak.toString(),async()=>{let calls=0;const r=request();tweak(r);const s=res();await createPm10Receiver({env:{INTERNAL_CERTIFIED_DATA_CONTRACT_SHA:release},getSql:async()=>calls++})(r,s);assert.equal(calls,0);assert.ok([400,401,403,405,413,415].includes(s.code));assert.match(s.headers['Cache-Control'],/no-store/);});
test('bounded reader checks streamed bytes not only the Content-Length',async()=>{const r=request();delete r.body;r[Symbol.asyncIterator]=async function*(){yield ' '.repeat(65537);};const s=res();let calls=0;await createPm10Receiver({env:{INTERNAL_CERTIFIED_DATA_CONTRACT_SHA:release},getSql:async()=>calls++})(r,s);assert.equal(s.code,413);assert.equal(calls,0);});
test('handler hashes token and forwards approved source, never raw token to SQL',async()=>{const r=request(),s=res();await createPm10Receiver({env:{INTERNAL_CERTIFIED_DATA_CONTRACT_SHA:release},getSql:async()=>({}),receive:async(_sql,c,h,p,v)=>{assert.equal(c,connector);assert.equal(h,pm10Hash(token));assert.deepEqual(p,r.body);assert.equal(v,release);return{synthetic:true};}})(r,s);assert.equal(s.code,200);assert.ok(!JSON.stringify(s.payload).includes(token));});
test('missing certified data contract never selects a DB connection',async()=>{let calls=0;const s=res();await createPm10Receiver({env:{},getSql:async()=>calls++})(request(),s);assert.equal(calls,0);assert.equal(s.code,503);});
function access(){return{mode:'managed',session:{id:sid,email:'qa@example.invalid',version:1,mfa:true},principal:{user:{email:'qa@example.invalid'},tenant:{id:tid,membershipId:mid,source:'membership',certifiedReleaseSha:release}}};}
test('status inherits managed attendance gateway before SQL',async()=>{let required,calls=0;const s=res();await createInternalAttendanceHandler({env:{INTERNAL_CERTIFIED_DATA_CONTRACT_SHA:release},requireCompatibleInternalAccess:async(_r,_s,o)=>{required=o;return access();},getInternalSql:async()=>{calls++;return {};},getPm10Status:async(_sql,p,se)=>{assert.equal(p.tenant.id,tid);assert.equal(se.id,sid);return{version:'pm10-status.v1'};}})({method:'GET',query:{resource:'pm10-reception'},headers:{}},s);assert.equal(s.code,200);assert.equal(calls,1);assert.deepEqual(required.requiredCapabilities,['attendance.read']);assert.equal(required.allowLegacy,false);assert.equal(required.requireCertifiedDataBinding,true);});
test('denied status gateway never reads SQL',async()=>{let calls=0;await createInternalAttendanceHandler({requireCompatibleInternalAccess:async()=>null,getInternalSql:async()=>calls++})({method:'GET',query:{resource:'pm10-reception'},headers:{}},res());assert.equal(calls,0);});
