import test from 'node:test';import assert from 'node:assert/strict';
import {createPositionAssignmentHandler} from '../api/internal-position-assignment.js';
import {positionFingerprint} from '../lib/internal-position-assignment.js';
import {runError} from '../lib/internal-own-payroll-run.js';
import {command,bootstrap,runCapture,uid,hash} from './fixtures/position-assignment-synthetic.js';
const caps=['workforce.employee.read','workforce.structure.read','workforce.structure.assignment.prepare','workforce.structure.assignment.approve','payroll.calculation.read'],principal={user:{email:'qa@example.invalid'},tenant:{source:'membership',id:uid(1),membershipId:uid(2),effectiveCapabilities:caps}},session={email:'qa@example.invalid',id:uid(3),version:1,releaseSha:'d'.repeat(40)};
const res=()=>({headers:{},setHeader(k,v){this.headers[k]=v;},status(n){this.statusCode=n;return this;},json(v){this.value=v;return this;}});
const request=()=>({method:'POST',url:'/api/internal-position-assignment',query:{},headers:{origin:'https://municipio.example','content-type':'application/json','idempotency-key':uid(9)},body:JSON.stringify({operation:'command',payload:command()})});
const receipt=()=>({version:'position-assignment-receipt.v1',id:uid(10),key:uid(9),command:'propose',contractId:uid(1),year:2026,bodySha256:positionFingerprint(command()),proposalId:uid(10),revision:0,replayed:false});
test('fallo de la captura compañera es global: capacidad, bloqueo o fuente inválida',()=>{for(const [message,code,status]of [['POSITION_ASSIGNMENT_LIMIT','OWN_RUN_LIMIT',422],['POSITION_ASSIGNMENT_BUSY','OWN_RUN_BUSY',409],['POSITION_ASSIGNMENT_CAPTURE_INVALID','OWN_RUN_CONTRACT_INVALID',503]]){const error=runError(Error(message));assert.equal(error.code,code);assert.equal(error.status,status);assert.ok(!error.message.includes(message));}});
function setup(overrides={}){const calls=[],stats={connections:0};const handler=createPositionAssignmentHandler({env:{INTERNAL_APP_ORIGIN:'https://municipio.example'},requireAccess:async()=>({mode:'managed',principal}),sessionFor:()=>session,getSql:async()=>{stats.connections++;return {query:async(q,v)=>{calls.push({q,v});return [{result:receipt()}];}};},...overrides});return {handler,calls,stats};}
test('propuesta expresa y no-store; contexto procede de membresía y sesión',async()=>{const a=setup(),out=res();await a.handler(request(),out);assert.equal(out.statusCode,201);assert.equal(a.calls.length,1);assert.equal(JSON.parse(a.calls[0].v[0]).actorSessionId,session.id);assert.match(out.headers['Cache-Control'],/no-store/);});
for(const [label,change]of [['origen',r=>r.headers.origin='https://otro.invalid'],['IAM inyectado',r=>r.body=JSON.stringify({operation:'command',payload:command({tenantId:uid(1)})})],['medio',r=>r.headers['content-type']='text/plain'],['JSON duplicado',r=>r.body='{"operation":"command","operati\\u006fn":"command"}'],['clave',r=>delete r.headers['idempotency-key']],['query repetida',r=>{r.method='GET';r.query={resource:'bootstrap',contractId:uid(1),year:'2026'};r.url+='?resource=bootstrap&contractId='+uid(1)+'&year=2026&year=2026';}],['UTF8',r=>r.body=Buffer.from([255])],['método',r=>r.method='DELETE'],['sin revisión',r=>r.body=JSON.stringify({operation:'command',payload:command({reviewConfirmed:true})})]])test('rechaza '+label+' sin abrir SQL',async()=>{const a=setup(),r=request(),out=res();change(r);await a.handler(r,out);assert.ok(out.statusCode>=400);assert.equal(a.calls.length,0);});
test('revocación o sesión inválida no lee bytes ni abre SQL',async()=>{for(const extra of [{requireAccess:async()=>({mode:'managed',principal:{...principal,tenant:{...principal.tenant,effectiveCapabilities:[]}}})},{sessionFor:()=>({...session,id:null})}]){const a=setup(extra),r=request(),out=res();let reads=0;Object.defineProperty(r,'body',{get(){reads++;throw Error('prohibido');}});await a.handler(r,out);assert.ok([401,403].includes(out.statusCode));assert.equal(reads,0);assert.equal(a.stats.connections,0);}});
test('consulta sin permiso de preparación; captura exige lectura de cálculo',async()=>{const r=request();r.method='GET';r.query={resource:'bootstrap',contractId:uid(1),year:'2026'};r.url+='?'+new URLSearchParams(r.query);const a=setup({requireAccess:async()=>({mode:'managed',principal:{...principal,tenant:{...principal.tenant,effectiveCapabilities:caps.slice(0,2)}}}),getSql:async()=>({query:async()=>[{result:bootstrap()}]})}),out=res();await a.handler(r,out);assert.equal(out.statusCode,200);const denied=res();await a.handler(request(),denied);assert.equal(denied.statusCode,403);const captureReq={...r,url:'/api/internal-position-assignment?resource=capture&captureId='+uid(80),query:{resource:'capture',captureId:uid(80)}},blocked=res();await a.handler(captureReq,blocked);assert.equal(blocked.statusCode,403);});
test('captura completa verificada; rechaza otro id, huella o cantidad alterada',async()=>{const r=request();r.method='GET';r.query={resource:'capture',captureId:uid(80)};r.url+='?'+new URLSearchParams(r.query);for(const mutate of [()=>{},v=>v.captureId=uid(90),v=>v.payloadSha256=hash('0'),v=>v.payload.employees[0].allocations[0].quantity='999']){const value=runCapture();mutate(value);const a=setup({getSql:async()=>({query:async()=>[{result:value}]})}),out=res();await a.handler(r,out);assert.equal(out.statusCode,value.captureId===uid(80)&&value.payloadSha256===positionFingerprint(value.payload)?200:503);}});
test('fallos redacted y recibos ajenos rechazados',async()=>{for(const getSql of [async()=>({query:async()=>[{result:{...receipt(),bodySha256:hash('f')}}]}),async()=>({query:async()=>[{result:{...receipt(),key:uid(50)}}]}),async()=>({query:async()=>{throw Error('private-secret');}})]){const a=setup({getSql}),out=res();await a.handler(request(),out);assert.equal(out.statusCode,503);assert.ok(!JSON.stringify(out.value).includes('private-secret'));}});
test('reenvío conserva cuerpo y clave; no recalcula ni altera operación',async()=>{const a=setup({getSql:async()=>({query:async()=>[{result:{...receipt(),replayed:true}}]})}),out=res();await a.handler(request(),out);assert.equal(out.statusCode,200);assert.equal(out.headers['Idempotency-Replayed'],'true');assert.equal(out.value.data.bodySha256,positionFingerprint(command()));});
