import assert from 'node:assert/strict';
import test from 'node:test';
import fs from 'node:fs';
import {employees,createInternalDataHandler} from '../api/internal-data.js';
import {directorySourceBinding,operationalScopeFromRow,DEFAULT_WORKFORCE_STATUS,WORKFORCE_STATUSES} from '../lib/workforce-operational-scope.js';
function mock(){const calls=[];return{calls,async query(statement,values=[]){calls.push({statement,values});if(statement.includes('AS "totalContracts"'))return[{totalContracts:17,totalPeople:15,activeContracts:12,activePeople:10,payrollIncluded:9,activeOutsidePayroll:3,inactiveContracts:4,stateErrorContracts:1,unknownContracts:0,multipleActiveContracts:4,multipleActivePeople:2,lastClosedContracts:11,lastClosedMonth:'2026-07-01',sourceCutoffFrom:'2026-08-06T18:15:21Z',sourceCutoffTo:'2026-08-06T18:15:21Z',snapshotFrom:'2026-08-31',snapshotTo:'2026-08-31'}];if(statement.includes('SELECT count(*)::int AS total FROM directory'))return[{total:12}];if(statement.includes('SELECT * FROM directory'))return[{contractId:'00000000-0000-4000-8000-000000000001',nombre:'PERSONA QA',legajo:'00001',sourceSystem:'GRH',sourceBatchId:'internal-source',sourceCutoff:'2026-08-06'}];return[]}}}
for(const [input,expected] of [[undefined,'administrative_active'],['','administrative_active'],['active','administrative_active'],['all','all'],['inactive','inactive'],['last_closed','last_closed'],['multiple_active','multiple_active'],['state_error','state_error']])test('directory cohort '+String(input),async()=>{const sql=mock();const result=await employees(sql,{query:{status:input,includeFacets:'0'}});assert.equal(result.status,200);assert.equal(result.payload.operational.selectedStatus,expected);const query=sql.calls.find(x=>x.statement.includes('SELECT count(*)::int AS total FROM directory')).statement.split('SELECT count(*)::int AS total FROM directory')[1];if(expected==='administrative_active')assert.match(query,/activo IS TRUE/);if(expected==='all')assert.equal(query.trim(),'');if(expected==='last_closed')assert.match(query,/closed_contracts/);if(expected==='multiple_active')assert.match(query,/multiple_active_people/);if(expected==='state_error')assert.match(query,/state_error/)});
test('dates and counts are source driven, absent is not zero',()=>{const a=operationalScopeFromRow();assert.equal(a.activeContracts,null);assert.equal(a.sourceCutoffTo,null);assert.equal(a.currentCensusCertified,false);assert.equal(a.payrollEligibilityCertified,false);assert.equal(operationalScopeFromRow({activeContracts:0}).activeContracts,0);for(const bad of [-1,NaN,Infinity,'wrong',1.5])assert.equal(operationalScopeFromRow({activeContracts:bad}).activeContracts,null);assert.equal(operationalScopeFromRow({sourceCutoffTo:new Date('2026-08-06T00:00Z')}).sourceCutoffTo,'2026-08-06T00:00:00.000Z')});
test('certified source restriction, pagination and search are parameters',async()=>{const sql=mock();const source={database:'test_source',companyId:7};const r=await employees(sql,{query:{search:"x' OR 1=1 --",status:'all',page:'2',limit:'20'}},source);assert.equal(r.status,200);assert.equal(r.payload.data[0].sourceBatchId,undefined);for(const c of sql.calls){assert.match(c.statement,/source_batch.source_database=\$1::text/);assert.match(c.statement,/legacy_company_id=\$2::bigint/);assert.deepEqual(c.values.slice(0,2),['test_source',7]);assert.ok(!c.statement.includes("x' OR 1=1 --"))}const row=sql.calls.find(x=>x.statement.includes('SELECT * FROM directory'));assert.deepEqual(row.values.slice(-2),[20,20]);assert.equal(r.payload.operational.activeContracts,12)});
test('invalid enum never reaches database',async()=>{const sql=mock();assert.equal((await employees(sql,{query:{status:'paid;DROP'}})).status,400);assert.equal(sql.calls.length,0)});
test('directory binding rejects incomplete config and unsafe names',()=>{assert.equal(directorySourceBinding({}),null);assert.deepEqual(directorySourceBinding({FRIENDLY_GRH_SOURCE_DATABASE:'grh_qa',FRIENDLY_GRH_COMPANY_ID:'7'}),{database:'grh_qa',companyId:7});for(const env of [{FRIENDLY_GRH_COMPANY_ID:7},{FRIENDLY_GRH_SOURCE_DATABASE:'db'},{FRIENDLY_GRH_SOURCE_DATABASE:'db;bad',FRIENDLY_GRH_COMPANY_ID:7}])assert.throws(()=>directorySourceBinding(env))});
test('errors do not belong to active cohort and inactive override is explicit',async()=>{const sql=mock();await employees(sql,{query:{}});const s=sql.calls[0].statement;assert.match(s,/CASE WHEN contract.status IN \('inactive','state_error'\)/);assert.match(s,/contract.status = 'active' AND latest_status.administrative_status IN/);const active=s.split("contract.status = 'active' AND")[1].split('AS activo')[0];assert.ok(!active.includes('state_error'));assert.match(s,/validation_state='published'/);assert.match(s,/legacy_import_run_id IS NOT NULL/)});
test('last closed counts unique contracts across runs not sum of rows',async()=>{const sql=mock();await employees(sql,{query:{status:'last_closed'}});assert.match(sql.calls[0].statement,/SELECT DISTINCT f.employment_contract_id/);assert.match(sql.calls[0].statement,/r.closure_status='closed'/);assert.match(sql.calls[0].statement,/r.source_batch_id=f.source_batch_id/)});
test('all queries are read-only, no real headcount constants in source',async()=>{const sql=mock();await employees(sql,{query:{}});for(const q of sql.calls)assert.doesNotMatch(q.statement,/\b(?:INSERT|DELETE|UPDATE|TRUNCATE|ALTER)\b/i);const code=fs.readFileSync('lib/workforce-operational-scope.js','utf8')+fs.readFileSync('assets/workforce-operations.js','utf8');assert.doesNotMatch(code,/\b(?:882|814|854|856|880)\b/)});
test('markup default and clearing both select active, history explicit',()=>{const html=fs.readFileSync('internal-dashboard.html','utf8');assert.match(html,/<option value="administrative_active" selected>/);assert.match(html,/status: 'administrative_active', crosswalk/);assert.match(html,/els.statusFilter.value = 'administrative_active'/);assert.match(html,/id="workforceWorkspace"/);assert.match(html,/data-workforce-status="inactive"/);assert.ok(WORKFORCE_STATUSES.includes(DEFAULT_WORKFORCE_STATUS))});
test('access gateway is still mandatory for directory, no SQL on denial',async()=>{let queried=false;const handler=createInternalDataHandler({requireAccess:async()=>null,getSql:async()=>{queried=true;return mock()}});const res={setHeader(){},status(){return this},json(){return this}};await handler({method:'GET',query:{resource:'employees'}},res);assert.equal(queried,false)});
