import test from 'node:test';import assert from 'node:assert/strict';
import {createZk40Receiver} from '../api/attendance-zk40.js';
import {zk40Hash} from '../lib/internal-zk40-reception.js';
const token='q'.repeat(43),release='a'.repeat(40),connector='qa-zk40-connector';
const tid='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',mid='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',sid='cccccccc-cccc-4ccc-8ccc-cccccccccccc';
function body(){const data=Buffer.alloc(40,1),rh=zk40Hash(data),sh='a'.repeat(64);return{version:'zk40-delivery.v1',serial:'SYNTHETIC-CLOCK-01',batchId:zk40Hash(sh+':'+rh),snapshotSha256:sh,recordsSha256:rh,snapshotRecordCount:1,totalRecords:1,partStart:0,capturedAt:'2026-09-13T09:00:00.000Z',partSha256:rh,ordinals:[1],recordsBase64:data.toString('base64')};}
function request(){return{method:'POST',headers:{authorization:'Bearer '+token,'x-clock-connector':connector,'content-type':'application/json'},query:{},body:body()};}
function res(){return{headers:{},setHeader(k,v){this.headers[k]=v;},status(n){this.code=n;return this;},json(p){this.payload=p;return this;}};}
for(const tweak of [r=>r.method='GET',r=>delete r.headers.authorization,r=>r.headers.authorization='Bearer short',r=>r.headers.origin='https://example.invalid',r=>r.headers['content-type']='text/plain',r=>r.query={tenant:tid},r=>r.body={...r.body,secret:'x'},r=>r.headers['content-length']='65537'])test('invalid HTTP request reaches no SQL '+tweak.toString(),async()=>{let calls=0;const r=request();tweak(r);const s=res();await createZk40Receiver({env:{INTERNAL_CERTIFIED_DATA_CONTRACT_SHA:release},getSql:async()=>calls++})(r,s);assert.equal(calls,0);assert.ok([400,401,403,405,413,415].includes(s.code));assert.match(s.headers['Cache-Control'],/no-store/);});
test('bounded reader checks streamed bytes not only the Content-Length',async()=>{const r=request();delete r.body;r[Symbol.asyncIterator]=async function*(){yield ' '.repeat(65537);};const s=res();let calls=0;await createZk40Receiver({env:{INTERNAL_CERTIFIED_DATA_CONTRACT_SHA:release},getSql:async()=>calls++})(r,s);assert.equal(s.code,413);assert.equal(calls,0);});
test('handler hashes token and forwards approved source, never raw token to SQL',async()=>{const r=request(),s=res();await createZk40Receiver({env:{INTERNAL_CERTIFIED_DATA_CONTRACT_SHA:release},getSql:async()=>({}),receive:async(_sql,c,h,p,v)=>{assert.equal(c,connector);assert.equal(h,zk40Hash(token));assert.deepEqual(p,r.body);assert.equal(v,release);return{synthetic:true};}})(r,s);assert.equal(s.code,200);assert.ok(!JSON.stringify(s.payload).includes(token));});
test('missing certified data contract never selects a DB connection',async()=>{let calls=0;const s=res();await createZk40Receiver({env:{},getSql:async()=>calls++})(request(),s);assert.equal(calls,0);assert.equal(s.code,503);});
for(const tweak of [r=>r.headers.Authorization=r.headers.authorization,r=>r.headers.authorization=[r.headers.authorization],r=>r.rawHeaders=['Authorization',r.headers.authorization,'AUTHORIZATION',r.headers.authorization],r=>r.headers['x-clock-connector']=['duplicate'],r=>r.headers['content-length']='-1'])test('ambiguous headers fail before database '+tweak,async()=>{let calls=0;const q=request();tweak(q);const s=res();await createZk40Receiver({env:{INTERNAL_CERTIFIED_DATA_CONTRACT_SHA:release},getSql:async()=>calls++})(q,s);assert.ok(s.code>=400);assert.equal(calls,0);});
test('mixed-case single headers are accepted, duplicates are not',async()=>{const q=request();q.headers.Authorization=q.headers.authorization;delete q.headers.authorization;const s=res();let calls=0;await createZk40Receiver({env:{INTERNAL_CERTIFIED_DATA_CONTRACT_SHA:release},getSql:async()=>({}),receive:async()=>{calls++;return {};}})(q,s);assert.equal(s.code,200);assert.equal(calls,1);});
test('body overflow stops reading without waiting for the rest of a stream',async()=>{const q=request();delete q.body;let chunks=0;q[Symbol.asyncIterator]=async function*(){chunks++;yield Buffer.alloc(65537);chunks++;throw Error('must not read second chunk');};const s=res();await createZk40Receiver({getSql:async()=>assert.fail('SQL')})(q,s);assert.equal(s.code,413);assert.equal(chunks,1);});
