import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {validateZk40Payload,assertZk40Receipt,zk40Hash,receiveZk40} from '../lib/internal-zk40-reception.js';
const uuid='a1111111-1111-4111-8111-111111111111',sha='a'.repeat(40);
function payload(){const bytes=Buffer.alloc(40,1),rh=zk40Hash(bytes),sh='a'.repeat(64);return {version:'zk40-delivery.v1',serial:'SYNTHETIC-CLOCK-01',batchId:zk40Hash(sh+':'+rh),snapshotSha256:sh,recordsSha256:rh,totalRecords:1,partStart:0,snapshotRecordCount:1,capturedAt:'2026-09-13T09:00:00.000Z',ordinals:[1],partSha256:rh,recordsBase64:bytes.toString('base64')};}
function receipt(p){return {version:'zk40-receipt.v1',serial:p.serial,receiptId:uuid,batchId:p.batchId,partStart:p.partStart,partSha256:p.partSha256,snapshotSha256:p.snapshotSha256,count:1,newCanonical:1,duplicates:0,observed:0,receivedAt:'2026-09-13T09:10:00.000Z',persisted:true,payrollModified:false,replayed:false};}
test('part and receipt obey receiver contract',()=>{const p=payload(),r=receipt(p);assert.equal(validateZk40Payload(p),p);assert.equal(assertZk40Receipt(r,p),r);});
for(const change of [{tenantId:uuid},{serial:'wrong'},{capturedAt:'2026-02-30T09:00:00.000Z'},{capturedAt:'2026-09-13'},{totalRecords:2},{partStart:1},{recordsBase64:'YWJj'},{partSha256:'f'.repeat(64)},{ordinals:[0]},{ordinals:[1,2]},{ordinals:['1']},{snapshotRecordCount:0},{totalRecords:104858},{recordsSha256:'0'.repeat(64)}])test('receiver rejects mutated input '+Object.keys(change),()=>assert.throws(()=>validateZk40Payload({...payload(),...change})));
test('receiver SQL is parameterized and emits only verified counters',async()=>{const p=payload(),r=receipt(p);let called=0;const out=await receiveZk40({query:async(sql,args)=>{called++;assert.match(sql,/attendance_zk40_receive_v1/);assert.equal(args[0],'qa-connector');assert.equal(args[1],'b'.repeat(64));assert.deepEqual(JSON.parse(args[2]),p);assert.equal(args[3],sha);return[{result:r}];}},'qa-connector','b'.repeat(64),p,sha);assert.deepEqual(out,r);assert.equal(called,1);});
for(const [message,status] of [['ZK40_AUTH_DENIED',401],['ZK40_BUSY',409],['ZK40_PAYLOAD_INVALID',400],['ZK40_IDEMPOTENCY_CONFLICT',409],['ZK40_BINDING_REQUIRED',503],['unrecognized private error with DNI',503]])test('database failure does not leak payload '+message.split(' ')[0],async()=>{await assert.rejects(receiveZk40({query:async()=>{throw Error(message);}},'qa-connector','b'.repeat(64),payload(),sha),e=>e.status===status&&!e.message.includes('DNI'));});
for(const patch of [{serial:'SYNTHETIC-CLOCK-02'},{persisted:false},{payrollModified:true},{count:2},{version:'pm10-receipt.v1'},{newCanonical:-1},{receivedAt:'invalid'},{secret:'must not leak'}])test('receipt validation '+Object.keys(patch),()=>{const p=payload();assert.throws(()=>assertZk40Receipt({...receipt(p),...patch},p));});
test('last part of 501 records preserves one source ordinal and exact wire hash',()=>{const p=payload();p.totalRecords=501;p.snapshotRecordCount=501;p.partStart=500;p.ordinals=[501];p.recordsSha256='d'.repeat(64);p.batchId=zk40Hash(p.snapshotSha256+':'+p.recordsSha256);assert.equal(validateZk40Payload(p),p);assert.throws(()=>validateZk40Payload({...p,ordinals:[502]}));});
test('replayed receipt is accepted but still checks its device',()=>{const p=payload();assert.equal(assertZk40Receipt({...receipt(p),replayed:true},p).replayed,true);assert.throws(()=>assertZk40Receipt({...receipt(p),replayed:true,serial:'OTHER-CLOCK'},p));});
test('migration gates each serial by enrolled tenant, device, connector and site; never activates devices',()=>{const s=fs.readFileSync('scripts/migrations/070-zk40-multiclock-reception.sql','utf8');assert.match(s,/ZK40_PREREQUISITE_DRIFT/);for(const field of ['e.tenant_id=c.tenant_id','e.device_id=d.id','e.connector_id=c.id','e.serial_number=d.serial_number','e.site_id=d.site_id'])assert.ok(s.includes(field));assert.match(s,/ENABLE ROW LEVEL SECURITY/);assert.match(s,/BEFORE TRUNCATE/);assert.doesNotMatch(s,/UPDATE public.attendance_device|INSERT INTO public.attendance_device|ALTER.*DISABLE ROW LEVEL|CREATE.*TABLE.*fingerprint/i);});
