-- Frozen sources and immutable technical results. No posting, annulment,
-- confirmation or payment. No role grants and no legacy identity resolver.
DO $$ BEGIN
 IF to_regclass('public.own_payroll_run_capture') IS NOT NULL OR to_regclass('public.own_payroll_run_result') IS NOT NULL THEN RAISE EXCEPTION 'OWN_RUN_ALREADY_INSTALLED';END IF;
 IF EXISTS(SELECT 1 FROM pg_proc WHERE pronamespace='public'::regnamespace AND proname LIKE 'own_run_%') THEN RAISE EXCEPTION 'OWN_RUN_OBJECT_CONFLICT';END IF;
 IF to_regprocedure('public.own_program_bootstrap_v1(jsonb)') IS NULL OR to_regprocedure('public.native_employment_lifecycle_range_v1(jsonb,uuid,date,date,boolean)') IS NULL OR to_regprocedure('public.payroll_novelty_export_v2(jsonb,uuid)') IS NULL OR to_regprocedure('public.payroll_fixed_registry_export_v1(jsonb,date,text)') IS NULL THEN RAISE EXCEPTION 'OWN_RUN_PREREQUISITE';END IF;
 IF EXISTS(SELECT 1 FROM public.iam_capability WHERE capability_key IN('payroll.calculation.read','payroll.calculation.nominal.read','payroll.calculation.prepare')) THEN RAISE EXCEPTION 'OWN_RUN_CAPABILITY_CONFLICT';END IF;
END $$;
INSERT INTO public.iam_capability(capability_key,label,description,scope_kind,sensitivity) VALUES
 ('payroll.calculation.read','Consultar corridas propias','Metadatos de corridas técnicas propias, sin datos nominales.','tenant','standard'),
 ('payroll.calculation.nominal.read','Consultar resultados propios','Fuentes y resultados nominales de corridas técnicas propias.','tenant','privileged'),
 ('payroll.calculation.prepare','Calcular corrida propia','Capturar fuentes y conservar un cálculo técnico. No confirma, anula, liquida definitivamente ni paga.','tenant','privileged');
CREATE TABLE public.own_payroll_run_capture(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES public.platform_tenant(id),source_binding_id uuid NOT NULL,
 actor_membership_id uuid NOT NULL,actor_person_id uuid NOT NULL REFERENCES public.person_identity(id),actor_email text NOT NULL CHECK(actor_email=lower(actor_email)),
 actor_session_id uuid NOT NULL REFERENCES public.tenant_identity_session(id),actor_session_version integer NOT NULL CHECK(actor_session_version>0),release_sha text NOT NULL CHECK(release_sha~'^[a-f0-9]{40}$'),
 request_key uuid NOT NULL CHECK(request_key::text~'^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$'),
 body jsonb NOT NULL CHECK(jsonb_typeof(body)='object' AND octet_length(body::text)<=524288),body_sha256 text NOT NULL CHECK(body_sha256~'^[a-f0-9]{64}$'),
 algorithm_sha256 text NOT NULL CHECK(algorithm_sha256~'^[a-f0-9]{64}$'),payload jsonb NOT NULL CHECK(jsonb_typeof(payload)='object' AND octet_length(payload::text)<=33554432),payload_sha256 text NOT NULL CHECK(payload_sha256~'^[a-f0-9]{64}$'),
 created_at timestamptz NOT NULL DEFAULT clock_timestamp(),UNIQUE(tenant_id,source_binding_id,actor_membership_id,request_key),
 FOREIGN KEY(tenant_id,source_binding_id) REFERENCES public.platform_tenant_source_binding(tenant_id,id),FOREIGN KEY(actor_membership_id,tenant_id) REFERENCES public.tenant_membership(id,tenant_id)
);
CREATE TABLE public.own_payroll_run_result(
 capture_id uuid PRIMARY KEY REFERENCES public.own_payroll_run_capture(id),algorithm_sha256 text NOT NULL CHECK(algorithm_sha256~'^[a-f0-9]{64}$'),
 input jsonb NOT NULL CHECK(jsonb_typeof(input)='object' AND octet_length(input::text)<=8388608),result jsonb NOT NULL CHECK(jsonb_typeof(result)='object' AND octet_length(result::text)<=33554432),
 input_sha256 text NOT NULL CHECK(input_sha256~'^[a-f0-9]{64}$'),result_sha256 text NOT NULL CHECK(result_sha256~'^[a-f0-9]{64}$'),recorded_at timestamptz NOT NULL DEFAULT clock_timestamp()
);
ALTER TABLE public.own_payroll_run_capture ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.own_payroll_run_result ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.own_payroll_run_capture,public.own_payroll_run_result FROM PUBLIC,municontrol_actions_runtime_app;
CREATE FUNCTION public.own_run_immutable_v1() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$ BEGIN RAISE EXCEPTION 'OWN_RUN_IMMUTABLE';END $$;
CREATE TRIGGER own_run_capture_immutable BEFORE UPDATE OR DELETE ON public.own_payroll_run_capture FOR EACH ROW EXECUTE FUNCTION public.own_run_immutable_v1();
CREATE TRIGGER own_run_capture_no_truncate BEFORE TRUNCATE ON public.own_payroll_run_capture FOR EACH STATEMENT EXECUTE FUNCTION public.own_run_immutable_v1();
CREATE TRIGGER own_run_result_immutable BEFORE UPDATE OR DELETE ON public.own_payroll_run_result FOR EACH ROW EXECUTE FUNCTION public.own_run_immutable_v1();
CREATE TRIGGER own_run_result_no_truncate BEFORE TRUNCATE ON public.own_payroll_run_result FOR EACH STATEMENT EXECUTE FUNCTION public.own_run_immutable_v1();
CREATE FUNCTION public.own_run_hash_v1(v jsonb) RETURNS text LANGUAGE sql IMMUTABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$ SELECT encode(public.digest(public.native_salary_serialized_v1(v),'sha256'),'hex') $$;
CREATE FUNCTION public.own_run_context_v1(p jsonb,nominal boolean DEFAULT false,write_access boolean DEFAULT false) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE ctx jsonb;k text;BEGIN ctx:=public.native_salary_context_v1(p);
 FOREACH k IN ARRAY CASE WHEN write_access THEN ARRAY['payroll.calculation.read','payroll.calculation.nominal.read','payroll.calculation.prepare','payroll.novelty.read','payroll.novelty.nominal.read','payroll.novelty.export'] WHEN nominal THEN ARRAY['payroll.calculation.read','payroll.calculation.nominal.read','payroll.novelty.read','payroll.novelty.nominal.read','payroll.novelty.export'] ELSE ARRAY['payroll.calculation.read'] END LOOP
  IF NOT public.action_center_context_has_capability(ctx,k) THEN RAISE EXCEPTION 'OWN_RUN_FORBIDDEN';END IF;
 END LOOP;
 IF (nominal OR write_access) AND(ctx->>'actorPersonId' IS NULL OR ctx->>'employmentContractId' IS NULL) THEN RAISE EXCEPTION 'OWN_RUN_EMPLOYMENT_REQUIRED';END IF;
 RETURN ctx||jsonb_build_object('certifiedBindingId',ctx->>'sourceBindingId');END $$;
CREATE FUNCTION public.own_run_lock_v1(ctx jsonb) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
BEGIN IF NOT pg_try_advisory_xact_lock(hashtextextended('own-run:v1:'||(ctx->>'tenantId')||':'||(ctx->>'sourceBindingId'),0)) THEN RAISE EXCEPTION 'OWN_RUN_BUSY';END IF;END $$;
CREATE FUNCTION public.own_run_capacity_v1(extra bigint) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
BEGIN IF NOT pg_try_advisory_xact_lock(hashtextextended('own-run:capacity:v1',0)) THEN RAISE EXCEPTION 'OWN_RUN_BUSY';END IF;
 IF extra>41943040 OR coalesce((SELECT sum(octet_length(payload::text)+octet_length(body::text)) FROM public.own_payroll_run_capture),0)+coalesce((SELECT sum(octet_length(input::text)+octet_length(result::text)) FROM public.own_payroll_run_result),0)+extra>536870912 THEN RAISE EXCEPTION 'OWN_RUN_LIMIT';END IF;END $$;
CREATE FUNCTION public.own_run_saved_v1(r public.own_payroll_run_result) RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
 SELECT CASE WHEN r.capture_id IS NULL THEN 'null'::jsonb ELSE jsonb_build_object('version','own-payroll-saved.v1','id',r.capture_id,'algorithmSha256',r.algorithm_sha256,'inputSha256',r.input_sha256,'resultSha256',r.result_sha256,'input',r.input,'result',r.result,'recordedAt',r.recorded_at) END $$;
CREATE FUNCTION public.own_run_receipt_v1(c public.own_payroll_run_capture,replayed boolean) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE r public.own_payroll_run_result;BEGIN SELECT * INTO r FROM public.own_payroll_run_result WHERE capture_id=c.id;
 RETURN jsonb_build_object('version','own-payroll-run.v1','id',c.id,'key',c.request_key,'body',c.body,'bodySha256',c.body_sha256,'algorithmSha256',c.algorithm_sha256,'payload',c.payload,'payloadSha256',c.payload_sha256,'createdAt',c.created_at,'replayed',replayed,'saved',public.own_run_saved_v1(r));END $$;
CREATE FUNCTION public.own_run_owned_v1(ctx jsonb,c public.own_payroll_run_capture) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
BEGIN IF c.id IS NULL OR c.tenant_id IS DISTINCT FROM(ctx->>'tenantId')::uuid OR c.source_binding_id IS DISTINCT FROM(ctx->>'sourceBindingId')::uuid OR c.actor_membership_id IS DISTINCT FROM(ctx->>'membershipId')::uuid THEN RAISE EXCEPTION 'OWN_RUN_NOT_FOUND';END IF;
 IF c.actor_person_id IS DISTINCT FROM(ctx->>'actorPersonId')::uuid OR c.actor_email IS DISTINCT FROM ctx->>'actorEmail' THEN RAISE EXCEPTION 'OWN_RUN_FORBIDDEN';END IF;END $$;
CREATE FUNCTION public.own_run_fixed_v1(p jsonb,period_date date,contracts uuid[],payroll_type text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE ctx jsonb;list_rows jsonb;export_rows jsonb;token text;month_end date;effects jsonb;
BEGIN ctx:=public.payroll_fixed_registry_context_v1(p,'payroll.novelty.export');PERFORM public.payroll_fixed_registry_lock_v1(ctx);month_end:=(period_date+interval '1 month - 1 day')::date;
 -- Reuse the published092/093 record/identity readers, with an explicit
 -- own-contract scope. Unselected historical records cannot block own hires.
 WITH items AS MATERIALIZED(SELECT public.payroll_fixed_registry_record_json_v1(ctx,n) item FROM public.payroll_fixed_novelty n WHERE n.tenant_id=(ctx->>'tenantId')::uuid AND n.certified_binding_id=(ctx->>'certifiedBindingId')::uuid AND n.employment_contract_id=ANY(contracts))
 SELECT coalesce(jsonb_agg(item ORDER BY item->>'id'),'[]') INTO list_rows FROM items WHERE item#>>'{approved,operation}'='set' AND item#>>'{approved,values,payrollType}'=payroll_type AND (item#>>'{approved,values,validFrom}')::date<=month_end AND ((item#>>'{approved,values,validTo}') IS NULL OR (item#>>'{approved,values,validTo}')::date>=period_date);
 IF jsonb_array_length(list_rows)>500 THEN RAISE EXCEPTION 'OWN_RUN_LIMIT';END IF;
 IF EXISTS(SELECT 1 FROM jsonb_array_elements(list_rows) r WHERE r->>'identityCurrent' IS DISTINCT FROM 'true' OR r#>>'{subject,origin}' IS DISTINCT FROM 'MUNICONTROL') THEN RAISE EXCEPTION 'PAYROLL_FIXED_IDENTITY_CHANGED';END IF;
 IF EXISTS(SELECT 1 FROM jsonb_array_elements(list_rows) r WHERE NOT public.native_employment_lifecycle_range_v1(ctx,(r#>>'{subject,contractId}')::uuid,greatest(period_date,(r#>>'{approved,values,validFrom}')::date),least(month_end,coalesce((r#>>'{approved,values,validTo}')::date,month_end)),true)) THEN RAISE EXCEPTION 'PAYROLL_FIXED_DATES_INVALID';END IF;
 SELECT coalesce(jsonb_agg(jsonb_build_object('recordId',r->>'id','version',(r->>'version')::integer,'proposalId',r#>>'{approved,id}','subject',r->'subject','values',r#>'{approved,values}') ORDER BY r->>'id'),'[]') INTO export_rows FROM jsonb_array_elements(list_rows) r;
 token:=public.own_run_hash_v1(jsonb_build_object('version','own-payroll-fixed-scope.v1','tenantId',ctx->>'tenantId','bindingId',ctx->>'certifiedBindingId','membershipId',ctx->>'membershipId','period',period_date,'contracts',to_jsonb(contracts),'payrollType',payroll_type,'rows',list_rows));effects:=public.payroll_fixed_registry_effects_v1();
 RETURN jsonb_build_object('list',jsonb_build_object('ok',true,'data',jsonb_build_object('version','payroll-fixed-list.v1','periodMonth',to_char(period_date,'YYYY-MM-DD'),'snapshotToken',token,'rows',list_rows,'total',jsonb_array_length(list_rows),'effects',effects)),'export',jsonb_build_object('ok',true,'data',jsonb_build_object('version','payroll-fixed-export.v1','periodMonth',to_char(period_date,'YYYY-MM-DD'),'snapshotToken',token,'rows',export_rows,'total',jsonb_array_length(export_rows),'effects',effects)));END $$;
CREATE FUNCTION public.own_run_bootstrap_v1(p jsonb) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp SET timezone='UTC' AS $$
DECLARE ctx jsonb;rows_json jsonb;BEGIN ctx:=public.own_run_context_v1(p);PERFORM public.own_run_lock_v1(ctx);
 SELECT coalesce(jsonb_agg(jsonb_build_object('id',c.id,'key',c.request_key,'period',c.body->>'period','liquidationType',c.body->>'liquidationType','selectionKind',c.body#>>'{selection,kind}','selectionValueCount',jsonb_array_length(c.body#>'{selection,values}'),'createdAt',c.created_at,'state',CASE WHEN r.capture_id IS NULL THEN 'captured' ELSE 'calculated' END,'inputSha256',r.input_sha256,'resultSha256',r.result_sha256) ORDER BY c.created_at,c.id),'[]') INTO rows_json FROM public.own_payroll_run_capture c LEFT JOIN public.own_payroll_run_result r ON r.capture_id=c.id WHERE c.tenant_id=(ctx->>'tenantId')::uuid AND c.source_binding_id=(ctx->>'sourceBindingId')::uuid AND c.actor_membership_id=(ctx->>'membershipId')::uuid AND c.actor_person_id IS NOT DISTINCT FROM(ctx->>'actorPersonId')::uuid AND c.actor_email=ctx->>'actorEmail';
 IF jsonb_array_length(rows_json)>1000 THEN RAISE EXCEPTION 'OWN_RUN_LIMIT';END IF;
 RETURN jsonb_build_object('version','own-payroll-bootstrap.v1','scopeVersion',public.native_salary_scope_v1(ctx),'programVersion',public.own_program_current_v1(ctx)->>'version','canCalculate',ctx->>'actorPersonId' IS NOT NULL AND ctx->>'employmentContractId' IS NOT NULL AND public.action_center_context_has_capability(ctx,'payroll.calculation.prepare') AND public.action_center_context_has_capability(ctx,'payroll.calculation.nominal.read') AND public.action_center_context_has_capability(ctx,'payroll.novelty.read') AND public.action_center_context_has_capability(ctx,'payroll.novelty.nominal.read') AND public.action_center_context_has_capability(ctx,'payroll.novelty.export'),'runs',rows_json,'complete',true);END $$;
CREATE FUNCTION public.own_run_attempt_v1(p jsonb,key uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp SET timezone='UTC' AS $$
DECLARE ctx jsonb;c public.own_payroll_run_capture;BEGIN ctx:=public.own_run_context_v1(p,true);SELECT * INTO c FROM public.own_payroll_run_capture WHERE tenant_id=(ctx->>'tenantId')::uuid AND source_binding_id=(ctx->>'sourceBindingId')::uuid AND actor_membership_id=(ctx->>'membershipId')::uuid AND request_key=key;PERFORM public.own_run_owned_v1(ctx,c);RETURN public.own_run_receipt_v1(c,true);END $$;
CREATE FUNCTION public.own_run_capture_v1(p jsonb,body jsonb,key uuid,algorithm text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp SET timezone='UTC' AS $$
DECLARE ctx jsonb;prior public.own_payroll_run_capture;c public.own_payroll_run_capture;reg record;s jsonb;program_state jsonb;employees jsonb:='[]';ids uuid[]:='{}';batches jsonb:='[]';b record;batch_data jsonb;list_value jsonb;export_value jsonb;list_rows jsonb;export_rows jsonb;population jsonb;payload_value jsonb;inventory jsonb;first_date date;last_date date;kind text;v text;fingerprint text;field text;
BEGIN ctx:=public.own_run_context_v1(p,true,true);
 IF NOT public.own_program_exact_v1(body,ARRAY['period','liquidationType','selection','scopeVersion','programVersion','populationDomain']) OR NOT public.own_program_exact_v1(body->'selection',ARRAY['kind','values']) OR octet_length(body::text)>524288 THEN RAISE EXCEPTION 'OWN_RUN_INPUT_INVALID';END IF;
 FOREACH field IN ARRAY ARRAY['period','liquidationType','scopeVersion','programVersion','populationDomain'] LOOP IF jsonb_typeof(body->field) IS DISTINCT FROM 'string' THEN RAISE EXCEPTION 'OWN_RUN_INPUT_INVALID';END IF;END LOOP;
 IF coalesce(body->>'period','')!~'^(19|20)[0-9]{2}-(0[1-9]|1[0-2])$' OR body->>'liquidationType' NOT IN('monthly','first_fortnight','sac','vacation','supplementary','final','other') OR body->>'populationDomain'<>'native_registered' OR coalesce(body->>'scopeVersion','')!~'^[a-f0-9]{64}$' OR coalesce(body->>'programVersion','')!~'^[a-f0-9]{64}$' OR coalesce(algorithm,'')!~'^[a-f0-9]{64}$' OR key IS NULL OR key::text!~'^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$' THEN RAISE EXCEPTION 'OWN_RUN_INPUT_INVALID';END IF;
 kind:=body#>>'{selection,kind}';IF jsonb_typeof(body#>'{selection,kind}') IS DISTINCT FROM 'string' OR kind NOT IN('all','contracts','agreements','departments') OR jsonb_typeof(body#>'{selection,values}') IS DISTINCT FROM 'array' OR jsonb_array_length(body#>'{selection,values}')>10000 THEN RAISE EXCEPTION 'OWN_RUN_SELECTION_INVALID';END IF;
 IF (kind='all')<>(jsonb_array_length(body#>'{selection,values}')=0) OR EXISTS(SELECT 1 FROM jsonb_array_elements(body#>'{selection,values}') x WHERE jsonb_typeof(x)<>'string' OR x#>>'{}'!~CASE WHEN kind='contracts' THEN '^[a-f0-9]{8}-[a-f0-9]{4}-[1-5][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$' ELSE '^[0-9]{1,9}$' END) OR (SELECT count(*)<>count(DISTINCT x) FROM jsonb_array_elements_text(body#>'{selection,values}') x) OR body#>'{selection,values}' IS DISTINCT FROM(SELECT coalesce(jsonb_agg(x ORDER BY x COLLATE "C"),'[]') FROM jsonb_array_elements_text(body#>'{selection,values}') x) THEN RAISE EXCEPTION 'OWN_RUN_SELECTION_INVALID';END IF;
 PERFORM public.own_run_lock_v1(ctx);fingerprint:=public.own_run_hash_v1(body);
 SELECT * INTO prior FROM public.own_payroll_run_capture WHERE tenant_id=(ctx->>'tenantId')::uuid AND source_binding_id=(ctx->>'sourceBindingId')::uuid AND actor_membership_id=(ctx->>'membershipId')::uuid AND request_key=key;
 IF FOUND THEN PERFORM public.own_run_owned_v1(ctx,prior);IF prior.body<>body OR prior.body_sha256<>fingerprint THEN RAISE EXCEPTION 'OWN_RUN_IDEMPOTENCY_REUSE';END IF;RETURN public.own_run_receipt_v1(prior,true);END IF;
 IF body->>'scopeVersion'<>public.native_salary_scope_v1(ctx) THEN RAISE EXCEPTION 'OWN_RUN_SCOPE_CHANGED';END IF;
 -- SHARE locks prevent concurrent source changes during this read-committed
 -- transaction. Existing advisory locks remain effective. No source mutation.
 LOCK TABLE public.person_identity,public.employment_contract,public.native_employee_registration,public.native_employment_change_review,public.native_employment_lifecycle_review,public.native_salary_event,public.own_payroll_program_event,public.payroll_novelty_batch,public.payroll_novelty_row,public.payroll_novelty_issue,public.payroll_novelty_event,public.payroll_fixed_novelty,public.payroll_fixed_novelty_event IN SHARE MODE NOWAIT;
 program_state:=public.own_program_bootstrap_v1(p);
 IF body->>'programVersion'<>program_state#>>'{program,version}' THEN RAISE EXCEPTION 'OWN_RUN_PROGRAM_CHANGED';END IF;
 IF (program_state#>>'{program,revision}')::integer<1 OR program_state#>>'{program,salaryVersion}' IS DISTINCT FROM program_state#>>'{salaryCatalog,version}' THEN RAISE EXCEPTION 'OWN_RUN_PROGRAM_REQUIRED';END IF;
 first_date:=(body->>'period'||'-01')::date;last_date:=(first_date+interval '1 month - 1 day')::date;
 FOR reg IN SELECT n.*,n.contract_id AS employment_contract_id,ec.legacy_legajo,ec.agreement_code,ec.category_code,ec.sector_source_id FROM public.native_employee_registration n JOIN public.employment_contract ec ON ec.id=n.contract_id WHERE n.tenant_id=(ctx->>'tenantId')::uuid AND n.source_binding_id=(ctx->>'sourceBindingId')::uuid AND ec.tenant_id=n.tenant_id AND ec.source_system='MUNICONTROL' AND ec.source_batch_id IS NULL AND(kind='all' OR kind='contracts' AND body#>'{selection,values}' ? ec.id::text OR kind='agreements' AND body#>'{selection,values}' ? ec.agreement_code OR kind='departments' AND body#>'{selection,values}' ? ec.sector_source_id) ORDER BY ec.id LOOP
  IF NOT public.native_employment_lifecycle_range_v1(ctx,reg.employment_contract_id,first_date,last_date,false) THEN IF kind='contracts' THEN RAISE EXCEPTION 'OWN_RUN_SELECTION_INVALID';END IF;CONTINUE;END IF;
  IF NOT public.native_employment_lifecycle_range_v1(ctx,reg.employment_contract_id,first_date,last_date,true) THEN RAISE EXCEPTION 'OWN_RUN_PRORATION_REQUIRED';END IF;
  -- Current classification is not a historical reconstruction. Never apply
  -- a later registration/correction retroactively to an earlier payroll.
  IF (reg.created_at AT TIME ZONE 'America/Argentina/Mendoza')::date>last_date OR EXISTS(SELECT 1 FROM public.native_employment_change_review r WHERE r.contract_id=reg.employment_contract_id AND r.decision='approve' AND (r.reviewed_at AT TIME ZONE 'America/Argentina/Mendoza')::date>=first_date) THEN RAISE EXCEPTION 'OWN_RUN_HISTORY_REQUIRED';END IF;
  s:=public.payroll_fixed_registry_subject_by_contract_v1(ctx,reg.employment_contract_id,true)->'subject';
  IF s->>'origin'<>'MUNICONTROL' OR s->>'contractId'<>reg.employment_contract_id::text OR s->>'legajo'<>reg.legacy_legajo OR coalesce(reg.agreement_code,'')!~'^[0-9]{1,9}$' OR coalesce(reg.category_code,'')!~'^[0-9]{1,9}$' OR coalesce(reg.sector_source_id,'')!~'^[0-9]{1,9}$' THEN RAISE EXCEPTION 'OWN_RUN_SELECTION_INVALID';END IF;
  ids:=array_append(ids,reg.employment_contract_id);employees:=employees||jsonb_build_array(jsonb_build_object('contractId',reg.employment_contract_id,'employeeNumber',reg.legacy_legajo,'agreementCode',reg.agreement_code,'categoryCode',reg.category_code,'departmentCode',reg.sector_source_id,'identityToken',s->>'identityToken','origin','MUNICONTROL'));
  IF cardinality(ids)>10000 THEN RAISE EXCEPTION 'OWN_RUN_LIMIT';END IF;
 END LOOP;
 IF cardinality(ids)=0 OR kind='contracts' AND cardinality(ids)<>jsonb_array_length(body#>'{selection,values}') OR kind IN('agreements','departments') AND EXISTS(SELECT 1 FROM jsonb_array_elements_text(body#>'{selection,values}') chosen WHERE NOT EXISTS(SELECT 1 FROM jsonb_array_elements(employees) e WHERE e->>CASE kind WHEN 'agreements' THEN 'agreementCode' ELSE 'departmentCode' END=chosen)) THEN RAISE EXCEPTION 'OWN_RUN_SELECTION_INVALID';END IF;
 population:=jsonb_build_object('complete',true,'version',public.own_run_hash_v1(employees),'employees',employees);
 FOR b IN SELECT nb.id FROM public.payroll_novelty_batch nb WHERE nb.tenant_id=(ctx->>'tenantId')::uuid AND nb.certified_binding_id=(ctx->>'sourceBindingId')::uuid AND nb.period_month=first_date AND nb.payroll_type=body->>'liquidationType' AND nb.status='approved' AND EXISTS(SELECT 1 FROM public.payroll_novelty_row nr WHERE nr.batch_id=nb.id AND nr.employment_contract_id=ANY(ids)) ORDER BY nb.id LOOP
  batch_data:=public.payroll_novelty_export_v2(p,b.id)->'data';
  IF batch_data IS NULL OR batch_data->>'contractVersion'<>'payroll-novelty-batch.v2' OR EXISTS(SELECT 1 FROM jsonb_array_elements(batch_data->'rows') r WHERE NOT((r->>'employmentContractId')::uuid=ANY(ids))) THEN RAISE EXCEPTION 'OWN_RUN_SELECTION_INVALID';END IF;
  batches:=batches||jsonb_build_array(batch_data);IF jsonb_array_length(batches)>10000 THEN RAISE EXCEPTION 'OWN_RUN_LIMIT';END IF;
 END LOOP;
 s:=public.own_run_fixed_v1(p,first_date,ids,body->>'liquidationType');list_value:=s#>'{list,data}';export_value:=s#>'{export,data}';
 inventory:=jsonb_build_object('populationDomain','native_registered','departmentSource','employment_contract.sector_source_id','monthlyBatches',jsonb_array_length(batches),'fixedScope','approved_selected_native','fixedSnapshotToken',list_value->>'snapshotToken','fixedListCount',list_value->'total','fixedExportCount',export_value->'total','fixedExportSha256',public.own_run_hash_v1(export_value));
 payload_value:=jsonb_build_object('programState',program_state,'population',population,'monthly',jsonb_build_object('complete',true,'batches',batches),'fixed',jsonb_build_object('list',jsonb_build_object('ok',true,'data',list_value),'export',jsonb_build_object('ok',true,'data',export_value)),'period',body->>'period','liquidationType',body->>'liquidationType','selection',body->'selection','sourceInventory',inventory);
 IF octet_length(payload_value::text)+octet_length(body::text)+8192>4194304 OR (SELECT count(*) FROM public.own_payroll_run_capture WHERE tenant_id=(ctx->>'tenantId')::uuid AND source_binding_id=(ctx->>'sourceBindingId')::uuid)>=1000 THEN RAISE EXCEPTION 'OWN_RUN_LIMIT';END IF;
 PERFORM public.own_run_capacity_v1(octet_length(payload_value::text)+octet_length(body::text));
 INSERT INTO public.own_payroll_run_capture(tenant_id,source_binding_id,actor_membership_id,actor_person_id,actor_email,actor_session_id,actor_session_version,release_sha,request_key,body,body_sha256,algorithm_sha256,payload,payload_sha256) VALUES((ctx->>'tenantId')::uuid,(ctx->>'sourceBindingId')::uuid,(ctx->>'membershipId')::uuid,(ctx->>'actorPersonId')::uuid,ctx->>'actorEmail',(p->>'actorSessionId')::uuid,(p->>'actorSessionVersion')::integer,p->>'releaseSha',key,body,fingerprint,algorithm,payload_value,public.own_run_hash_v1(payload_value)) RETURNING * INTO c;
 RETURN public.own_run_receipt_v1(c,false);END $$;
CREATE FUNCTION public.own_run_complete_v1(p jsonb,capture uuid,input_value jsonb,result_value jsonb,algorithm text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp SET timezone='UTC' AS $$
DECLARE ctx jsonb;c public.own_payroll_run_capture;r public.own_payroll_run_result;ih text;rh text;BEGIN ctx:=public.own_run_context_v1(p,true,true);PERFORM public.own_run_lock_v1(ctx);
 SELECT * INTO c FROM public.own_payroll_run_capture WHERE id=capture;PERFORM public.own_run_owned_v1(ctx,c);
 IF algorithm IS DISTINCT FROM c.algorithm_sha256 THEN RAISE EXCEPTION 'OWN_RUN_ENGINE_CHANGED';END IF;
 IF NOT public.own_program_exact_v1(input_value,ARRAY['version','period','liquidationType','selection','sourceVersions','populationComplete','totalsPrecision','employees','rules']) OR NOT public.own_program_exact_v1(result_value,ARRAY['version','period','liquidationType','selection','sourceVersions','employeeCount','rowCount','rows','employeeTotals','payrollCalculated','payrollPosted','municipalApprovalVerified','paymentExecuted']) OR input_value->>'version'<>'own-payroll-input.v1' OR result_value->>'version'<>'own-payroll-result.v1' OR input_value->>'period' IS DISTINCT FROM c.body->>'period' OR input_value->>'liquidationType' IS DISTINCT FROM c.body->>'liquidationType' OR input_value->'selection' IS DISTINCT FROM c.body->'selection' OR result_value->>'period' IS DISTINCT FROM input_value->>'period' OR result_value->>'liquidationType' IS DISTINCT FROM input_value->>'liquidationType' OR result_value->'selection' IS DISTINCT FROM input_value->'selection' OR result_value->'sourceVersions' IS DISTINCT FROM input_value->'sourceVersions' OR input_value->'populationComplete' IS DISTINCT FROM 'true'::jsonb OR result_value->'payrollCalculated' IS DISTINCT FROM 'true'::jsonb OR result_value->'payrollPosted' IS DISTINCT FROM 'false'::jsonb OR result_value->'municipalApprovalVerified' IS DISTINCT FROM 'false'::jsonb OR result_value->'paymentExecuted' IS DISTINCT FROM 'false'::jsonb THEN RAISE EXCEPTION 'OWN_RUN_INPUT_INVALID';END IF;
 IF octet_length(input_value::text)+octet_length(result_value::text)+octet_length(c.payload::text)+octet_length(c.body::text)+8192>4194304 THEN RAISE EXCEPTION 'OWN_RUN_LIMIT';END IF;
 IF input_value->'rules' IS DISTINCT FROM c.payload#>'{programState,program,definition,rules}' OR input_value->'totalsPrecision' IS DISTINCT FROM c.payload#>'{programState,program,definition,totalsPrecision}' OR input_value#>>'{sourceVersions,population}' IS DISTINCT FROM c.payload#>>'{population,version}' OR input_value#>>'{sourceVersions,rules}' IS DISTINCT FROM public.own_run_hash_v1(jsonb_build_object('program',c.payload#>'{programState,program}','salary',c.payload#>'{programState,salaryCatalog}')) OR input_value#>>'{sourceVersions,novelties}' IS DISTINCT FROM public.own_run_hash_v1(jsonb_build_object('monthly',c.payload->'monthly','fixed',c.payload#>'{fixed,export,data}')) THEN RAISE EXCEPTION 'OWN_RUN_INPUT_INVALID';END IF;
 IF jsonb_typeof(input_value->'employees') IS DISTINCT FROM 'array' OR jsonb_typeof(result_value->'rows') IS DISTINCT FROM 'array' OR jsonb_typeof(result_value->'employeeTotals') IS DISTINCT FROM 'array' THEN RAISE EXCEPTION 'OWN_RUN_INPUT_INVALID';END IF;
 IF (SELECT jsonb_agg(e->>'contractId' ORDER BY e->>'contractId') FROM jsonb_array_elements(input_value->'employees') e) IS DISTINCT FROM(SELECT jsonb_agg(e->>'contractId' ORDER BY e->>'contractId') FROM jsonb_array_elements(c.payload#>'{population,employees}') e) OR result_value->'employeeCount' IS DISTINCT FROM to_jsonb(jsonb_array_length(input_value->'employees')) OR result_value->'employeeCount' IS DISTINCT FROM to_jsonb(jsonb_array_length(result_value->'employeeTotals')) OR result_value->'rowCount' IS DISTINCT FROM to_jsonb(jsonb_array_length(result_value->'rows')) OR EXISTS(SELECT 1 FROM jsonb_array_elements(result_value->'rows') row_value WHERE NOT EXISTS(SELECT 1 FROM jsonb_array_elements(input_value->'employees') e WHERE e->>'contractId'=row_value->>'contractId')) THEN RAISE EXCEPTION 'OWN_RUN_INPUT_INVALID';END IF;
 ih:=public.own_run_hash_v1(input_value);rh:=public.own_run_hash_v1(result_value);SELECT * INTO r FROM public.own_payroll_run_result WHERE capture_id=c.id;
 IF FOUND THEN IF r.input_sha256<>ih OR r.result_sha256<>rh OR r.input<>input_value OR r.result<>result_value THEN RAISE EXCEPTION 'OWN_RUN_RESULT_CONFLICT';END IF;RETURN public.own_run_saved_v1(r);END IF;
 PERFORM public.own_run_capacity_v1(octet_length(input_value::text)+octet_length(result_value::text));
 INSERT INTO public.own_payroll_run_result(capture_id,algorithm_sha256,input,result,input_sha256,result_sha256) VALUES(c.id,algorithm,input_value,result_value,ih,rh) RETURNING * INTO r;RETURN public.own_run_saved_v1(r);END $$;
DO $$ DECLARE fn record;BEGIN FOR fn IN SELECT oid::regprocedure signature FROM pg_proc WHERE pronamespace='public'::regnamespace AND proname LIKE 'own_run_%' LOOP EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC,municontrol_actions_runtime_app',fn.signature);END LOOP;END $$;
GRANT EXECUTE ON FUNCTION public.own_run_bootstrap_v1(jsonb),public.own_run_attempt_v1(jsonb,uuid),public.own_run_capture_v1(jsonb,jsonb,uuid,text),public.own_run_complete_v1(jsonb,uuid,jsonb,jsonb,text) TO municontrol_actions_runtime_app;
