-- Administrative decisions on immutable, calculated own-payroll results.
-- One full selection per atomic event. No posting, period close, payment,
-- employee edits, role assignments, live GRH calls or recalculation.
DO $$ BEGIN
 IF to_regclass('public.own_payroll_liquidation_event') IS NOT NULL OR EXISTS(SELECT 1 FROM pg_proc WHERE pronamespace='public'::regnamespace AND proname LIKE 'own_liquidation_%') OR EXISTS(SELECT 1 FROM public.iam_capability WHERE capability_key='payroll.calculation.approve') THEN RAISE EXCEPTION 'OWN_LIQ_ALREADY_INSTALLED';END IF;
 IF to_regprocedure('public.own_run_receipt_v1(public.own_payroll_run_capture,boolean)') IS NULL OR to_regprocedure('public.own_run_context_v1(jsonb,boolean,boolean)') IS NULL THEN RAISE EXCEPTION 'OWN_LIQ_PREREQUISITE';END IF;
END $$;
INSERT INTO public.iam_capability(capability_key,label,description,scope_kind,sensitivity) VALUES('payroll.calculation.approve','Confirmar y anular resultados propios','Revisar un cálculo propio de otra persona; confirmar o anular legajos conservando resultados y decisiones. No cierra, contabiliza ni paga.','tenant','privileged');
CREATE TABLE public.own_payroll_liquidation_event(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES public.platform_tenant(id),source_binding_id uuid NOT NULL,
 capture_id uuid NOT NULL REFERENCES public.own_payroll_run_capture(id),command text NOT NULL CHECK(command IN('confirm','annul','cancel')),
 actor_membership_id uuid NOT NULL,actor_person_id uuid NOT NULL REFERENCES public.person_identity(id),actor_email text NOT NULL CHECK(actor_email=lower(actor_email)),actor_label text NOT NULL,
 actor_session_id uuid NOT NULL REFERENCES public.tenant_identity_session(id),actor_session_version integer NOT NULL CHECK(actor_session_version>0),release_sha text NOT NULL CHECK(release_sha~'^[a-f0-9]{40}$'),
 request_key uuid NOT NULL CHECK(request_key::text~'^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$'),
 body jsonb NOT NULL CHECK(jsonb_typeof(body)='object' AND octet_length(body::text)<=524288),body_sha256 text NOT NULL CHECK(body_sha256~'^[a-f0-9]{64}$'),
 changes jsonb NOT NULL CHECK(jsonb_typeof(changes)='array' AND jsonb_array_length(changes)>0 AND jsonb_array_length(changes)<=10000 AND octet_length(changes::text)<=3145728),
 receipt jsonb NOT NULL CHECK(jsonb_typeof(receipt)='object' AND octet_length(receipt::text)<=4194304),recorded_at timestamptz NOT NULL DEFAULT clock_timestamp(),
 UNIQUE(tenant_id,source_binding_id,actor_membership_id,request_key),
 FOREIGN KEY(tenant_id,source_binding_id) REFERENCES public.platform_tenant_source_binding(tenant_id,id),FOREIGN KEY(actor_membership_id,tenant_id) REFERENCES public.tenant_membership(id,tenant_id)
);
ALTER TABLE public.own_payroll_liquidation_event ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.own_payroll_liquidation_event FROM PUBLIC,municontrol_actions_runtime_app;
CREATE FUNCTION public.own_liquidation_immutable_v1() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$ BEGIN RAISE EXCEPTION 'OWN_LIQ_IMMUTABLE';END $$;
CREATE TRIGGER own_liquidation_event_immutable BEFORE UPDATE OR DELETE ON public.own_payroll_liquidation_event FOR EACH ROW EXECUTE FUNCTION public.own_liquidation_immutable_v1();
CREATE TRIGGER own_liquidation_event_no_truncate BEFORE TRUNCATE ON public.own_payroll_liquidation_event FOR EACH STATEMENT EXECUTE FUNCTION public.own_liquidation_immutable_v1();
CREATE FUNCTION public.own_liquidation_context_v1(p jsonb,nominal boolean DEFAULT false,command text DEFAULT NULL) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE ctx jsonb;BEGIN ctx:=public.own_run_context_v1(p,nominal,false);
 IF command IS NOT NULL AND(command NOT IN('confirm','annul','cancel') OR NOT public.action_center_context_has_capability(ctx,CASE WHEN command='cancel' THEN 'payroll.calculation.prepare' ELSE 'payroll.calculation.approve' END)) THEN RAISE EXCEPTION 'OWN_LIQ_FORBIDDEN';END IF;
 RETURN ctx;END $$;
CREATE FUNCTION public.own_liquidation_capture_v1(ctx jsonb,run_id uuid) RETURNS public.own_payroll_run_capture LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE c public.own_payroll_run_capture;r public.own_payroll_run_result;BEGIN SELECT * INTO c FROM public.own_payroll_run_capture WHERE id=run_id AND tenant_id=(ctx->>'tenantId')::uuid AND source_binding_id=(ctx->>'sourceBindingId')::uuid;
 SELECT * INTO r FROM public.own_payroll_run_result WHERE capture_id=c.id;
 IF c.id IS NULL OR r.capture_id IS NULL THEN RAISE EXCEPTION 'OWN_LIQ_NOT_FOUND';END IF;
 IF(c.actor_membership_id IS DISTINCT FROM(ctx->>'membershipId')::uuid OR c.actor_person_id IS DISTINCT FROM(ctx->>'actorPersonId')::uuid OR c.actor_email IS DISTINCT FROM ctx->>'actorEmail') AND NOT public.action_center_context_has_capability(ctx,'payroll.calculation.approve') THEN RAISE EXCEPTION 'OWN_LIQ_FORBIDDEN';END IF;
 IF c.body_sha256<>public.own_run_hash_v1(c.body) OR c.payload_sha256<>public.own_run_hash_v1(c.payload) OR r.input_sha256<>public.own_run_hash_v1(r.input) OR r.result_sha256<>public.own_run_hash_v1(r.result) OR r.result->'payrollCalculated' IS DISTINCT FROM 'true'::jsonb OR r.result->'paymentExecuted' IS DISTINCT FROM 'false'::jsonb OR r.algorithm_sha256<>c.algorithm_sha256 THEN RAISE EXCEPTION 'OWN_LIQ_CONTRACT_INVALID';END IF;
 RETURN c;END $$;
CREATE FUNCTION public.own_liquidation_current_v1(ctx jsonb,period text,payroll_type text) RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
 SELECT coalesce(jsonb_agg(jsonb_build_object('runId',z.capture_id,'contractId',z.contract_id,'state',z.change->>'state','liquidationVersion',z.change->'liquidationVersion') ORDER BY z.capture_id,z.contract_id),'[]'::jsonb)
 FROM(SELECT DISTINCT ON(e.capture_id,x.value->>'contractId') e.capture_id,x.value->>'contractId' contract_id,x.value change
 FROM public.own_payroll_liquidation_event e JOIN public.own_payroll_run_capture c ON c.id=e.capture_id CROSS JOIN LATERAL jsonb_array_elements(e.changes) x
 WHERE e.tenant_id=(ctx->>'tenantId')::uuid AND e.source_binding_id=(ctx->>'sourceBindingId')::uuid AND c.body->>'period'=period AND c.body->>'liquidationType'=payroll_type
 ORDER BY e.capture_id,x.value->>'contractId',(x.value->>'version')::integer DESC) z $$;
CREATE FUNCTION public.own_liquidation_rows_v1(ctx jsonb,c public.own_payroll_run_capture) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE person jsonb;last_change jsonb;events jsonb;blocked uuid;rows_value jsonb:='[]';active jsonb;state text;revision integer;liquidation integer;allowed jsonb;independent boolean;BEGIN
 active:=public.own_liquidation_current_v1(ctx,c.body->>'period',c.body->>'liquidationType');
 independent:=c.actor_person_id IS DISTINCT FROM(ctx->>'actorPersonId')::uuid AND c.actor_membership_id IS DISTINCT FROM(ctx->>'membershipId')::uuid AND c.actor_email IS DISTINCT FROM ctx->>'actorEmail';
 FOR person IN SELECT value FROM jsonb_array_elements((SELECT input->'employees' FROM public.own_payroll_run_result WHERE capture_id=c.id)) ORDER BY value->>'contractId' LOOP
  SELECT x.value INTO last_change FROM public.own_payroll_liquidation_event e CROSS JOIN LATERAL jsonb_array_elements(e.changes) x WHERE e.capture_id=c.id AND x.value->>'contractId'=person->>'contractId' ORDER BY(x.value->>'version')::integer DESC LIMIT 1;
  state:=coalesce(last_change->>'state','calculated');revision:=coalesce((last_change->>'version')::integer,0);liquidation:=(last_change->>'liquidationVersion')::integer;
  SELECT coalesce(jsonb_agg(jsonb_build_object('id',e.id,'command',e.command,'version',x.value->'version','liquidationVersion',x.value->'liquidationVersion','recordedAt',e.recorded_at,'actorLabel',e.actor_label,'reason',e.body->>'reason') ORDER BY(x.value->>'version')::integer),'[]') INTO events FROM public.own_payroll_liquidation_event e CROSS JOIN LATERAL jsonb_array_elements(e.changes) x WHERE e.capture_id=c.id AND x.value->>'contractId'=person->>'contractId';
  SELECT(value->>'runId')::uuid INTO blocked FROM jsonb_array_elements(active) WHERE value->>'contractId'=person->>'contractId' AND value->>'state'='confirmed' AND value->>'runId'<>c.id::text;
  allowed:='[]';IF state='calculated' AND independent AND blocked IS NULL AND public.action_center_context_has_capability(ctx,'payroll.calculation.approve') THEN allowed:=allowed||'"confirm"'::jsonb;END IF;
  IF state='confirmed' AND independent AND public.action_center_context_has_capability(ctx,'payroll.calculation.approve') THEN allowed:=allowed||'"annul"'::jsonb;END IF;
  IF state='calculated' AND c.actor_person_id=(ctx->>'actorPersonId')::uuid AND c.actor_membership_id=(ctx->>'membershipId')::uuid AND c.actor_email=ctx->>'actorEmail' AND public.action_center_context_has_capability(ctx,'payroll.calculation.prepare') THEN allowed:=allowed||'"cancel"'::jsonb;END IF;
  rows_value:=rows_value||jsonb_build_array(jsonb_build_object('contractId',person->>'contractId','state',state,'version',revision,'liquidationVersion',liquidation,'blockedBy',blocked,'allowedCommands',allowed,'events',events));
 END LOOP;RETURN rows_value;END $$;
CREATE FUNCTION public.own_liquidation_state_v1(ctx jsonb,c public.own_payroll_run_capture) RETURNS text LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
 SELECT public.own_run_hash_v1(jsonb_build_object('scopeVersion',public.native_salary_scope_v1(ctx),'runId',c.id,'resultSha256',(SELECT result_sha256 FROM public.own_payroll_run_result WHERE capture_id=c.id),'events',(SELECT coalesce(jsonb_agg(jsonb_build_object('id',e.id,'bodySha256',e.body_sha256) ORDER BY e.id),'[]') FROM public.own_payroll_liquidation_event e JOIN public.own_payroll_run_capture r ON r.id=e.capture_id WHERE e.tenant_id=c.tenant_id AND e.source_binding_id=c.source_binding_id AND r.body->>'period'=c.body->>'period' AND r.body->>'liquidationType'=c.body->>'liquidationType'))) $$;
CREATE FUNCTION public.own_liquidation_bootstrap_v1(p jsonb) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp SET timezone='UTC' AS $$
DECLARE ctx jsonb;rows_value jsonb;BEGIN ctx:=public.own_liquidation_context_v1(p);
 IF(SELECT count(*) FROM public.own_payroll_run_capture c JOIN public.own_payroll_run_result r ON r.capture_id=c.id WHERE c.tenant_id=(ctx->>'tenantId')::uuid AND c.source_binding_id=(ctx->>'sourceBindingId')::uuid)>1000 THEN RAISE EXCEPTION 'OWN_LIQ_LIMIT';END IF;
 SELECT coalesce(jsonb_agg(jsonb_build_object('id',c.id,'period',c.body->>'period','liquidationType',c.body->>'liquidationType','createdAt',c.created_at,'employeeCount',r.result->'employeeCount','resultSha256',r.result_sha256,'canConsult',ctx->>'actorPersonId' IS NOT NULL AND ctx->>'employmentContractId' IS NOT NULL AND NOT EXISTS(SELECT 1 FROM unnest(ARRAY['payroll.calculation.nominal.read','payroll.novelty.read','payroll.novelty.nominal.read','payroll.novelty.export']) cap WHERE NOT public.action_center_context_has_capability(ctx,cap)) AND(c.actor_membership_id=(ctx->>'membershipId')::uuid AND c.actor_person_id=(ctx->>'actorPersonId')::uuid AND c.actor_email=ctx->>'actorEmail' OR public.action_center_context_has_capability(ctx,'payroll.calculation.approve'))) ORDER BY c.created_at DESC,c.id),'[]') INTO rows_value FROM public.own_payroll_run_capture c JOIN public.own_payroll_run_result r ON r.capture_id=c.id WHERE c.tenant_id=(ctx->>'tenantId')::uuid AND c.source_binding_id=(ctx->>'sourceBindingId')::uuid;
 RETURN jsonb_build_object('version','own-liquidation-bootstrap.v1','scopeVersion',public.native_salary_scope_v1(ctx),'runs',rows_value,'complete',true);END $$;
CREATE FUNCTION public.own_liquidation_detail_v1(p jsonb,run_id uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp SET timezone='UTC' AS $$
DECLARE ctx jsonb;c public.own_payroll_run_capture;value jsonb;BEGIN ctx:=public.own_liquidation_context_v1(p,true);PERFORM public.own_run_lock_v1(ctx);c:=public.own_liquidation_capture_v1(ctx,run_id);
 value:=jsonb_build_object('version','own-liquidation-detail.v1','id',c.id,'scopeVersion',public.native_salary_scope_v1(ctx),'stateVersion',public.own_liquidation_state_v1(ctx,c),'reviewAccessRequired',c.actor_membership_id IS DISTINCT FROM(ctx->>'membershipId')::uuid OR c.actor_person_id IS DISTINCT FROM(ctx->>'actorPersonId')::uuid OR c.actor_email IS DISTINCT FROM ctx->>'actorEmail','capture',public.own_run_receipt_v1(c,true),'employees',public.own_liquidation_rows_v1(ctx,c),'effects',jsonb_build_object('paymentExecuted',false,'accountingPosted',false,'periodClosed',false));
 IF octet_length(value::text)+8192>4194304 THEN RAISE EXCEPTION 'OWN_LIQ_LIMIT';END IF;RETURN value;END $$;
CREATE FUNCTION public.own_liquidation_attempt_v1(p jsonb,key uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE ctx jsonb;e public.own_payroll_liquidation_event;BEGIN ctx:=public.own_liquidation_context_v1(p,true);SELECT * INTO e FROM public.own_payroll_liquidation_event WHERE tenant_id=(ctx->>'tenantId')::uuid AND source_binding_id=(ctx->>'sourceBindingId')::uuid AND actor_membership_id=(ctx->>'membershipId')::uuid AND request_key=key;
 IF e.id IS NULL THEN RAISE EXCEPTION 'OWN_LIQ_NOT_FOUND';END IF;IF e.actor_person_id IS DISTINCT FROM(ctx->>'actorPersonId')::uuid OR e.actor_email IS DISTINCT FROM ctx->>'actorEmail' THEN RAISE EXCEPTION 'OWN_LIQ_FORBIDDEN';END IF;RETURN e.receipt||jsonb_build_object('replayed',true);END $$;
CREATE FUNCTION public.own_liquidation_command_v1(p jsonb,body jsonb,key uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp SET timezone='UTC' AS $$
DECLARE ctx jsonb;c public.own_payroll_run_capture;e public.own_payroll_liquidation_event;r public.own_payroll_run_result;rows_value jsonb;person jsonb;row_value jsonb;selection jsonb;changes jsonb:='[]';chosen text[]:='{}';kind text;val text;command text;fingerprint text;revision integer;liquidation integer;event_id uuid:=gen_random_uuid();at_time timestamptz:=clock_timestamp();receipt_value jsonb;BEGIN
 IF NOT public.own_program_exact_v1(body,ARRAY['runId','resultSha256','scopeVersion','stateVersion','command','selection','reason','reviewConfirmed']) OR jsonb_typeof(body->'runId') IS DISTINCT FROM 'string' OR(body->>'runId')!~'^[a-f0-9]{8}(-[a-f0-9]{4}){3}-[a-f0-9]{12}$' OR jsonb_typeof(body->'command') IS DISTINCT FROM 'string' OR body->>'command' NOT IN('confirm','annul','cancel') OR key IS NULL OR key::text!~'^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$' OR octet_length(body::text)>524288 OR body->'reviewConfirmed' IS DISTINCT FROM 'true'::jsonb OR jsonb_typeof(body->'reason') IS DISTINCT FROM 'string' OR length(body->>'reason') NOT BETWEEN 10 AND 500 OR btrim(body->>'reason')<>body->>'reason' OR body->>'reason'~'[[:cntrl:]]' THEN RAISE EXCEPTION 'OWN_LIQ_INPUT_INVALID';END IF;
 FOREACH val IN ARRAY ARRAY['resultSha256','scopeVersion','stateVersion'] LOOP IF jsonb_typeof(body->val) IS DISTINCT FROM 'string' OR body->>val!~'^[a-f0-9]{64}$' THEN RAISE EXCEPTION 'OWN_LIQ_INPUT_INVALID';END IF;END LOOP;
 command:=body->>'command';ctx:=public.own_liquidation_context_v1(p,true,command);PERFORM public.own_run_lock_v1(ctx);fingerprint:=public.own_run_hash_v1(body);
 SELECT * INTO e FROM public.own_payroll_liquidation_event WHERE tenant_id=(ctx->>'tenantId')::uuid AND source_binding_id=(ctx->>'sourceBindingId')::uuid AND actor_membership_id=(ctx->>'membershipId')::uuid AND request_key=key;
 IF FOUND THEN IF e.actor_person_id IS DISTINCT FROM(ctx->>'actorPersonId')::uuid OR e.actor_email IS DISTINCT FROM ctx->>'actorEmail' THEN RAISE EXCEPTION 'OWN_LIQ_FORBIDDEN';END IF;IF e.body<>body OR e.body_sha256<>fingerprint THEN RAISE EXCEPTION 'OWN_LIQ_IDEMPOTENCY_REUSE';END IF;RETURN e.receipt||jsonb_build_object('replayed',true);END IF;
 c:=public.own_liquidation_capture_v1(ctx,(body->>'runId')::uuid);SELECT * INTO r FROM public.own_payroll_run_result WHERE capture_id=c.id;
 IF body->>'resultSha256'<>r.result_sha256 THEN RAISE EXCEPTION 'OWN_LIQ_RESULT_CHANGED';END IF;
 IF body->>'scopeVersion'<>public.native_salary_scope_v1(ctx) OR body->>'stateVersion'<>public.own_liquidation_state_v1(ctx,c) THEN RAISE EXCEPTION 'OWN_LIQ_STATE_CHANGED';END IF;
 selection:=body->'selection';kind:=selection->>'kind';IF NOT public.own_program_exact_v1(selection,ARRAY['kind','values']) OR jsonb_typeof(selection->'kind') IS DISTINCT FROM 'string' OR kind NOT IN('all','contracts','agreements','departments') OR jsonb_typeof(selection->'values') IS DISTINCT FROM 'array' OR jsonb_array_length(selection->'values')>10000 OR(kind='all' AND jsonb_array_length(selection->'values')<>0) OR(kind<>'all' AND jsonb_array_length(selection->'values')=0) OR EXISTS(SELECT 1 FROM jsonb_array_elements(selection->'values') x WHERE jsonb_typeof(x) IS DISTINCT FROM 'string' OR x#>>'{}'!~CASE WHEN kind='contracts' THEN '^[a-f0-9]{8}(-[a-f0-9]{4}){3}-[a-f0-9]{12}$' ELSE '^[0-9]{1,9}$' END) OR(SELECT count(DISTINCT value) FROM jsonb_array_elements(selection->'values'))<>jsonb_array_length(selection->'values') THEN RAISE EXCEPTION 'OWN_LIQ_SELECTION_INVALID';END IF;
 rows_value:=public.own_liquidation_rows_v1(ctx,c);
 FOR person IN SELECT value FROM jsonb_array_elements(r.input->'employees') ORDER BY value->>'contractId' LOOP
  val:=CASE kind WHEN 'contracts' THEN person->>'contractId' WHEN 'agreements' THEN person->>'agreementCode' WHEN 'departments' THEN person->>'departmentCode' ELSE NULL END;
  IF kind='all' OR selection->'values' ? val THEN
   SELECT value INTO row_value FROM jsonb_array_elements(rows_value) WHERE value->>'contractId'=person->>'contractId';
   IF NOT row_value->'allowedCommands' ? command THEN RAISE EXCEPTION 'OWN_LIQ_DECISION_INVALID';END IF;
   revision:=(row_value->>'version')::integer+1;liquidation:=(row_value->>'liquidationVersion')::integer;
   IF command='confirm' THEN SELECT coalesce(max((x.value->>'liquidationVersion')::integer),0)+1 INTO liquidation FROM public.own_payroll_liquidation_event z JOIN public.own_payroll_run_capture pc ON pc.id=z.capture_id CROSS JOIN LATERAL jsonb_array_elements(z.changes) x WHERE z.tenant_id=c.tenant_id AND z.source_binding_id=c.source_binding_id AND pc.body->>'period'=c.body->>'period' AND pc.body->>'liquidationType'=c.body->>'liquidationType' AND x.value->>'contractId'=person->>'contractId';END IF;
   changes:=changes||jsonb_build_array(jsonb_build_object('contractId',person->>'contractId','state',CASE command WHEN 'confirm' THEN 'confirmed' WHEN 'annul' THEN 'annulled' ELSE 'cancelled' END,'version',revision,'liquidationVersion',liquidation));chosen:=array_append(chosen,val);
  END IF;
 END LOOP;
 IF jsonb_array_length(changes)=0 OR(kind<>'all' AND EXISTS(SELECT 1 FROM jsonb_array_elements_text(selection->'values') x WHERE NOT x=ANY(chosen))) THEN RAISE EXCEPTION 'OWN_LIQ_SELECTION_INVALID';END IF;
 receipt_value:=jsonb_build_object('version','own-liquidation-receipt.v1','id',event_id,'key',key,'body',body,'bodySha256',fingerprint,'runId',c.id,'resultSha256',r.result_sha256,'affected',changes,'recordedAt',at_time,'replayed',false);
 IF octet_length(receipt_value::text)+8192>4194304 THEN RAISE EXCEPTION 'OWN_LIQ_LIMIT';END IF;
 IF NOT pg_try_advisory_xact_lock(hashtextextended('own-run:capacity:v1',0)) THEN RAISE EXCEPTION 'OWN_LIQ_BUSY';END IF;
 IF(SELECT coalesce(sum(octet_length(le.body::text)+octet_length(le.changes::text)+octet_length(le.receipt::text)),0) FROM public.own_payroll_liquidation_event le)+octet_length(body::text)+octet_length(changes::text)+octet_length(receipt_value::text)>67108864 OR(SELECT count(*) FROM public.own_payroll_liquidation_event le WHERE le.capture_id=c.id)>=4000 THEN RAISE EXCEPTION 'OWN_LIQ_LIMIT';END IF;
 INSERT INTO public.own_payroll_liquidation_event(id,tenant_id,source_binding_id,capture_id,command,actor_membership_id,actor_person_id,actor_email,actor_label,actor_session_id,actor_session_version,release_sha,request_key,body,body_sha256,changes,receipt,recorded_at) VALUES(event_id,c.tenant_id,c.source_binding_id,c.id,command,(ctx->>'membershipId')::uuid,(ctx->>'actorPersonId')::uuid,ctx->>'actorEmail',coalesce(nullif(ctx->>'actorLabel',''),'Autoridad municipal'),(p->>'actorSessionId')::uuid,(p->>'actorSessionVersion')::integer,p->>'releaseSha',key,body,fingerprint,changes,receipt_value,at_time);
 RETURN receipt_value;END $$;
DO $$ DECLARE fn record;BEGIN FOR fn IN SELECT oid::regprocedure signature FROM pg_proc WHERE pronamespace='public'::regnamespace AND proname LIKE 'own_liquidation_%' LOOP EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC,municontrol_actions_runtime_app',fn.signature);END LOOP;END $$;
GRANT EXECUTE ON FUNCTION public.own_liquidation_bootstrap_v1(jsonb),public.own_liquidation_detail_v1(jsonb,uuid),public.own_liquidation_attempt_v1(jsonb,uuid),public.own_liquidation_command_v1(jsonb,jsonb,uuid) TO municontrol_actions_runtime_app;
