-- Own calculated liquidation history. Closing is scoped to a declared group
-- of confirmed native employees, never a claim that all municipal payroll is
-- migrated. No accounting, payment, rates, IAM assignments or live GRH calls.
DO $$ BEGIN
 IF to_regclass('public.own_payroll_close_event') IS NOT NULL OR EXISTS(SELECT 1 FROM pg_proc WHERE pronamespace='public'::regnamespace AND proname LIKE 'own_close_%') OR EXISTS(SELECT 1 FROM public.iam_capability WHERE capability_key='payroll.calculation.close') THEN RAISE EXCEPTION 'OWN_CLOSE_ALREADY_INSTALLED';END IF;
 IF to_regprocedure('public.own_liquidation_current_v1(jsonb,text,text)') IS NULL THEN RAISE EXCEPTION 'OWN_CLOSE_PREREQUISITE';END IF;
END $$;
INSERT INTO public.iam_capability(capability_key,label,description,scope_kind,sensitivity) VALUES('payroll.calculation.close','Cerrar y reabrir liquidaciones propias','Conservar el histórico de grupos confirmados y reabrirlos con motivo antes de modificar sus versiones. No contabiliza ni paga.','tenant','privileged');
CREATE TABLE public.own_payroll_close_event(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES public.platform_tenant(id),source_binding_id uuid NOT NULL,
 group_id uuid NOT NULL,command text NOT NULL CHECK(command IN('close','reopen')),period text NOT NULL CHECK(period~'^(19|20)[0-9]{2}-(0[1-9]|1[0-2])$'),liquidation_type text NOT NULL CHECK(liquidation_type IN('monthly','first_fortnight','sac','vacation','supplementary','final','other')),
 actor_membership_id uuid NOT NULL,actor_person_id uuid NOT NULL REFERENCES public.person_identity(id),actor_email text NOT NULL CHECK(actor_email=lower(actor_email)),actor_label text NOT NULL,
 actor_session_id uuid NOT NULL REFERENCES public.tenant_identity_session(id),actor_session_version integer NOT NULL CHECK(actor_session_version>0),release_sha text NOT NULL CHECK(release_sha~'^[a-f0-9]{40}$'),
 request_key uuid NOT NULL CHECK(request_key::text~'^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$'),
 body jsonb NOT NULL CHECK(jsonb_typeof(body)='object' AND octet_length(body::text)<=524288),body_sha256 text NOT NULL CHECK(body_sha256~'^[a-f0-9]{64}$'),
 snapshot jsonb NOT NULL CHECK(jsonb_typeof(snapshot)='object' AND octet_length(snapshot::text)<=3145728),snapshot_sha256 text NOT NULL CHECK(snapshot_sha256~'^[a-f0-9]{64}$'),
 receipt jsonb NOT NULL CHECK(jsonb_typeof(receipt)='object' AND octet_length(receipt::text)<=4194304),recorded_at timestamptz NOT NULL DEFAULT clock_timestamp(),
 UNIQUE(tenant_id,source_binding_id,actor_membership_id,request_key),UNIQUE(tenant_id,source_binding_id,group_id,command),
 FOREIGN KEY(tenant_id,source_binding_id) REFERENCES public.platform_tenant_source_binding(tenant_id,id),FOREIGN KEY(actor_membership_id,tenant_id) REFERENCES public.tenant_membership(id,tenant_id)
);
ALTER TABLE public.own_payroll_close_event ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.own_payroll_close_event FROM PUBLIC,municontrol_actions_runtime_app;
CREATE FUNCTION public.own_close_immutable_v1() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$ BEGIN RAISE EXCEPTION 'OWN_CLOSE_IMMUTABLE';END $$;
CREATE TRIGGER own_close_event_immutable BEFORE UPDATE OR DELETE ON public.own_payroll_close_event FOR EACH ROW EXECUTE FUNCTION public.own_close_immutable_v1();
CREATE TRIGGER own_close_event_no_truncate BEFORE TRUNCATE ON public.own_payroll_close_event FOR EACH STATEMENT EXECUTE FUNCTION public.own_close_immutable_v1();
CREATE FUNCTION public.own_close_context_v1(p jsonb,nominal boolean DEFAULT false,write_access boolean DEFAULT false) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE ctx jsonb;BEGIN ctx:=public.own_run_context_v1(p,nominal,false);
 IF nominal AND NOT public.action_center_context_has_capability(ctx,'payroll.calculation.approve') OR write_access AND NOT public.action_center_context_has_capability(ctx,'payroll.calculation.close') THEN RAISE EXCEPTION 'OWN_CLOSE_FORBIDDEN';END IF;RETURN ctx;END $$;
CREATE FUNCTION public.own_close_active_v1(ctx jsonb,period_value text,type_value text) RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
 SELECT coalesce(jsonb_agg(jsonb_build_object('id',e.id,'snapshot',e.snapshot) ORDER BY e.id),'[]') FROM public.own_payroll_close_event e WHERE e.tenant_id=(ctx->>'tenantId')::uuid AND e.source_binding_id=(ctx->>'sourceBindingId')::uuid AND e.period=period_value AND e.liquidation_type=type_value AND e.command='close' AND NOT EXISTS(SELECT 1 FROM public.own_payroll_close_event r WHERE r.tenant_id=e.tenant_id AND r.source_binding_id=e.source_binding_id AND r.group_id=e.id AND r.command='reopen') $$;
CREATE FUNCTION public.own_close_guard_v1(ctx jsonb,period_value text,type_value text,contracts uuid[]) RETURNS void LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
BEGIN IF EXISTS(SELECT 1 FROM jsonb_array_elements(public.own_close_active_v1(ctx,period_value,type_value)) g CROSS JOIN LATERAL jsonb_array_elements(g.value#>'{snapshot,employees}') e WHERE (e.value->>'contractId')::uuid=ANY(contracts)) THEN RAISE EXCEPTION 'OWN_CLOSE_REOPEN_REQUIRED';END IF;END $$;
CREATE FUNCTION public.own_close_roster_v1(ctx jsonb,period_value text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE reg record;subject jsonb;rows_value jsonb:='[]';first_date date:=(period_value||'-01')::date;last_date date:=(first_date+interval '1 month - 1 day')::date;BEGIN
 LOCK TABLE public.person_identity,public.employment_contract,public.native_employee_registration,public.native_employment_change_review,public.native_employment_lifecycle_review IN SHARE MODE NOWAIT;
 FOR reg IN SELECT n.*,ec.legacy_legajo,ec.agreement_code,ec.category_code,ec.sector_source_id FROM public.native_employee_registration n JOIN public.employment_contract ec ON ec.id=n.contract_id WHERE n.tenant_id=(ctx->>'tenantId')::uuid AND n.source_binding_id=(ctx->>'sourceBindingId')::uuid AND ec.tenant_id=n.tenant_id AND ec.source_system='MUNICONTROL' AND ec.source_batch_id IS NULL ORDER BY ec.id LOOP
  IF NOT public.native_employment_lifecycle_range_v1(ctx,reg.contract_id,first_date,last_date,false) THEN CONTINUE;END IF;
  IF NOT public.native_employment_lifecycle_range_v1(ctx,reg.contract_id,first_date,last_date,true) THEN RAISE EXCEPTION 'OWN_RUN_PRORATION_REQUIRED';END IF;
  IF(reg.created_at AT TIME ZONE 'America/Argentina/Mendoza')::date>last_date OR EXISTS(SELECT 1 FROM public.native_employment_change_review r WHERE r.contract_id=reg.contract_id AND r.decision='approve' AND(r.reviewed_at AT TIME ZONE 'America/Argentina/Mendoza')::date>=first_date) THEN RAISE EXCEPTION 'OWN_RUN_HISTORY_REQUIRED';END IF;
  subject:=public.payroll_fixed_registry_subject_by_contract_v1(ctx,reg.contract_id,true)->'subject';
  IF subject->>'origin'<>'MUNICONTROL' OR subject->>'contractId'<>reg.contract_id::text OR subject->>'legajo'<>reg.legacy_legajo OR coalesce(reg.legacy_legajo,'')!~'^[0-9]{1,9}$' OR coalesce(reg.agreement_code,'')!~'^[0-9]{1,9}$' OR coalesce(reg.sector_source_id,'')!~'^[0-9]{1,9}$' THEN RAISE EXCEPTION 'OWN_CLOSE_CONTRACT_INVALID';END IF;
  rows_value:=rows_value||jsonb_build_array(jsonb_build_object('contractId',reg.contract_id,'employeeNumber',reg.legacy_legajo,'agreementCode',reg.agreement_code,'departmentCode',reg.sector_source_id));IF jsonb_array_length(rows_value)>10000 THEN RAISE EXCEPTION 'OWN_CLOSE_LIMIT';END IF;
 END LOOP;RETURN rows_value;END $$;
CREATE FUNCTION public.own_close_detail_v1(p jsonb,period_value text,type_value text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp SET timezone='UTC' AS $$
DECLARE ctx jsonb;roster jsonb;current_rows jsonb;closed jsonb;groups_value jsonb;rows_value jsonb:='[]';captures jsonb:='[]';person jsonb;decision jsonb;group_value jsonb;c public.own_payroll_run_capture;r public.own_payroll_run_result;state_version text;detail_value jsonb;independent boolean;BEGIN
 ctx:=public.own_close_context_v1(p,true);IF coalesce(period_value,'')!~'^(19|20)[0-9]{2}-(0[1-9]|1[0-2])$' OR coalesce(type_value,'') NOT IN('monthly','first_fortnight','sac','vacation','supplementary','final','other') THEN RAISE EXCEPTION 'OWN_CLOSE_INPUT_INVALID';END IF;
 PERFORM public.own_run_lock_v1(ctx);roster:=public.own_close_roster_v1(ctx,period_value);current_rows:=public.own_liquidation_current_v1(ctx,period_value,type_value);closed:=public.own_close_active_v1(ctx,period_value,type_value);
 IF(SELECT count(*) FROM public.own_payroll_close_event e WHERE e.tenant_id=(ctx->>'tenantId')::uuid AND e.source_binding_id=(ctx->>'sourceBindingId')::uuid AND e.period=period_value AND e.liquidation_type=type_value AND e.command='close')>1000 THEN RAISE EXCEPTION 'OWN_CLOSE_LIMIT';END IF;
 SELECT coalesce(jsonb_agg(jsonb_build_object('id',e.id,'state',CASE WHEN reopened.id IS NULL THEN 'closed' ELSE 'reopened' END,'employeeCount',e.snapshot->'employeeCount','populationCount',e.snapshot->'populationCount','populationComplete',e.snapshot->'populationComplete','recordedAt',e.recorded_at,'reopenedAt',reopened.recorded_at,'actorLabel',e.actor_label,'reason',e.body->>'reason','snapshotSha256',e.snapshot_sha256,'canReopen',reopened.id IS NULL AND public.action_center_context_has_capability(ctx,'payroll.calculation.close') AND NOT EXISTS(SELECT 1 FROM jsonb_array_elements(e.snapshot->'employees') selected JOIN public.own_payroll_run_capture source_capture ON source_capture.id=(selected.value->>'runId')::uuid WHERE source_capture.actor_person_id=(ctx->>'actorPersonId')::uuid OR source_capture.actor_membership_id=(ctx->>'membershipId')::uuid OR source_capture.actor_email=ctx->>'actorEmail')) ORDER BY e.recorded_at DESC,e.id),'[]') INTO groups_value FROM public.own_payroll_close_event e LEFT JOIN public.own_payroll_close_event reopened ON reopened.tenant_id=e.tenant_id AND reopened.source_binding_id=e.source_binding_id AND reopened.group_id=e.id AND reopened.command='reopen' WHERE e.tenant_id=(ctx->>'tenantId')::uuid AND e.source_binding_id=(ctx->>'sourceBindingId')::uuid AND e.period=period_value AND e.liquidation_type=type_value AND e.command='close';
 FOR person IN SELECT value FROM jsonb_array_elements(roster) LOOP
  IF(SELECT count(*) FROM jsonb_array_elements(current_rows) x WHERE x.value->>'contractId'=person->>'contractId' AND x.value->>'state'='confirmed')>1 THEN RAISE EXCEPTION 'OWN_CLOSE_CONTRACT_INVALID';END IF;
  SELECT x.value INTO decision FROM jsonb_array_elements(current_rows) x WHERE x.value->>'contractId'=person->>'contractId' AND x.value->>'state'='confirmed';
  IF decision IS NULL THEN rows_value:=rows_value||jsonb_build_array(person||jsonb_build_object('state','missing','runId',NULL,'resultSha256',NULL,'liquidationVersion',NULL,'groupId',NULL,'canClose',false));CONTINUE;END IF;
  c:=public.own_liquidation_capture_v1(ctx,(decision->>'runId')::uuid);SELECT * INTO r FROM public.own_payroll_run_result WHERE capture_id=c.id;
  IF NOT EXISTS(SELECT 1 FROM jsonb_array_elements(r.input->'employees') x WHERE x.value->>'contractId'=person->>'contractId' AND x.value->>'employeeNumber'=person->>'employeeNumber' AND x.value->>'agreementCode'=person->>'agreementCode' AND x.value->>'departmentCode'=person->>'departmentCode') THEN RAISE EXCEPTION 'OWN_CLOSE_CONTRACT_INVALID';END IF;
  IF NOT EXISTS(SELECT 1 FROM jsonb_array_elements(captures) x WHERE x.value->>'id'=c.id::text) THEN captures:=captures||jsonb_build_array(public.own_run_receipt_v1(c,true));END IF;
  SELECT g.value INTO group_value FROM jsonb_array_elements(closed) g WHERE EXISTS(SELECT 1 FROM jsonb_array_elements(g.value#>'{snapshot,employees}') x WHERE x.value->>'contractId'=person->>'contractId');
  independent:=c.actor_person_id IS DISTINCT FROM(ctx->>'actorPersonId')::uuid AND c.actor_membership_id IS DISTINCT FROM(ctx->>'membershipId')::uuid AND c.actor_email IS DISTINCT FROM ctx->>'actorEmail';
  rows_value:=rows_value||jsonb_build_array(person||jsonb_build_object('state',CASE WHEN group_value IS NULL THEN 'confirmed' ELSE 'closed' END,'runId',c.id,'resultSha256',r.result_sha256,'liquidationVersion',decision->'liquidationVersion','groupId',group_value->>'id','canClose',group_value IS NULL AND independent AND public.action_center_context_has_capability(ctx,'payroll.calculation.close')));
 END LOOP;
 state_version:=public.own_run_hash_v1(jsonb_build_object('scopeVersion',public.native_salary_scope_v1(ctx),'roster',roster,'rows',rows_value,'groups',groups_value,'events',(SELECT coalesce(jsonb_agg(jsonb_build_object('id',le.id,'bodySha256',le.body_sha256) ORDER BY le.id),'[]') FROM public.own_payroll_liquidation_event le JOIN public.own_payroll_run_capture pc ON pc.id=le.capture_id WHERE le.tenant_id=(ctx->>'tenantId')::uuid AND le.source_binding_id=(ctx->>'sourceBindingId')::uuid AND pc.body->>'period'=period_value AND pc.body->>'liquidationType'=type_value)));
 detail_value:=jsonb_build_object('version','own-close-detail.v1','period',period_value,'liquidationType',type_value,'scopeVersion',public.native_salary_scope_v1(ctx),'stateVersion',state_version,'populationDomain','native_registered','rosterVersion',public.own_run_hash_v1(roster),'rows',rows_value,'captures',captures,'groups',groups_value,'canWrite',public.action_center_context_has_capability(ctx,'payroll.calculation.close'),'complete',true);
 IF jsonb_array_length(captures)>1000 OR octet_length(detail_value::text)+8192>4194304 THEN RAISE EXCEPTION 'OWN_CLOSE_LIMIT';END IF;RETURN detail_value;END $$;
CREATE FUNCTION public.own_close_snapshot_v1(detail jsonb,selection jsonb) RETURNS jsonb LANGUAGE plpgsql IMMUTABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE kind text:=selection->>'kind';row_value jsonb;capture jsonb;saved jsonb;total jsonb;concept jsonb;employees jsonb:='[]';concepts jsonb:='[]';chosen text[]:='{}';key_value text;val text;precision integer:=0;totals jsonb:='{"remuneration":0,"non_remuneration":0,"deduction":0,"employer_contribution":0,"gross":0,"net":0}';amount numeric;expected numeric;formatted jsonb:='{}';BEGIN
 IF NOT public.own_program_exact_v1(selection,ARRAY['kind','values']) OR jsonb_typeof(selection->'kind') IS DISTINCT FROM 'string' OR kind NOT IN('all','contracts','agreements','departments') OR jsonb_typeof(selection->'values') IS DISTINCT FROM 'array' OR jsonb_array_length(selection->'values')>10000 OR(kind='all')<>(jsonb_array_length(selection->'values')=0) OR EXISTS(SELECT 1 FROM jsonb_array_elements(selection->'values') x WHERE jsonb_typeof(x) IS DISTINCT FROM 'string' OR x#>>'{}'!~CASE WHEN kind='contracts' THEN '^[a-f0-9]{8}(-[a-f0-9]{4}){3}-[a-f0-9]{12}$' ELSE '^[0-9]{1,9}$' END) OR(SELECT count(DISTINCT value) FROM jsonb_array_elements(selection->'values'))<>jsonb_array_length(selection->'values') OR selection->'values' IS DISTINCT FROM(SELECT coalesce(jsonb_agg(x ORDER BY x COLLATE "C"),'[]') FROM jsonb_array_elements_text(selection->'values') x) THEN RAISE EXCEPTION 'OWN_CLOSE_SELECTION_INVALID';END IF;
 FOR row_value IN SELECT value FROM jsonb_array_elements(detail->'rows') ORDER BY value->>'contractId' COLLATE "C" LOOP
  val:=row_value->>CASE kind WHEN 'contracts' THEN 'contractId' WHEN 'agreements' THEN 'agreementCode' ELSE 'departmentCode' END;
  IF kind<>'all' AND NOT selection->'values' ? val THEN CONTINUE;END IF;
  IF row_value->>'state'<>'confirmed' OR row_value->'canClose' IS DISTINCT FROM 'true'::jsonb THEN RAISE EXCEPTION 'OWN_CLOSE_DECISION_INVALID';END IF;
  chosen:=array_append(chosen,val);SELECT x.value INTO capture FROM jsonb_array_elements(detail->'captures') x WHERE x.value->>'id'=row_value->>'runId';saved:=capture->'saved';
  SELECT x.value INTO total FROM jsonb_array_elements(saved#>'{result,employeeTotals}') x WHERE x.value->>'contractId'=row_value->>'contractId';
  IF total IS NULL OR jsonb_array_length(saved#>'{result,employeeTotals}')<>(saved#>>'{result,employeeCount}')::integer OR saved#>'{result,payrollPosted}' IS DISTINCT FROM 'false'::jsonb OR(saved#>>'{input,totalsPrecision}')::integer NOT BETWEEN 0 AND 8 THEN RAISE EXCEPTION 'OWN_CLOSE_CONTRACT_INVALID';END IF;
  precision:=greatest(precision,(saved#>>'{input,totalsPrecision}')::integer);
  FOREACH key_value IN ARRAY ARRAY['remuneration','non_remuneration','deduction','employer_contribution','gross','net'] LOOP
   IF jsonb_typeof(total->key_value) IS DISTINCT FROM 'string' OR total->>key_value!~'^-?(0|[1-9][0-9]{0,95})(\.[0-9]{1,8})?$' THEN RAISE EXCEPTION 'OWN_CLOSE_CONTRACT_INVALID';END IF;amount:=(total->>key_value)::numeric;
   IF key_value IN('gross','net') THEN expected:=(total->>'remuneration')::numeric+(total->>'non_remuneration')::numeric-CASE WHEN key_value='net' THEN(total->>'deduction')::numeric ELSE 0 END;
   ELSE SELECT coalesce(sum((x.value->>'amount')::numeric),0) INTO expected FROM jsonb_array_elements(saved#>'{result,rows}') x WHERE x.value->>'contractId'=row_value->>'contractId' AND x.value->>'nature'=key_value;END IF;
   IF amount<>expected OR scale(amount)<>(saved#>>'{input,totalsPrecision}')::integer THEN RAISE EXCEPTION 'OWN_CLOSE_CONTRACT_INVALID';END IF;
   totals:=jsonb_set(totals,ARRAY[key_value],to_jsonb((totals->>key_value)::numeric+amount));
  END LOOP;
  employees:=employees||jsonb_build_array(jsonb_build_object('contractId',row_value->>'contractId','employeeNumber',row_value->>'employeeNumber','agreementCode',row_value->>'agreementCode','departmentCode',row_value->>'departmentCode','runId',row_value->>'runId','inputSha256',saved->>'inputSha256','resultSha256',saved->>'resultSha256','liquidationVersion',row_value->'liquidationVersion','precision',saved#>'{input,totalsPrecision}','conceptCount',(SELECT count(*) FROM jsonb_array_elements(saved#>'{result,rows}') x WHERE x.value->>'contractId'=row_value->>'contractId'),'totals',total));
  FOR concept IN SELECT value FROM jsonb_array_elements(saved#>'{result,rows}') WHERE value->>'contractId'=row_value->>'contractId' LOOP concepts:=concepts||jsonb_build_array(concept);END LOOP;
 END LOOP;
 IF jsonb_array_length(employees)=0 OR kind<>'all' AND EXISTS(SELECT 1 FROM jsonb_array_elements_text(selection->'values') x WHERE NOT x=ANY(chosen)) THEN RAISE EXCEPTION 'OWN_CLOSE_SELECTION_INVALID';END IF;
 FOREACH key_value IN ARRAY ARRAY['remuneration','non_remuneration','deduction','employer_contribution','gross','net'] LOOP amount:=(totals->>key_value)::numeric;IF amount<>trunc(amount,precision) THEN RAISE EXCEPTION 'OWN_CLOSE_CONTRACT_INVALID';END IF;formatted:=formatted||jsonb_build_object(key_value,trunc(amount,precision)::text);END LOOP;
 RETURN jsonb_build_object('version','own-close-snapshot.v1','period',detail->>'period','liquidationType',detail->>'liquidationType','populationDomain',detail->>'populationDomain','rosterVersion',detail->>'rosterVersion','selection',selection,'employeeCount',jsonb_array_length(employees),'populationCount',jsonb_array_length(detail->'rows'),'populationComplete',jsonb_array_length(employees)=jsonb_array_length(detail->'rows'),'precision',precision,'totals',formatted,'employees',employees,'concepts',concepts,'conceptCount',jsonb_array_length(concepts),'payrollCalculated',true,'payrollPosted',false,'paymentExecuted',false);END $$;
CREATE FUNCTION public.own_close_attempt_v1(p jsonb,key uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE ctx jsonb;e public.own_payroll_close_event;BEGIN ctx:=public.own_close_context_v1(p,true);SELECT * INTO e FROM public.own_payroll_close_event WHERE tenant_id=(ctx->>'tenantId')::uuid AND source_binding_id=(ctx->>'sourceBindingId')::uuid AND actor_membership_id=(ctx->>'membershipId')::uuid AND request_key=key;
 IF e.id IS NULL THEN RAISE EXCEPTION 'OWN_CLOSE_NOT_FOUND';END IF;IF e.actor_person_id IS DISTINCT FROM(ctx->>'actorPersonId')::uuid OR e.actor_email IS DISTINCT FROM ctx->>'actorEmail' THEN RAISE EXCEPTION 'OWN_CLOSE_FORBIDDEN';END IF;RETURN e.receipt||jsonb_build_object('replayed',true);END $$;
CREATE FUNCTION public.own_close_group_v1(p jsonb,group_value uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE ctx jsonb;e public.own_payroll_close_event;BEGIN ctx:=public.own_close_context_v1(p,true);SELECT * INTO e FROM public.own_payroll_close_event WHERE tenant_id=(ctx->>'tenantId')::uuid AND source_binding_id=(ctx->>'sourceBindingId')::uuid AND id=group_value AND command='close';IF e.id IS NULL THEN RAISE EXCEPTION 'OWN_CLOSE_NOT_FOUND';END IF;RETURN e.receipt||jsonb_build_object('replayed',true);END $$;
CREATE FUNCTION public.own_close_command_v1(p jsonb,body jsonb,key uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp SET timezone='UTC' AS $$
DECLARE ctx jsonb;e public.own_payroll_close_event;original public.own_payroll_close_event;detail jsonb;snapshot_value jsonb;fingerprint text;event_id uuid:=gen_random_uuid();group_value uuid;at_time timestamptz:=clock_timestamp();receipt_value jsonb;val text;period_value text;type_value text;BEGIN
 IF NOT public.own_program_exact_v1(body,ARRAY['period','liquidationType','scopeVersion','stateVersion','selection','command','groupId','reason','reviewConfirmed']) OR octet_length(body::text)>524288 OR body->'reviewConfirmed' IS DISTINCT FROM 'true'::jsonb OR jsonb_typeof(body->'command') IS DISTINCT FROM 'string' OR body->>'command' NOT IN('close','reopen') OR jsonb_typeof(body->'reason') IS DISTINCT FROM 'string' OR length(body->>'reason') NOT BETWEEN 10 AND 500 OR btrim(body->>'reason')<>body->>'reason' OR body->>'reason'~'[[:cntrl:]]' OR key IS NULL OR key::text!~'^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$' THEN RAISE EXCEPTION 'OWN_CLOSE_INPUT_INVALID';END IF;
 FOREACH val IN ARRAY ARRAY['scopeVersion','stateVersion'] LOOP IF jsonb_typeof(body->val) IS DISTINCT FROM 'string' OR body->>val!~'^[a-f0-9]{64}$' THEN RAISE EXCEPTION 'OWN_CLOSE_INPUT_INVALID';END IF;END LOOP;
 ctx:=public.own_close_context_v1(p,true,true);PERFORM public.own_run_lock_v1(ctx);fingerprint:=public.own_run_hash_v1(body);
 SELECT * INTO e FROM public.own_payroll_close_event WHERE tenant_id=(ctx->>'tenantId')::uuid AND source_binding_id=(ctx->>'sourceBindingId')::uuid AND actor_membership_id=(ctx->>'membershipId')::uuid AND request_key=key;
 IF FOUND THEN IF e.actor_person_id IS DISTINCT FROM(ctx->>'actorPersonId')::uuid OR e.actor_email IS DISTINCT FROM ctx->>'actorEmail' THEN RAISE EXCEPTION 'OWN_CLOSE_FORBIDDEN';END IF;IF e.body<>body OR e.body_sha256<>fingerprint THEN RAISE EXCEPTION 'OWN_CLOSE_IDEMPOTENCY_REUSE';END IF;RETURN e.receipt||jsonb_build_object('replayed',true);END IF;
 IF jsonb_typeof(body->'period') IS DISTINCT FROM 'string' OR jsonb_typeof(body->'liquidationType') IS DISTINCT FROM 'string' THEN RAISE EXCEPTION 'OWN_CLOSE_INPUT_INVALID';END IF;
 period_value:=body->>'period';type_value:=body->>'liquidationType';detail:=public.own_close_detail_v1(p,period_value,type_value);IF body->>'scopeVersion'<>detail->>'scopeVersion' OR body->>'stateVersion'<>detail->>'stateVersion' THEN RAISE EXCEPTION 'OWN_CLOSE_STATE_CHANGED';END IF;
 IF body->>'command'='close' THEN IF body->'groupId' IS DISTINCT FROM 'null'::jsonb THEN RAISE EXCEPTION 'OWN_CLOSE_INPUT_INVALID';END IF;group_value:=event_id;snapshot_value:=public.own_close_snapshot_v1(detail,body->'selection');
 ELSE
  IF jsonb_typeof(body->'groupId') IS DISTINCT FROM 'string' OR body->>'groupId'!~'^[a-f0-9]{8}(-[a-f0-9]{4}){3}-[a-f0-9]{12}$' OR body->'selection' IS DISTINCT FROM '{"kind":"all","values":[]}'::jsonb THEN RAISE EXCEPTION 'OWN_CLOSE_INPUT_INVALID';END IF;group_value:=(body->>'groupId')::uuid;
  SELECT * INTO original FROM public.own_payroll_close_event WHERE id=group_value AND tenant_id=(ctx->>'tenantId')::uuid AND source_binding_id=(ctx->>'sourceBindingId')::uuid AND period=period_value AND liquidation_type=type_value AND command='close';
  IF original.id IS NULL OR EXISTS(SELECT 1 FROM public.own_payroll_close_event r WHERE r.group_id=group_value AND r.command='reopen') THEN RAISE EXCEPTION 'OWN_CLOSE_DECISION_INVALID';END IF;
  IF EXISTS(SELECT 1 FROM jsonb_array_elements(original.snapshot->'employees') x JOIN public.own_payroll_run_capture c ON c.id=(x.value->>'runId')::uuid WHERE c.actor_person_id=(ctx->>'actorPersonId')::uuid OR c.actor_membership_id=(ctx->>'membershipId')::uuid OR c.actor_email=ctx->>'actorEmail') THEN RAISE EXCEPTION 'OWN_CLOSE_FORBIDDEN';END IF;
  IF original.snapshot_sha256<>public.own_run_hash_v1(original.snapshot) THEN RAISE EXCEPTION 'OWN_CLOSE_CONTRACT_INVALID';END IF;snapshot_value:=original.snapshot;
 END IF;
 receipt_value:=jsonb_build_object('version','own-close-receipt.v1','id',event_id,'key',key,'body',body,'bodySha256',fingerprint,'groupId',group_value,'snapshot',snapshot_value,'snapshotSha256',public.own_run_hash_v1(snapshot_value),'recordedAt',at_time,'replayed',false);
 IF octet_length(snapshot_value::text)>3145728 OR octet_length(receipt_value::text)+8192>4194304 THEN RAISE EXCEPTION 'OWN_CLOSE_LIMIT';END IF;
 IF NOT pg_try_advisory_xact_lock(hashtextextended('own-run:capacity:v1',0)) THEN RAISE EXCEPTION 'OWN_CLOSE_BUSY';END IF;
 IF(SELECT coalesce(sum(octet_length(le.body::text)+octet_length(le.snapshot::text)+octet_length(le.receipt::text)),0) FROM public.own_payroll_close_event le)+octet_length(body::text)+octet_length(snapshot_value::text)+octet_length(receipt_value::text)>67108864 OR(SELECT count(*) FROM public.own_payroll_close_event le WHERE le.tenant_id=(ctx->>'tenantId')::uuid AND le.source_binding_id=(ctx->>'sourceBindingId')::uuid)>=4000 THEN RAISE EXCEPTION 'OWN_CLOSE_LIMIT';END IF;
 INSERT INTO public.own_payroll_close_event(id,tenant_id,source_binding_id,group_id,command,period,liquidation_type,actor_membership_id,actor_person_id,actor_email,actor_label,actor_session_id,actor_session_version,release_sha,request_key,body,body_sha256,snapshot,snapshot_sha256,receipt,recorded_at) VALUES(event_id,(ctx->>'tenantId')::uuid,(ctx->>'sourceBindingId')::uuid,group_value,body->>'command',body->>'period',body->>'liquidationType',(ctx->>'membershipId')::uuid,(ctx->>'actorPersonId')::uuid,ctx->>'actorEmail',coalesce(nullif(ctx->>'actorLabel',''),'Autoridad municipal'),(p->>'actorSessionId')::uuid,(p->>'actorSessionVersion')::integer,p->>'releaseSha',key,body,fingerprint,snapshot_value,public.own_run_hash_v1(snapshot_value),receipt_value,at_time);RETURN receipt_value;END $$;
DO $$ DECLARE fn record;BEGIN FOR fn IN SELECT oid::regprocedure signature FROM pg_proc WHERE pronamespace='public'::regnamespace AND proname LIKE 'own_close_%' LOOP EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC,municontrol_actions_runtime_app',fn.signature);END LOOP;END $$;
GRANT EXECUTE ON FUNCTION public.own_close_detail_v1(jsonb,text,text),public.own_close_attempt_v1(jsonb,uuid),public.own_close_group_v1(jsonb,uuid),public.own_close_command_v1(jsonb,jsonb,uuid) TO municontrol_actions_runtime_app;
