-- Native receipt preparations and independent decisions. Does not sign, post
-- payroll, pay, assign IAM roles or use a live/historical GRH salary engine.
DO $$ BEGIN
 IF to_regclass('public.own_payroll_receipt_event') IS NOT NULL OR EXISTS(SELECT 1 FROM pg_proc WHERE pronamespace='public'::regnamespace AND proname LIKE 'own_receipt_%') THEN RAISE EXCEPTION 'OWN_RECEIPT_ALREADY_INSTALLED';END IF;
 IF to_regprocedure('public.own_close_context_v1(jsonb,boolean,boolean)') IS NULL OR to_regclass('public.tenant_action_employment_link') IS NULL THEN RAISE EXCEPTION 'OWN_RECEIPT_PREREQUISITE';END IF;
 IF EXISTS(SELECT 1 FROM public.iam_capability WHERE capability_key IN('payroll.receipt.prepare','payroll.receipt.approve','payroll.receipt.self.read')) THEN RAISE EXCEPTION 'OWN_RECEIPT_CAPABILITY_CONFLICT';END IF;
END $$;
INSERT INTO public.iam_capability(capability_key,label,description,scope_kind,sensitivity) VALUES
 ('payroll.receipt.prepare','Preparar recibos propios','Conservar una copia completa de liquidaciones propias cerradas para revisión. No firma ni paga.','tenant','privileged'),
 ('payroll.receipt.approve','Revisar recibos propios','Aprobar o retirar la disponibilidad de recibos propios conservando sus copias y decisiones.','tenant','privileged'),
 ('payroll.receipt.self.read','Consultar mis recibos propios','Consultar exclusivamente recibos aprobados del contrato vinculado a la membresía.','tenant','standard');
CREATE TABLE public.own_payroll_receipt_event(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES public.platform_tenant(id),source_binding_id uuid NOT NULL,
 batch_id uuid NOT NULL,command text NOT NULL CHECK(command IN('prepare','approve','withdraw')),
 actor_membership_id uuid NOT NULL,actor_person_id uuid NOT NULL REFERENCES public.person_identity(id),actor_email text NOT NULL CHECK(actor_email=lower(actor_email)),actor_label text NOT NULL,
 actor_session_id uuid NOT NULL REFERENCES public.tenant_identity_session(id),actor_session_version integer NOT NULL CHECK(actor_session_version>0),release_sha text NOT NULL CHECK(release_sha~'^[a-f0-9]{40}$'),request_key uuid NOT NULL,
 body jsonb NOT NULL CHECK(jsonb_typeof(body)='object' AND octet_length(body::text)<=16384),body_sha256 text NOT NULL CHECK(body_sha256~'^[a-f0-9]{64}$'),
 snapshot jsonb CHECK(snapshot IS NULL OR jsonb_typeof(snapshot)='object' AND octet_length(snapshot::text)<=33546240),snapshot_sha256 text NOT NULL CHECK(snapshot_sha256~'^[a-f0-9]{64}$'),recorded_at timestamptz NOT NULL DEFAULT clock_timestamp(),
 CHECK((command='prepare')=(snapshot IS NOT NULL)),CHECK((command='prepare')=(id=batch_id)),
 UNIQUE(tenant_id,source_binding_id,actor_membership_id,request_key),UNIQUE(tenant_id,source_binding_id,batch_id,command),
 FOREIGN KEY(tenant_id,source_binding_id) REFERENCES public.platform_tenant_source_binding(tenant_id,id),FOREIGN KEY(actor_membership_id,tenant_id) REFERENCES public.tenant_membership(id,tenant_id)
);
ALTER TABLE public.own_payroll_receipt_event ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.own_payroll_receipt_event FROM PUBLIC,municontrol_actions_runtime_app;
CREATE FUNCTION public.own_receipt_immutable_v1() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$ BEGIN RAISE EXCEPTION 'OWN_RECEIPT_IMMUTABLE';END $$;
CREATE TRIGGER own_receipt_event_immutable BEFORE UPDATE OR DELETE ON public.own_payroll_receipt_event FOR EACH ROW EXECUTE FUNCTION public.own_receipt_immutable_v1();
CREATE TRIGGER own_receipt_event_no_truncate BEFORE TRUNCATE ON public.own_payroll_receipt_event FOR EACH STATEMENT EXECUTE FUNCTION public.own_receipt_immutable_v1();
CREATE FUNCTION public.own_receipt_context_v1(p jsonb,operation text DEFAULT 'read') RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE ctx jsonb;BEGIN
 IF operation NOT IN('read','prepare','approve','withdraw','self') THEN RAISE EXCEPTION 'OWN_RECEIPT_INPUT_INVALID';END IF;
 IF operation='self' THEN
  IF NOT public.own_program_exact_v1(p,ARRAY['actorEmail','actorSessionId','actorSessionVersion','membershipId','releaseSha','tenantId']) THEN RAISE EXCEPTION 'OWN_RECEIPT_FORBIDDEN';END IF;
  ctx:=public.action_center_assert_tenant_read_session_v2(p->>'actorEmail',(p->>'actorSessionId')::uuid,(p->>'actorSessionVersion')::integer,p->>'releaseSha',(p->>'tenantId')::uuid,(p->>'membershipId')::uuid);
  IF NOT public.action_center_context_has_capability(ctx,'actions.read') OR NOT public.action_center_context_has_capability(ctx,'payroll.receipt.self.read') THEN RAISE EXCEPTION 'OWN_RECEIPT_FORBIDDEN';END IF;
 ELSE
  ctx:=public.own_close_context_v1(p,true,false);
  IF operation<>'read' AND NOT public.action_center_context_has_capability(ctx,CASE WHEN operation='prepare' THEN 'payroll.receipt.prepare' ELSE 'payroll.receipt.approve' END) THEN RAISE EXCEPTION 'OWN_RECEIPT_FORBIDDEN';END IF;
 END IF;RETURN ctx;
END $$;
CREATE FUNCTION public.own_receipt_text_v1(v jsonb,lo integer,hi integer) RETURNS boolean LANGUAGE sql IMMUTABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
 SELECT coalesce(jsonb_typeof(v)='string' AND length(v#>>'{}') BETWEEN lo AND hi AND btrim(v#>>'{}')=v#>>'{}' AND normalize(v#>>'{}',NFC)=v#>>'{}' AND v#>>'{}'!~'[<>[:cntrl:]\u202a-\u202e\u2066-\u2069]',false) $$;
CREATE FUNCTION public.own_receipt_params_v1(v jsonb) RETURNS void LANGUAGE plpgsql IMMUTABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE k text;a text;b text;BEGIN
 IF NOT public.own_program_exact_v1(v,ARRAY['period','types','filters','issuer','paymentDate','legend']) OR jsonb_typeof(v->'period') IS DISTINCT FROM 'string' OR v->>'period'!~'^(19|20)[0-9]{2}-(0[1-9]|1[0-2])$' OR jsonb_typeof(v->'types') IS DISTINCT FROM 'array' THEN RAISE EXCEPTION 'OWN_RECEIPT_INPUT_INVALID';END IF;
 IF jsonb_array_length(v->'types') NOT BETWEEN 1 AND 7 OR EXISTS(SELECT 1 FROM jsonb_array_elements(v->'types') x WHERE jsonb_typeof(x) IS DISTINCT FROM 'string' OR x#>>'{}' NOT IN('monthly','first_fortnight','sac','vacation','supplementary','final','other')) OR(SELECT count(DISTINCT value) FROM jsonb_array_elements(v->'types'))<>jsonb_array_length(v->'types') OR v->'types' IS DISTINCT FROM(SELECT jsonb_agg(x ORDER BY x COLLATE "C") FROM jsonb_array_elements_text(v->'types') x) THEN RAISE EXCEPTION 'OWN_RECEIPT_INPUT_INVALID';END IF;
 IF NOT public.own_program_exact_v1(v->'filters',ARRAY['employeeFrom','employeeTo','agreementFrom','agreementTo','departmentFrom','departmentTo']) OR NOT public.own_program_exact_v1(v->'issuer',ARRAY['name','taxId','address']) OR NOT public.own_receipt_text_v1(v#>'{issuer,name}',3,160) OR NOT public.own_receipt_text_v1(v#>'{issuer,address}',3,240) OR jsonb_typeof(v#>'{issuer,taxId}') IS DISTINCT FROM 'string' OR v#>>'{issuer,taxId}'!~'^[0-9]{11}$' OR NOT public.own_receipt_text_v1(v->'legend',0,240) THEN RAISE EXCEPTION 'OWN_RECEIPT_INPUT_INVALID';END IF;
 FOREACH k IN ARRAY ARRAY['employee','agreement','department'] LOOP
  a:=v#>>ARRAY['filters',k||'From'];b:=v#>>ARRAY['filters',k||'To'];
  IF jsonb_typeof(v#>ARRAY['filters',k||'From']) IS DISTINCT FROM 'string' OR jsonb_typeof(v#>ARRAY['filters',k||'To']) IS DISTINCT FROM 'string' OR a!~'^([0-9]{1,9})?$' OR b!~'^([0-9]{1,9})?$' OR(a<>'' AND b<>'' AND a::numeric>b::numeric) THEN RAISE EXCEPTION 'OWN_RECEIPT_INPUT_INVALID';END IF;
 END LOOP;
 IF v->'paymentDate' IS DISTINCT FROM 'null'::jsonb THEN
  IF jsonb_typeof(v->'paymentDate') IS DISTINCT FROM 'string' OR v->>'paymentDate'!~'^(19|20)[0-9]{2}-(0[1-9]|1[0-2])-[0-9]{2}$' THEN RAISE EXCEPTION 'OWN_RECEIPT_INPUT_INVALID';END IF;
  BEGIN IF to_char((v->>'paymentDate')::date,'YYYY-MM-DD')<>v->>'paymentDate' THEN RAISE EXCEPTION 'OWN_RECEIPT_INPUT_INVALID';END IF;EXCEPTION WHEN datetime_field_overflow OR invalid_datetime_format THEN RAISE EXCEPTION 'OWN_RECEIPT_INPUT_INVALID';END;
 END IF;
END $$;
CREATE FUNCTION public.own_receipt_source_version_v1(ctx jsonb,params jsonb) RETURNS text LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
 SELECT public.own_run_hash_v1(coalesce(jsonb_agg(jsonb_build_object('id',e.id,'groupId',e.group_id,'command',e.command,'snapshotSha256',e.snapshot_sha256) ORDER BY e.id),'[]')) FROM public.own_payroll_close_event e WHERE e.tenant_id=(ctx->>'tenantId')::uuid AND e.source_binding_id=(ctx->>'sourceBindingId')::uuid AND e.period=params->>'period' AND params->'types' ? e.liquidation_type $$;
CREATE FUNCTION public.own_receipt_snapshot_v1(ctx jsonb,params jsonb) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE g public.own_payroll_close_event;c public.own_payroll_run_capture;employee jsonb;line jsonb;item jsonb;identity_row record;record_value jsonb;concepts jsonb;records jsonb:='[]';sources jsonb:='[]';n integer;concept_count integer:=0;result_value jsonb;BEGIN
 PERFORM public.own_receipt_params_v1(params);PERFORM public.own_run_lock_v1(ctx);
 LOCK TABLE public.person_identity,public.employment_contract,public.native_employee_registration IN SHARE MODE NOWAIT;
 FOR g IN SELECT e.* FROM public.own_payroll_close_event e WHERE e.tenant_id=(ctx->>'tenantId')::uuid AND e.source_binding_id=(ctx->>'sourceBindingId')::uuid AND e.period=params->>'period' AND params->'types' ? e.liquidation_type AND e.command='close' AND NOT EXISTS(SELECT 1 FROM public.own_payroll_close_event r WHERE r.tenant_id=e.tenant_id AND r.source_binding_id=e.source_binding_id AND r.group_id=e.id AND r.command='reopen') ORDER BY e.liquidation_type,e.id LOOP
  IF g.snapshot_sha256<>public.own_run_hash_v1(g.snapshot) OR g.snapshot->>'version'<>'own-close-snapshot.v1' OR g.snapshot->>'period'<>g.period OR g.snapshot->>'liquidationType'<>g.liquidation_type OR jsonb_array_length(g.snapshot->'employees')<>(g.snapshot->>'employeeCount')::integer OR jsonb_array_length(g.snapshot->'concepts')<>(g.snapshot->>'conceptCount')::integer THEN RAISE EXCEPTION 'OWN_RECEIPT_CONTRACT_INVALID';END IF;n:=0;
  FOR employee IN SELECT value FROM jsonb_array_elements(g.snapshot->'employees') ORDER BY(value->>'employeeNumber')::numeric,value->>'contractId' LOOP
   IF EXISTS(SELECT 1 FROM unnest(ARRAY['employee','agreement','department'],ARRAY['employeeNumber','agreementCode','departmentCode']) f(range_key,field_key) WHERE nullif(params#>>ARRAY['filters',range_key||'From'],'')::numeric>(employee->>field_key)::numeric OR nullif(params#>>ARRAY['filters',range_key||'To'],'')::numeric<(employee->>field_key)::numeric) THEN CONTINUE;END IF;
   SELECT pi.id AS person_id,pi.full_name,pi.dni,pi.cuil,reg.id AS registration_id INTO identity_row FROM public.native_employee_registration reg JOIN public.employment_contract ec ON ec.id=reg.contract_id AND ec.person_id=reg.person_id AND ec.tenant_id=reg.tenant_id AND ec.source_system='MUNICONTROL' AND ec.source_batch_id IS NULL JOIN public.person_identity pi ON pi.id=reg.person_id WHERE reg.contract_id=(employee->>'contractId')::uuid AND reg.tenant_id=g.tenant_id AND reg.source_binding_id=g.source_binding_id;
   IF NOT FOUND OR NOT public.own_receipt_text_v1(to_jsonb(identity_row.full_name),3,160) OR coalesce(identity_row.dni,'')!~'^[0-9]{5,12}$' OR coalesce(identity_row.cuil,'')!~'^[0-9]{11}$' THEN RAISE EXCEPTION 'OWN_RECEIPT_IDENTITY_REQUIRED';END IF;
   SELECT * INTO c FROM public.own_payroll_run_capture WHERE id=(employee->>'runId')::uuid AND tenant_id=g.tenant_id AND source_binding_id=g.source_binding_id;
   IF c.id IS NULL OR c.payload_sha256<>public.own_run_hash_v1(c.payload) THEN RAISE EXCEPTION 'OWN_RECEIPT_CONTRACT_INVALID';END IF;concepts:='[]';
   FOR line IN SELECT value FROM jsonb_array_elements(g.snapshot->'concepts') WHERE value->>'contractId'=employee->>'contractId' ORDER BY(value->>'conceptCode')::numeric LOOP
    SELECT x.value INTO item FROM jsonb_array_elements(c.payload#>'{programState,salaryCatalog,items}') x WHERE x.value->>'kind'='concept' AND x.value->>'code'=line->>'conceptCode' AND x.value->>'agreementCode'=employee->>'agreementCode' AND x.value->'active'='true'::jsonb AND x.value->>'validFrom'<=g.period AND(x.value->'validUntil'='null'::jsonb OR x.value->>'validUntil'>=g.period);
    IF item IS NULL OR(SELECT count(*) FROM jsonb_array_elements(c.payload#>'{programState,salaryCatalog,items}') x WHERE x.value->>'kind'='concept' AND x.value->>'code'=line->>'conceptCode' AND x.value->>'agreementCode'=employee->>'agreementCode' AND x.value->'active'='true'::jsonb AND x.value->>'validFrom'<=g.period AND(x.value->'validUntil'='null'::jsonb OR x.value->>'validUntil'>=g.period))<>1 OR NOT public.own_receipt_text_v1(item->'label',1,240) OR item->>'nature'<>line->>'nature' THEN RAISE EXCEPTION 'OWN_RECEIPT_LABEL_REQUIRED';END IF;
    concepts:=concepts||jsonb_build_array(jsonb_build_object('code',line->>'conceptCode','label',item->>'label','nature',line->>'nature','unit',line->>'unit','amount',line->>'amount','labelSourceSha256',c.payload_sha256));
   END LOOP;
   IF jsonb_array_length(concepts)<>(employee->>'conceptCount')::integer OR EXISTS(SELECT 1 FROM jsonb_array_elements(records) old JOIN jsonb_array_elements(sources) source ON source.value->>'id'=old.value->>'sourceGroupId' WHERE source.value->>'type'=g.liquidation_type AND old.value->>'contractId'=employee->>'contractId') THEN RAISE EXCEPTION 'OWN_RECEIPT_CONTRACT_INVALID';END IF;
   record_value:=jsonb_build_object('sourceGroupId',g.id,'contractId',employee->>'contractId','personId',identity_row.person_id,'registrationId',identity_row.registration_id,'employeeNumber',employee->>'employeeNumber','name',identity_row.full_name,'dni',identity_row.dni,'cuil',identity_row.cuil,'agreementCode',employee->>'agreementCode','departmentCode',employee->>'departmentCode','runId',employee->>'runId','liquidationVersion',employee->'liquidationVersion','precision',employee->'precision','totals',(employee->'totals')-'contractId','concepts',concepts);
   records:=records||jsonb_build_array(record_value);n:=n+1;concept_count:=concept_count+jsonb_array_length(concepts);
   IF jsonb_array_length(records)>20000 OR concept_count>250000 THEN RAISE EXCEPTION 'OWN_RECEIPT_LIMIT';END IF;
  END LOOP;
  sources:=sources||jsonb_build_array(jsonb_build_object('id',g.id,'snapshotSha256',g.snapshot_sha256,'period',g.period,'type',g.liquidation_type,'employeeCount',g.snapshot->'employeeCount','populationCount',g.snapshot->'populationCount','selectedCount',n));IF jsonb_array_length(sources)>1000 THEN RAISE EXCEPTION 'OWN_RECEIPT_LIMIT';END IF;
 END LOOP;
 result_value:=jsonb_build_object('version','own-receipt-snapshot.v1','params',params,'sourceVersion',public.own_receipt_source_version_v1(ctx,params),'sources',sources,'records',records,'recordCount',jsonb_array_length(records),'conceptCount',concept_count,'identityBasis','native_registration_immutable','paymentDateBasis','declared','signatureState','pending','payrollPosted',false,'paymentExecuted',false);
 IF octet_length(result_value::text)>33546240 THEN RAISE EXCEPTION 'OWN_RECEIPT_LIMIT';END IF;RETURN result_value;
END $$;
CREATE FUNCTION public.own_receipt_preview_v1(p jsonb,params jsonb) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE ctx jsonb;s jsonb;BEGIN ctx:=public.own_receipt_context_v1(p);s:=public.own_receipt_snapshot_v1(ctx,params);RETURN jsonb_build_object('version','own-receipt-preview.v1','scopeVersion',public.native_salary_scope_v1(ctx),'snapshot',s,'snapshotSha256',public.own_run_hash_v1(s),'permissions',jsonb_build_object('canPrepare',public.action_center_context_has_capability(ctx,'payroll.receipt.prepare')));END $$;
CREATE FUNCTION public.own_receipt_event_v1(e public.own_payroll_receipt_event,replay boolean DEFAULT false) RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
 SELECT jsonb_build_object('version','own-receipt-event.v1','id',e.id,'key',e.request_key,'body',e.body,'bodySha256',e.body_sha256,'batchId',e.batch_id,'recordedAt',e.recorded_at,'replayed',replay) $$;
CREATE FUNCTION public.own_receipt_batch_value_v1(ctx jsonb,e public.own_payroll_receipt_event) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE r public.own_payroll_receipt_event;state_value text:='prepared';current_value boolean;independent boolean;BEGIN
 IF e.id IS NULL OR e.command<>'prepare' OR e.snapshot_sha256<>public.own_run_hash_v1(e.snapshot) THEN RAISE EXCEPTION 'OWN_RECEIPT_CONTRACT_INVALID';END IF;
 SELECT * INTO r FROM public.own_payroll_receipt_event WHERE tenant_id=e.tenant_id AND source_binding_id=e.source_binding_id AND batch_id=e.id AND command<>'prepare' ORDER BY CASE command WHEN 'withdraw' THEN 0 ELSE 1 END LIMIT 1;
 IF r.id IS NOT NULL THEN state_value:=CASE r.command WHEN 'approve' THEN 'approved' ELSE 'withdrawn' END;END IF;
 current_value:=e.snapshot->>'sourceVersion'=public.own_receipt_source_version_v1(ctx,e.snapshot->'params');independent:=e.actor_membership_id IS DISTINCT FROM(ctx->>'membershipId')::uuid AND e.actor_person_id IS DISTINCT FROM(ctx->>'actorPersonId')::uuid AND e.actor_email IS DISTINCT FROM ctx->>'actorEmail';
 RETURN jsonb_build_object('version','own-receipt-batch.v1','id',e.id,'preparedAt',e.recorded_at,'preparedBy',e.actor_label,'snapshot',e.snapshot,'snapshotSha256',e.snapshot_sha256,'state',state_value,'sourceCurrent',current_value,'review',CASE WHEN r.id IS NULL THEN NULL ELSE jsonb_build_object('id',r.id,'decision',state_value,'at',r.recorded_at,'by',r.actor_label,'reason',r.body->>'reason') END,'permissions',jsonb_build_object('canApprove',state_value='prepared' AND current_value AND independent AND public.action_center_context_has_capability(ctx,'payroll.receipt.approve'),'canWithdraw',state_value<>'withdrawn' AND public.action_center_context_has_capability(ctx,'payroll.receipt.approve'),'canDownload',state_value<>'withdrawn' AND current_value));
END $$;
CREATE FUNCTION public.own_receipt_batch_v1(p jsonb,target uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE ctx jsonb;e public.own_payroll_receipt_event;BEGIN ctx:=public.own_receipt_context_v1(p);SELECT * INTO e FROM public.own_payroll_receipt_event WHERE id=target AND tenant_id=(ctx->>'tenantId')::uuid AND source_binding_id=(ctx->>'sourceBindingId')::uuid AND command='prepare';IF NOT FOUND THEN RAISE EXCEPTION 'OWN_RECEIPT_NOT_FOUND';END IF;RETURN public.own_receipt_batch_value_v1(ctx,e);END $$;
CREATE FUNCTION public.own_receipt_list_v1(p jsonb,period_value text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE ctx jsonb;items jsonb;BEGIN ctx:=public.own_receipt_context_v1(p);IF coalesce(period_value,'')!~'^(19|20)[0-9]{2}-(0[1-9]|1[0-2])$' THEN RAISE EXCEPTION 'OWN_RECEIPT_INPUT_INVALID';END IF;
 SELECT coalesce(jsonb_agg(jsonb_build_object('id',e.id,'preparedAt',e.recorded_at,'preparedBy',e.actor_label,'recordCount',e.snapshot->'recordCount','types',e.snapshot#>'{params,types}') ORDER BY e.recorded_at DESC,e.id),'[]') INTO items FROM public.own_payroll_receipt_event e WHERE tenant_id=(ctx->>'tenantId')::uuid AND source_binding_id=(ctx->>'sourceBindingId')::uuid AND command='prepare' AND snapshot#>>'{params,period}'=period_value;
 IF jsonb_array_length(items)>1000 THEN RAISE EXCEPTION 'OWN_RECEIPT_LIMIT';END IF;RETURN jsonb_build_object('version','own-receipt-list.v1','scopeVersion',public.native_salary_scope_v1(ctx),'period',period_value,'items',items);
END $$;
CREATE FUNCTION public.own_receipt_attempt_v1(p jsonb,key uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE ctx jsonb;e public.own_payroll_receipt_event;BEGIN ctx:=public.own_receipt_context_v1(p);SELECT * INTO e FROM public.own_payroll_receipt_event WHERE tenant_id=(ctx->>'tenantId')::uuid AND source_binding_id=(ctx->>'sourceBindingId')::uuid AND actor_membership_id=(ctx->>'membershipId')::uuid AND actor_person_id=(ctx->>'actorPersonId')::uuid AND actor_email=ctx->>'actorEmail' AND request_key=key;IF NOT FOUND THEN RAISE EXCEPTION 'OWN_RECEIPT_NOT_FOUND';END IF;RETURN public.own_receipt_event_v1(e,true);END $$;
CREATE FUNCTION public.own_receipt_command_v1(p jsonb,body jsonb,key uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp SET timezone='UTC' AS $$
DECLARE ctx jsonb;e public.own_payroll_receipt_event;prepared public.own_payroll_receipt_event;s jsonb;view_value jsonb;id_value uuid:=gen_random_uuid();batch_value uuid;hash_value text;fingerprint text;val text;BEGIN
 IF NOT public.own_program_exact_v1(body,ARRAY['command','scopeVersion','sourceVersion','params','batchId','batchSha256','reason','reviewConfirmed']) OR jsonb_typeof(body->'command') IS DISTINCT FROM 'string' OR body->>'command' NOT IN('prepare','approve','withdraw') OR NOT public.own_receipt_text_v1(body->'reason',10,1000) OR octet_length(body::text)>16384 OR key IS NULL OR key::text!~'^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$' THEN RAISE EXCEPTION 'OWN_RECEIPT_INPUT_INVALID';END IF;
 FOREACH val IN ARRAY ARRAY['scopeVersion','sourceVersion'] LOOP IF jsonb_typeof(body->val) IS DISTINCT FROM 'string' OR body->>val!~'^[a-f0-9]{64}$' THEN RAISE EXCEPTION 'OWN_RECEIPT_INPUT_INVALID';END IF;END LOOP;
 ctx:=public.own_receipt_context_v1(p,body->>'command');PERFORM public.own_run_lock_v1(ctx);fingerprint:=public.own_run_hash_v1(body);
 SELECT * INTO e FROM public.own_payroll_receipt_event WHERE tenant_id=(ctx->>'tenantId')::uuid AND source_binding_id=(ctx->>'sourceBindingId')::uuid AND actor_membership_id=(ctx->>'membershipId')::uuid AND request_key=key;
 IF FOUND THEN IF e.actor_person_id IS DISTINCT FROM(ctx->>'actorPersonId')::uuid OR e.actor_email IS DISTINCT FROM ctx->>'actorEmail' THEN RAISE EXCEPTION 'OWN_RECEIPT_FORBIDDEN';END IF;IF e.body<>body OR e.body_sha256<>fingerprint THEN RAISE EXCEPTION 'OWN_RECEIPT_IDEMPOTENCY_REUSE';END IF;RETURN public.own_receipt_event_v1(e,true);END IF;
 IF body->>'scopeVersion'<>public.native_salary_scope_v1(ctx) THEN RAISE EXCEPTION 'OWN_RECEIPT_STATE_CHANGED';END IF;
 IF body->>'command'='prepare' THEN
  IF body->'reviewConfirmed' IS DISTINCT FROM 'false'::jsonb OR body->'batchId' IS DISTINCT FROM 'null'::jsonb OR body->'batchSha256' IS DISTINCT FROM 'null'::jsonb THEN RAISE EXCEPTION 'OWN_RECEIPT_INPUT_INVALID';END IF;
  s:=public.own_receipt_snapshot_v1(ctx,body->'params');IF s->>'sourceVersion'<>body->>'sourceVersion' THEN RAISE EXCEPTION 'OWN_RECEIPT_STATE_CHANGED';END IF;IF(s->>'recordCount')::integer=0 THEN RAISE EXCEPTION 'OWN_RECEIPT_EMPTY';END IF;batch_value:=id_value;hash_value:=public.own_run_hash_v1(s);
  IF EXISTS(SELECT 1 FROM public.own_payroll_receipt_event old WHERE old.tenant_id=(ctx->>'tenantId')::uuid AND old.source_binding_id=(ctx->>'sourceBindingId')::uuid AND old.command='prepare' AND old.snapshot_sha256=hash_value AND NOT EXISTS(SELECT 1 FROM public.own_payroll_receipt_event r WHERE r.batch_id=old.id AND r.command='withdraw')) THEN RAISE EXCEPTION 'OWN_RECEIPT_DUPLICATE';END IF;
 ELSE
  IF body->'reviewConfirmed' IS DISTINCT FROM 'true'::jsonb OR body->'params' IS DISTINCT FROM 'null'::jsonb OR jsonb_typeof(body->'batchId') IS DISTINCT FROM 'string' OR body->>'batchId'!~'^[a-f0-9]{8}(-[a-f0-9]{4}){3}-[a-f0-9]{12}$' OR jsonb_typeof(body->'batchSha256') IS DISTINCT FROM 'string' OR body->>'batchSha256'!~'^[a-f0-9]{64}$' THEN RAISE EXCEPTION 'OWN_RECEIPT_INPUT_INVALID';END IF;
  batch_value:=(body->>'batchId')::uuid;SELECT * INTO prepared FROM public.own_payroll_receipt_event WHERE id=batch_value AND tenant_id=(ctx->>'tenantId')::uuid AND source_binding_id=(ctx->>'sourceBindingId')::uuid AND command='prepare';IF NOT FOUND THEN RAISE EXCEPTION 'OWN_RECEIPT_NOT_FOUND';END IF;
  view_value:=public.own_receipt_batch_value_v1(ctx,prepared);hash_value:=prepared.snapshot_sha256;
  IF hash_value<>body->>'batchSha256' OR prepared.snapshot->>'sourceVersion'<>body->>'sourceVersion' THEN RAISE EXCEPTION 'OWN_RECEIPT_STATE_CHANGED';END IF;
  IF NOT(view_value#>>ARRAY['permissions',CASE WHEN body->>'command'='approve' THEN 'canApprove' ELSE 'canWithdraw' END])::boolean THEN RAISE EXCEPTION 'OWN_RECEIPT_DECISION_INVALID';END IF;
 END IF;
 IF NOT pg_try_advisory_xact_lock(hashtextextended('own-receipt:capacity:v1',0)) THEN RAISE EXCEPTION 'OWN_RECEIPT_BUSY';END IF;
 IF(SELECT count(*) FROM public.own_payroll_receipt_event WHERE tenant_id=(ctx->>'tenantId')::uuid AND source_binding_id=(ctx->>'sourceBindingId')::uuid)>=3000 OR(SELECT coalesce(sum(coalesce(octet_length(le.snapshot::text),0)+octet_length(le.body::text)),0) FROM public.own_payroll_receipt_event le)+coalesce(octet_length(s::text),0)+octet_length(body::text)>268435456 THEN RAISE EXCEPTION 'OWN_RECEIPT_LIMIT';END IF;
 INSERT INTO public.own_payroll_receipt_event(id,tenant_id,source_binding_id,batch_id,command,actor_membership_id,actor_person_id,actor_email,actor_label,actor_session_id,actor_session_version,release_sha,request_key,body,body_sha256,snapshot,snapshot_sha256) VALUES(id_value,(ctx->>'tenantId')::uuid,(ctx->>'sourceBindingId')::uuid,batch_value,body->>'command',(ctx->>'membershipId')::uuid,(ctx->>'actorPersonId')::uuid,ctx->>'actorEmail',coalesce(nullif(ctx->>'actorLabel',''),'Autoridad municipal'),(p->>'actorSessionId')::uuid,(p->>'actorSessionVersion')::integer,p->>'releaseSha',key,body,fingerprint,s,hash_value) RETURNING * INTO e;RETURN public.own_receipt_event_v1(e);
END $$;
CREATE FUNCTION public.own_receipt_self_v1(p jsonb) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE ctx jsonb;target uuid;person uuid;items jsonb;BEGIN ctx:=public.own_receipt_context_v1(p,'self');
 SELECT link.employment_contract_id,ec.person_id INTO target,person FROM public.tenant_action_employment_link link JOIN public.employment_contract ec ON ec.id=link.employment_contract_id AND ec.tenant_id=link.tenant_id AND ec.source_system='MUNICONTROL' AND ec.source_batch_id IS NULL JOIN public.native_employee_registration reg ON reg.contract_id=ec.id AND reg.person_id=ec.person_id AND reg.tenant_id=ec.tenant_id AND reg.source_binding_id=link.source_binding_id WHERE link.membership_id=(ctx->>'membershipId')::uuid AND link.tenant_id=(ctx->>'tenantId')::uuid AND link.source_binding_id=(ctx->>'sourceBindingId')::uuid AND link.active FOR SHARE OF link,ec,reg;
 IF target IS NULL OR(ctx->>'actorPersonId' IS NOT NULL AND person IS DISTINCT FROM(ctx->>'actorPersonId')::uuid) OR(SELECT count(*) FROM public.tenant_action_employment_link link WHERE link.membership_id=(ctx->>'membershipId')::uuid AND link.tenant_id=(ctx->>'tenantId')::uuid AND link.source_binding_id=(ctx->>'sourceBindingId')::uuid AND link.active)<>1 THEN RAISE EXCEPTION 'OWN_RECEIPT_FORBIDDEN';END IF;
 SELECT coalesce(jsonb_agg(jsonb_build_object('batchId',e.id,'preparedAt',e.recorded_at,'approvedAt',a.recorded_at,'params',(e.snapshot->'params')-'filters'-'types','record',r.value,'source',s.value-'employeeCount'-'populationCount'-'selectedCount','signatureState','pending','paymentDateBasis','declared','payrollPosted',false,'paymentExecuted',false) ORDER BY e.recorded_at DESC,e.id,r.value->>'sourceGroupId'),'[]') INTO items FROM public.own_payroll_receipt_event e JOIN public.own_payroll_receipt_event a ON a.batch_id=e.id AND a.command='approve' AND a.tenant_id=e.tenant_id AND a.source_binding_id=e.source_binding_id CROSS JOIN LATERAL jsonb_array_elements(e.snapshot->'records') r JOIN LATERAL jsonb_array_elements(e.snapshot->'sources') s ON s.value->>'id'=r.value->>'sourceGroupId' WHERE e.tenant_id=(ctx->>'tenantId')::uuid AND e.source_binding_id=(ctx->>'sourceBindingId')::uuid AND e.command='prepare' AND r.value->>'contractId'=target::text AND r.value->>'personId'=person::text AND e.snapshot_sha256=public.own_run_hash_v1(e.snapshot) AND e.snapshot->>'sourceVersion'=public.own_receipt_source_version_v1(ctx,e.snapshot->'params') AND NOT EXISTS(SELECT 1 FROM public.own_payroll_receipt_event w WHERE w.batch_id=e.id AND w.command='withdraw');
 IF jsonb_array_length(items)>1000 OR octet_length(items::text)>33546240 THEN RAISE EXCEPTION 'OWN_RECEIPT_LIMIT';END IF;RETURN jsonb_build_object('version','own-receipt-self.v1','items',items);
END $$;
DO $$ DECLARE fn record;BEGIN FOR fn IN SELECT oid::regprocedure signature FROM pg_proc WHERE pronamespace='public'::regnamespace AND proname LIKE 'own_receipt_%' LOOP EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC,municontrol_actions_runtime_app',fn.signature);END LOOP;END $$;
GRANT EXECUTE ON FUNCTION public.own_receipt_preview_v1(jsonb,jsonb),public.own_receipt_list_v1(jsonb,text),public.own_receipt_batch_v1(jsonb,uuid),public.own_receipt_attempt_v1(jsonb,uuid),public.own_receipt_command_v1(jsonb,jsonb,uuid),public.own_receipt_self_v1(jsonb) TO municontrol_actions_runtime_app;
