-- Declared payment channel, independent from recipient CBU/bank. No data rewrite.
DO $guard$ DECLARE fingerprint text; BEGIN
 SELECT encode(public.digest(replace(p.prosrc,E'\r\n',E'\n'),'sha256'),'hex') INTO fingerprint FROM pg_proc p WHERE p.oid=to_regprocedure('public.own_bank_accounts_definition_v1(jsonb,jsonb,jsonb)');
 IF fingerprint='fb83ab4dbf1df01287de9f99a8e60e1309066777847c8269653ac8c4f06cde7e' THEN RAISE EXCEPTION 'BANK_CHANNEL_ALREADY_INSTALLED';END IF;
 IF fingerprint IS DISTINCT FROM 'c16e40b861ffc37b11411ffe3efabd7801177fbad6d04c7b4fd8425329a9f0d7' THEN RAISE EXCEPTION 'BANK_CHANNEL_PRIOR_SOURCE_CHANGED';END IF;
END $guard$;
CREATE OR REPLACE FUNCTION public.own_bank_accounts_definition_v1(d jsonb,sources jsonb,baseline jsonb DEFAULT NULL) RETURNS jsonb LANGUAGE plpgsql IMMUTABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE r jsonb;result jsonb;
BEGIN
 IF NOT public.own_program_exact_v1(d,ARRAY['accounts']) OR jsonb_typeof(d->'accounts') IS DISTINCT FROM 'array' OR jsonb_array_length(d->'accounts')=0 THEN RAISE EXCEPTION 'BANK_ACCOUNTS_INPUT_INVALID';END IF;
 IF jsonb_array_length(d->'accounts')>10000 THEN RAISE EXCEPTION 'BANK_ACCOUNTS_LIMIT';END IF;
 FOR r IN SELECT value FROM jsonb_array_elements(d->'accounts') LOOP
  IF NOT (public.own_program_exact_v1(r,ARRAY['id','contractId','bankLabel','cbu','accountType','accountNumber','currency','validFrom','validUntil','status','documentReference']) OR public.own_program_exact_v1(r,ARRAY['id','contractId','bankLabel','cbu','accountType','accountNumber','currency','validFrom','validUntil','status','documentReference','paymentChannelVersion','paymentChannel'])) OR jsonb_typeof(r->'id') IS DISTINCT FROM 'string' OR r->>'id'!~*'^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$' OR jsonb_typeof(r->'contractId') IS DISTINCT FROM 'string' OR r->>'contractId'!~*'^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$' OR NOT public.own_program_text_v1(r->'bankLabel',1,160) OR NOT public.own_bank_accounts_cbu_v1(r->'cbu') OR (r->'accountType'<>'null' AND (jsonb_typeof(r->'accountType') IS DISTINCT FROM 'string' OR r->>'accountType' NOT IN('CA','CC'))) OR (r->'accountNumber'<>'null' AND NOT public.own_program_text_v1(r->'accountNumber',1,40)) OR jsonb_typeof(r->'currency') IS DISTINCT FROM 'string' OR r->>'currency' NOT IN('ARS','USD') OR jsonb_typeof(r->'status') IS DISTINCT FROM 'string' OR r->>'status' NOT IN('enabled','withdrawn') OR NOT public.own_program_text_v1(r->'documentReference',3,180) OR NOT public.own_bank_accounts_day_v1(r->'validFrom') OR (r->'validUntil'<>'null' AND (NOT public.own_bank_accounts_day_v1(r->'validUntil') OR r->>'validUntil'<r->>'validFrom')) THEN RAISE EXCEPTION 'BANK_ACCOUNTS_INPUT_INVALID';END IF;
  IF r ? 'paymentChannelVersion' AND (jsonb_typeof(r->'paymentChannelVersion') IS DISTINCT FROM 'string' OR r->>'paymentChannelVersion'<>'own-bank-payment-channel.v1' OR (r->'paymentChannel'<>'null' AND (jsonb_typeof(r->'paymentChannel') IS DISTINCT FROM 'string' OR r->>'paymentChannel' NOT IN('bank_payroll','credicoop_transfers'))) OR (r->>'paymentChannel'='credicoop_transfers' AND r->>'accountType' IS DISTINCT FROM 'CA')) THEN RAISE EXCEPTION 'BANK_ACCOUNTS_INPUT_INVALID';END IF;
 END LOOP;
 IF EXISTS(SELECT 1 FROM jsonb_array_elements(d->'accounts') x GROUP BY lower(x->>'id') HAVING count(*)>1) THEN RAISE EXCEPTION 'BANK_ACCOUNTS_INPUT_INVALID';END IF;
 PERFORM public.own_bank_accounts_history_v1(baseline,d);
 IF EXISTS(SELECT 1 FROM jsonb_array_elements(d->'accounts') x LEFT JOIN jsonb_array_elements(sources->'contracts') c ON lower(c->>'contractId')=lower(x->>'contractId') LEFT JOIN jsonb_array_elements(coalesce(nullif(baseline,'null')->'accounts','[]')) old ON lower(old->>'id')=lower(x->>'id') WHERE c IS NULL AND (old IS NULL OR NOT(x=old OR x->>'status'='withdrawn' AND x=old||jsonb_build_object('status','withdrawn')))) THEN RAISE EXCEPTION 'BANK_ACCOUNTS_SOURCE_REQUIRED';END IF;
 IF EXISTS(SELECT 1 FROM(SELECT x->>'validFrom' started,max(coalesce(x->>'validUntil','9999-12-31')) OVER(PARTITION BY lower(x->>'contractId') ORDER BY x->>'validFrom' ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING) prior_end FROM jsonb_array_elements(d->'accounts') x WHERE x->>'status'='enabled') intervals WHERE intervals.prior_end>=intervals.started) THEN RAISE EXCEPTION 'BANK_ACCOUNTS_OVERLAP';END IF;
 SELECT jsonb_build_object('accounts',jsonb_agg(x ORDER BY lower(x->>'id') COLLATE "C")) INTO result FROM jsonb_array_elements(d->'accounts') x;
 RETURN result;
END $$;
