// SPDX-License-Identifier: GPL-2.0-only
import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtemp,rm,writeFile,readFile,readdir,mkdir,symlink} from 'node:fs/promises';import path from 'node:path';import os from 'node:os';
import {CaptureStore,hash} from '../store.mjs';import {dataSet} from './fixture.mjs';
import {DeliveryStore,partPayload,checkReceipt,validateBatch,validateSenderConfig,loadToken,sendPart,ENDPOINT} from '../delivery.mjs';import {runSender} from '../sender.mjs';
const capturedAt='2026-09-13T09:00:00.000Z',token='s'.repeat(43),connectorKey='qa-pm10-connector';
async function temp(fn){const d=await mkdtemp(path.join(os.tmpdir(),'pm10-delivery-'));try{return await fn(d);}finally{await rm(d,{recursive:true,force:true});}}
async function fixture(d,count=3){const s=await new CaptureStore(d,{freeBytes:async()=>1e10}).init(),raw=dataSet(count);for(let i=0;i<count;i++)raw.writeUInt16LE(i+1,4+i*40);const saved=await s.save(raw,{capturedAt});return {s,raw,saved,store:await new DeliveryStore(d).init()};}
const receipt=p=>({version:'pm10-receipt.v1',receiptId:'a1111111-1111-4111-8111-111111111111',batchId:p.batchId,partStart:p.partStart,partSha256:p.partSha256,snapshotSha256:p.snapshotSha256,count:p.ordinals.length,newCanonical:p.ordinals.length,observed:0,duplicates:0,receivedAt:capturedAt,persisted:true,payrollModified:false,replayed:false});
const reply=(p,patch={})=>new Response(JSON.stringify({ok:true,receipt:{...receipt(p),...patch}}),{status:200});
const config=d=>validateSenderConfig({schema:'pm10-delivery-config.v1',approved:true,stateDir:d,tokenFile:path.join(d,'api-token'),connectorKey,pollSeconds:60});
for(const change of [{approved:false},{pollSeconds:1},{endpoint:'http://evil.invalid'},{stateDir:'relative'},{schema:'other'},{connectorKey:'bad'},{tokenFile:'../token'}])test('sender rejects configuration '+Object.keys(change),()=>assert.throws(()=>validateSenderConfig({...config(os.tmpdir()),...change})));
test('secret file is local, base64url and not the clock numeric CommKey',()=>temp(async d=>{const p=config(d).tokenFile;await writeFile(p,token+'\n',{mode:0o600});assert.equal(await loadToken(p),token);await writeFile(p,'123456');await assert.rejects(loadToken(p));}));
test('token permissions reject group/world readable', {skip:process.platform==='win32'},()=>temp(async d=>{await writeFile(config(d).tokenFile,token,{mode:0o644});await assert.rejects(loadToken(config(d).tokenFile));}));
test('sender token cannot follow symlink',{skip:process.platform==='win32'},()=>temp(async d=>{await writeFile(path.join(d,'actual'),token);await symlink(path.join(d,'actual'),config(d).tokenFile);await assert.rejects(loadToken(config(d).tokenFile));}));
test('part boundaries 500+1 preserve bytes, source ordinals and hashes',()=>temp(async d=>{const {store,raw}=await fixture(d,501);const [{manifest:m,bytes}]=await store.batches();const a=partPayload(m,bytes,0),b=partPayload(m,bytes,500);assert.equal(a.ordinals.length,500);assert.deepEqual(b.ordinals,[501]);assert.ok(Buffer.concat([Buffer.from(a.recordsBase64,'base64'),Buffer.from(b.recordsBase64,'base64')]).equals(raw.subarray(4)));assert.throws(()=>partPayload(m,bytes,1));}));
test('acknowledged queue survives restart without any resend or capture deletion',()=>temp(async d=>{let {store}=await fixture(d);let calls=0;const fetchImpl=async(url,o)=>{calls++;assert.equal(url,ENDPOINT);assert.equal(o.redirect,'error');assert.equal(o.headers.authorization,'Bearer '+token);return reply(JSON.parse(o.body));};const a=await store.deliver({token,connectorKey,fetchImpl});assert.equal(a.confirmedRecords,3);store=await new DeliveryStore(d).init();const b=await store.deliver({token,connectorKey,fetchImpl});assert.equal(calls,1);assert.equal(b.sent,0);assert.equal(b.confirmedRecords,3);assert.equal((await readdir(path.join(d,'pending'))).length,1);}));
test('lost reply is retried with identical payload; replay receipt is accepted once',()=>temp(async d=>{const {store}=await fixture(d);let first,calls=0;const fetchImpl=async(_url,o)=>{calls++;const p=JSON.parse(o.body);if(!first){first=o.body;throw Error('reply lost after simulated DB commit');}assert.equal(o.body,first);return reply(p,{replayed:true});};await assert.rejects(store.deliver({token,connectorKey,fetchImpl}),/DELIVERY_NETWORK_RETRY/);assert.equal((await readdir(store.receiptDir)).length,0);const r=await store.deliver({token,connectorKey,fetchImpl});assert.equal(r.confirmedRecords,3);assert.equal(calls,2);}));
test('write interruption after remote success leaves part eligible for idempotent retry',()=>temp(async d=>{const {store}=await fixture(d);store.confirm=async()=>{throw Object.assign(Error('disk'),{code:'ENOSPC'});};await assert.rejects(store.deliver({token,connectorKey,fetchImpl:async(_u,o)=>reply(JSON.parse(o.body))}),/disk/);assert.equal((await readdir(store.receiptDir)).length,0);const next=await new DeliveryStore(d).init();const r=await next.deliver({token,connectorKey,fetchImpl:async(_u,o)=>reply(JSON.parse(o.body),{replayed:true})});assert.equal(r.confirmedRecords,3);}));
for(const patch of [{persisted:false},{payrollModified:true},{partStart:500},{count:0},{newCanonical:4},{partSha256:'0'.repeat(64)},{batchId:'0'.repeat(64)},{receiptId:'bad'},{records:['private']},{receivedAt:'bad'}])test('wrong acknowledgment is never checkpointed '+Object.keys(patch),()=>temp(async d=>{const {store}=await fixture(d);await assert.rejects(store.deliver({token,connectorKey,fetchImpl:async(_u,o)=>reply(JSON.parse(o.body),patch)}));assert.equal((await readdir(store.receiptDir)).length,0);}));
for(const status of [401,403,409,400,429,500,503])test('HTTP '+status+' does not acknowledge records',()=>temp(async d=>{const {store}=await fixture(d);await assert.rejects(store.deliver({token,connectorKey,fetchImpl:async()=>new Response('{"ok":false}',{status})}));assert.equal((await readdir(store.receiptDir)).length,0);}));
test('retry uses max four parts per cycle and reports pending accurately',()=>temp(async d=>{const {store}=await fixture(d,2501);let calls=0;const fetchImpl=async(_u,o)=>{calls++;return reply(JSON.parse(o.body));};const a=await store.deliver({token,connectorKey,fetchImpl});assert.equal(calls,4);assert.equal(a.remainingParts,2);assert.equal(a.confirmedRecords,2000);const b=await store.deliver({token,connectorKey,fetchImpl});assert.equal(b.remainingParts,0);assert.equal(b.confirmedRecords,2501);}));
test('corrupt bytes block before HTTP request',()=>temp(async d=>{const {store,saved}=await fixture(d);await writeFile(path.join(d,'pending',saved.batchId,'records.bin'),Buffer.alloc(120));let calls=0;await assert.rejects(store.deliver({token,connectorKey,fetchImpl:async()=>{calls++;}}));assert.equal(calls,0);}));
test('corrupt receipt does not silently become an unacknowledged part',()=>temp(async d=>{const {store}=await fixture(d);const [{manifest:m,bytes}]=await store.batches();const p=partPayload(m,bytes,0);await writeFile(store.receiptFile(p),'{}',{mode:0o600});await assert.rejects(store.deliver({token,connectorKey,fetchImpl:async()=>{throw Error('must not fetch');}}),/DELIVERY_RECEIPT_CORRUPT/);}));
test('auth block persists after restart until explicit resume',()=>temp(async d=>{const {store}=await fixture(d);const cfg=config(d);await writeFile(cfg.tokenFile,token,{mode:0o600});let calls=0;const fetchImpl=async()=>{calls++;return new Response(null,{status:401});};await assert.rejects(runSender(cfg,{once:true,fetchImpl}));await assert.rejects(runSender(cfg,{once:true,fetchImpl}),/DELIVERY_REVIEW_REQUIRED/);assert.equal(calls,1);await runSender(cfg,{resume:true});assert.equal(JSON.parse(await readFile(path.join(store.root,'status.json'))).state,'ready');}));
test('retry deadline persists across restart; no rapid reattempt',()=>temp(async d=>{await fixture(d);const cfg=config(d);await writeFile(cfg.tokenFile,token,{mode:0o600});let calls=0;const opts={once:true,now:()=>new Date(capturedAt),fetchImpl:async()=>{calls++;throw Error('offline');}};await assert.rejects(runSender(cfg,opts));await runSender(cfg,opts);assert.equal(calls,1);}));
test('incomplete capture directory is retained and not sent',()=>temp(async d=>{const {store}=await fixture(d);await mkdir(path.join(d,'pending','.pending-aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'));const r=await store.deliver({token,connectorKey,fetchImpl:async(_u,o)=>reply(JSON.parse(o.body))});assert.equal(r.confirmedRecords,3);assert.equal((await readdir(path.join(d,'pending'))).length,2);}));
test('response body is bounded and discarded on overflow',()=>temp(async d=>{const {store}=await fixture(d);await assert.rejects(store.deliver({token,connectorKey,fetchImpl:async()=>new Response(' '.repeat(8193))}),/DELIVERY_RECEIPT_INVALID/);}));
test('numeric serial/state and capture metadata mismatches are blocked',()=>temp(async d=>{const {store}=await fixture(d);const [{manifest:m,bytes}]=await store.batches();for(const patch of [{capturedAt:'2026-02-30T09:00:00.000Z'},{ordinals:[1,1,3]},{snapshotBytes:0},{clockTimeZone:'UTC'},{cloudConfirmed:true}])assert.throws(()=>validateBatch(m.batchId,{...m,...patch},bytes));}));
