// SPDX-License-Identifier: GPL-2.0-only
import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtemp,writeFile,readFile,readdir,rm} from 'node:fs/promises';import path from 'node:path';import os from 'node:os';
import {replaceFile} from '../file-replacement.mjs';
const regular={isFile:()=>true,isSymbolicLink:()=>false};
const options=(patch={})=>({platform:'win32',inspect:async()=>regular,sleep:async()=>{},...patch});
for(const code of ['EPERM','EACCES','EBUSY'])test('temporary '+code+' retries the same pair without deletion',async()=>{let n=0;const waits=[];await replaceFile('/state/a.tmp','/state/a',options({renameFile:async(a,b)=>{assert.equal(a,'/state/a.tmp');assert.equal(b,'/state/a');if(++n<3)throw Object.assign(Error(),{code});},sleep:async n=>waits.push(n)}));assert.equal(n,3);assert.deepEqual(waits,[25,50]);});
for(const code of ['ENOSPC','EROFS','EIO','EINVAL','EXDEV','ENOENT'])test('permanent '+code+' stops immediately',async()=>{let n=0;await assert.rejects(replaceFile('/state/a.tmp','/state/a',options({renameFile:async()=>{n++;throw Object.assign(Error(),{code});}})),{code});assert.equal(n,1);});
test('persistent denied rename is bounded and preserves original error',async()=>{let n=0;const waits=[],error=Object.assign(Error('blocked'),{code:'EPERM'});await assert.rejects(replaceFile('/state/a.tmp','/state/a',options({renameFile:async()=>{n++;throw error;},sleep:async ms=>waits.push(ms)})),e=>e===error);assert.equal(n,7);assert.equal(waits.reduce((a,b)=>a+b,0),1575);});
test('Linux does not reinterpret permission errors as sharing contention',async()=>{let n=0;await assert.rejects(replaceFile('/state/a.tmp','/state/a',options({platform:'linux',renameFile:async()=>{n++;throw Object.assign(Error(),{code:'EPERM'});}})));assert.equal(n,1);});
for(const target of ['directory','symlink'])test('never replaces '+target+' after failure',async()=>{let n=0;await assert.rejects(replaceFile('/state/a.tmp','/state/a',options({renameFile:async()=>{n++;throw Object.assign(Error(),{code:'EPERM'});},inspect:async p=>p.endsWith('.tmp')?regular:{isFile:()=>target!=='directory',isSymbolicLink:()=>target==='symlink'}})));assert.equal(n,1);});
test('actual files retain old and temporary bytes when every rename fails',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'mc-atomic-'));try{const from=path.join(root,'x.tmp'),to=path.join(root,'x');await writeFile(from,'new');await writeFile(to,'old');await assert.rejects(replaceFile(from,to,{platform:'win32',renameFile:async()=>{throw Object.assign(Error(),{code:'EPERM'});},sleep:async()=>{}}));assert.equal(await readFile(from,'utf8'),'new');assert.equal(await readFile(to,'utf8'),'old');assert.deepEqual((await readdir(root)).sort(),['x','x.tmp']);}finally{await rm(root,{recursive:true,force:true});}});
test('actual replacement makes complete new file readable',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'mc-atomic-'));try{const from=path.join(root,'x.tmp'),to=path.join(root,'x');await writeFile(from,'new');await writeFile(to,'old');await replaceFile(from,to);assert.equal(await readFile(to,'utf8'),'new');}finally{await rm(root,{recursive:true,force:true});}});
