import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtemp,rm,readFile,writeFile} from 'node:fs/promises';import path from 'node:path';import os from 'node:os';
import {validateFleetConfig,captureClock} from '../../clock-fleet/runner.mjs';
import {dataSet} from './fixture.mjs';
const clock=(root,id,n)=>({clockId:id,label:'Synthetic '+id,host:'172.100.126.'+n,port:4370,serial:'TEST-'+id,credentialFile:path.join(root,id+'.key'),pollSeconds:60,enabled:true});
const fleet=root=>({schema:'municontrol-clock-fleet.v1',approved:true,stateDir:root,maxQueueMiB:64,minFreeMiB:64,clocks:[clock(root,'clock-a',241),clock(root,'clock-b',242)]});
const raw=dataSet(3);const good=identity=>({raw,parsed:{layout:'legacy-40-byte-candidate'},report:{authenticationAccepted:true,finishedAt:new Date().toISOString(),metadata:{serialNumber:identity.serial,deviceTimeBefore:'2026-09-17T09:00:00'},transfer:{plannedBytes:raw.length,receivedBytes:raw.length,confirmedChunkBytes:raw.length},attendanceTransferComplete:true,cleanup:{bufferReleaseConfirmed:true,exitConfirmed:true}}});
const io={route:async()=>({localLookup:true}),credential:async()=>Buffer.from('0'),collect:async identity=>good(identity)};
for(const field of ['clockId','serial','host'])test('duplicate '+field+' is rejected',()=>{const v=fleet(os.tmpdir());v.clocks[1][field]=v.clocks[0][field];assert.throws(()=>validateFleetConfig(v),e=>e.code==='FLEET_DUPLICATE_IDENTITY');});
test('default route and outside municipal network are refused',()=>{const v=fleet(os.tmpdir());v.clocks[0].host='192.0.2.4';assert.throws(()=>validateFleetConfig(v));});
test('a failed clock does not prevent its sibling capture',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'fleet-synthetic-'));try{const v=validateFleetConfig(fleet(root));const results=await Promise.all(v.clocks.map(c=>captureClock(v,c,{...io,collect:async identity=>{if(identity.serial==='TEST-clock-a')throw Object.assign(Error(),{code:'AUTH_NOT_ACCEPTED'});return good(identity);}})));assert.equal(results[0].blocked,true);assert.equal(results[1].status,'captured_locally');assert.equal(results[1].uniqueLocalRecords,3);assert.equal(results[1].cloudReception,'not_configured');let connections=0;await captureClock(v,v.clocks[0],{...io,collect:async()=>{connections++;}});assert.equal(connections,0);}finally{await rm(root,{recursive:true,force:true});}});
test('identity changes never overwrite original status or queue',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'fleet-synthetic-'));try{const v=validateFleetConfig(fleet(root)),c=v.clocks[0];await captureClock(v,c,io);const file=path.join(root,c.clockId,'status.json'),before=await readFile(file,'utf8');await assert.rejects(()=>captureClock(v,{...c,serial:'CHANGED'},io),e=>e.code==='FLEET_IDENTITY_MISMATCH');assert.equal(await readFile(file,'utf8'),before);}finally{await rm(root,{recursive:true,force:true});}});
test('a corrupt status is retained instead of silently reset',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'fleet-synthetic-'));try{const v=validateFleetConfig(fleet(root)),c=v.clocks[0];await captureClock(v,c,io);const file=path.join(root,c.clockId,'status.json');await writeFile(file,'{"schema":"wrong"}');await assert.rejects(()=>captureClock(v,c,io),e=>e.code==='FLEET_STATE_INVALID');assert.equal(await readFile(file,'utf8'),'{"schema":"wrong"}');}finally{await rm(root,{recursive:true,force:true});}});
test('network loss never reads a credential or connects',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'fleet-synthetic-'));try{const v=validateFleetConfig(fleet(root));let keyReads=0;const s=await captureClock(v,v.clocks[0],{...io,route:async()=>{throw Object.assign(Error(),{code:'MUNICIPAL_ROUTE_REQUIRED'});},credential:async()=>{keyReads++;return Buffer.from('0');}});assert.equal(s.status,'network_wait');assert.equal(s.blocked,false);assert.equal(keyReads,0);}finally{await rm(root,{recursive:true,force:true});}});

test('malformed JSON status is not overwritten',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'fleet-synthetic-'));try{const v=validateFleetConfig(fleet(root)),c=v.clocks[0];await captureClock(v,c,io);const file=path.join(root,c.clockId,'status.json');await writeFile(file,'{broken');await assert.rejects(()=>captureClock(v,c,io),e=>e.code==='FLEET_STATE_INVALID');assert.equal(await readFile(file,'utf8'),'{broken');}finally{await rm(root,{recursive:true,force:true});}});
