import test from 'node:test';import assert from 'node:assert/strict';import os from 'node:os';import path from 'node:path';
import {mkdtemp,mkdir,writeFile,readFile,rm} from 'node:fs/promises';
import {control,desiredState} from '../../clock-fleet/control.mjs';import {fleetOverview} from '../../clock-fleet/overview.mjs';
async function fixture(){const root=await mkdtemp(path.join(os.tmpdir(),'fleet-control-'));await mkdir(path.join(root,'config'));const config={schema:'municontrol-clock-fleet.v1',approved:true,stateDir:path.join(root,'state'),maxQueueMiB:128,minFreeMiB:128,clocks:[{clockId:'clock-test',label:'Sede <script>prueba</script>',host:'172.100.126.241',port:4370,serial:'SYNTHETIC-ONLY',credentialFile:path.join(root,'never-read.key'),pollSeconds:900,enabled:true}]};await writeFile(path.join(root,'config','fleet.json'),JSON.stringify(config));return{root,config};}
test('missing desired state never starts a clock',async()=>{const {root}=await fixture();try{let calls=0;const r=await control(['tick','--base',root],{execute:async()=>{calls++;}});assert.equal(r.state,'stopped');assert.equal(calls,0);}finally{await rm(root,{recursive:true,force:true});}});
test('start enables future ticks, stop persists without discarding any queue',async()=>{const {root}=await fixture();try{let calls=0;const run=args=>control(args,{execute:async()=>{calls++;}});await run(['start','--base',root]);assert.equal(calls,0);await run(['tick','--base',root]);assert.equal(calls,1);await run(['stop','--base',root]);await run(['tick','--base',root]);assert.equal(calls,1);assert.equal(JSON.parse(await readFile(path.join(root,'control','desired.json'))).state,'stopped');}finally{await rm(root,{recursive:true,force:true});}});
test('malformed control is preserved and refuses execution',async()=>{const {root}=await fixture();try{await mkdir(path.join(root,'control'));const file=path.join(root,'control','desired.json');await writeFile(file,'{broken');await assert.rejects(control(['tick','--base',root],{execute:async()=>assert.fail()}),e=>e.code==='FLEET_CONTROL_INVALID');assert.equal(await readFile(file,'utf8'),'{broken');}finally{await rm(root,{recursive:true,force:true});}});
test('another live cycle is left untouched',async()=>{const {root}=await fixture();try{await control(['start','--base',root]);const r=await control(['tick','--base',root],{execute:async()=>{throw Object.assign(Error(),{code:'ALREADY_RUNNING'});}});assert.equal(r.state,'cycle_already_running');}finally{await rm(root,{recursive:true,force:true});}});
test('stop while a cycle finishes remains stopped at its completion',async()=>{const {root}=await fixture();try{await control(['start','--base',root]);await control(['tick','--base',root],{execute:async()=>{await control(['stop','--base',root]);}});assert.equal(desiredState(JSON.parse(await readFile(path.join(root,'control','desired.json')))),'stopped');}finally{await rm(root,{recursive:true,force:true});}});
test('summary is sanitized, distinguishes local capture and server reception and never exposes raw identifiers',()=>{const config={clocks:[{clockId:'clock-test',label:'Sede <script>alert(1)</script>',host:'172.100.126.241',serial:'PRIVATE-SERIAL',credentialFile:'PRIVATE-KEY'}]};const html=fleetOverview(config,{updatedAt:'2026-09-17T13:00:00Z',clocks:[{clockId:'clock-test',status:'captured_locally',uniqueLocalRecords:10}]});assert.match(html,/&lt;script&gt;/);assert.doesNotMatch(html,/<script>|PRIVATE-SERIAL|PRIVATE-KEY|172\.100/);assert.match(html,/Recepción en Neon: no configurada/);assert.match(html,/Sin comprobación/);});
test('invalid desired states are rejected',()=>{for(const v of [null,{}, {schema:'clock-fleet-desired.v1',state:'running',updatedAt:'wrong'}])assert.throws(()=>desiredState(v));});
