// SPDX-License-Identifier: GPL-2.0-only
// ALL fixtures and credentials here are synthetic; only loopback sockets are used.
import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtemp,rm,writeFile,readFile,mkdir,readdir,stat,symlink} from 'node:fs/promises';
import path from 'node:path';import os from 'node:os';
import {CaptureStore,acquireLock,atomicJson,hash,splitRaw} from '../store.mjs';
import {validateConfig,readCredential,SCHEMA} from '../config.mjs';
import {runCycle as guardedRunCycle,initialState,loadState,ensureCapture,statusHtml,writeStatus,nextDelaySeconds} from '../service.mjs';
import {collect,TARGET,PORT,SERIAL,makePacket} from '../reader/lector-fichadas.mjs';
import {withClock,dataSet,fakeKey} from './fixture.mjs';
const config=root=>validateConfig({schema:SCHEMA,mode:'capture_only',approved:true,host:TARGET,port:PORT,serial:SERIAL,stateDir:root,credentialFile:path.join(root,'commkey'),pollSeconds:60,maxQueueMiB:256,minFreeMiB:16});
async function temp(fn){const dir=await mkdtemp(path.join(os.tmpdir(),'pm10-059-'));try{return await fn(dir);}finally{await rm(dir,{recursive:true,force:true});}}
async function storeAt(dir,opts={}){return new CaptureStore(dir,{freeBytes:async()=>1e10,...opts}).init();}
const success=(raw=dataSet(3))=>({raw,parsed:{layout:'legacy-40-byte-candidate'},report:{authenticationAccepted:true,attendanceTransferComplete:true,finishedAt:'2026-09-13T09:00:00.000Z',metadata:{serialNumber:SERIAL,deviceTimeBefore:'2026-09-13T06:00:00'},transfer:{plannedBytes:raw.length,receivedBytes:raw.length,confirmedChunkBytes:raw.length},cleanup:{bufferReleaseConfirmed:true,exitConfirmed:true},error:null}});
const fixedNow=()=>new Date('2026-09-13T09:00:00.000Z');
// Existing protocol tests inject a synthetic route; real-route refusal is tested separately.
const runCycle=(cfg,store,state,deps={})=>guardedRunCycle(cfg,store,state,{routeCheck:async()=>({prefix:'172.100.96.0/19',interface:'synthetic',localLookup:true}),...deps});
for(const patch of [{approved:false},{host:'1.1.1.1'},{port:23},{serial:'wrong'},{mode:'cloud'},{pollSeconds:5},{maxQueueMiB:1},{endpoint:'https://example.invalid'},{credential:'999'}])test('config blocks unsafe variant '+Object.keys(patch),()=>assert.throws(()=>validateConfig({...config(os.tmpdir()),...patch})));
test('credential read accepts protected known numeric key and trims one newline',()=>temp(async d=>{const f=path.join(d,'key');await writeFile(f,'876543\n',{mode:0o600});const k=await readCredential(f);assert.equal(k.toString(),'876543');k.fill(0);}));
for(const key of ['', 'abc',' 1234','1234  ','123456789012345'])test('credential malformed '+key.length+':'+key.slice(0,1),()=>temp(async d=>{const f=path.join(d,'key');await writeFile(f,key,{mode:0o600});await assert.rejects(readCredential(f));}));
test('credential group-readable file is rejected', {skip:process.platform==='win32'},()=>temp(async d=>{const f=path.join(d,'key');await writeFile(f,'876543',{mode:0o644});await assert.rejects(readCredential(f),/CREDENTIAL_PERMISSIONS_UNSAFE/);}));
test('symlink credential is rejected', {skip:process.platform==='win32'},()=>temp(async d=>{await writeFile(path.join(d,'real'),'876543',{mode:0o600});await symlink(path.join(d,'real'),path.join(d,'key'));await assert.rejects(readCredential(path.join(d,'key')));}));
test('only one live process lock, regardless of elapsed time',()=>temp(async d=>{const release=await acquireLock(d);await assert.rejects(acquireLock(d),/ALREADY_RUNNING/);await release();const other=await acquireLock(d);await other();}));
test('unowned incomplete lock fails closed',()=>temp(async d=>{await mkdir(path.join(d,'process.lock'),{mode:0o700});await assert.rejects(acquireLock(d),/LOCK_NEEDS_REVIEW/);}));
test('queue persists exact raw bytes once and rebuilds after restart',()=>temp(async d=>{let store=await storeAt(d);const a=dataSet(3);let r=await store.save(a,{capturedAt:fixedNow().toISOString()});assert.equal(r.newUniqueRecords,3);assert.equal(store.summary().uniqueLocalRecords,3);const bin=await readFile(path.join(d,'pending',r.batchId,'records.bin'));assert.ok(bin.equals(a.subarray(4)));store=await storeAt(d);r=await store.save(a);assert.equal(r.saved,false);assert.equal(store.summary().pendingLocalBatches,1);r=await store.save(dataSet(4));assert.equal(r.newUniqueRecords,1);assert.equal(store.summary().uniqueLocalRecords,4);assert.equal(store.summary().cloudConfirmedRecords,0);}));
test('multiple occurrences with identical raw record do not become extra event identities',()=>temp(async d=>{const s=await storeAt(d),one=dataSet(1).subarray(4),raw=Buffer.concat([Buffer.from([80,0,0,0]),one,one]);const r=await s.save(raw);assert.equal(r.snapshotRecordCount,2);assert.equal(r.newUniqueRecords,1);const m=JSON.parse(await readFile(path.join(d,'pending',r.batchId,'manifest.json')));assert.equal(m.repeatedWithinNewRecords,1);}));
test('same-minute different seconds retain different raw identities',()=>temp(async d=>{const s=await storeAt(d);const raw=dataSet(2);raw.subarray(4,30).copy(raw,44);const r=await s.save(raw);assert.equal(r.newUniqueRecords,2);}));
test('queue hash corruption blocks restart instead of losing seen IDs',()=>temp(async d=>{const s=await storeAt(d);const r=await s.save(dataSet(2));const f=path.join(d,'pending',r.batchId,'records.bin');const b=await readFile(f);b[0]^=1;await writeFile(f,b);await assert.rejects(storeAt(d),/QUEUE_CORRUPT/);}));
test('interrupted writes retained but never become a committed batch',()=>temp(async d=>{const s=await storeAt(d),p=path.join(d,'pending','.pending-00000000-0000-4000-8000-000000000000');await mkdir(p);await writeFile(path.join(p,'records.bin'),dataSet(2).subarray(4));const again=await storeAt(d);assert.equal(again.summary().interruptedWrites,1);assert.equal(again.summary().uniqueLocalRecords,0);assert.equal((await again.save(dataSet(2))).newUniqueRecords,2);}));
test('low disk stops before requesting any bytes from clock',()=>temp(async d=>{const store=await storeAt(d,{freeBytes:async()=>0});let calls=0;const state=await runCycle(config(d),store,initialState(),{credentialReader:async()=>fakeKey(),collectImpl:async()=>{calls++;return success();},now:fixedNow});assert.equal(calls,0);assert.equal(state.lastError,'DISK_SPACE_LOW');assert.equal(state.blocked,true);}));
test('full queue never deletes old records or calls clock',()=>temp(async d=>{const store=await storeAt(d,{maxQueueBytes:1});let calls=0;const state=await runCycle(config(d),store,initialState(),{collectImpl:async()=>{calls++;},now:fixedNow});assert.equal(calls,0);assert.equal(state.lastError,'QUEUE_CAPACITY_REACHED');assert.equal(state.cloudConfirmedRecords,0);}));
for(const patch of [{authenticationAccepted:false},{metadata:{serialNumber:'ANOTHER'}},{attendanceTransferComplete:false},{cleanup:{bufferReleaseConfirmed:false,exitConfirmed:false}},{error:{code:'SESSION_MISMATCH'}}])test('uncertified transfer not queued '+JSON.stringify(patch),()=>temp(async d=>{const s=await storeAt(d),result=success();Object.assign(result.report,patch);const v=await runCycle(config(d),s,initialState(),{credentialReader:async()=>fakeKey(),collectImpl:async()=>result,now:fixedNow});assert.equal(v.blocked,true);assert.equal(s.summary().pendingLocalBatches,0);}));
test('wrong credential holds persistently after exactly one attempt',()=>temp(async d=>{const s=await storeAt(d);let calls=0;const deps={credentialReader:async()=>fakeKey(),collectImpl:async()=>{calls++;return {report:{status:'AUTH_NOT_ACCEPTED',authenticationAccepted:false}};},now:fixedNow};const v=await runCycle(config(d),s,initialState(),deps);await writeStatus(d,v);const restart=await loadState(d);await runCycle(config(d),s,restart,deps);assert.equal(calls,1);assert.equal(v.lastError,'AUTH_NOT_ACCEPTED');assert.equal(v.blocked,true);}));
test('retry deadline survives a restart and does not retry on each launch',()=>temp(async d=>{const s=await storeAt(d);let calls=0;const deps={credentialReader:async()=>fakeKey(),collectImpl:async()=>{calls++;throw Object.assign(new Error('internal'),{code:'ECONNREFUSED'});},now:fixedNow};let v=await runCycle(config(d),s,initialState(),deps);assert.equal(v.blocked,false);assert.equal(v.nextPollAt,'2026-09-13T09:01:00.000Z');await writeStatus(d,v);await runCycle(config(d),s,await loadState(d),deps);assert.equal(calls,1);}));
test('six consecutive transport failures require operator review',()=>temp(async d=>{const s=await storeAt(d);let v=initialState();for(let i=0;i<6;i++){v.nextPollAt=null;v=await runCycle(config(d),s,v,{credentialReader:async()=>fakeKey(),collectImpl:async()=>{throw Object.assign(new Error('x'),{code:'RESPONSE_TIMEOUT'});},now:fixedNow});}assert.equal(v.failureCount,6);assert.equal(v.blocked,true);assert.equal(v.nextPollAt,null);}));
test('backoff is bounded',()=>{assert.deepEqual([1,2,3,4,5,6].map(n=>nextDelaySeconds(n,60)),[60,120,240,480,900,900]);});
test('successful capture resets error and zeroizes credential',()=>temp(async d=>{const s=await storeAt(d),k=fakeKey();const v=await runCycle(config(d),s,{...initialState(),failureCount:3,lastError:'ECONNREFUSED'},{credentialReader:async()=>k,collectImpl:async()=>success(),now:fixedNow});assert.ok(k.equals(Buffer.alloc(k.length)));assert.equal(v.failureCount,0);assert.equal(v.lastError,null);assert.equal(v.status,'captured_locally');assert.equal(v.cloudReception,'not_connected');assert.equal(v.uniqueLocalRecords,3);}));
test('status HTML distinguishes local capture from cloud and excludes identities',()=>{const html=statusHtml({...initialState(),lastError:'<script>evil</script>',uniqueLocalRecords:11111});assert.match(html,/Subida a Neon pendiente/);assert.match(html,/11111/);assert.doesNotMatch(html,/<script>/);assert.match(html,/&lt;script&gt;/);assert.doesNotMatch(html,/99000001/);});
test('raw length and header inconsistencies fail closed',()=>{for(const raw of [Buffer.alloc(3),Buffer.alloc(44),dataSet(2).subarray(0,40)])assert.throws(()=>splitRaw(raw),/RAW_LAYOUT_INVALID/);});
test('empty complete capture preserved as a successful poll, no artificial rows',()=>temp(async d=>{const s=await storeAt(d),r=success(dataSet(0));r.parsed={layout:null};const v=await runCycle(config(d),s,initialState(),{credentialReader:async()=>fakeKey(),collectImpl:async()=>r,now:fixedNow});assert.equal(v.snapshotRecordCount,0);assert.equal(v.uniqueLocalRecords,0);assert.equal(v.status,'captured_locally');}));
test('actual protocol fixture completes read, cleanup, raw queue and restart',()=>temp(async d=>withClock({count:100,fragment:true},async(port,commands,raw)=>{
 const s=await storeAt(d);const state=await runCycle(config(d),s,initialState(),{credentialReader:async()=>fakeKey(),collectImpl:opts=>collect({...opts,host:'127.0.0.1',port,timeoutMs:1000,pacingMs:0,totalMs:10000}),now:fixedNow});
 assert.equal(state.status,'captured_locally');assert.equal(state.snapshotRecordCount,100);assert.equal(state.uniqueLocalRecords,100);assert.equal(state.lastCaptureSha256,hash(raw));assert.equal(state.cloudReception,'not_connected');assert.equal(commands.filter(x=>x.code===1102).length,1);assert.equal(commands.at(-1).code,1001);assert.ok(commands.some(x=>x.code===1502));assert.ok(commands.every(x=>[1000,1102,11,50,201,1503,1504,1502,1001].includes(x.code)));
 const after=await storeAt(d);assert.equal(after.summary().uniqueLocalRecords,100);
})));
test('bad auth on real loopback protocol never reaches ATTLOG transfer',()=>temp(async d=>withClock({count:3},async(port,commands)=>{const s=await storeAt(d);const state=await runCycle(config(d),s,initialState(),{credentialReader:async()=>Buffer.from('111111'),collectImpl:opts=>collect({...opts,host:'127.0.0.1',port,pacingMs:0,timeoutMs:1000,totalMs:3000}),now:fixedNow});assert.equal(state.lastError,'AUTH_NOT_ACCEPTED');assert.equal(state.blocked,true);assert.equal(commands.filter(x=>x.code===1102).length,1);assert.equal(commands.some(x=>x.code===1503),false);})));
for(const command of [14,18,19,1003,1004,1006,2003])test('protocol writer rejects non-allowlisted command '+command,()=>assert.throws(()=>makePacket(command,1,1),{code:'COMMAND_NOT_ALLOWED'}));
for(const [scenario,expect] of [[{badChecksum:true},'CHECKSUM_MISMATCH'],[{omitAck:true},'RESPONSE_TIMEOUT'],[{ackSid:3},'SESSION_MISMATCH'],[{dataSid:54321},'SESSION_MISMATCH'],[{wrongControl:11},'SESSION_MISMATCH']])test('malformed transport stops queue: '+expect+JSON.stringify(scenario),()=>temp(async d=>withClock({count:5,...scenario},async(port)=>{const s=await storeAt(d);const v=await runCycle(config(d),s,initialState(),{credentialReader:async()=>fakeKey(),collectImpl:opts=>collect({...opts,host:'127.0.0.1',port,pacingMs:0,timeoutMs:100,totalMs:2000}),now:fixedNow});assert.equal(v.lastError,expect);assert.equal(v.uniqueLocalRecords,0);assert.equal(v.cloudConfirmedRecords,0);})));
test('only current snapshot unique additions consume persistent record storage',()=>temp(async d=>{const s=await storeAt(d);await s.save(dataSet(100));const before=s.bytes;for(let i=0;i<20;i++)await s.save(dataSet(100));assert.equal(s.bytes,before);await s.save(dataSet(101));assert.equal(s.summary().uniqueLocalRecords,101);assert.ok(s.bytes-before<4000);}));
test('service implementation contains no HTTP sender, cloud token, SQL or browser dependency',async()=>{const text=await readFile(new URL('../service.mjs',import.meta.url),'utf8');assert.doesNotMatch(text,/fetch\(|https\.request\(|http\.request\(|ATTENDANCE_CONNECTOR_TOKEN|DATABASE_URL|@neondatabase|playwright/);});
