DO $qa$
DECLARE
 t uuid:='10000000-0000-4000-8000-000000000001'; b uuid:='20000000-0000-4000-8000-000000000001';
 maker uuid:='30000000-0000-4000-8000-000000000001'; checker uuid:='30000000-0000-4000-8000-000000000002';
 mp uuid:='40000000-0000-4000-8000-000000000001'; cp uuid:='40000000-0000-4000-8000-000000000002';
 p1 uuid:='50000000-0000-4000-8000-000000000001'; p2 uuid:='50000000-0000-4000-8000-000000000002'; p3 uuid:='50000000-0000-4000-8000-000000000003';
 k1 uuid:='60000000-0000-4000-8000-000000000001'; k2 uuid:='60000000-0000-4000-8000-000000000002'; k3 uuid:='60000000-0000-4000-8000-000000000003';
 c jsonb; m jsonb; draft jsonb; a jsonb; got jsonb; period text:=to_char(CURRENT_DATE+interval '1 month','YYYY-MM'); future text:=to_char(CURRENT_DATE+interval '2 months','YYYY-MM');
 old text:=to_char(CURRENT_DATE-interval '2 months','YYYY-MM');
BEGIN
 c:=jsonb_build_object('syntheticSession','test-only','tenantId',t,'certifiedBindingId',b,'membershipId',checker,'actorPersonId',cp,'actorSessionId','70000000-0000-4000-8000-000000000001','actorSessionVersion',1,'releaseSha',repeat('a',40),'capabilities',jsonb_build_array('payroll.parameter.read','payroll.parameter.approve'));
 m:=c||jsonb_build_object('membershipId',maker,'actorPersonId',mp,'capabilities',jsonb_build_array('payroll.parameter.read','payroll.parameter.prepare'));
 draft:=jsonb_build_object('ruleId','aux88-class13i-150','agreementIds',jsonb_build_array(2,7,11),'baseAmountCents','10001','rounding','nearest_cent','sourceReference','QA SINTETICA - NO MUNICIPAL','validFrom',period);
 INSERT INTO mcqa_aux.payroll_parameter_proposal VALUES(p1,t,b,3,'approved',true,mcqa_aux.payroll_parameter_build_draft_v1(draft),(period||'-01')::date,maker,mp);
 INSERT INTO mcqa_aux.payroll_parameter_proposal VALUES(p2,t,b,3,'approved',true,mcqa_aux.payroll_parameter_build_draft_v1(draft||'{"baseAmountCents":"20001"}'),(period||'-01')::date,maker,mp);
 INSERT INTO mcqa_aux.payroll_parameter_proposal VALUES(p3,t,b,3,'approved',true,mcqa_aux.payroll_parameter_build_draft_v1(draft||jsonb_build_object('baseAmountCents','30001','validFrom',future)),(future||'-01')::date,maker,mp);
 got:=mcqa_aux.payroll_auxiliary_catalog_v1(c,period,NULL);
 PERFORM mcqa_aux.ok(got->'catalog'->'rows'='[]'::jsonb AND got->>'currentRevision'='0','empty catalogue is explicit');
 got:=mcqa_aux.payroll_auxiliary_preview_v1(c,p1,3);
 PERFORM mcqa_aux.ok((got->'preview'->>'canActivate')::boolean AND got->'preview'->'changes'->0->>'newValueCents'='15002','approved rule preview and exact half-cent');
 PERFORM mcqa_aux.ok(got->'preview'->'changes'->0->'previousValueCents'='null'::jsonb,'missing prior value is not zero');
 got:=mcqa_aux.payroll_auxiliary_preview_v1(m,p1,3);
 PERFORM mcqa_aux.ok(got->'preview'->>'blockedReason'='reviewer_required','maker sees independent reviewer requirement');
 PERFORM mcqa_aux.expect_failure(format('SELECT mcqa_aux.payroll_auxiliary_activate_v1(%L,%L,3,0,%L,%L)',m,p1,k1,repeat('a',64)),'PAYROLL_PARAMETER_CAPABILITY_REQUIRED','maker cannot activate');
 PERFORM mcqa_aux.expect_failure(format('SELECT mcqa_aux.payroll_auxiliary_preview_v1(%L,%L,2)',c,p1),'PAYROLL_CATALOG_PROPOSAL_CHANGED','stale proposal version rejected');
 a:=mcqa_aux.payroll_auxiliary_activate_v1(c,p1,3,0,k1,repeat('a',64));
 PERFORM mcqa_aux.ok(a->'activation'->>'revision'='1' AND a->>'replayed'='false','first activation creates revision one');
 PERFORM mcqa_aux.ok(a->>'payrollCalculated'='false' AND a->>'payrollPosted'='false','activation never claims a calculated payroll');
 got:=mcqa_aux.payroll_auxiliary_activate_v1(c,p1,3,0,k1,repeat('a',64));
 PERFORM mcqa_aux.ok(got->>'replayed'='true' AND got->'activation'=a->'activation','same attempt recovers same immutable activation');
 PERFORM mcqa_aux.ok((SELECT count(*)=1 FROM mcqa_aux.payroll_auxiliary_release),'idempotency does not duplicate ledger');
 PERFORM mcqa_aux.expect_failure(format('SELECT mcqa_aux.payroll_auxiliary_activate_v1(%L,%L,3,0,%L,%L)',c,p1,k1,repeat('b',64)),'PAYROLL_CATALOG_ATTEMPT_CONFLICT','idempotency cannot replace command');
 PERFORM mcqa_aux.expect_failure(format('SELECT mcqa_aux.payroll_auxiliary_activate_v1(%L,%L,3,0,%L,%L)',c,p2,k2,repeat('b',64)),'PAYROLL_CATALOG_VERSION_CONFLICT','stale catalogue revision rejected');
 got:=mcqa_aux.payroll_auxiliary_preview_v1(c,p2,3);
 PERFORM mcqa_aux.ok(got->'preview'->'changes'->0->>'previousValueCents'='15002','impact includes previously effective value');
 got:=mcqa_aux.payroll_auxiliary_activate_v1(c,p2,3,1,k2,repeat('b',64));
 PERFORM mcqa_aux.ok(got->'catalog'->'rows'->0->>'newValueCents'='30002','second activation supersedes same-period pair');
 got:=mcqa_aux.payroll_auxiliary_catalog_v1(c,period,1);
 PERFORM mcqa_aux.ok(got->'catalog'->'rows'->0->>'newValueCents'='15002' AND got->>'currentRevision'='2','pinned historical revision remains unchanged');
 got:=mcqa_aux.payroll_auxiliary_catalog_v1(c,old,NULL);
 PERFORM mcqa_aux.ok(got->'catalog'->'rows'='[]'::jsonb,'future scale never leaks into prior period');
 PERFORM mcqa_aux.payroll_auxiliary_activate_v1(c,p3,3,2,k3,repeat('c',64));
 got:=mcqa_aux.payroll_auxiliary_catalog_v1(c,period,NULL);
 PERFORM mcqa_aux.ok(got->'catalog'->'rows'->0->>'newValueCents'='30002','future effective date preserves earlier period');
 got:=mcqa_aux.payroll_auxiliary_catalog_v1(c,future,NULL);
 PERFORM mcqa_aux.ok(got->'catalog'->'rows'->0->>'newValueCents'='45002','new period selects scheduled scale');
 got:=mcqa_aux.payroll_auxiliary_catalog_v1(c,future,2);
 PERFORM mcqa_aux.ok(got->'catalog'->'rows'->0->>'newValueCents'='30002','historical revision applies before later publication');
 got:=mcqa_aux.payroll_auxiliary_catalog_v1(c,period,0);
 PERFORM mcqa_aux.ok(got->'catalog'->'rows'='[]'::jsonb,'revision zero remains empty');
 got:=mcqa_aux.payroll_auxiliary_catalog_v1(c||jsonb_build_object('tenantId','10000000-0000-4000-8000-000000000002'),period,NULL);
 PERFORM mcqa_aux.ok(got->'catalog'->'rows'='[]'::jsonb,'tenant isolation');
 got:=mcqa_aux.payroll_auxiliary_catalog_v1(c||jsonb_build_object('certifiedBindingId','20000000-0000-4000-8000-000000000002'),period,NULL);
 PERFORM mcqa_aux.ok(got->'catalog'->'rows'='[]'::jsonb,'certified binding isolation');
 PERFORM mcqa_aux.expect_failure(format('SELECT mcqa_aux.payroll_auxiliary_preview_v1(%L,%L,3)',c||jsonb_build_object('tenantId','10000000-0000-4000-8000-000000000002'),p1),'PAYROLL_CATALOG_NOT_FOUND','other tenant cannot preview proposal');
 PERFORM mcqa_aux.expect_failure(format('SELECT mcqa_aux.payroll_auxiliary_catalog_v1(%L,%L,99)',c,period),'PAYROLL_CATALOG_REVISION_INVALID','unpublished revision refused');
 PERFORM mcqa_aux.expect_failure(format('SELECT mcqa_aux.payroll_auxiliary_catalog_v1(%L,%L,NULL)',c,'2026-13'),'PAYROLL_CATALOG_INPUT_INVALID','invalid period refused');
 got:=mcqa_aux.payroll_auxiliary_attempt_v1(c,k1);
 PERFORM mcqa_aux.ok(got->'activation'=a->'activation' AND got->>'replayed'='true','receipt resolves original activation');
 PERFORM mcqa_aux.expect_failure(format('SELECT mcqa_aux.payroll_auxiliary_attempt_v1(%L,%L)',c||'{"actorSessionVersion":2}',k1),'PAYROLL_CATALOG_ATTEMPT_CONFLICT','receipt requires original session context');
 PERFORM mcqa_aux.expect_failure(format('SELECT mcqa_aux.payroll_auxiliary_activate_v1(%L,%L,3,3,%L,%L)',c,p1,gen_random_uuid(),repeat('d',64)),'PAYROLL_CATALOG_ALREADY_ACTIVATED','same proposal cannot activate twice');
 INSERT INTO mcqa_aux.payroll_parameter_proposal VALUES('50000000-0000-4000-8000-000000000004',t,b,1,'prepared',false,mcqa_aux.payroll_parameter_build_draft_v1(draft),(period||'-01')::date,maker,mp);
 PERFORM mcqa_aux.expect_failure(format('SELECT mcqa_aux.payroll_auxiliary_activate_v1(%L,%L,1,3,%L,%L)',c,'50000000-0000-4000-8000-000000000004',gen_random_uuid(),repeat('d',64)),'PAYROLL_CATALOG_APPROVAL_REQUIRED','draft cannot become effective');
 INSERT INTO mcqa_aux.payroll_parameter_proposal VALUES('50000000-0000-4000-8000-000000000005',t,b,3,'approved',true,mcqa_aux.payroll_parameter_build_draft_v1(draft||jsonb_build_object('validFrom',old)),(old||'-01')::date,maker,mp);
 PERFORM mcqa_aux.expect_failure(format('SELECT mcqa_aux.payroll_auxiliary_activate_v1(%L,%L,3,3,%L,%L)',c,'50000000-0000-4000-8000-000000000005',gen_random_uuid(),repeat('e',64)),'PAYROLL_CATALOG_PAST_PERIOD','closed prior months are not activated retroactively');
 INSERT INTO mcqa_aux.payroll_parameter_proposal VALUES('50000000-0000-4000-8000-000000000006',t,b,3,'approved',true,mcqa_aux.payroll_parameter_build_draft_v1(draft)||'{"rows":[]}',(period||'-01')::date,maker,mp);
 PERFORM mcqa_aux.expect_failure(format('SELECT mcqa_aux.payroll_auxiliary_activate_v1(%L,%L,3,3,%L,%L)',c,'50000000-0000-4000-8000-000000000006',gen_random_uuid(),repeat('e',64)),'PAYROLL_CATALOG_SOURCE_INVALID','tampered approved values refused');
 INSERT INTO mcqa_aux.payroll_parameter_proposal VALUES('50000000-0000-4000-8000-000000000007',t,b,3,'approved',true,mcqa_aux.payroll_parameter_build_draft_v1(draft),(period||'-01')::date,checker,cp);
 PERFORM mcqa_aux.expect_failure(format('SELECT mcqa_aux.payroll_auxiliary_activate_v1(%L,%L,3,3,%L,%L)',c,'50000000-0000-4000-8000-000000000007',gen_random_uuid(),repeat('e',64)),'PAYROLL_CATALOG_INDEPENDENT_REVIEWER_REQUIRED','reviewer cannot activate own proposal');
 PERFORM mcqa_aux.ok((SELECT count(*)=3 FROM mcqa_aux.payroll_auxiliary_release),'rejected operations leave ledger unchanged');
 PERFORM mcqa_aux.ok((SELECT count(*)=7 AND bool_and(saved.draft->>'applied'='false') FROM mcqa_aux.payroll_parameter_proposal saved),'proposal semantics and flags preserved');
 PERFORM mcqa_aux.ok(NOT has_table_privilege('municontrol_actions_runtime_app','mcqa_aux.payroll_auxiliary_release','SELECT'),'runtime cannot bypass guarded reads');
 PERFORM mcqa_aux.ok(NOT has_table_privilege('municontrol_actions_runtime_app','mcqa_aux.payroll_auxiliary_release','INSERT'),'runtime cannot insert arbitrary values');
 PERFORM mcqa_aux.ok(NOT has_table_privilege('municontrol_actions_runtime_app','mcqa_aux.payroll_auxiliary_release','UPDATE'),'runtime cannot rewrite ledger');
 PERFORM mcqa_aux.ok(NOT has_function_privilege('municontrol_actions_runtime_app','mcqa_aux.payroll_auxiliary_snapshot_v1(uuid,uuid,text,integer)','EXECUTE'),'internal projection is not a public read bypass');
 PERFORM mcqa_aux.ok(has_function_privilege('municontrol_actions_runtime_app','mcqa_aux.payroll_auxiliary_activate_v1(jsonb,uuid,integer,integer,uuid,text)','EXECUTE'),'runtime can call the guarded activation facade');
 PERFORM mcqa_aux.ok((SELECT relrowsecurity FROM pg_class WHERE oid='mcqa_aux.payroll_auxiliary_release'::regclass),'row level security enabled');
 PERFORM mcqa_aux.ok((SELECT count(*)=2 FROM pg_trigger WHERE tgrelid='mcqa_aux.payroll_auxiliary_release'::regclass AND NOT tgisinternal),'immutable row and truncate guards installed');
 PERFORM mcqa_aux.expect_failure('SELECT public.payroll_parameter_assert_context_v1(''{}''::jsonb,''payroll.parameter.read'')','PAYROLL_PARAMETER_SESSION_INVALID','real existing guard rejects fabricated empty context');
END $qa$;
