-- Isolated QA only. All synthetic schema/data are reverted in the nested transaction.
DO $qa$
DECLARE c jsonb;reader jsonb;outsider jsonb;body jsonb;receipt jsonb;updated jsonb;f uuid;k uuid:=gen_random_uuid();k2 uuid:=gen_random_uuid();definition text;name text;checks integer:=0;res jsonb;
BEGIN
 IF current_setting('neon.project_id',true) IS DISTINCT FROM 'wild-cake-87689498' OR to_regnamespace('mc_qa_followups_079') IS NOT NULL THEN RAISE EXCEPTION 'QA_TARGET_INVALID';END IF;
 BEGIN
  CREATE SCHEMA mc_qa_followups_079;
  SET LOCAL search_path=mc_qa_followups_079,public,pg_catalog;
  CREATE TABLE internal_users(email text PRIMARY KEY,active boolean,auth_mode text,identity_version integer);
  CREATE TABLE platform_tenant(id uuid PRIMARY KEY,status text);
  CREATE TABLE tenant_membership(id uuid PRIMARY KEY,tenant_id uuid,user_email text,status text,UNIQUE(id,tenant_id));
  CREATE TABLE tenant_identity_session(id uuid PRIMARY KEY,user_email text,active_tenant_id uuid,session_version integer,identity_version integer,source text,auth_level text,status text,expires_at timestamptz,last_seen_at timestamptz);
  CREATE TABLE capabilities(membership_id uuid,capability_key text);
  CREATE TABLE legal_norm(id uuid,tenant_id uuid,current_version integer,PRIMARY KEY(tenant_id,id));
  CREATE TABLE legal_norm_revision(tenant_id uuid,norm_id uuid,version integer,PRIMARY KEY(tenant_id,norm_id,version));
  CREATE TABLE legal_followup(LIKE public.legal_followup INCLUDING ALL);
  CREATE TABLE legal_followup_event(LIKE public.legal_followup_event INCLUDING ALL);
  ALTER TABLE legal_followup ADD FOREIGN KEY(tenant_id,norm_id,norm_version) REFERENCES legal_norm_revision(tenant_id,norm_id,version);
  ALTER TABLE legal_followup_event ADD FOREIGN KEY(tenant_id,followup_id) REFERENCES legal_followup(tenant_id,id);
  ALTER TABLE legal_followup_event ADD FOREIGN KEY(actor_membership_id,tenant_id) REFERENCES tenant_membership(id,tenant_id);
  ALTER TABLE legal_followup_event ADD FOREIGN KEY(actor_session_id) REFERENCES tenant_identity_session(id);
  CREATE TRIGGER immutable_task BEFORE UPDATE OR DELETE ON legal_followup FOR EACH ROW EXECUTE FUNCTION public.reject_immutable_source_change();
  CREATE TRIGGER immutable_event BEFORE UPDATE OR DELETE ON legal_followup_event FOR EACH ROW EXECUTE FUNCTION public.reject_immutable_source_change();
  CREATE FUNCTION tenant_iam_assert_no_sod_conflict(uuid) RETURNS void LANGUAGE plpgsql AS $f$ BEGIN RETURN;END $f$;
  CREATE FUNCTION tenant_iam_effective_capabilities(m uuid) RETURNS TABLE(capability_key text) LANGUAGE sql SET search_path=mc_qa_followups_079,public AS $f$ SELECT c.capability_key FROM capabilities c WHERE c.membership_id=m $f$;
  FOREACH name IN ARRAY ARRAY['legal_norm_context_v1(jsonb,boolean)','legal_followup_record_v1(uuid,uuid,boolean)','legal_followup_operation_v1(jsonb,text,jsonb,uuid)'] LOOP
   definition:=pg_get_functiondef(('public.'||name)::regprocedure);
   definition:=replace(definition,'CREATE OR REPLACE FUNCTION public.','CREATE OR REPLACE FUNCTION mc_qa_followups_079.');
   definition:=replace(definition,E' SET search_path TO ''pg_catalog'', ''public'', ''pg_temp''\n',E' SET search_path TO ''pg_catalog'', ''mc_qa_followups_079'', ''public'', ''pg_temp''\n');
   EXECUTE definition;
  END LOOP;
  CREATE FUNCTION assert_true(v boolean,label text) RETURNS void LANGUAGE plpgsql AS $f$ BEGIN IF v IS DISTINCT FROM true THEN RAISE EXCEPTION 'FOLLOWUP_QA_FAILED: %',label;END IF;END $f$;
  CREATE FUNCTION rejects(p jsonb,op text,d jsonb,k uuid,wanted text) RETURNS boolean LANGUAGE plpgsql SET search_path=mc_qa_followups_079,public AS $f$
  BEGIN PERFORM legal_followup_operation_v1(p,op,d,k);RETURN false;EXCEPTION WHEN OTHERS THEN IF SQLERRM=wanted THEN RETURN true;END IF;RAISE;END $f$;
  INSERT INTO internal_users VALUES('writer@example.invalid',true,'managed',1),('reader@example.invalid',true,'managed',1),('other@example.invalid',true,'managed',1);
  INSERT INTO platform_tenant VALUES('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','active'),('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','active');
  INSERT INTO tenant_membership VALUES('cccccccc-cccc-4ccc-8ccc-cccccccccccc','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','writer@example.invalid','active'),('dddddddd-dddd-4ddd-8ddd-dddddddddddd','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','reader@example.invalid','active'),('eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee','bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','other@example.invalid','active');
  INSERT INTO tenant_identity_session SELECT (CASE WHEN user_email LIKE 'writer%' THEN '10000000-0000-4000-8000-000000000001' WHEN user_email LIKE 'reader%' THEN '10000000-0000-4000-8000-000000000002' ELSE '10000000-0000-4000-8000-000000000003' END)::uuid,user_email,tenant_id,1,1,'membership','mfa','active',now()+interval '1 hour',now() FROM tenant_membership;
  INSERT INTO capabilities SELECT id,'legal.norm.read' FROM tenant_membership;
  INSERT INTO capabilities SELECT id,'legal.norm.register' FROM tenant_membership WHERE user_email<>'reader@example.invalid';
  INSERT INTO legal_norm VALUES('11111111-1111-4111-8111-111111111111','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',2);
  INSERT INTO legal_norm_revision SELECT 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'::uuid,'11111111-1111-4111-8111-111111111111'::uuid,generate_series(1,2);
  c:=jsonb_build_object('actorEmail','writer@example.invalid','actorSessionId','10000000-0000-4000-8000-000000000001','actorSessionVersion',1,'membershipId','cccccccc-cccc-4ccc-8ccc-cccccccccccc','tenantId','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa');
  reader:=c||'{"actorEmail":"reader@example.invalid","actorSessionId":"10000000-0000-4000-8000-000000000002","membershipId":"dddddddd-dddd-4ddd-8ddd-dddddddddddd"}'::jsonb;
  outsider:=c||'{"actorEmail":"other@example.invalid","actorSessionId":"10000000-0000-4000-8000-000000000003","membershipId":"eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee","tenantId":"bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb"}'::jsonb;
  body:='{"id":null,"normId":"11111111-1111-4111-8111-111111111111","normVersion":1,"expectedVersion":0,"title":"Revisar referencia","dueDate":"2026-09-30","status":"open","note":"Ensayo aislado","reason":"Alta de seguimiento de ensayo"}'::jsonb;
  PERFORM assert_true(jsonb_array_length(legal_followup_operation_v1(c,'list',jsonb_build_object('normId',body->>'normId'),NULL)->'rows')=0,'empty');checks:=checks+1;
  receipt:=legal_followup_operation_v1(c,'save',body,k);f:=(receipt->>'id')::uuid;
  PERFORM assert_true((receipt->>'recordVersion')::int=1 AND NOT (receipt->>'replayed')::boolean,'create');checks:=checks+1;
  PERFORM assert_true(legal_followup_operation_v1(c,'save',body,k)=receipt||'{"replayed":true}'::jsonb,'idempotent create');checks:=checks+1;
  PERFORM assert_true((SELECT count(*)=1 FROM legal_followup_event),'single event');checks:=checks+1;
  PERFORM assert_true(rejects(c,'save',body||'{"title":"Contenido distinto"}',k,'FOLLOWUP_IDEMPOTENCY_CONFLICT'),'key conflict');checks:=checks+1;
  PERFORM assert_true((legal_followup_operation_v1(c,'attempt','{}',k)->>'id')::uuid=f,'receipt recovery');checks:=checks+1;
  PERFORM assert_true(rejects(outsider,'detail',jsonb_build_object('id',f),NULL,'FOLLOWUP_NOT_FOUND'),'tenant isolation detail');checks:=checks+1;
  PERFORM assert_true(rejects(outsider,'list',jsonb_build_object('normId',body->>'normId'),NULL,'FOLLOWUP_NOT_FOUND'),'tenant isolation list');checks:=checks+1;
  PERFORM assert_true(rejects(reader,'save',body,gen_random_uuid(),'LEGAL_FORBIDDEN'),'reader cannot write');checks:=checks+1;
  PERFORM assert_true(NOT (legal_followup_operation_v1(reader,'list',jsonb_build_object('normId',body->>'normId'),NULL)->>'canManage')::boolean,'reader reads');checks:=checks+1;
  PERFORM assert_true(rejects(c||'{"actorSessionVersion":2}','list',jsonb_build_object('normId',body->>'normId'),NULL,'LEGAL_SESSION_INVALID'),'session version');checks:=checks+1;
  PERFORM assert_true(rejects(c,'save',body||'{"dueDate":"2026-02-30"}',gen_random_uuid(),'FOLLOWUP_INPUT_INVALID'),'invalid date');checks:=checks+1;
  PERFORM assert_true(rejects(c,'save',body||'{"tenantId":"external"}',gen_random_uuid(),'FOLLOWUP_INPUT_INVALID'),'extra authority');checks:=checks+1;
  PERFORM assert_true(rejects(c,'save',body||'{"reason":""}',gen_random_uuid(),'FOLLOWUP_INPUT_INVALID'),'reason required');checks:=checks+1;
  updated:=body||jsonb_build_object('id',f,'expectedVersion',1,'status','done','reason','Resolución de ensayo');
  PERFORM assert_true((legal_followup_operation_v1(c,'save',updated,k2)->>'recordVersion')::int=2,'resolve');checks:=checks+1;
  PERFORM assert_true((legal_followup_operation_v1(c,'save',updated,k2)->>'replayed')::boolean,'update replay');checks:=checks+1;
  PERFORM assert_true(rejects(c,'save',updated,gen_random_uuid(),'FOLLOWUP_VERSION_CONFLICT'),'stale update');checks:=checks+1;
  PERFORM assert_true(rejects(c,'save',updated||'{"expectedVersion":2,"normVersion":2}',gen_random_uuid(),'FOLLOWUP_SOURCE_IMMUTABLE'),'version reference frozen');checks:=checks+1;
  PERFORM assert_true(rejects(c,'save',updated||'{"expectedVersion":2}',gen_random_uuid(),'FOLLOWUP_NO_CHANGE'),'no change');checks:=checks+1;
  PERFORM legal_followup_operation_v1(c,'save',updated||'{"expectedVersion":2,"status":"cancelled","reason":"Cancelación de ensayo"}',gen_random_uuid());
  PERFORM legal_followup_operation_v1(c,'save',updated||'{"expectedVersion":3,"status":"open","reason":"Reapertura documentada de ensayo"}',gen_random_uuid());
  res:=legal_followup_operation_v1(c,'detail',jsonb_build_object('id',f),NULL)->'record';
  PERFORM assert_true(jsonb_array_length(res->'history')=4 AND res->>'status'='open' AND (res->>'normVersion')::int=1 AND (res->>'currentNormVersion')::int=2,'cancel reopen and historical reference');checks:=checks+1;
  BEGIN UPDATE legal_followup_event SET title='Forbidden edit' WHERE followup_id=f;RAISE EXCEPTION 'MUTATION_UNEXPECTED';EXCEPTION WHEN OTHERS THEN IF SQLERRM='MUTATION_UNEXPECTED' THEN RAISE;END IF;END;
  PERFORM assert_true((SELECT title='Revisar referencia' FROM legal_followup_event WHERE followup_id=f AND version=1),'event immutable');checks:=checks+1;
  UPDATE tenant_identity_session SET auth_level='password' WHERE user_email='writer@example.invalid';
  PERFORM assert_true(rejects(c,'list',jsonb_build_object('normId',body->>'normId'),NULL,'LEGAL_SESSION_INVALID'),'MFA required');checks:=checks+1;
  UPDATE tenant_identity_session SET auth_level='mfa' WHERE user_email='writer@example.invalid';
  FOR v IN 1..99 LOOP PERFORM legal_followup_operation_v1(c,'save',body||jsonb_build_object('title','Tarea de ensayo '||v),gen_random_uuid());END LOOP;
  PERFORM assert_true(jsonb_array_length(legal_followup_operation_v1(c,'list',jsonb_build_object('normId',body->>'normId'),NULL)->'rows')=100,'bounded list');checks:=checks+1;
  PERFORM assert_true(rejects(c,'save',body,gen_random_uuid(),'FOLLOWUP_CAPACITY'),'per norm capacity');checks:=checks+1;
  PERFORM assert_true(NOT has_table_privilege('municontrol_actions_runtime_app','public.legal_followup','SELECT,INSERT,UPDATE,DELETE'),'no direct table access');checks:=checks+1;
  PERFORM assert_true(NOT has_function_privilege('municontrol_actions_runtime_app','public.legal_followup_record_v1(uuid,uuid,boolean)','EXECUTE'),'no helper access');checks:=checks+1;
  PERFORM assert_true((SELECT count(*)=1 FROM legal_norm) AND (SELECT count(*)=2 FROM legal_norm_revision),'norms unchanged');checks:=checks+1;
  RAISE EXCEPTION USING ERRCODE='P0790',MESSAGE='FOLLOWUP_QA_SUCCESS';
 EXCEPTION WHEN SQLSTATE 'P0790' THEN NULL;
 END;
 IF to_regnamespace('mc_qa_followups_079') IS NOT NULL OR checks<>27 THEN RAISE EXCEPTION 'FOLLOWUP_QA_NOT_ROLLED_BACK';END IF;
 PERFORM set_config('mc.followup_qa',jsonb_build_object('checksPassed',checks,'syntheticSchemaRolledBack',true,'municipalRowsWritten',0)::text,true);
END $qa$;
SELECT current_setting('mc.followup_qa')::jsonb AS evidence;
