import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {LegalVersionComparison} from './legal-version-comparison';
import {LegalDocumentaryWorkspace} from './legal-documentary-workspace';
import {legalPageCsv,legalDossierHtml,assertSameLegalRecord} from '../../assets/legal-document-export.js';
import {LegalPdfAssistant} from './legal-pdf-assistant';
import {DocumentReaderDialog} from './document-reader-dialog';
import {LegalArticleWorkspace} from './legal-article-workspace';
import {blankLegalDraft,legalDraftFingerprint,legalDraftChanged,normalizeLegalDraft,LEGAL_KINDS,LEGAL_ISSUERS,LEGAL_MAX_FILE,legalUuid,verifyLegalResponse} from '../../assets/legal-registry-model.js';
type Article={label:string;text:string;page:number};
type Draft=ReturnType<typeof blankLegalDraft>;
type RecordData={id:string;kind:string;issuer:string;number:string;year:number;version:number;currentVersion:number;metadata:Draft['metadata'];recordedAt:string;recordedBy:string;reason:string;legalStatus:string;document:{filename:string;sha256:string;bytes:number;pages:number};history:{version:number;recordedAt:string;recordedBy:string;reason:string}[]};
type Boot={canRegister:boolean;total:number;storageBytes:number;storageLimitBytes:number};
type ListData={total:number;page:number;pageSize:number;rows:{id:string;kind:string;issuer:string;number:string;year:number;title:string;current_version:number;stage:string}[]};
const API='/api/internal-legal-registry';
async function request(params:Record<string,string>|null,body?:unknown,key?:string,signal?:AbortSignal){const response=await fetch(API+(params?'?'+new URLSearchParams(params):''),{method:body?'POST':'GET',credentials:'same-origin',cache:'no-store',headers:{Accept:'application/json',...(body?{'Content-Type':'application/json','Idempotency-Key':key!}: {})},...(body?{body:JSON.stringify(body)}:{}),signal:signal??AbortSignal.timeout(25000)});let value;try{value=await response.json();}catch{throw Object.assign(Error('No llegó una confirmación válida.'),{status:503});}if(!response.ok||!value?.ok)throw Object.assign(Error(value?.error||'No se pudo completar la operación.'),{status:response.status,code:value?.code});try{return verifyLegalResponse(body?'save':params?.resource,value.data);}catch{throw Object.assign(Error('La respuesta no pudo verificarse.'),{status:503});}}
const date=(value:string)=>value?new Date(value).toLocaleString('es-AR'):'Sin informar';
const field=(name:string,label:string,value:string|number,onChange:(v:string)=>void,options:Record<string,any>={})=><label className={options.wide?'lr-wide':''}>{label}{options.multiline?<textarea name={name} value={value} onChange={e=>onChange(e.target.value)} rows={options.rows||3} maxLength={options.maxLength||4000}/>:<input name={name} value={value} onChange={e=>onChange(e.target.value)} type={options.type||'text'} required={!!options.required} maxLength={options.maxLength||240} min={options.min} max={options.max} readOnly={!!options.readOnly}/>}</label>;
function LegalRegistry(){
 const[boot,setBoot]=useState<Boot|null>(null),[list,setList]=useState<ListData|null>(null),[record,setRecord]=useState<RecordData|null>(null);
 const[draft,setDraft]=useState<Draft|null>(null),[review,setReview]=useState(false),[pending,setPending]=useState<{key:string;body:Draft}|null>(null);
 const[filters,setFilters]=useState({q:'',kind:'',year:''}),[busy,setBusy]=useState(false),[message,setMessage]=useState('Verificando tu acceso al registro normativo…'),[error,setError]=useState(false),[blocked,setBlocked]=useState(false);
 const[comparing,setComparing]=useState(false);
 const[reading,setReading]=useState(false);
 const[documentary,setDocumentary]=useState(false);
 const[appliedFilters,setAppliedFilters]=useState({q:'',kind:'',year:''});
 const baselineRef=useRef('');
 const alive=useRef(true),generation=useRef(0),pendingRef=useRef(pending),dirtyRef=useRef(false),opLock=useRef(false);pendingRef.current=pending;dirtyRef.current=legalDraftChanged(draft,baselineRef.current);
 const say=(text:string,isError=false)=>{setMessage(text);setError(isError);};
 const deny=()=>{setReading(false);generation.current++;pendingRef.current=null;dirtyRef.current=false;setBlocked(true);setBoot(null);setList(null);setRecord(null);setDraft(null);setPending(null);say('Tu sesión o permiso cambió. Volvé a ingresar para continuar.',true);};
 const run=async(work:()=>Promise<void>)=>{if(opLock.current||blocked)return;opLock.current=true;setBusy(true);try{await work();}catch(e:any){if(!alive.current)return;if([401,403].includes(e.status))deny();else say(e instanceof TypeError||e.name==='TimeoutError'?'No se recibió confirmación del servidor. Revisá la conexión y consultá el mismo intento si estabas guardando.':e.message||'No se pudo completar la operación.',true);}finally{opLock.current=false;if(alive.current)setBusy(false);}};
 const getList=async(page=1,selected=appliedFilters)=>{const token=generation.current;const value=await request({resource:'list',...selected,page:String(page)});if(token===generation.current&&alive.current){setList(value);setAppliedFilters({...selected});}};
 const getRecord=async(id:string,version?:number)=>{const token=generation.current;const data=await request({resource:'detail',id,version:version?String(version):''});if(token===generation.current&&alive.current){if(data.record?.id!==id||(version&&data.record.version!==version)||!data.record.metadata||!Array.isArray(data.record.history))throw Error('Ficha no verificable.');setComparing(false);setRecord(data.record);const anchor=/^#articulo-[1-9][0-9]{0,2}$/.test(location.hash)?location.hash:'';history.replaceState(null,'','/juridica?norma='+encodeURIComponent(id)+'&version='+data.record.version+anchor);setTimeout(()=>{const target=anchor?document.getElementById(anchor.slice(1)):null;if(target)target.scrollIntoView();else document.getElementById('lrRecordTitle')?.focus();},0);}};
 useEffect(()=>{
  alive.current=true;const before=(e:BeforeUnloadEvent)=>{if(dirtyRef.current||pendingRef.current){e.preventDefault();e.returnValue='';}};
  const access=(e:Event)=>{const raw=(e as CustomEvent).detail?.tenantCapabilities;const caps=raw instanceof Set?raw:new Set(Array.isArray(raw)?raw:[]);if(!caps.has('legal.norm.read')){deny();return;}if(!caps.has('legal.norm.register')){generation.current++;setDraft(null);setPending(null);pendingRef.current=null;dirtyRef.current=false;setBoot(b=>b?{...b,canRegister:false}:null);say('Tu acceso permite consultar; la preparación de cambios ya no está habilitada.',true);}};
  const pagehide=()=>{generation.current++;alive.current=false;setRecord(null);setDraft(null);setList(null);setPending(null);};
  const pageshow=(e:PageTransitionEvent)=>{if(e.persisted)location.reload();};const logout=()=>{deny();void fetch('/api/internal-auth',{method:'DELETE',credentials:'same-origin'}).finally(()=>location.replace('/acceso'));};document.getElementById('logoutButton')?.addEventListener('click',logout);
  document.addEventListener('municontrol:capabilities-ready',access);window.addEventListener('beforeunload',before);window.addEventListener('pagehide',pagehide);window.addEventListener('pageshow',pageshow);
  void run(async()=>{const initialToken=generation.current;const gate=await (window as any).MuniControlCapabilityGate?.ready;if(!gate?.tenantCapabilities?.has('legal.norm.read')){deny();return;}const b=await request({resource:'bootstrap'});if(!alive.current||initialToken!==generation.current)return;setBoot(b);if(new URLSearchParams(location.search).get("revision")==="documental")setDocumentary(true);if(location.hash==="#lector")setReading(true);await getList(1,{q:'',kind:'',year:''});if(!alive.current||initialToken!==generation.current)return;const params=new URLSearchParams(location.search),id=params.get('norma');if(id&&legalUuid(id)){const v=params.get('version');await getRecord(id,v&&/^[1-9][0-9]{0,3}$/.test(v)?Number(v):undefined);}say('Registro municipal disponible. Las fichas se guardan aquí; no se importan desde GRH.');});
  return()=>{alive.current=false;document.getElementById('logoutButton')?.removeEventListener('click',logout);document.removeEventListener('municontrol:capabilities-ready',access);window.removeEventListener('beforeunload',before);window.removeEventListener('pagehide',pagehide);window.removeEventListener('pageshow',pageshow);};
 },[]);
 const update=(section:'identity'|'metadata',key:string,value:unknown)=>setDraft(d=>d?{...d,[section]:{...d[section],[key]:value}}:d);
 async function fileSelected(file?:File){if(!file||!draft)return;await run(async()=>{if(file.size>LEGAL_MAX_FILE||!file.name.toLowerCase().endsWith('.pdf'))throw Error('Adjuntá un PDF de hasta 2 MiB.');const token=generation.current;const bytes=await file.arrayBuffer();const sha=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))).map(b=>b.toString(16).padStart(2,'0')).join('');const base64=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(Error('No se pudo leer el archivo.'));reader.readAsDataURL(file);});if(token===generation.current){setDraft(d=>d?{...d,document:{filename:file.name,contentBase64:base64,sha256:sha}}:d);say('Archivo seleccionado. Se verificará en el servidor al confirmar.');}});}
 const begin=(r?:RecordData)=>{if(!boot?.canRegister||busy||blocked)return;setComparing(false);setPending(null);history.replaceState(null,'','/juridica'+(r?'?norma='+r.id+'&version='+r.version:''));setReview(false);const nextDraft=r?{id:r.id,expectedVersion:r.currentVersion,identity:{kind:r.kind,issuer:r.issuer,number:r.number,year:r.year},metadata:structuredClone(r.metadata),document:null,reason:''}:blankLegalDraft();baselineRef.current=legalDraftFingerprint(nextDraft);setDraft(nextDraft);say(r?'Prepará una nueva versión. El historial y el PDF anterior se conservan.':'Completá la ficha y adjuntá su fuente. Todavía no se guardó nada.');setTimeout(()=>document.querySelector<HTMLInputElement>('input[name="title"]')?.focus(),0);};
 const cancel=()=>{if(pending||busy)return;if(dirtyRef.current&&!confirm('¿Descartar este formulario sin guardar?'))return;setDraft(null);setReview(false);say('Formulario descartado. No se modificó el registro.');};
 const preview=(e:React.FormEvent)=>{e.preventDefault();if(!draft||busy)return;try{setDraft(normalizeLegalDraft(draft));setReview(true);say('Revisá la ficha y el documento. Confirmar registra información, no acredita vigencia jurídica.');}catch(e:any){say(e.message,true);document.querySelector<HTMLElement>(`[name="${e.field||'title'}"]`)?.focus();}};
 async function send(recover=false){if(busy||!draft)return;const attempt=pending||{key:crypto.randomUUID(),body:draft};setPending(attempt);const token=generation.current;await run(async()=>{try{const receipt=recover?await request({resource:'attempt',key:attempt.key}):await request(null,attempt.body,attempt.key);if(token!==generation.current)return;if(!legalUuid(receipt.id)||!Number.isInteger(receipt.recordVersion))throw Error('Confirmación no verificable.');setPending(null);setDraft(null);setReview(false);await getRecord(receipt.id,receipt.recordVersion);await getList();const fresh=await request({resource:'bootstrap'});if(token!==generation.current||!alive.current)return;setBoot(fresh);say('Norma guardada · versión '+receipt.recordVersion+'. El original y la auditoría están disponibles.');}catch(e:any){if(!recover&&e.status>=400&&e.status<500&&e.status!==408){setPending(null);setReview(false);}throw e;}});}
 function downloadLocal(content:string,type:string,filename:string){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);}
 async function exportPage(){if(!list||!list.rows.length)return;const shown=list,selection={...appliedFilters},token=generation.current;await run(async()=>{const fresh=await request({resource:'list',...selection,page:String(shown.page)});if(!alive.current||token!==generation.current)return;if(JSON.stringify(fresh)!==JSON.stringify(shown)){setList(fresh);throw Error('Los resultados cambiaron. Revisá la página actualizada antes de exportar.');}downloadLocal(legalPageCsv(fresh,selection,new Date().toISOString()),'text/csv;charset=utf-8',`registro-normativo-pagina-${fresh.page}.csv`);say('Página exportada con los filtros aplicados y referencias de versión. No incluye páginas que no se muestran.');});}
 async function exportDossier(){if(!record)return;const shown=record,token=generation.current;await run(async()=>{const fresh=(await request({resource:'detail',id:shown.id,version:String(shown.version)})).record;if(!alive.current||token!==generation.current)return;assertSameLegalRecord(shown,fresh);downloadLocal(legalDossierHtml(fresh,new Date().toISOString()),'text/html;charset=utf-8',`ficha-normativa-${fresh.number.replace(/[^A-Za-z0-9-]/g,'-')}-${fresh.year}-v${fresh.version}.html`);say('Ficha HTML descargada para imprimir desde el navegador. Incluye artículos, historial y huella; no sustituye el PDF original ni acredita firma o vigencia.');});}
 async function download(){if(!record)return;const r=record,token=generation.current;await run(async()=>{const response=await fetch(API+'?'+new URLSearchParams({resource:'download',id:r.id,version:String(r.version)}),{credentials:'same-origin',cache:'no-store',signal:AbortSignal.timeout(25000)});if(!response.ok)throw Object.assign(Error('No se pudo descargar el documento.'),{status:response.status});const bytes=await response.arrayBuffer();const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))).map(v=>v.toString(16).padStart(2,'0')).join('');if(hash!==r.document.sha256)throw Error('La huella del archivo no coincide. Descarga rechazada.');if(!alive.current||token!==generation.current)return;const url=URL.createObjectURL(new Blob([bytes],{type:'application/pdf'})),a=document.createElement('a');a.href=url;a.download=`norma-${r.number.replace(/[^A-Za-z0-9-]/g,'-')}-${r.year}-v${r.version}.pdf`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);say('PDF original descargado; huella SHA-256 comprobada.');});}
 return <div className="legal-workspace">
  <header className="lr-heading"><div><p className="lr-eyebrow">JURÍDICA Y LEGISLATIVA · MUNICIPIO</p><h1>Registro normativo</h1><p>Ordenanzas, decretos y resoluciones con su documento fuente, artículos e historial. Dentro de MuniControl, separado de los procesos de sueldos.</p></div><a href="/personal#inicio" className="button">Volver al portal</a></header>
  <div className={'lr-notice '+(error?'lr-error':'')} role="status" aria-live="polite">{message}</div>
  {blocked?<section className="lr-card"><h2>Acceso no disponible</h2><p>Este registro exige una sesión municipal con permiso específico de consulta.</p><a href="/acceso?next=%2Fjuridica" className="button primary">Ingresar nuevamente</a></section>:<>
  <nav className="lr-tabs" aria-label="Secciones del área jurídica"><button className="button primary" type="button" onClick={()=>{if(draft){cancel();return;}setDocumentary(false);setRecord(null);history.replaceState(null,'','/juridica');}} disabled={busy||!!pending}>Registro normativo</button><button className="button" type="button" disabled={!boot||busy} onClick={()=>setReading(true)}>Lector documental · OCR y extractos</button><button className="button" type="button" disabled={!boot||busy||!!draft||!!pending} onClick={()=>{setDocumentary(true);setRecord(null);setComparing(false);history.replaceState(null,"","/juridica?revision=documental");}}>Revisión documental</button><a href="/internal-legal-followups.html" className="button" data-requires-any-capability="legal.norm.read">Agenda de seguimientos</a><a href="/internal-legal-matters.html" className="button" data-requires-any-capability="legal.norm.read">Asuntos jur?dicos</a><a href="/internal-legal-expedients.html" className="button" data-requires-any-capability="legal.norm.read">Expedientes</a><a href="/modulos#juridica" className="button">Alcance de contratos y expedientes</a><span>Vigencia y análisis jurídico: siguiente etapa</span></nav>
  {!boot&&!busy&&<button className="button" onClick={()=>location.reload()}>Reintentar consulta</button>}
  {boot&&<div className="lr-stats"><div><strong>{boot.total}</strong><span>Normas registradas en este municipio</span></div><div><strong>{(boot.storageBytes/1048576).toFixed(1)} MiB</strong><span>Archivo privado utilizado / {boot.storageLimitBytes/1048576} MiB iniciales</span></div><div><strong>Historial conservado</strong><span>Las correcciones crean versiones; no sobrescriben el original.</span></div></div>}
  {documentary&&boot&&!draft&&!record&&<LegalDocumentaryWorkspace onDenied={deny}/>}
  {!documentary&&!draft&&!record&&<section className="lr-card" aria-labelledby="lrSearchTitle"><div className="lr-section-heading"><div><h2 id="lrSearchTitle">Buscar normas del municipio</h2><p>Por número, título, tema o texto de los artículos cargados. No es el buscador de módulos del menú.</p></div>{boot?.canRegister&&<button className="button primary" onClick={()=>begin()} disabled={busy}>Registrar norma</button>}</div>
    <form className="lr-search" onSubmit={e=>{e.preventDefault();void run(()=>getList(1,filters));}}><label>Buscar en el registro<input name="q" disabled={busy} value={filters.q} maxLength={160} placeholder="Ej.: 1021, presupuesto, luminarias…" onChange={e=>setFilters({...filters,q:e.target.value})}/></label><label>Tipo<select disabled={busy} value={filters.kind} onChange={e=>setFilters({...filters,kind:e.target.value})}><option value="">Todos</option>{Object.entries(LEGAL_KINDS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Año<input name="yearFilter" disabled={busy} type="number" min="1700" max="2200" value={filters.year} onChange={e=>setFilters({...filters,year:e.target.value})}/></label><button className="button" disabled={busy||!boot}>Buscar</button><button className="button" type="button" disabled={busy||!boot} onClick={()=>{const clean={q:"",kind:"",year:""};setFilters(clean);void run(()=>getList(1,clean));}}>Limpiar filtros</button></form><p className="lr-subtle" aria-live="polite">Filtros aplicados: {[appliedFilters.q&&("Texto: "+appliedFilters.q),appliedFilters.kind&&LEGAL_KINDS[appliedFilters.kind],appliedFilters.year&&("Año: "+appliedFilters.year)].filter(Boolean).join(" · ")||"Todos los registros"}. Los cambios del formulario se aplican al pulsar Buscar.</p>
    {list&&<><p className="lr-subtle">{list.total} resultados · Página {list.page}. La búsqueda sólo cubre las fichas y artículos incorporados; no interpreta automáticamente el texto de los PDF.</p>{list.rows.length?<div className="lr-results">{list.rows.map(r=><article key={r.id}><div><span className="lr-tag">{LEGAL_KINDS[r.kind]} {r.number}/{r.year} · {r.issuer}</span><h3>{r.title}</h3><p>{r.stage==='proyecto'?'Proyecto':'Acto registrado'} · Versión {r.current_version} · Vigencia no determinada</p></div><button className="button" disabled={busy} onClick={()=>void run(()=>getRecord(r.id))}>Abrir ficha</button></article>)}</div>:<div className="lr-empty"><h3>{boot?.total===0?'El registro todavía no tiene normas cargadas':'No hay coincidencias con estos filtros'}</h3><p>{boot?.total===0?'Empezá incorporando una norma y su PDF. Las normas históricas también pueden registrarse con su año y fechas originales.':'Probá otro título, número, año o palabra presente en un artículo cargado.'}</p></div>}<div className="lr-actions"><button className="button" type="button" disabled={busy||!list.rows.length} onClick={()=>void exportPage()}>Exportar página · CSV</button><button className="button" disabled={busy||list.page<=1} onClick={()=>void run(()=>getList(list.page-1))}>Anterior</button><button className="button" disabled={busy||list.page*list.pageSize>=list.total} onClick={()=>void run(()=>getList(list.page+1))}>Siguiente</button></div></>}
  </section>}
  {draft&&!review&&!pending&&<form className="lr-card" onSubmit={preview}><h2>{draft.id?'Preparar una nueva versión':'Registrar una norma'}</h2><p>Para normativa de consulta municipal. No cargues expedientes reservados ni documentación personal en este registro compartido del área.</p><fieldset disabled={busy}><legend>1 · Identificación y fuente</legend><div className="lr-grid">
    <label>Tipo<select name="kind" value={draft.identity.kind} disabled={!!draft.id} onChange={e=>update('identity','kind',e.target.value)}>{Object.entries(LEGAL_KINDS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Órgano emisor<select name="issuer" value={draft.identity.issuer} disabled={!!draft.id} onChange={e=>update('identity','issuer',e.target.value)}>{Object.entries(LEGAL_ISSUERS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>
    {field('number','Número o identificador',draft.identity.number,v=>update('identity','number',v),{required:true,maxLength:30,readOnly:!!draft.id})}{field('year','Año de la norma',draft.identity.year,v=>update('identity','year',Number(v)),{required:true,type:'number',min:1700,max:2200,readOnly:!!draft.id})}
    {field('title','Título o asunto',draft.metadata.title,v=>update('metadata','title',v),{required:true,wide:true})}
    <label>Clase de documento<select name="stage" value={draft.metadata.stage} onChange={e=>update('metadata','stage',e.target.value)}><option value="acto_registrado">Acto registrado</option><option value="proyecto">Proyecto — no es una norma sancionada</option></select></label>
    {field('topics','Temas o palabras clave',draft.metadata.topics,v=>update('metadata','topics',v),{maxLength:300})}
    {field('sourceReference','Procedencia: expediente, archivo o publicación',draft.metadata.sourceReference,v=>update('metadata','sourceReference',v),{required:true,maxLength:500,wide:true})}
    <label className="lr-wide">{draft.id?'PDF fuente nuevo (opcional; si no, se conserva el anterior)':'Documento fuente en PDF'}<input name="pdf" type="file" accept="application/pdf,.pdf" onChange={e=>void fileSelected(e.target.files?.[0])}/><small>Hasta 2 MiB y 30 páginas en este primer corte. Se conserva exactamente el archivo recibido, sin modificarlo.</small>{draft.document&&<strong>{draft.document.filename} · Archivo seleccionado</strong>}</label>
    </div></fieldset><fieldset disabled={busy}><legend>2 · Fechas y contenido de consulta</legend><div className="lr-grid">
    {field('issueDate','Emisión o sanción (según corresponda)',draft.metadata.issueDate,v=>update('metadata','issueDate',v),{type:'date',min:'1700-01-01',max:'2200-12-31'})}
    {field('publicationDate','Publicación',draft.metadata.publicationDate,v=>update('metadata','publicationDate',v),{type:'date',min:'1700-01-01',max:'2200-12-31'})}
    {field('effectiveDate','Fecha de efectos declarada',draft.metadata.effectiveDate,v=>update('metadata','effectiveDate',v),{type:'date',min:'1700-01-01',max:'2200-12-31'})}
    <p className="lr-subtle">Las fechas son datos documentales declarados. Guardarlas no certifica la vigencia ni una derogación.</p>
    {field('summary','Resumen documental (opcional)',draft.metadata.summary,v=>update('metadata','summary',v),{multiline:true,wide:true,maxLength:4000})}
    </div></fieldset><fieldset disabled={busy}><legend>3 · Artículos referenciables (opcional)</legend><p>Transcribí el texto y la página del PDF. Esta transcripción sirve para buscar y citar; no reemplaza al original ni implica revisión jurídica.</p>
    <LegalPdfAssistant document={draft.document} articles={draft.metadata.articles} disabled={busy} onAdd={(article:Article,sha:string)=>{if(!draft.document||draft.document.sha256!==sha)throw Error("El PDF seleccionado cambió. Volvé a leer la fuente actual.");update("metadata","articles",[...draft.metadata.articles,article]);}}/>
    {draft.metadata.articles.map((a:Article,i:number)=><div className="lr-article-editor" key={i}>{field('articleLabel'+i,'Identificador: artículo, inciso o anexo',a.label,v=>update('metadata','articles',draft.metadata.articles.map((x:Article,n:number)=>n===i?{...x,label:v}:x)),{required:true,maxLength:60})}{field('articlePage'+i,'Página del PDF',a.page,v=>update('metadata','articles',draft.metadata.articles.map((x:Article,n:number)=>n===i?{...x,page:Number(v)}:x)),{type:'number',min:1,max:30,required:true})}{field('articleText'+i,'Texto transcrito',a.text,v=>update('metadata','articles',draft.metadata.articles.map((x:Article,n:number)=>n===i?{...x,text:v}:x)),{multiline:true,wide:true,maxLength:12000})}<button type="button" className="button" onClick={()=>update('metadata','articles',draft.metadata.articles.filter((_:Article,n:number)=>n!==i))}>Quitar artículo {i+1}</button></div>)}
    <button type="button" className="button" disabled={draft.metadata.articles.length>=150} onClick={()=>update('metadata','articles',[...draft.metadata.articles,{label:'',text:'',page:1}])}>Agregar artículo</button></fieldset>
    <fieldset disabled={busy}><legend>4 · Fundamento del registro</legend>{field('reason','Motivo del alta o de la corrección',draft.reason,v=>setDraft({...draft,reason:v}),{required:true,maxLength:500,wide:true})}<p>El sistema registra tu usuario y la fecha. Ninguna corrección elimina el historial previo.</p><div className="lr-actions"><button className="button primary" type="submit">Revisar antes de guardar</button><button className="button" type="button" onClick={cancel}>Cancelar</button></div></fieldset>
  </form>}
  {draft&&review&&!pending&&<section className="lr-card"><h2>Revisar el registro</h2><p className="lr-tag">{LEGAL_KINDS[draft.identity.kind]} {draft.identity.number}/{draft.identity.year} · {draft.identity.issuer}</p><h3>{draft.metadata.title}</h3><dl><dt>Fuente</dt><dd>{draft.document?.filename||'Se conserva el PDF de la versión anterior'}</dd><dt>Procedencia</dt><dd>{draft.metadata.sourceReference}</dd><dt>Artículos transcritos</dt><dd>{draft.metadata.articles.length}</dd><dt>Motivo</dt><dd>{draft.reason}</dd><dt>Vigencia jurídica</dt><dd>No determinada por este registro</dd></dl><section className="lr-review-articles" aria-label="Contenido que se va a guardar"><h3>Artículos de esta versión</h3><p>Contrastá texto, página y fuente. La lectura asistida no reemplaza al PDF original.</p>{draft.document&&<p className="lr-hash">PDF seleccionado · SHA-256 {draft.document.sha256}</p>}{draft.metadata.articles.length?draft.metadata.articles.map((a:Article,i:number)=><article key={i}><h4>{a.label} <span className="lr-tag">Página {a.page}</span></h4><p>{a.text}</p></article>):<p>No se incorporarán artículos; sólo la ficha y su documento fuente.</p>}</section><p>Confirmar guarda una {draft.id?'nueva versión documental':'ficha y su primera versión'}. No modifica liquidaciones, contratos ni normas externas.</p><div className="lr-actions"><button className="button primary" disabled={busy} onClick={()=>void send()}>Confirmar y guardar</button><button className="button" disabled={busy} onClick={()=>setReview(false)}>Volver a editar</button></div></section>}
  {pending&&<section className="lr-card"><h2>{busy?'Guardando la versión…':'Confirmación pendiente'}</h2><p>Conservamos la misma clave para evitar duplicados. Consultá el resultado de este intento antes de iniciar otro.</p><div className="lr-actions"><button className="button primary" disabled={busy} onClick={()=>void send(true)}>Consultar este intento</button><button className="button" disabled={busy} onClick={()=>void send(false)}>Reenviar el mismo intento</button></div></section>}
  {record&&!draft&&comparing&&<LegalVersionComparison key={record.id+":"+record.version} record={record} loadVersion={async(id,version,signal)=>(await request({resource:"detail",id,version:String(version)},undefined,undefined,signal)).record} onDenied={deny} onClose={()=>{setComparing(false);setTimeout(()=>document.getElementById("lrRecordTitle")?.focus(),0);}}/>}
  {record&&!draft&&!comparing&&<section className="lr-card lr-record" aria-labelledby="lrRecordTitle"><div className="lr-section-heading"><div><span className="lr-tag">{LEGAL_KINDS[record.kind]} {record.number}/{record.year} · {record.issuer}</span><h2 id="lrRecordTitle" tabIndex={-1}>{record.metadata.title}</h2><p>Versión documental {record.version} de {record.currentVersion} · {record.metadata.stage==='proyecto'?'Proyecto — no es una norma sancionada':'Acto registrado'}</p></div><div className="lr-actions">{record.currentVersion>1&&<button className="button" onClick={()=>setComparing(true)} disabled={busy}>Comparar versiones</button>}<button className="button primary" onClick={()=>void download()} disabled={busy}>Descargar PDF original</button><button className="button" onClick={()=>void exportDossier()} disabled={busy}>Exportar ficha · HTML imprimible</button><a href={"/internal-legal-matters.html?"+new URLSearchParams({norma:record.id,version:String(record.version)})} className="button" data-requires-any-capability="legal.norm.read">Crear asunto jur?dico</a><a href={"/internal-legal-norm-relations.html?"+new URLSearchParams({norma:record.id,version:String(record.version)})} className="button" data-requires-any-capability="legal.norm.read">Relaciones normativas</a>{boot?.canRegister&&record.version===record.currentVersion&&<button className="button" onClick={()=>begin(record)} disabled={busy}>Crear nueva versión</button>}{record.version!==record.currentVersion&&<button className="button" onClick={()=>void run(()=>getRecord(record.id))} disabled={busy}>Abrir versión actual</button>}</div></div>
    <div className="lr-notice">Vigencia no determinada. Esta ficha conserva documentación y transcripciones; no verifica firmas ni declara derogaciones.</div>
    <dl className="lr-record-fields"><dt>Órgano emisor</dt><dd>{LEGAL_ISSUERS[record.issuer]}</dd><dt>Procedencia</dt><dd>{record.metadata.sourceReference}</dd><dt>Temas</dt><dd>{record.metadata.topics||'Sin informar'}</dd><dt>Emisión o sanción</dt><dd>{record.metadata.issueDate?record.metadata.issueDate.split('-').reverse().join('/'):'Sin informar'}</dd><dt>Publicación</dt><dd>{record.metadata.publicationDate?record.metadata.publicationDate.split('-').reverse().join('/'):'Sin informar'}</dd><dt>Fecha de efectos declarada</dt><dd>{record.metadata.effectiveDate?record.metadata.effectiveDate.split('-').reverse().join('/'):'Sin informar'}</dd><dt>Archivo recibido</dt><dd>{record.document.filename} · {record.document.pages} páginas · {(record.document.bytes/1024).toFixed(1)} KiB</dd><dt>Huella del documento</dt><dd className="lr-hash">{record.document.sha256}</dd><dt>Incorporado por</dt><dd>{record.recordedBy} · {date(record.recordedAt)}</dd><dt>Fundamento de esta versión</dt><dd>{record.reason}</dd></dl>
    {record.metadata.summary&&<section className="lr-summary"><h3>Resumen documental</h3><p>{record.metadata.summary}</p></section>}
    <LegalArticleWorkspace key={record.id+":"+record.version+":"+record.document.sha256} record={record} disabled={busy} onDenied={deny} loadRecord={async(id:string,version:number,signal:AbortSignal)=>(await request({resource:"detail",id,version:String(version)},undefined,undefined,signal)).record}/>
    <section className="lr-history"><h3>Historial de versiones</h3><p className="lr-subtle">Cada modificación conserva su documento, metadatos, responsable y motivo. La versión documental no implica un cambio en la vigencia jurídica.</p><ol>{record.history.map(h=><li key={h.version}><div><strong>Versión {h.version}{h.version===record.currentVersion?' · Actual':''}</strong><p>{h.reason}</p><small>{h.recordedBy} · {date(h.recordedAt)}</small></div><button className="button" disabled={busy||h.version===record.version} onClick={()=>void run(()=>getRecord(record.id,h.version))}>{h.version===record.version?'Versión abierta':'Ver versión '+h.version}</button></li>)}</ol></section>
  </section>}
  {reading&&boot&&!blocked&&<DocumentReaderDialog onClose={()=>setReading(false)} onRecheck={async()=>{try{await request({resource:"bootstrap"});}catch(e:any){setReading(false);if([401,403].includes(e.status))deny();throw e;}}}/>}
  <aside className="lr-footer"><strong>Un área dentro del mismo MuniControl</strong><p>Este registro no modifica legajos, liquidaciones ni contratos. Compartir una referencia no concede acceso a quien no tenga permiso de consulta.</p></aside>
  </>}
 </div>;
}
const host=document.getElementById('legalRegistryRoot');if(host)createRoot(host).render(<LegalRegistry/>);
