import {useState} from 'react';
import {salaryRowKey,salarySerialized} from '../../assets/native-salary-catalog-model.js';
import {salaryCopyPlan} from '../../assets/native-salary-copy-model.js';
import Definition,{salaryDefinitionTitle as title} from './NativeSalaryDefinition.jsx';

const PAGE=20,clone=value=>structuredClone(value),natural=new Intl.Collator('es',{numeric:true});
function Comparison({item}){return <details><summary>{title(item.target)} · {({new:'Nueva definición',reuse:'Existente idéntica; se conserva',different:'Definición diferente; requiere revisión individual',missing_scale:'Falta escala revisada en destino',missing_class:'Falta clase inequívoca en destino',overlap:'Vigencia superpuesta'})[item.disposition]}</summary><h5>Origen</h5><Definition row={item.source}/><h5>Existente en destino</h5><Definition row={item.existing}/>{item.overlapping?.map(row=><div key={salaryRowKey(row)}><h5>Intervalo existente</h5><Definition row={row}/></div>)}<h5>Propuesto para destino</h5><Definition row={item.target}/></details>;}

export default function NativeSalaryCopy({items,classification,disabled,individualEditing,onApply,onNotice}){
 const [source,setSource]=useState(''),[targets,setTargets]=useState([]),[selection,setSelection]=useState([]),[query,setQuery]=useState(''),[page,setPage]=useState(0),[review,setReview]=useState(null),[conflicts,setConflicts]=useState(null),[confirmed,setConfirmed]=useState(false);
 const agreements=classification.filter(row=>row.kind==='agreements'),sources=[...new Set(items.filter(row=>['concept','auxiliary'].includes(row.kind)&&row.active).map(row=>row.agreementCode))].sort(natural.compare);
 const filtered=items.filter(row=>['concept','auxiliary'].includes(row.kind)&&row.active&&row.agreementCode===source&&[row.code,row.label,row.validFrom].join(' ').toLowerCase().includes(query.toLowerCase())).sort((a,b)=>natural.compare(a.code,b.code)||a.validFrom.localeCompare(b.validFrom));
 const last=Math.max(0,Math.ceil(filtered.length/PAGE)-1),currentPage=Math.min(page,last),visible=filtered.slice(currentPage*PAGE,(currentPage+1)*PAGE),selected=new Set(selection.map(row=>row.key));
 const clearReview=()=>{setReview(null);setConflicts(null);setConfirmed(false);};
 const plan=()=>salaryCopyPlan(items,selection,targets,classification);
 function select(rows,checked=true){if(disabled)return;clearReview();setSelection(previous=>{const next=new Map(previous.map(row=>[row.key,row]));for(const row of rows){const key=salaryRowKey(row);if(checked)next.set(key,{key,before:clone(row)});else next.delete(key);}return [...next.values()];});}
 function preview(){if(disabled)return;clearReview();try{const next=plan();setReview(next);onNotice(`${next.selectedCount} seleccionados, ${next.dependencyCount} dependencias y ${next.targets.length} destinos: ${next.newDefinitionsCount} nuevas definiciones y ${next.reusedCount} existentes idénticas para revisar.`);}catch(error){if(error.comparisons)setConflicts(error.comparisons);onNotice(error.message);}}
 function apply(){if(disabled||!review||!confirmed||!review.changes.length)return;try{const next=plan();if(salarySerialized(next)!==salarySerialized(review))throw Error('Cambió la preparación completa. Volvé a compararla antes de incorporar.');onApply(next.items);setSelection([]);clearReview();onNotice(`${next.newDefinitionsCount} definiciones incorporadas al borrador completo. Revisá la versión y enviala para aprobación independiente.`);}catch(error){clearReview();if(error.comparisons)setConflicts(error.comparisons);onNotice(error.message);}}
 return <details className="sc-copy" data-salary-copy><style>{css}</style><summary>Preparar conceptos en otros convenios</summary><h3>Comparar origen, dependencias y destinos</h3><p>Conservá código, naturaleza, unidad, precisión, valor exacto, vigencia y respaldo de conceptos y auxiliares declarados. Revisá expresamente que corresponden a cada destino. No se copian fórmulas ni se calculan importes. Las escalas necesarias deben existir idénticas en destino; no se equiparan clases automáticamente.</p>{individualEditing&&<p>Terminá la edición individual o usá Limpiar fila. Sus datos se conservan.</p>}
 <fieldset disabled={disabled}><div className="sc-form"><label>Convenio de origen<select aria-label="Convenio de origen" value={source} onChange={event=>{setSource(event.target.value);setSelection([]);setTargets(previous=>previous.filter(code=>code!==event.target.value));setPage(0);clearReview();}}><option value="">Elegí origen</option>{sources.map(code=><option key={code} value={code}>{code} · {agreements.find(row=>row.code===code)?.label??'Definiciones propias'}</option>)}</select></label><label>Buscar conceptos del origen<input type="search" maxLength={160} value={query} onChange={event=>{setQuery(event.target.value);setPage(0);clearReview();}}/></label></div>
 <h4>Convenios de destino</h4><div className="sc-copy-targets">{agreements.filter(row=>row.code!==source).map(row=><label className="sc-copy-check" key={row.code}><input type="checkbox" data-salary-copy-target={row.code} checked={targets.includes(row.code)} onChange={event=>{setTargets(previous=>event.target.checked?[...previous,row.code]:previous.filter(code=>code!==row.code));clearReview();}}/><span>{row.code} · {row.label}</span></label>)}</div>
 <p aria-live="polite">{selection.length} conceptos seleccionados en todas las páginas · {filtered.length} en este filtro · página {currentPage+1}.</p><div className="sc-actions"><button type="button" disabled={!visible.length} onClick={()=>select(visible)}>Seleccionar esta página de conceptos</button><button type="button" disabled={!selection.length} onClick={()=>{setSelection([]);clearReview();}}>Quitar selección de conceptos</button></div><ul className="sc-copy-list">{visible.map(row=><li key={salaryRowKey(row)}><label className="sc-copy-check"><input type="checkbox" data-salary-copy-key={salaryRowKey(row)} checked={selected.has(salaryRowKey(row))} onChange={event=>select([row],event.target.checked)}/><span>{title(row)} · {row.label}</span></label></li>)}</ul>{!filtered.length&&<p>No hay conceptos habilitados para este origen y búsqueda.</p>}<div className="sc-actions"><button type="button" disabled={currentPage===0} onClick={()=>setPage(currentPage-1)}>Conceptos anteriores</button><button type="button" disabled={currentPage>=last} onClick={()=>setPage(currentPage+1)}>Conceptos siguientes</button><button type="button" onClick={preview}>Comparar preparación completa</button><button type="button" onClick={()=>{setSource('');setTargets([]);setSelection([]);setQuery('');setPage(0);clearReview();}}>Reiniciar preparación de conceptos</button></div>
 {conflicts&&<section data-salary-copy-conflicts><h4>Conflictos que requieren revisión individual</h4><p>No se incorporó ninguna definición. La comparación incluye todos los destinos y dependencias, también los que ya coinciden.</p>{conflicts.map(item=><Comparison key={salaryRowKey(item.target)} item={item}/>)}</section>}
 {review&&<section data-salary-copy-impact><h4>Preparación completa para revisión</h4><p>{review.selectedCount} seleccionados · {review.dependencyCount} dependencias adicionales · {review.targets.length} convenios de destino · {review.newDefinitionsCount} nuevas definiciones · {review.reusedCount} existentes idénticas. Se conservarán las {items.length} definiciones anteriores.</p>{review.comparisons.map(item=><Comparison key={salaryRowKey(item.target)} item={item}/>)}{review.changes.length?<><label className="sc-copy-check"><input type="checkbox" checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/><span>Revisé cada destino, su código, unidad, vigencia, respaldo y dependencias. Esta preparación no homologa una fórmula.</span></label><div className="sc-actions"><button type="button" className="sc-primary" disabled={!confirmed} onClick={apply}>Incorporar conceptos revisados al borrador</button><button type="button" onClick={clearReview}>Volver sin incorporar conceptos</button></div></>:<p>Todos los destinos ya coinciden. No hay cambios que incorporar.</p>}</section>}
 </fieldset></details>;
}
const css=`.sc-copy{margin:20px 0;border:1px solid #c9deda;border-radius:9px;background:#f7fbf9;min-width:0}.sc-copy p{overflow-wrap:anywhere}.sc-copy .sc-copy-check{display:flex;flex-direction:row;align-items:center;gap:12px;min-height:44px;cursor:pointer}.sc-copy .sc-copy-check input{flex:0 0 20px;width:20px;height:20px;min-height:20px;padding:0;accent-color:#007d75}.sc-copy-check span{min-width:0;overflow-wrap:anywhere}.sc-copy-targets{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.sc-copy-list{list-style:none;padding:0;margin:0}.sc-copy-list li{border-bottom:1px solid #dce9e5;padding:8px 0}.sc-copy h5{font-size:1rem}@media(max-width:700px){.sc-copy-targets{grid-template-columns:minmax(0,1fr)}}`;
