import {useEffect,useRef,useState} from 'react';
import {SALARY_NATURES,SALARY_UNITS,salaryBootstrap,salaryCommand,salaryDiff,salaryItems,salaryReceipt,salaryRowKey,salarySerialized} from '../../assets/native-salary-catalog-model.js';
import NativeSalaryBulk from './NativeSalaryBulk.jsx';
import NativeSalaryCopy from './NativeSalaryCopy.jsx';
import NativeSalaryFile from './NativeSalaryFileLoader.jsx';
import Definition,{salaryDefinitionTitle as display} from './NativeSalaryDefinition.jsx';
const API='/api/internal-native-salary',PAGE=20;
export async function salaryRequest(resource='resource=bootstrap',attempt=null){
 const response=await fetch(attempt?API:API+'?'+resource,{credentials:'same-origin',cache:'no-store',signal:AbortSignal.timeout(25000),headers:{Accept:'application/json',...(attempt?{'Content-Type':'application/json','Idempotency-Key':attempt.key}:{})},...(attempt?{method:'POST',body:JSON.stringify({operation:'command',payload:attempt.body})}:{})});
 let data;try{data=await response.json();}catch{throw Object.assign(Error('No se pudo verificar la respuesta. Consultá el mismo intento.'),{status:503});}
 if(!response.ok||data?.ok!==true)throw Object.assign(Error(data?.error||'No se completó la consulta.'),{status:response.status,code:data?.code});return data.data;
}
const blank=()=>({kind:'concept',code:'',agreementCode:'',categoryCode:null,label:'',nature:'',unit:'',precision:'',value:'',validFrom:'',validUntil:'',ruleReference:'',dependencies:[],active:true});
const clone=v=>JSON.parse(JSON.stringify(v));
const natural=new Intl.Collator('es',{numeric:true});
function Differences({before,after}){if(!after.length)return <p>Todavía no hay definiciones en el borrador.</p>;const changes=salaryDiff(before,after);return <div data-sc-comparison><p>{changes.length} cambios en el conjunto completo. La búsqueda y la página no reducen esta revisión.</p>{changes.map(d=><details key={d.key}><summary>{display(d.after)} · {d.before?'Cambio':'Incorporación'}</summary>{d.before&&<><h4>Anterior</h4><Definition row={d.before}/></>}<h4>Propuesto</h4><Definition row={d.after}/></details>)}</div>;}
export default function NativeSalaryCatalog({request=salaryRequest,revoked=false}){
 const[boot,setBoot]=useState(null),[draft,setDraft]=useState(null),[form,setForm]=useState(blank),[editing,setEditing]=useState(null),[selected,setSelected]=useState(null),[confirm,setConfirm]=useState(null),[query,setQuery]=useState(''),[page,setPage]=useState(0),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('Consultá el maestro salarial propio.'),[retry,setRetry]=useState(false),[hasPending,setHasPending]=useState(false);
 const pending=useRef(null),scope=useRef(null),alive=useRef(true),epoch=useRef(0),lock=useRef(false),dialog=useRef(null),draftGeneration=useRef(0);
 function erase(){epoch.current++;scope.current=null;setBoot(null);setDraft(null);setForm(blank());setEditing(null);setSelected(null);setConfirm(null);setReason('');setQuery('');setRetry(false);}
 useEffect(()=>{alive.current=true;const hide=()=>{if(document.hidden){erase();setNotice('Se retiró la consulta al ocultar la página. Volvé a consultar.');}},logout=()=>{erase();setNotice('La sesión terminó. No se muestran datos anteriores.');};document.addEventListener('visibilitychange',hide);window.addEventListener('pagehide',logout);document.getElementById('logoutButton')?.addEventListener('click',logout);return()=>{alive.current=false;epoch.current++;document.removeEventListener('visibilitychange',hide);window.removeEventListener('pagehide',logout);document.getElementById('logoutButton')?.removeEventListener('click',logout);};},[]);
 useEffect(()=>{if(revoked){erase();setNotice('El permiso cambió. Consultá con la cuenta original para recuperar un envío pendiente.');}},[revoked]);
 useEffect(()=>{if(confirm)dialog.current?.showModal();else dialog.current?.close();},[confirm]);
 const live=seq=>alive.current&&seq===epoch.current&&!document.hidden&&!revoked;
 async function run(fn){if(lock.current||revoked)return;lock.current=true;setBusy(true);const seq=epoch.current;try{await fn(seq);}catch(e){if(alive.current&&seq===epoch.current){if([401,403].includes(e.status))erase();setNotice(e.message||'No se confirmó el envío. Consultá el mismo intento.');}}finally{lock.current=false;if(alive.current)setBusy(false);}}
 async function fresh(seq){const b=salaryBootstrap(await request('resource=bootstrap'));if(!live(seq))throw new DOMException('Consulta descartada','AbortError');if(pending.current&&b.scopeVersion!==pending.current.body.scopeVersion||scope.current&&scope.current!==b.scopeVersion){erase();const m='Cambió la cuenta o el ámbito. Volvé a consultar; un envío pendiente sólo puede recuperarse con su cuenta original.';setNotice(m);throw Error(m);}scope.current=b.scopeVersion;setBoot(b);return b;}
 async function refresh(){await run(async seq=>{const b=await fresh(seq);setNotice(draft&&draft.baseVersion!==b.catalog.version?'El maestro vigente cambió. Tu borrador se conserva: compará las versiones antes de preparar otro.':`${b.catalog.items.length} definiciones propias · revisión ${b.catalog.revision}. Ninguna calcula haberes.`);});}
 const rows=draft?.items??boot?.catalog.items??[],filtered=[...rows].sort((a,b)=>natural.compare(a.kind,b.kind)||natural.compare(a.agreementCode,b.agreementCode)||natural.compare(a.categoryCode??'',b.categoryCode??'')||natural.compare(a.code,b.code)||a.validFrom.localeCompare(b.validFrom)).filter(r=>[r.code,r.label,r.agreementCode,r.categoryCode??''].join(' ').toLowerCase().includes(query.toLowerCase())),last=Math.max(0,Math.ceil(filtered.length/PAGE)-1),visible=filtered.slice(Math.min(page,last)*PAGE,(Math.min(page,last)+1)*PAGE),disabled=busy||hasPending||revoked;
 const agreements=boot?.classification.items.filter(r=>r.kind==='agreements')??[],categories=boot?.classification.items.filter(r=>r.kind==='categories'&&r.agreementCode===form.agreementCode)??[];
 const edit=(k,v)=>setForm(old=>({...old,[k]:v}));
 function add(e){e.preventDefault();try{const r={...form,categoryCode:form.kind==='scale'?form.categoryCode:null,nature:form.kind==='scale'?null:form.kind==='auxiliary'?'auxiliary':form.nature,unit:form.kind==='scale'?'money':form.unit,precision:Number(form.precision),value:form.value===''?null:form.value.replace(',','.'),validUntil:form.validUntil||null,dependencies:[...form.dependencies].sort()};const next=rows.filter(x=>salaryRowKey(x)!==editing);next.push(r);const items=salaryItems(next);salaryDiff(draft.baseItems,items);setDraft({...draft,items});setForm(blank());setEditing(null);setNotice('Fila incorporada al borrador completo. Todavía no se guardó.');}catch(e){setNotice(e.message);}}
 function choose(r){setForm({...clone(r),precision:String(r.precision),value:r.value??'',validUntil:r.validUntil??'',nature:r.nature??''});setEditing(salaryRowKey(r));}
 function prepare(){setDraft({localId:++draftGeneration.current,scopeVersion:boot.scopeVersion,baseVersion:boot.catalog.version,classificationVersion:boot.classification.version,baseItems:clone(boot.catalog.items),items:clone(boot.catalog.items)});setForm(blank());setEditing(null);setReason('');setPage(0);setNotice('Prepará la versión completa. Conservá los antecedentes y declaralos desactivados cuando corresponda.');}
 function ask(command,proposal=null){try{if(command==='propose'&&!salaryDiff(draft.baseItems,draft.items).length)throw Error('La propuesta no contiene cambios.');if(reason.trim().length<10)throw Error('Indicá un motivo de al menos diez caracteres.');setConfirm({command,proposal,scopeVersion:boot.scopeVersion,items:clone(command==='propose'?draft.items:proposal.items),baseItems:clone(command==='propose'?draft.baseItems:proposal.baseItems),reason:reason.trim().normalize('NFC')});}catch(e){setNotice(e.message);}}
 async function checkedReceipt(r,a){salaryReceipt(r,a);const bytes=new TextEncoder().encode(salarySerialized(r.body)),hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),b=>b.toString(16).padStart(2,'0')).join('');if(hash!==r.requestSha256)throw Error('No se pudo verificar el contenido confirmado. Conservamos el intento original.');}
 async function send(a,seq){pending.current=a;setHasPending(true);setRetry(false);setConfirm(null);const r=await request('',a);await checkedReceipt(r,a);if(!live(seq))return;pending.current=null;setHasPending(false);setDraft(null);setForm(blank());setSelected(null);setReason('');await fresh(seq);setNotice(r.status==='approved'?'Versión aprobada en el maestro propio. No se recalcularon haberes.':r.status==='rejected'?'Propuesta rechazada; la versión vigente se conserva.':'Propuesta completa guardada para revisión independiente.');}
 async function commit(){await run(async seq=>{const c=confirm,b=await fresh(seq);if(!c||!live(seq))return;if(c.scopeVersion!==b.scopeVersion||draft&&draft.scopeVersion!==b.scopeVersion){erase();throw Error('Cambió la cuenta o el ámbito. Volvé a preparar con la sesión actual.');}let body;
  if(c.command==='propose'){if(!b.permissions.canPropose||b.catalog.version!==draft.baseVersion||b.classification.version!==draft.classificationVersion)throw Error('Cambió el catálogo o el permiso. El borrador se conserva para una revisión nueva.');body={command:'propose',scopeVersion:b.scopeVersion,baseVersion:draft.baseVersion,classificationVersion:draft.classificationVersion,proposalId:null,proposalSha256:null,items:c.items,reason:c.reason,reviewConfirmed:false};}
  else{const p=b.proposals.find(p=>p.id===c.proposal.id);if(!p?.canReview||p.status!=='pending'||salarySerialized(p)!==salarySerialized(c.proposal))throw Error('Cambió la propuesta o el permiso. Volvé a revisar su comparación completa.');body={command:c.command,scopeVersion:b.scopeVersion,baseVersion:p.baseVersion,classificationVersion:p.classificationVersion,proposalId:p.id,proposalSha256:p.requestSha256,items:null,reason:c.reason,reviewConfirmed:true};}
  await send({key:crypto.randomUUID(),body:salaryCommand(body)},seq);
 });}
 async function recover(){await run(async seq=>{const a=pending.current;if(!a)return;await fresh(seq);try{const r=await request('resource=attempt&key='+encodeURIComponent(a.key));await checkedReceipt(r,a);if(!live(seq))return;pending.current=null;setHasPending(false);setDraft(null);setSelected(null);await fresh(seq);setNotice('Se recuperó la confirmación del mismo envío.');}catch(e){if(e.status===404&&live(seq)){setRetry(true);setNotice('El intento todavía no tiene confirmación. Podés consultar otra vez o reenviar exactamente el mismo contenido.');}else throw e;}});}
 return <section className="sc-workspace" data-native-salary aria-label="Maestro salarial propio"><style>{css}</style><p className="sc-note">MÓDULO 6 · DEFINICIONES Y ESCALAS MUNICIPALES</p><h2>Maestro salarial propio</h2><p>Registrá conceptos y valores de escala con su unidad, precisión, vigencia y respaldo. Otra persona revisa la versión completa antes de incorporarla.</p><p className="sc-note">Este registro no ejecuta fórmulas, calcula salarios ni modifica los auxiliares vigentes del circuito anterior.</p><p role="status" aria-live="polite" className="sc-status">{notice}</p>
 <div className="sc-actions"><button disabled={busy||revoked} onClick={refresh}>Consultar maestro propio</button>{boot?.permissions.canPropose&&!draft&&!hasPending&&<button className="sc-primary" disabled={disabled} onClick={prepare}>Preparar nueva versión</button>}</div>
 {hasPending&&boot&&<section><h3>Envío pendiente de confirmación</h3><p>El contenido y su referencia se conservan en esta pantalla. Primero consultá su resultado.</p><div className="sc-actions"><button disabled={busy} onClick={recover}>Consultar confirmación</button><button disabled={busy||!retry} onClick={()=>run(async seq=>{await fresh(seq);await send(pending.current,seq);})}>Reenviar mismo envío</button></div></section>}
 {boot&&<><p>{boot.catalog.items.length} definiciones registradas · revisión {boot.catalog.revision} · {boot.proposals.length} propuestas en la historia completa.</p><label>Buscar código, convenio, clase o descripción<input type="search" value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}} disabled={busy} maxLength={160}/></label><ul className="sc-list">{visible.map(r=><li key={salaryRowKey(r)}><details><summary>{display(r)} · {r.label}</summary><Definition row={r}/></details>{draft&&<button disabled={disabled} onClick={()=>choose(r)}>Editar definición</button>}</li>)}</ul>{!filtered.length&&<p>No hay definiciones en esta consulta. No se muestran ejemplos como si fueran vigentes.</p>}<div className="sc-actions"><button disabled={busy||page===0} onClick={()=>setPage(page-1)}>Anterior</button><span>{filtered.length} filas del filtro · página {Math.min(page,last)+1}</span><button disabled={busy||page>=last} onClick={()=>setPage(page+1)}>Siguiente</button></div>
 {draft&&<><NativeSalaryFile key={'file:'+draft.localId} items={draft.items} classification={boot.classification.items} disabled={disabled||editing!==null||draft.baseVersion!==boot.catalog.version||draft.classificationVersion!==boot.classification.version} individualEditing={editing!==null} onNotice={setNotice} onApply={items=>setDraft({...draft,items})}/><NativeSalaryBulk key={draft.localId} items={draft.items} disabled={disabled||editing!==null||draft.baseVersion!==boot.catalog.version||draft.classificationVersion!==boot.classification.version} individualEditing={editing!==null} onNotice={setNotice} onApply={items=>setDraft({...draft,items})}/><NativeSalaryCopy key={'copy:'+draft.localId} items={draft.items} classification={boot.classification.items} disabled={disabled||editing!==null||draft.baseVersion!==boot.catalog.version||draft.classificationVersion!==boot.classification.version} individualEditing={editing!==null} onNotice={setNotice} onApply={items=>setDraft({...draft,items})}/><h3>{editing?'Editar definición del borrador':'Agregar definición al borrador'}</h3><form onSubmit={add}><fieldset disabled={disabled}><div className="sc-form">
 <label>Tipo<select aria-label="Tipo" value={form.kind} disabled={!!editing} onChange={e=>setForm({...blank(),kind:e.target.value,nature:e.target.value==='auxiliary'?'auxiliary':''})}><option value="concept">Concepto</option><option value="auxiliary">Auxiliar de cálculo</option><option value="scale">Valor de escala</option></select><small>Concepto y auxiliar pueden tener el mismo código. Se conservan como definiciones distintas.</small></label>
 <label>Código<input required value={form.code} readOnly={!!editing} maxLength={9} inputMode="numeric" onChange={e=>edit('code',e.target.value)}/></label>
 <label>Convenio<select aria-label="Convenio" required value={form.agreementCode} disabled={!!editing} onChange={e=>setForm({...form,agreementCode:e.target.value,categoryCode:null,dependencies:[]})}><option value="">Elegí convenio</option>{agreements.map(a=><option key={a.code} value={a.code}>{a.code} · {a.label}</option>)}</select></label>
 {form.kind==='scale'?<label>Clase<select aria-label="Clase" required value={form.categoryCode??''} disabled={!!editing} onChange={e=>edit('categoryCode',e.target.value)}><option value="">Elegí clase</option>{categories.map(c=><option key={c.code} value={c.code}>{c.code} · {c.label}</option>)}</select></label>:form.kind==='auxiliary'?<p>Auxiliar de cálculo: su valor no integra el haber.</p>:<label>Naturaleza<select aria-label="Naturaleza" required value={form.nature} onChange={e=>edit('nature',e.target.value)}><option value="">Elegí naturaleza</option>{Object.entries(SALARY_NATURES).filter(([k])=>k!=='auxiliary'||form.nature==='auxiliary').map(([k,v])=><option key={k} value={k}>{k==='auxiliary'?'Auxiliar histórico registrado como concepto':v}</option>)}</select></label>}
 <label>Descripción<input required value={form.label} maxLength={160} onChange={e=>edit('label',e.target.value)}/></label>
 <label>Unidad<select required value={form.kind==='scale'?'money':form.unit} disabled={form.kind==='scale'} onChange={e=>edit('unit',e.target.value)}><option value="">Elegí unidad</option>{Object.entries(SALARY_UNITS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>
 <label>Decimales declarados<select required value={form.precision} onChange={e=>edit('precision',e.target.value)}><option value="">Elegí precisión</option>{Array.from({length:9},(_,n)=><option key={n} value={n}>{n}</option>)}</select></label>
 <label>Valor declarado<input aria-label="Valor declarado" aria-describedby="sc-value-help" value={form.value} required={form.kind==='scale'} inputMode="decimal" maxLength={28} onChange={e=>edit('value',e.target.value)}/><small id="sc-value-help">Sin separador de miles. Vacío: no informado. Cero: declaralo con la precisión elegida.</small></label>
 <label>Desde mes<input type="month" required value={form.validFrom} readOnly={!!editing} onChange={e=>edit('validFrom',e.target.value)}/></label><label>Hasta mes, inclusive<input type="month" value={form.validUntil} onChange={e=>edit('validUntil',e.target.value)}/></label>
 <label>Estado<select value={String(form.active)} onChange={e=>edit('active',e.target.value==='true')}><option value="true">Habilitada</option><option value="false">Desactivada, conserva antecedente</option></select></label><label>Documento de respaldo<input required minLength={3} maxLength={180} value={form.ruleReference} onChange={e=>edit('ruleReference',e.target.value)}/></label></div>
 {form.kind!=='scale'&&<label>Dependencias declaradas del mismo convenio<select multiple size={4} value={form.dependencies} onChange={e=>edit('dependencies',Array.from(e.target.selectedOptions,o=>o.value))}>{rows.filter(r=>r.agreementCode===form.agreementCode&&salaryRowKey(r)!==editing).map(r=><option key={salaryRowKey(r)} value={salaryRowKey(r)}>{display(r)} · {r.label}</option>)}</select><small>Se registran referencias; no se ejecutan cálculos.</small></label>}
 <div className="sc-actions"><button type="submit" className="sc-primary">Incorporar fila al borrador</button><button type="button" onClick={()=>{setForm(blank());setEditing(null);}}>Limpiar fila</button></div></fieldset></form><Differences before={draft.baseItems} after={draft.items}/><label>Motivo de la versión<textarea value={reason} onChange={e=>setReason(e.target.value)} disabled={disabled} maxLength={1000}/></label><div className="sc-actions"><button disabled={disabled||!draft.items.length} className="sc-primary" onClick={()=>ask('propose')}>Revisar versión completa</button><button disabled={disabled} onClick={prepare}>Empezar desde versión consultada</button></div></>}
 <h3>Historia y revisión independiente</h3><ul className="sc-list">{boot.proposals.map(p=><li key={p.id}><button disabled={disabled} onClick={()=>{setSelected(p);setReason('');}}>{p.status==='pending'?'Pendiente':p.status==='approved'?'Aprobada':'Rechazada'} · {p.authorLabel} · {p.items.length} definiciones</button></li>)}</ul>
 {selected&&<section><h3>Comparación de la propuesta</h3><p>{selected.reason}</p><Differences before={selected.baseItems} after={selected.items}/><details><summary>Ver todas las definiciones propuestas</summary>{selected.items.map(r=><div key={salaryRowKey(r)}><h4>{display(r)}</h4><Definition row={r}/></div>)}</details>{selected.decision&&<p>Decisión: {selected.decision.command} · {selected.decision.reason} · {selected.decision.actorLabel}</p>}{selected.canReview&&<><label>Motivo de la decisión<textarea value={reason} onChange={e=>setReason(e.target.value)} disabled={disabled} maxLength={1000}/></label><div className="sc-actions"><button disabled={disabled} className="sc-primary" onClick={()=>ask('approve',selected)}>Revisar aprobación</button><button disabled={disabled} onClick={()=>ask('reject',selected)}>Revisar rechazo</button></div></>}</section>}</>}
 <dialog ref={dialog} aria-labelledby="sc-confirm-title" onCancel={()=>setConfirm(null)}><h3 id="sc-confirm-title">{confirm?.command==='propose'?'Enviar versión a revisión':confirm?.command==='approve'?'Aprobar versión del maestro':'Rechazar propuesta'}</h3>{confirm&&<><p>{confirm.reason}</p><Differences before={confirm.baseItems} after={confirm.items}/><p>Se revisa el conjunto completo. La decisión no liquida haberes.</p></>}<div className="sc-actions"><button disabled={busy} onClick={()=>setConfirm(null)}>Volver sin guardar</button><button disabled={busy} className="sc-primary" onClick={commit}>Confirmar {confirm?.command==='propose'?'envío':confirm?.command==='approve'?'aprobación':'rechazo'}</button></div></dialog></section>;
}
const css=`.sc-workspace{margin:0 0 28px;padding:24px;border:1px solid #c9deda;border-top:4px solid #007d75;border-radius:12px;background:#fff;color:#183e4b}.sc-workspace *{box-sizing:border-box}.sc-workspace h2{margin:8px 0 14px}.sc-workspace label{display:flex;flex-direction:column;gap:7px;font-weight:600}.sc-workspace input,.sc-workspace select,.sc-workspace textarea,.sc-workspace button{font:inherit;min-height:44px;border:1px solid #afc7cc;border-radius:7px;padding:9px;max-width:100%}.sc-workspace button{cursor:pointer;background:#fff;color:#154854}.sc-workspace button:disabled{opacity:.5;cursor:not-allowed}.sc-workspace .sc-primary{background:#007d75;color:#fff}.sc-workspace :focus-visible{outline:3px solid #a5660d;outline-offset:3px}.sc-actions{display:flex;gap:10px;flex-wrap:wrap;margin:16px 0}.sc-form{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px;padding:18px 0}.sc-values{display:grid;grid-template-columns:150px minmax(0,1fr);gap:8px}.sc-values dd{margin:0;overflow-wrap:anywhere}.sc-workspace details{padding:12px;border-bottom:1px solid #dce9e5}.sc-workspace summary{cursor:pointer;font-weight:600;overflow-wrap:anywhere}.sc-status{padding:12px;background:#eef7f4;border-left:4px solid #007d75}.sc-workspace dialog{max-width:760px;width:calc(100% - 24px);max-height:90dvh;overflow:auto;border:1px solid #afc7cc;border-radius:12px;color:inherit;padding:22px}.sc-workspace dialog::backdrop{background:#173849aa}.sc-workspace fieldset{border:0;padding:0;margin:0;min-width:0}.sc-workspace textarea{width:100%}.sc-list{list-style:none;padding:0}.sc-list li{padding:12px 0;border-bottom:1px solid #dce9e5;overflow-wrap:anywhere}.sc-note{color:#4d6973;font-size:.9em}@media(max-width:700px){.sc-workspace{padding:16px}.sc-form{grid-template-columns:1fr}.sc-values{grid-template-columns:1fr}.sc-values dd{margin-bottom:8px}.sc-actions button{flex:1 1 150px}}`;
