import {useId,useState} from 'react';
import {SALARY_UNITS,salaryRowKey,salarySerialized} from '../../assets/native-salary-catalog-model.js';
import {salaryBulkPlan} from '../../assets/native-salary-bulk-model.js';
import {salaryEffectivePlan} from '../../assets/native-salary-effective-model.js';
import {salaryDefinitionTitle as label} from './NativeSalaryDefinition.jsx';

const PAGE=20,clone=value=>JSON.parse(JSON.stringify(value));
const exactValue=value=>value===null?'No informado':value;
const natural=new Intl.Collator('es',{numeric:true});

export default function NativeSalaryBulk({items,disabled,individualEditing=false,onApply,onNotice}){
 const valueHelp=useId();
 const [selection,setSelection]=useState([]),[query,setQuery]=useState(''),[kind,setKind]=useState('all'),[unit,setUnit]=useState(''),[precision,setPrecision]=useState(''),[page,setPage]=useState(0),[valueState,setValueState]=useState('declared'),[value,setValue]=useState(''),[reference,setReference]=useState(''),[review,setReview]=useState(null),[operation,setOperation]=useState('current'),[startMonth,setStartMonth]=useState('');
 const filtered=items.filter(row=>row.active&&(kind==='all'||row.kind===kind)&&(!unit||row.unit===unit)&&(precision===''||row.precision===Number(precision))&&(operation!=='effective'||!startMonth||row.validFrom<startMonth&&(row.validUntil===null||row.validUntil>=startMonth))&&[row.code,row.agreementCode,row.categoryCode??'',row.label,row.validFrom,row.validUntil??''].join(' ').toLowerCase().includes(query.toLowerCase())).sort((a,b)=>natural.compare(a.code,b.code)||natural.compare(a.agreementCode,b.agreementCode)||salaryRowKey(a).localeCompare(salaryRowKey(b)));
 const last=Math.max(0,Math.ceil(filtered.length/PAGE)-1),currentPage=Math.min(page,last),visible=filtered.slice(currentPage*PAGE,(currentPage+1)*PAGE),selectedKeys=new Set(selection.map(row=>row.key));
 const change=()=>({unit,precision:precision===''?null:Number(precision),value:valueState==='unknown'?null:value.replace(',','.'),ruleReference:reference.trim().normalize('NFC')});
 const plan=()=>operation==='effective'?salaryEffectivePlan(items,selection,change(),startMonth):salaryBulkPlan(items,selection,change());
 const edit=(setter,next,filter=false)=>{if(disabled)return;setter(next);setReview(null);if(filter)setPage(0);};
 function select(rows,checked=true){if(disabled)return;setReview(null);setSelection(previous=>{const next=new Map(previous.map(row=>[row.key,row]));for(const row of rows){const key=salaryRowKey(row);if(checked)next.set(key,{key,before:clone(row)});else next.delete(key);}return [...next.values()];});}
 function preview(){if(disabled)return;try{const next=plan();setReview(next);onNotice(next.newDefinitionsCount?`${next.selectedCount} seleccionadas y ${next.relatedDefinitionsCount} dependientes: ${next.newDefinitionsCount} cierres y ${next.newDefinitionsCount} nuevas vigencias para revisar. Todavía no se incorporaron al borrador.`:`${next.selectedCount} filas seleccionadas: ${next.changes.length} cambios para revisar, ${next.unchangedSelectedCount} sin cambio. Todavía no se incorporaron al borrador.`);}catch(error){setReview(null);onNotice(error.message);}}
 function apply(){if(disabled||!review)return;try{const current=plan();if(salarySerialized(current)!==salarySerialized(review))throw Error('Cambió el conjunto revisado. Volvé a revisar la selección completa.');onApply(current.items);setSelection([]);setReview(null);setValue('');setReference('');onNotice(`${current.changes.length} cambios incorporados al borrador completo. Revisá la versión y enviala para revisión independiente.`);}catch(error){setReview(null);onNotice(error.message);}}
 return <details className="sc-bulk" data-salary-bulk><style>{css}</style><summary>Actualizar valores en varios convenios</summary><h3>Seleccionar, comparar e incorporar</h3><p>Elegí definiciones existentes y declarales un mismo valor y respaldo. Se conservan su unidad, precisión, vigencia y dependencias. Los filtros sólo ayudan a seleccionar; no recortan el borrador ni la revisión.</p>{individualEditing&&<p>Terminá la edición individual o usá Limpiar fila antes de actualizar varios valores. Sus datos se conservan.</p>}
 <fieldset disabled={disabled}><div className="sc-form">
  <label>Cómo aplicar la actualización<select aria-label="Cómo aplicar la actualización" value={operation} onChange={event=>edit(setOperation,event.target.value,true)}><option value="current">Corregir la vigencia seleccionada</option><option value="effective">Iniciar vigencia desde otro mes</option></select></label>
  {operation==='effective'&&<label>Mes inicial de la nueva vigencia<input type="month" min="1900-01" max="2099-12" value={startMonth} onChange={event=>edit(setStartMonth,event.target.value,true)}/></label>}
  <label>Buscar para selección múltiple<input type="search" maxLength={160} value={query} onChange={event=>edit(setQuery,event.target.value,true)}/></label>
  <label>Tipo de definición<select aria-label="Tipo de definición" value={kind} onChange={event=>edit(setKind,event.target.value,true)}><option value="all">Conceptos, auxiliares y escalas</option><option value="auxiliary">Auxiliares</option><option value="concept">Conceptos</option><option value="scale">Escalas</option></select></label>
  <label>Unidad de las filas<select aria-label="Unidad de las filas" value={unit} onChange={event=>edit(setUnit,event.target.value,true)}><option value="">Elegí unidad; se filtra la lista</option>{Object.entries(SALARY_UNITS).map(([key,text])=><option key={key} value={key}>{text}</option>)}</select></label>
  <label>Precisión de las filas<select aria-label="Precisión de las filas" value={precision} onChange={event=>edit(setPrecision,event.target.value,true)}><option value="">Elegí precisión; se filtra la lista</option>{Array.from({length:9},(_,number)=><option key={number} value={number}>{number} decimales</option>)}</select></label>
  <label>Cómo informar el valor<select aria-label="Cómo informar el valor" value={valueState} onChange={event=>edit(setValueState,event.target.value)}><option value="declared">Declarar valor exacto</option><option value="unknown">Dejar como no informado</option></select></label>
  <label>Nuevo valor para la selección<input aria-label="Nuevo valor para la selección" aria-describedby={valueHelp} inputMode="decimal" maxLength={28} value={value} disabled={valueState==='unknown'} onChange={event=>edit(setValue,event.target.value)}/><small id={valueHelp}>Sin separador de miles, con los decimales declarados. Cero y no informado son distintos.</small></label>
  <label>Respaldo de la actualización<input maxLength={180} value={reference} onChange={event=>edit(setReference,event.target.value)}/></label>
 </div>{operation==='effective'&&<p>La vigencia anterior se cerrará al mes previo, conservando su valor y respaldo. Se crearán las nuevas definiciones y se versionarán sus dependientes con los mismos valores y unidades; todas se mostrarán para revisión. Las fechas finales ya declaradas se conservan. No se ejecutan fórmulas.</p>}
 <p>{selection.length} seleccionadas en todas las páginas · {filtered.length} resultados completos del filtro · página {currentPage+1} de {last+1}.</p>
 <div className="sc-actions"><button type="button" disabled={!filtered.length} onClick={()=>select(filtered)}>Seleccionar los {filtered.length} resultados completos</button><button type="button" disabled={!selection.length} onClick={()=>{setSelection([]);setReview(null);}}>Quitar toda la selección</button></div>
 <ul className="sc-bulk-list">{visible.map(row=><li key={salaryRowKey(row)}><label className="sc-check"><input type="checkbox" checked={selectedKeys.has(salaryRowKey(row))} onChange={event=>select([row],event.target.checked)}/><span>{label(row)}<small>{row.label} · {SALARY_UNITS[row.unit]} · {row.precision} decimales · valor {exactValue(row.value)} · hasta {row.validUntil??'sin fin informado'}</small></span></label></li>)}</ul>
 {!filtered.length&&<p>No hay filas habilitadas para este filtro. La selección anterior se conserva.</p>}
 <div className="sc-actions"><button type="button" disabled={currentPage===0} onClick={()=>setPage(currentPage-1)}>Página anterior de selección</button><button type="button" disabled={currentPage>=last} onClick={()=>setPage(currentPage+1)}>Página siguiente de selección</button><button type="button" className="sc-primary" disabled={!selection.length} onClick={preview}>Comparar actualización completa</button></div>
 {review&&<section data-salary-bulk-impact aria-label="Impacto de la actualización"><h4>{review.changes.length} cambios en toda la selección</h4>{review.newDefinitionsCount?<><p data-salary-effective-impact>{review.selectedCount} definiciones seleccionadas y {review.relatedDefinitionsCount} dependientes con valores conservados. Se cierran {review.newDefinitionsCount} vigencias al {review.previousUntil} y se inician {review.newDefinitionsCount} desde {review.validFrom}. El borrador completo tendrá {review.items.length} definiciones.</p>{review.relinkedFutureDefinitionsCount>0&&<p>{review.relinkedFutureDefinitionsCount} definiciones ya previstas para ese mes o uno posterior actualizarán sólo sus referencias. Conservan fechas, valores, unidades y respaldo; se incluyen en la comparación.</p>}</>:<p>{review.unchangedSelectedCount} seleccionadas conservarán los mismos datos. Se mostrarán también en el borrador completo.</p>}{review.changes.map(change=><details key={change.key}><summary>{label(change.after)} · {change.before?(review.newDefinitionsCount?(change.before.validUntil!==change.after.validUntil?'Cierre de vigencia':'Referencia de vigencia prevista'):'Cambio'):'Nueva vigencia'}</summary><dl className="sc-values"><dt>Valor anterior de esta vigencia</dt><dd>{change.before?exactValue(change.before.value):'No existía una definición con este inicio'}</dd><dt>Valor propuesto</dt><dd>{exactValue(change.after.value)}</dd><dt>Respaldo anterior</dt><dd>{change.before?.ruleReference??'Nueva vigencia'}</dd><dt>Respaldo propuesto</dt><dd>{change.after.ruleReference}</dd><dt>Unidad / precisión</dt><dd>{SALARY_UNITS[change.after.unit]} · {change.after.precision} decimales</dd>{change.before&&<><dt>Vigencia anterior</dt><dd>{change.before.validFrom} a {change.before.validUntil??'sin fin informado'}</dd></>}<dt>Vigencia propuesta</dt><dd>{change.after.validFrom} a {change.after.validUntil??'sin fin informado'}</dd><dt>Dependencias propuestas</dt><dd>{change.after.dependencies.length?change.after.dependencies.join(' · '):'Sin dependencias declaradas'}</dd></dl></details>)}<div className="sc-actions"><button type="button" className="sc-primary" onClick={apply}>Incorporar cambios revisados al borrador</button><button type="button" onClick={()=>setReview(null)}>Volver a la selección</button></div></section>}
 </fieldset></details>;
}
const css=`.sc-bulk{margin:20px 0;border:1px solid #c9deda;border-radius:9px;background:#f7fbf9}.sc-workspace .sc-bulk-list{list-style:none;padding:0;margin:0}.sc-workspace .sc-bulk-list li{border-bottom:1px solid #dce9e5;padding:8px 0}.sc-workspace .sc-check{flex-direction:row;align-items:center;gap:12px;min-height:44px;cursor:pointer}.sc-workspace .sc-check input[type=checkbox]{flex:0 0 20px;width:20px;min-height:20px;height:20px;accent-color:#007d75;padding:0}.sc-workspace .sc-check span{min-width:0;overflow-wrap:anywhere}.sc-bulk small{display:block;font-weight:400}.sc-bulk p{overflow-wrap:anywhere}`;
