// SPDX-License-Identifier: GPL-2.0-only
import test from 'node:test';import assert from 'node:assert/strict';
import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
import {randomBytes,createHash} from 'node:crypto';
import {Store,Collector,config,seal,unseal,readCommKey} from '../core.mjs';
import {lock,runLoop} from '../cli.mjs';
import {collect,SERIAL} from '../vendor/lector-fichadas.mjs';
import {withClock,fakeKey,dataSet} from '../vendor/tests/fixture.mjs';
const defaults=JSON.parse(await fs.readFile(new URL('../config.example.json',import.meta.url),'utf8'));
function fixture(n=2){const raw=dataSet(n);return {raw,parsed:{status:n?'DECODED_CANDIDATE':'DECODED_EMPTY',layout:n?'legacy-40-byte-candidate':null,recordCount:n,invalidTimestampCount:0,nonDniOrUidCount:0,records:[]},report:{status:'ATTENDANCE_DOWNLOADED_FOR_REVIEW',authenticationAccepted:true,startedAt:'2026-09-12T09:00:00.000Z',finishedAt:'2026-09-12T09:00:01.000Z',metadata:{serialNumber:SERIAL,countsBefore:{counts:{attendanceRecordsReported:n}},countsAfter:{counts:{attendanceRecordsReported:n}}},cleanup:{bufferReleaseConfirmed:true,exitConfirmed:true},attendanceTransferComplete:true,transfer:{rawSha256:createHash('sha256').update(raw).digest('hex')}}}}
async function context(fn,overrides={}){const root=await fs.mkdtemp(path.join(os.tmpdir(),'mc59-'));const key=randomBytes(32);try{await fs.mkdir(path.join(root,'secrets'),{mode:0o700});await fs.writeFile(path.join(root,'secrets','commkey.enc'),seal(fakeKey(),key,'credential'),{mode:0o600});const store=new Store(root,key,{...defaults,enabled:true,...overrides});await store.open();await fn(store,root,key)}finally{key.fill(0);await fs.rm(root,{recursive:true,force:true})}}
const reader=async()=>fixture();
const worker=(store,fn=reader)=>new Collector(store,{reader:fn,credential:fakeKey,now:()=>new Date('2026-09-12T09:00:02Z')});
test('shipping configuration disables reads',()=>assert.equal(config(defaults).enabled,false));
for(const extra of [{host:'192.0.2.1'},{port:23},{serial:'other'},{site:'pm-11'},{endpoint:'https://example.invalid'},{intervalSeconds:1},{maxCaptures:1},{reserveFreeBytes:0},{storageMaxBytes:Infinity}])test('config refuses unverified target/limit '+Object.keys(extra),()=>assert.throws(()=>config({...defaults,...extra})));
test('GCM round-trip, randomized nonce and associated context',()=>{const key=randomBytes(32),b=Buffer.from('private test');const a=seal(b,key,'state'),c=seal(b,key,'state');assert.notDeepEqual(a,c);assert.deepEqual(unseal(a,key,'state'),b);assert.throws(()=>unseal(a,key,'credential'));a[a.length-1]^=1;assert.throws(()=>unseal(a,key,'state'))});
test('wrong encryption key cannot read previous content',()=>assert.throws(()=>unseal(seal(Buffer.from('test'),randomBytes(32),'state'),randomBytes(32),'state')));
test('disabled configuration performs no authentication',()=>context(async store=>{let called=0;const out=await worker(store,async()=>{called++}).tick();assert.equal(out.outcome,'DISABLED');assert.equal(called,0)}, {enabled:false}));
test('successful complete capture is encrypted; no plaintext DNI on disk',()=>context(async(store,root)=>{const out=await worker(store).tick();assert.equal(out.outcome,'CAPTURE_SAVED');const files=await fs.readdir(store.captures);assert.equal(files.length,1);const bytes=await fs.readFile(path.join(store.captures,files[0]));assert.equal(bytes.includes(Buffer.from('99000001')),false);const restored=await store.readCapture(files[0]);assert.deepEqual(restored.raw,dataSet(2));assert.equal(restored.meta.cloudAccepted,false);const state=await store.state();assert.equal(state.lastCount,2);const status=await store.status(new Date('2026-09-12T09:00:10Z'));assert.equal(status.localState,'RECENT_LOCAL_READ');assert.equal(status.automaticCloudCollectorVerified,false);assert.equal(status.cloudTransmission,'NOT_IMPLEMENTED');assert.equal(JSON.stringify(status).includes('99000001'),false)}));
test('repeat poll and process restart do not create duplicate capture',()=>context(async(store,root,key)=>{await worker(store).tick();const next=new Store(root,key,store.settings);await next.open();const out=await worker(next).tick();assert.equal(out.outcome,'UNCHANGED');assert.equal((await fs.readdir(next.captures)).length,1)}));
test('changed buffer creates new durable capture',()=>context(async store=>{await worker(store).tick();await worker(store,async()=>fixture(3)).tick();assert.equal((await fs.readdir(store.captures)).length,2);assert.equal((await store.state()).lastCount,3)}));
test('crash between first file and state recovers without reimport or loss',()=>context(async store=>{await store.capture(fixture());const restored=await store.state();assert.equal(restored.lastCount,2);assert.equal(restored.lastOutcome,'RECOVERED_LOCAL_CAPTURE');assert.equal((await worker(store).tick()).outcome,'UNCHANGED');assert.equal((await fs.readdir(store.captures)).length,1)}));
test('missing state after multiple captures stops instead of guessing checkpoint',()=>context(async store=>{await store.capture(fixture());await store.capture(fixture(3));await assert.rejects(store.state(),{code:'STATE_INVALID'})}));
test('authentication rejection blocks persistently; no password guessing',()=>context(async(store,root,key)=>{let calls=0;await worker(store,async()=>{calls++;return {report:{status:'AUTH_NOT_ACCEPTED'}}}).tick();assert.equal((await store.state()).blocked,'AUTH_NOT_ACCEPTED');const restarted=new Store(root,key,store.settings);await restarted.open();const second=await worker(restarted,async()=>{calls++;return fixture()}).tick();assert.equal(second.outcome,'BLOCKED');assert.equal(calls,1);assert.equal((await fs.readdir(store.captures)).length,0)}));
for(const code of ['SERIAL_MISMATCH','CHECKSUM_MISMATCH','SESSION_MISMATCH','LAYOUT_NOT_VERIFIED'])test('protocol failure blocks and never saves partial '+code,()=>context(async store=>{await worker(store,async()=>({report:{error:{code}}})).tick();assert.equal((await store.state()).blocked,'PROTOCOL_REVIEW');assert.equal((await fs.readdir(store.captures)).length,0)}));
test('counter decrease is preserved but blocks further reads for review',()=>context(async store=>{await worker(store,async()=>fixture(3)).tick();assert.equal((await worker(store).tick()).outcome,'BLOCKED');assert.equal((await store.state()).blocked,'COUNTER_DECREASE');assert.equal((await fs.readdir(store.captures)).length,2)}));
test('capacity full pauses before requesting clock and deletes no evidence',()=>context(async store=>{await worker(store).tick();await worker(store,async()=>fixture(3)).tick();let call=false;const out=await worker(store,async()=>{call=true;return fixture(4)}).tick();assert.equal(out.outcome,'BLOCKED');assert.equal(call,false);assert.equal((await fs.readdir(store.captures)).length,2)}, {maxCaptures:2}));
test('network retries are serialized and exponentially bounded',()=>context(async store=>{const c=worker(store,async()=>{throw Object.assign(new Error('secret details never logged'),{code:'ECONNREFUSED'})});const waits=[];for(let i=0;i<6;i++)waits.push((await c.tick()).waitSeconds);assert.deepEqual(waits,[120,240,480,900,900,900]);assert.equal((await store.state()).blocked,null)}));
test('unsupported 8-byte layout is not treated as DNI records',()=>context(async store=>{const f=fixture();f.parsed.layout='legacy-8-byte-candidate';await worker(store,async()=>f).tick();assert.equal((await store.state()).blocked,'PROTOCOL_REVIEW')}));
test('unconfirmed transfer cleanup is not a valid successful snapshot',()=>context(async store=>{const f=fixture();f.report.cleanup.exitConfirmed=false;await worker(store,async()=>f).tick();assert.equal((await fs.readdir(store.captures)).length,0)}));
test('binary tampering is rejected before archival',()=>context(async store=>{const f=fixture();f.raw[10]^=1;await worker(store,async()=>f).tick();assert.equal((await store.state()).blocked,'PROTOCOL_REVIEW')}));
test('unknown timestamps and identity formats remain in original encrypted bytes',()=>context(async store=>{const f=fixture();f.parsed.invalidTimestampCount=1;f.parsed.nonDniOrUidCount=1;await worker(store,async()=>f).tick();const saved=await store.readCapture((await fs.readdir(store.captures))[0]);assert.equal(saved.meta.invalidTimestamps,1);assert.equal(saved.meta.unresolvedIdentityFormats,1);assert.equal(saved.meta.records,2)}));
test('empty device is preserved without being a monthly coverage claim',()=>context(async store=>{await worker(store,async()=>fixture(0)).tick();assert.equal((await store.state()).lastCount,0);const saved=await store.readCapture((await fs.readdir(store.captures))[0]);assert.equal(saved.meta.periodCoverageCertified,false)}));
test('pre-cancelled cycle makes no connection',()=>context(async store=>{const ac=new AbortController();ac.abort();let called=false;const r=await worker(store,async()=>{called=true}).tick(ac.signal);assert.equal(r.outcome,'STOPPED');assert.equal(called,false)}));
test('same process cannot start overlapping cycles',()=>context(async store=>{let finish;const c=worker(store,async()=>new Promise(r=>{finish=r}));const p=c.tick();while(!finish)await new Promise(r=>setTimeout(r,2));await assert.rejects(c.tick(),{code:'CONCURRENT_CYCLE'});finish(fixture());await p}));
test('OS loopback lock prevents two resident processes; release permits restart',async()=>{const release=await lock();try{await assert.rejects(lock(),{code:'SINGLE_INSTANCE_REQUIRED'})}finally{await release()}const again=await lock();await again()});
test('loop stops on persistent block without restart loop',async()=>{let n=0;const r=await runLoop({tick:async()=>{n++;return {outcome:'BLOCKED',waitSeconds:0}}},{sleep:()=>assert.fail('must not sleep')});assert.equal(r.outcome,'BLOCKED');assert.equal(n,1)});
test('termination interrupts wait instead of waiting a polling interval',async()=>{const ac=new AbortController();const r=await runLoop({tick:async()=>({outcome:'UNCHANGED',waitSeconds:60})},{signal:ac.signal,onCycle:()=>ac.abort()});assert.equal(r.outcome,'STOPPED')});
test('unencrypted credential is not required after initialization',()=>context(async(store,root,key)=>{const p=await readCommKey(root,key);assert.equal(p.toString(),'876543');p.fill(0);assert.equal((await fs.readFile(path.join(root,'secrets','commkey.enc'))).includes(Buffer.from('876543')),false)}));
test('corrupted state never silently resets the baseline',()=>context(async store=>{await worker(store).tick();const f=path.join(store.dir,'state.enc');const b=await fs.readFile(f);b[b.length-1]^=1;await fs.writeFile(f,b);await assert.rejects(store.state(),{code:'KEY_MISMATCH'})}));
test('capture identifiers disallow path traversal',()=>context(async store=>await assert.rejects(store.readCapture('../config.json'),{code:'CAPTURE_IDENTIFIER_INVALID'})));
test('real reader over loopback, full packet transfer and durable encrypted capture',()=>context(async store=>withClock({count:5,fragment:true},async(port,commands)=>{
 const c=worker(store,options=>collect({...options,host:'127.0.0.1',port,pacingMs:0,timeoutMs:1000,totalMs:10000}));const r=await c.tick();assert.equal(r.outcome,'CAPTURE_SAVED');assert.equal(r.records,5);assert.equal(commands.filter(x=>x.code===1102).length,1);assert.ok(commands.every(x=>[1000,1102,11,50,201,1503,1504,1502,1001].includes(x.code)));assert.equal((await store.status()).cloudAccepted,false)
})));
test('service source has no transmission or destructive device commands',async()=>{const s=await fs.readFile(new URL('../core.mjs',import.meta.url),'utf8');assert.doesNotMatch(s,/\bfetch\s*\(|https\.request|execSync|spawn\s*\(/);const cli=await fs.readFile(new URL('../cli.mjs',import.meta.url),'utf8');assert.match(cli,/cloudAccepted:false/);assert.doesNotMatch(cli,/process\.env\..*KEY/)});

test('clock accepting an unauthenticated session requires operator review',()=>context(async store=>{const f=fixture();f.report.authenticationAccepted=false;await worker(store,async()=>f).tick();assert.equal((await store.state()).blocked,'PROTOCOL_REVIEW');assert.equal((await fs.readdir(store.captures)).length,0)}));
test('unknown counts do not authorize a layout',()=>context(async store=>{const f=fixture();f.report.metadata.countsAfter.counts.attendanceRecordsReported=null;await worker(store,async()=>f).tick();assert.equal((await fs.readdir(store.captures)).length,0)}));
test('outdated local success is never shown as recent/cloud',()=>context(async store=>{await worker(store).tick();const s=await store.status(new Date('2026-09-12T10:00:00Z'));assert.equal(s.localState,'NO_RECENT_LOCAL_READ');assert.equal(s.cloudAccepted,false)}));
test('installers require explicit enable and do not change firewall',async()=>{const win=await fs.readFile(new URL('../install/windows.ps1',import.meta.url),'utf8'),linux=await fs.readFile(new URL('../install/linux.sh',import.meta.url),'utf8'),unit=await fs.readFile(new URL('../install/municontrol-pm10.service',import.meta.url),'utf8');assert.match(win,/#Requires -RunAsAdministrator/);assert.match(win,/-LogonType ServiceAccount -RunLevel Limited/);assert.match(win,/-MultipleInstances IgnoreNew/);assert.match(win,/if \(\$EnableCapture\)/);assert.doesNotMatch(win+linux,/netsh|New-NetFirewallRule|iptables|ufw|curl |wget /);assert.match(unit,/NoNewPrivileges=true/);assert.match(unit,/ProtectSystem=strict/);assert.match(unit,/ReadOnlyPaths=.*secrets/);assert.match(linux,/--enable-capture/)});
test('previous validated TCP reader bytes are preserved exactly',async()=>{const b=await fs.readFile(new URL('../vendor/lector-fichadas.mjs',import.meta.url));assert.equal(createHash('sha256').update(b).digest('hex'),'bc2d2479675ae1a885b9b62b31fc915ae879506e626d1e7ea4d51a11ae886aa5')});

test('root symbolic links or junctions are rejected',()=>context(async(store,root,key)=>{const link=root+'-link';await fs.symlink(root,link,process.platform==='win32'?'junction':'dir');try{await assert.rejects(new Store(link,key,store.settings).open(),{code:'STORAGE_SYMLINK_REJECTED'})}finally{await fs.unlink(link)}}));
test('data junction is rejected before creating files in its target',()=>context(async(store,root,key)=>{await fs.rm(store.dir,{recursive:true,force:true});const elsewhere=await fs.mkdtemp(path.join(os.tmpdir(),'pm10-no-follow-'));await fs.symlink(elsewhere,store.dir,process.platform==='win32'?'junction':'dir');try{await assert.rejects(new Store(root,key,store.settings).open(),{code:'STORAGE_SYMLINK_REJECTED'});assert.deepEqual(await fs.readdir(elsewhere),[])}finally{await fs.unlink(store.dir);await fs.rm(elsewhere,{recursive:true,force:true})}}));
